"use client";
import {useState} from 'react';
import {moneyApi as api,type Category,type Account} from '@/lib/money/model';
import type {MeaningRule} from '@/lib/money/meaning';
import {categoryIndex} from '@/lib/money/categories';
import {useMoneyRows,useMoneyCache,useMoneyViewState} from './MoneyDataProvider';
import {useMoneyData,LoadState} from './MoneyWebData';
type Scope={ruleId:string;ruleVersion:number;from:string;to:string;accountId:string|null};
type Preview={items:{id:string;beforeCategoryId:string|null;categoryId:string;status:string;reason:string|null}[];eligible:number;protected:number;fingerprint:string};
type Run={run:{id:string;version:number;status:string};items:{transactionId:string;status:string;result:{reason?:string;categoryId?:string}}[];counts:{status:string;count:number}[];total:number};
const labels:Record<string,string>={RUNNING:'진행 중',PAUSED:'중단',COMPLETED:'처리 완료',PENDING:'처리 대기',APPLIED:'적용',PROTECTED:'최신 수정·범위 보호',FAILED:'실패'};
export function HistoricalClassification({rules,categories,accounts}:{rules:MeaningRule[];categories:Category[];accounts:Account[]}){
 const [ruleId,setRuleId]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[accountId,setAccountId]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[approvedScope,setApprovedScope]=useState<Scope|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[runId,setRunId]=useMoneyViewState<string|null>('historical-run',()=>null),[offset,setOffset]=useState(0);
 const coordinator=useMoneyRows(),cache=useMoneyCache(),index=categoryIndex(categories),runs=useMoneyData<{id:string;status:string}[]>('/ai/history-runs'),run=useMoneyData<Run>(runId?`/ai/history-runs/${runId}?offset=${offset}`:null);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');try{await work();}catch(e){setError(e instanceof Error?e.message:'과거 적용을 처리하지 못했습니다.');}finally{setBusy(false);}}
 function changed(){setPreview(null);setApprovedScope(null);}
 return <details className="meaning-history"><summary>과거 재분류 · 별도 범위 승인</summary><p>미래 규칙 저장과 별개 작업입니다. 현재 직접 지정과 이후 변경을 보호하고, 승인한 범위에서 거래별 결과를 남깁니다.</p><fieldset disabled={busy} className="money-toolbar"><select aria-label="과거 적용 규칙" value={ruleId} onChange={e=>{setRuleId(e.target.value);changed();}}><option value="">현재 활성 분류 규칙 선택</option>{rules.filter(r=>r.status==='ACTIVE'&&r.categoryId).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input aria-label="과거 적용 시작일" type="date" value={from} onChange={e=>{setFrom(e.target.value);changed();}}/><input aria-label="과거 적용 종료일" type="date" value={to} onChange={e=>{setTo(e.target.value);changed();}}/><select aria-label="과거 적용 계좌" value={accountId} onChange={e=>{setAccountId(e.target.value);changed();}}><option value="">전체 소유 계좌</option>{accounts.filter(a=>!a.archived).map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</select><button disabled={!ruleId||!from||!to} onClick={()=>void action(async()=>{const rule=rules.find(r=>r.id===ruleId);if(!rule)throw Error('규칙을 다시 확인해 주세요.');const scope={ruleId,ruleVersion:rule.version,from,to,accountId:accountId||null};setPreview(await api.post('/ai/history-runs/preview',scope));setApprovedScope(scope);})}>실제 영향 미리보기</button></fieldset><LoadState loading={run.loading} error={error||run.error} lastSuccessAt={run.lastSuccessAt}/>
 {preview&&<div><p>적용 예정 {preview.eligible}건 · 보호·동일값 제외 {preview.protected}건</p><ul>{preview.items.slice(0,50).map(item=><li key={item.id}>{index.path(item.beforeCategoryId)} → {index.path(item.categoryId)} · {item.reason??'적용 예정'}</li>)}</ul>{preview.items.length>50&&<p>전체 {preview.items.length}건 집계 · 대표 대상 50건 표시</p>}<button disabled={busy||!preview.eligible||!approvedScope} onClick={()=>void action(async()=>{const saved=await coordinator.execute<Run>('history-start','/ai/history-runs',{scope:approvedScope,fingerprint:preview.fingerprint});setRunId(saved.run.id);setOffset(0);setPreview(null);cache.mutate('ai');})}>확인한 과거 범위 작업 시작</button></div>}
 <select aria-label="저장된 과거 적용 작업" value={runId??''} onChange={e=>{setRunId(e.target.value||null);setOffset(0);}}><option value="">저장된 작업 선택</option>{runs.data?.map(r=><option key={r.id} value={r.id}>{labels[r.status]??r.status} · {r.id.slice(0,8)}</option>)}</select>
 {run.data&&<div><p>작업 상태: {labels[run.data.run.status]} · {run.data.counts.map(c=>`${labels[c.status]} ${c.count}건`).join(' · ')}</p><button disabled={busy||run.data.run.status!=='RUNNING'} onClick={()=>void action(async()=>{try{await api.post(`/ai/history-runs/${runId}/advance`,{});}catch{await api.get(`/ai/history-runs/${runId}`);throw Error('응답이 끊겨 저장된 작업 결과를 조회했습니다. 적용 이력을 확인한 후 대기 항목을 이어서 처리해 주세요.');}finally{cache.mutate('ai');cache.mutate('book');}})}>대기 최대 50건 이어서 처리</button><button disabled={busy} onClick={()=>void action(async()=>{await coordinator.execute('history-control:'+runId,'/ai/history-runs/control',{id:runId,expectedVersion:run.data!.run.version,pause:run.data!.run.status==='RUNNING',retryFailed:false});cache.mutate('ai');})}>{run.data.run.status==='RUNNING'?'작업 중단':'대기 작업 재개'}</button><button disabled={busy||!run.data.counts.some(c=>c.status==='FAILED'&&c.count>0)} onClick={()=>void action(async()=>{await coordinator.execute('history-retry:'+runId,'/ai/history-runs/control',{id:runId,expectedVersion:run.data!.run.version,pause:false,retryFailed:true});cache.mutate('ai');})}>실패 항목만 다시 대기</button><ul>{run.data.items.map(item=><li key={item.transactionId}>{labels[item.status]} · {item.result.reason??index.path(item.result.categoryId??null)}</li>)}</ul><button disabled={!offset||busy} onClick={()=>setOffset(Math.max(0,offset-50))}>이전 50건</button><button disabled={busy||offset+50>=run.data.total} onClick={()=>setOffset(offset+50)}>다음 50건</button></div>}
 </details>;
}
