"use client";
import {useState} from 'react';
import {moneyApi as api,type Category} from '@/lib/money/model';
import {categoryIndex} from '@/lib/money/categories';
import {useMoneyCache,useMoneyRows} from './MoneyDataProvider';
import {useMoneyData,LoadState,type BookRow} from './MoneyWebData';
import {useClassificationUndo} from './MoneyClassificationUndo';

export const classificationLabels:Record<string,string>={DIRECT:'직접 수정',CONFIRMED:'직접 확인',DIRECT_REFERENCE:'유효 직접 수정 참고',APPROVED_RULE:'승인 규칙',AI:'AI 판단',RESTORED:'복원',QUEUED:'판단 대기',RUNNING:'판단 중',FAILED:'판단 실패',PROTECTED:'최신 수정 보호',UNCHANGED:'구매 의미 유지',UNDONE:'실행 취소',SUCCEEDED:'판단 적용'};
export const classificationItem=(row:BookRow)=>({id:row.id,transactionVersion:row.transactionVersion,overrideVersion:row.version,projectionVersion:row.projectionVersion,classificationVersion:row.classificationVersion??0,categoryId:row.categoryId,directCorrection:false,thisTransactionOnly:false});
export function ClassificationBatch({rows,selected,onSelection,categories}:{rows:BookRow[];selected:string[];onSelection:(ids:string[])=>void;categories:Category[]}){
 const coordinator=useMoneyRows(),cache=useMoneyCache(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[only,setOnly]=useState(false);
 const {remember}=useClassificationUndo();
 const pageIds=selected.filter(id=>rows.some(row=>row.id===id));
 const eligibility=useMoneyData<{items:{id:string;completeEligible:boolean;requestEligible:boolean;reason:string}[]}>(pageIds.length?'/ai/classification/eligibility?ids='+pageIds.join(','):null);
 const current=rows.filter(row=>selected.includes(row.id)).map(row=>coordinator.latest(row));
 const index=categoryIndex(categories),eligible=current.filter(row=>{if(!eligibility.data?.items.some(item=>item.id===row.id&&item.completeEligible))return false;const category=row.categoryId?index.byId.get(row.categoryId):undefined;return ['EXPENSE','INCOME'].includes(row.type)&&!row.excluded&&category&&index.active(category);});
 const excluded=current.filter(row=>!eligible.includes(row));
 async function run(request=false){setBusy(true);setError('');setNotice('');try{if(request){const requestRows=current.filter(row=>eligibility.data?.items.some(item=>item.id===row.id&&item.requestEligible));await coordinator.flush(requestRows.map(row=>row.id));const items=requestRows.map(row=>classificationItem(coordinator.latest(row)));const result=await coordinator.execute<{queued:number}>('request:'+items.map(r=>r.id).join(','),'/ai/classification/request',{items});setNotice(`${result.queued}건의 재판단 요청을 저장했습니다. 적용 결과는 거래별로 확인합니다.`);}else{const result=await coordinator.classify(eligible.map(row=>({...classificationItem(row),thisTransactionOnly:only})));remember(result.items.map(item=>item.eventId),`${result.completed}건의 분류를 함께 저장했습니다.`,result.items.map(item=>item.id));setNotice(`${result.completed}건을 함께 저장하고 검토 완료했습니다.`);onSelection(selected.filter(id=>!eligible.some(row=>row.id===id)));}cache.mutate('ai');cache.mutate('book');}catch(e){setError(e instanceof Error?e.message:'적용하지 못했습니다.');}finally{setBusy(false);}}
 return <div className="money-classification-batch"><LoadState loading={eligibility.loading} error={eligibility.error} lastSuccessAt={eligibility.lastSuccessAt}/><span>현재 페이지 선택 {current.length}건 · 완료 가능 {eligible.length}건 · 제외 {excluded.length}건</span>{excluded.length>0&&<details><summary>완료 제외 사유</summary>{excluded.map(row=><p key={row.id}>{row.title} · {eligibility.data?.items.find(item=>item.id===row.id)?.reason??(row.excluded?'가계부 제외':!['EXPENSE','INCOME'].includes(row.type)?'금융 확인 경로 필요':!row.categoryId?'최종 분류 미선택':'현재 분류가 유효하지 않음')}</p>)}</details>}<label><input type="checkbox" checked={only} onChange={e=>setOnly(e.target.checked)}/>이번 거래만 반영 · 향후 참고 제외</label><button disabled={busy||!eligible.length} onClick={()=>void run()}>선택 적격 {eligible.length}건 함께 저장·완료</button><button disabled={busy||!eligibility.data?.items.some(item=>item.requestEligible)} onClick={()=>void run(true)}>선택 내역 재판단 요청</button><button disabled={busy||!selected.length} onClick={()=>onSelection([])}>선택 해제</button>{error&&<p role="alert">{error} 선택과 초안을 유지했습니다.</p>}{notice&&<p role="status">{notice}</p>}</div>;
}
export function ClassificationStatus({row}:{row:BookRow}){
 const coordinator=useMoneyRows(),cache=useMoneyCache(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="money-classification-status"><small>{classificationLabels[row.classificationOrigin??'']??(row.categoryId?'현재 분류':'미분류')} · {classificationLabels[row.classificationJobStatus??'']??'판단 이력 없음'}</small>{row.classificationOrigin&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await coordinator.execute('reference:'+row.id,'/ai/classification/reference-exclusion',{id:row.id,expectedVersion:row.classificationVersion??0,excluded:!row.futureReferenceExcluded});cache.mutate('ai');cache.mutate('book');}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}}>{row.futureReferenceExcluded?'향후 참고 제외 해제':'이번 거래만 반영'}</button>}{row.futureReferenceExcluded&&<small>현재 분류 보존 · 향후 참고 제외</small>}{error&&<small role="alert">{error}</small>}</div>;
}
type Event={id:string;transactionId:string;bundleId:string;origin:string;categoryId:string|null;active:boolean;createdAt:string;previousValue:{categoryId:string|null};evidence:{reason?:string;retention?:string}};
type Preview={eligibleEventIds:string[];excluded:{eventId:string;reason:string}[];fingerprint:string};
export function ClassificationHistory({categories}:{categories:Category[]}){
 const [additional,setAdditional]=useState<Event[]>([]),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const data=useMoneyData<{items:Event[];total:number}>('/ai/classification/history?offset=0'),cache=useMoneyCache(),coordinator=useMoneyRows(),index=categoryIndex(categories);
 const events=[...new Map([...(data.data?.items??[]),...additional].map(event=>[event.id,event])).values()];
 return <section className="money-card"><h3>자동화·직접 분류 이력</h3><LoadState loading={data.loading} error={data.error||error} lastSuccessAt={data.lastSuccessAt}/><div className="money-table-wrap"><table className="money-table"><thead><tr><th>선택</th><th>시각</th><th>출처</th><th>이전 → 결과</th><th>근거·상태</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td><input type="checkbox" aria-label={`${event.id} 복구 선택`} checked={selected.includes(event.id)} onChange={e=>{setSelected(e.target.checked?[...selected,event.id].slice(0,50):selected.filter(id=>id!==event.id));setPreview(null);}}/></td><td>{new Date(event.createdAt).toLocaleString('ko-KR')}</td><td>{classificationLabels[event.origin]??event.origin}</td><td>{index.path(event.previousValue.categoryId)} → {index.path(event.categoryId)}</td><td>{event.evidence.retention==='EXPIRED'?'근거 보관 종료':event.evidence.reason??'사용자 선택'} · {event.active?'적용 이력':'실행 취소 · 참고 제외'}</td></tr>)}</tbody></table></div><button disabled={busy||!selected.length} onClick={async()=>{setBusy(true);setError('');try{setPreview(await api.post('/ai/classification/undo-preview',selected));}catch(e){setError(e instanceof Error?e.message:'미리보기 실패');}finally{setBusy(false);}}}>선택 변경 복구 미리보기</button>{preview&&<div><p>복구 가능 {preview.eligibleEventIds.length}건 · 제외 {preview.excluded.length}건 · 제목·메모와 금융 사실은 보존합니다.</p>{preview.excluded.map(row=><p key={row.eventId}>{row.reason}</p>)}<button disabled={busy||!preview.eligibleEventIds.length} onClick={async()=>{setBusy(true);setError('');try{await coordinator.execute('undo:'+preview.eligibleEventIds.join(','),'/ai/classification/undo',{eventIds:preview.eligibleEventIds,fingerprint:preview.fingerprint});cache.mutate('ai');cache.mutate('book');setPreview(null);setSelected([]);}catch(e){setError(e instanceof Error?e.message:'복구 미적용');}finally{setBusy(false);}}}>미리본 적격 묶음 함께 복구</button></div>}<button disabled={busy||events.length>=(data.data?.total??0)} onClick={async()=>{setBusy(true);setError('');try{const next=await api.get<{items:Event[];total:number}>('/ai/classification/history?offset='+events.length);setAdditional(old=>[...old,...next.items]);}catch(e){setError(e instanceof Error?e.message:'추가 조회 실패');}finally{setBusy(false);}}}>50건 더 불러오기</button><p className="money-muted">변경 근거는 최소 1년 보관합니다. 이력 목록의 50건 제한은 보관 기간이 아닙니다.</p></section>;
}
