package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static com.kafka.backend.money.MoneyTypes.*;
import static com.kafka.backend.money.MoneyProductService.*;

/** V71 migration and domain contract checks, isolated schema and whole transaction rolled back. */
@EnabledIfEnvironmentVariable(named="DEV_DB_URL",matches=".+")
@EnabledIfEnvironmentVariable(named="APP_DEV_USER_ID",matches=".+")
class MoneyWebRevisionPostgresTest {
 private final MoneyMobilePostgresTest fixture=new MoneyMobilePostgresTest();
 @Test void layoutPersistsAndLegacyRequestsNeverEraseSavedRows()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var revision=new MoneyWebRevisionService(db,()->MoneyPostgresIntegrationTest.OWNER,m,p,mobile,JsonMapper.builder().build());var a=fixture.account(m,AccountRole.SPENDING);var b=fixture.account(m,AccountRole.SAVINGS);var before=p.accountBalances();var layout=new MoneyWebRevisionService.Layout(1,List.of(new MoneyWebRevisionService.LayoutRow("living","생활",List.of(a.id())),new MoneyWebRevisionService.LayoutRow("saving","저축",List.of(b.id()))));var saved=revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(List.of(a.id(),b.id()),0L,layout));assertThat(revision.preferences().layout()).isEqualTo(layout);var compatible=revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(saved.accountIds(),saved.version()));assertThat(compatible.layout()).isEqualTo(layout);assertThatThrownBy(()->revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(List.of(b.id(),a.id()),compatible.version()))).isInstanceOf(InvalidRequestException.class);assertThat(revision.preferences()).isEqualTo(compatible);assertThat(p.accountBalances()).isEqualTo(before);});}
 @Test void spendingPaceAggregatesPopulatedDaysAndUnresolvedLoansWithTypedJdbcResults()throws Exception{
  fixture.isolated((db,m,p,w,mobile)->{
   var owner=MoneyPostgresIntegrationTest.OWNER;
   var revision=new MoneyWebRevisionService(db,()->owner,m,p,mobile,JsonMapper.builder().build());
   var account=fixture.account(m,AccountRole.SPENDING);
   Instant september=Instant.parse("2026-09-01T01:00:00Z"),august=Instant.parse("2026-08-01T01:00:00Z");
   var expense=p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("10000"),september,"Fixture",null,null,false,null,null));
   p.save(null,new Entry(TransactionType.REFUND,null,account.id(),new BigDecimal("2000"),september.plusSeconds(86400),"Fixture refund",null,null,false,expense.id(),null));
   p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("5000"),august,"Previous",null,null,false,null,null));
   p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("1000"),august.plusSeconds(86400),"Previous",null,null,false,null,null));
   // Canonical loan facts exercise nullable split fields and PostgreSQL numeric/bigint aggregates.
   var loan=w.saveLoan(null,new MoneyWebPostgresTest().loanInput(account.id(),0,"ACTIVE",1000));
   var financial=new MoneyFinancialService(db,()->owner,m,p,w,JsonMapper.builder().build());
   financial.payment(null,new MoneyFinancialService.PaymentInput(loan.id(),account.id(),new BigDecimal("1000"),null,null,null,september.plusSeconds(172800),"Unknown split",null,loan.version()));
   financial.payment(null,new MoneyFinancialService.PaymentInput(loan.id(),account.id(),new BigDecimal("1000"),new BigDecimal("900"),new BigDecimal("70"),new BigDecimal("30"),september.plusSeconds(259200),"Known split",null,w.loan(loan.id()).version()));
   var pace=revision.spendingPace("2026-09-01","2026-09-30");
   assertThat((BigDecimal)pace.get("current")).isEqualByComparingTo("8100");
   assertThat((BigDecimal)pace.get("previous")).isEqualByComparingTo("6000");
   assertThat((BigDecimal)pace.get("delta")).isEqualByComparingTo("2100");
   assertThat(pace.get("unresolvedLoanPayments")).isEqualTo(1L);
   var buckets=(List<Map<String,Object>>)pace.get("buckets");
   assertThat(buckets).hasSize(30);
   assertThat((BigDecimal)buckets.get(0).get("current")).isEqualByComparingTo("10000");
   assertThat((BigDecimal)buckets.get(1).get("current")).isEqualByComparingTo("8000");
   assertThat((BigDecimal)buckets.get(2).get("current")).isEqualByComparingTo("8000");
   assertThat((BigDecimal)buckets.get(3).get("current")).isEqualByComparingTo("8100");
   assertThat((BigDecimal)buckets.getLast().get("previous")).isEqualByComparingTo("6000");
   assertThat(pace.get("analyticsUnavailable")).isEqualTo(false);
   var empty=revision.spendingPace("2026-07-01","2026-07-31");
   assertThat((BigDecimal)empty.get("current")).isZero();
   assertThat((BigDecimal)empty.get("previous")).isZero();
   assertThat(empty.get("unresolvedLoanPayments")).isEqualTo(0L);
  });
 }
 @Test void structuralMappingPreservesFinancialIdentityAndRootFinalAssignments()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var json=JsonMapper.builder().build();var owner=MoneyPostgresIntegrationTest.OWNER;var revision=new MoneyWebRevisionService(db,()->owner,m,p,mobile,json);assertThat(revision.groups()).isEmpty();var root=p.saveCategory(null,new CategoryInput("Root","#123456",false,null,"EXPENSE","☕",0));var child=p.saveCategory(null,new CategoryInput("Child","#123456",false,null,"EXPENSE",null,0,root.id(),false));var a=fixture.account(m,AccountRole.SPENDING);var tx=p.save(null,new Entry(TransactionType.EXPENSE,a.id(),null,new BigDecimal("10000"),fixture.at,"Fixture",root.id(),null,false,null,null));var group=revision.saveGroup(null,new MoneyWebRevisionService.GroupInput("User group","EXPENSE",0,null,false,"ICON","Coffee"));var mapped=revision.mapGroup(root.id(),new MoneyWebRevisionService.GroupMapping(group.id(),root.version()));assertThat(mapped.id()).isEqualTo(root.id());assertThat(mapped.parentId()).isNull();assertThat(mapped.structuralGroupId()).isEqualTo(group.id());assertThat(p.categories().stream().filter(c->c.id().equals(child.id())).findFirst().orElseThrow().parentId()).isEqualTo(root.id());assertThat(m.transaction(tx.id())).isEqualTo(tx);assertThat(mapped.iconType()).isEqualTo("EMOJI");assertThatThrownBy(()->revision.mapGroup(child.id(),new MoneyWebRevisionService.GroupMapping(group.id(),child.version()))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->revision.mapGroup(root.id(),new MoneyWebRevisionService.GroupMapping(null,root.version()))).isInstanceOf(OptimisticLockConflictException.class);var outsider=new MoneyWebRevisionService(db,UUID::randomUUID,m,p,mobile,json);assertThat(outsider.groups()).isEmpty();});}
 @Test void representativeOrderAndTrackingStayIndependentWithVersionGuard()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var owner=MoneyPostgresIntegrationTest.OWNER;var json=JsonMapper.builder().build();var revision=new MoneyWebRevisionService(db,()->owner,m,p,mobile,json);var first=fixture.account(m,AccountRole.SPENDING);var second=fixture.account(m,AccountRole.SAVINGS);var meaning=new MoneyMeaningService(db,()->owner,json);var tracking=meaning.saveTracking(new MoneyMeaningService.TrackingInput(List.of(first.id()),List.of(),0L));var saved=revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(List.of(second.id(),first.id()),0L));assertThat(saved.accountIds()).containsExactly(second.id(),first.id());assertThat(meaning.tracking()).isEqualTo(tracking);assertThatThrownBy(()->revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(List.of(),0L))).isInstanceOf(OptimisticLockConflictException.class);m.archiveAccount(second.id(),new ArchiveAccount(0L,true));assertThat(revision.preferences().accountIds()).containsExactly(second.id(),first.id());revision.savePreferences(new MoneyWebRevisionService.PreferencesInput(List.of(first.id()),saved.version()));});}
 @Test void fullQueryAmountAndDirectRootFiltersUseSameCountAndAggregates()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var owner=MoneyPostgresIntegrationTest.OWNER;var account=fixture.account(m,AccountRole.SPENDING);new MoneyMeaningService(db,()->owner,JsonMapper.builder().build()).saveTracking(new MoneyMeaningService.TrackingInput(List.of(account.id()),List.of(),0L));var root=p.saveCategory(null,new CategoryInput("Root","#123456",false,null));var child=p.saveCategory(null,new CategoryInput("Child","#123456",false,null,"EXPENSE",null,0,root.id(),false));for(int amount:List.of(9999,10000,49999,50000))p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,BigDecimal.valueOf(amount),fixture.at,"Fixture",root.id(),null,false,null,null));p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("20000"),fixture.at,"Child",child.id(),null,false,null,null));var books=w.bookkeeping("2026-09-01","2026-09-30","EXPENSE",null,1,0,false,null,"direct:"+root.id(),new BigDecimal("10000"),new BigDecimal("49999"));assertThat(books.get("total")).isEqualTo(2L);assertThat((List<?>)books.get("items")).hasSize(1);assertThat(((Map<?,?>)books.get("summary")).get("total")).isEqualTo(new BigDecimal("59999.00"));var ledger=p.transactions("2026-09-01","2026-09-30",null,null,null,null,false,1,0,false,null,"direct:"+root.id(),null,null,new BigDecimal("10000"),new BigDecimal("49999"));assertThat(ledger.total()).isEqualTo(2);assertThat(ledger.items()).hasSize(1);assertThat(w.bookkeeping("2026-09-01","2026-09-30","EXPENSE",null,1,0,false,"none",null,null,null).get("total")).isEqualTo(0L);});}
 @Test void nonTransactionPreviewRespectsLaterCheckpointAndDoesNotWriteFacts()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var account=fixture.account(m,AccountRole.SPENDING);var tx=p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("4500"),fixture.at,"Fixture",null,null,false,null,null));var owner=MoneyPostgresIntegrationTest.OWNER;var preview=new MoneyNonTransactionPreview(db,()->owner,m,p,w,JsonMapper.builder().build());var input=new MoneyNonTransactionPreview.Input("TRANSACTION",tx.id(),0L,0L,0L);var first=preview.preview(input);assertThat(((Map<?,?>)((List<?>)first.get("accountImpacts")).getFirst()).get("delta")).isEqualTo(new BigDecimal("4500.00"));p.checkpoint(account.id(),new Checkpoint(new BigDecimal("420000"),fixture.at.plusSeconds(1),"Synthetic anchor",0L));var after=preview.preview(input);assertThat(((Map<?,?>)((List<?>)after.get("accountImpacts")).getFirst()).get("delta")).isEqualTo(new BigDecimal("0.00"));assertThat(after.get("fingerprint")).isNotEqualTo(first.get("fingerprint"));assertThat(m.transaction(tx.id())).isEqualTo(tx);assertThat(p.corrections(tx.id())).isEmpty();assertThat(((Map<?,?>)after.get("statisticsImpact")).get("consumptionDelta")).isEqualTo(new BigDecimal("-4500.00"));});}
 @Test void staleNonTransactionImpactCannotMutateFactsOrBecomePositiveLearning()throws Exception{fixture.isolated((db,m,p,w,mobile)->{var owner=MoneyPostgresIntegrationTest.OWNER;var json=JsonMapper.builder().build();var meaning=new MoneyMeaningService(db,()->owner,json);var review=new MoneyReviewService(db,()->owner,w,p,meaning,json);var ai=new MoneyAiService(db,()->owner,json,review,w,p,m,meaning);var account=fixture.account(m,AccountRole.SPENDING);var tx=p.save(null,new Entry(TransactionType.EXPENSE,account.id(),null,new BigDecimal("4500"),fixture.at,"Fixture",null,null,false,null,null));var preview=new MoneyNonTransactionPreview(db,()->owner,m,p,w,json);var first=preview.preview(new MoneyNonTransactionPreview.Input("TRANSACTION",tx.id(),0L,0L,0L));p.save(null,new Entry(TransactionType.INCOME,null,account.id(),new BigDecimal("100"),fixture.at.plusSeconds(1),"New fact",null,null,false,null,null));assertThatThrownBy(()->ai.decide(new MoneyAiService.Decision(tx.id(),"TRANSACTION","NON_TRANSACTION",0L,0L,0L,null,Map.of(),"Explicit reason",first.get("fingerprint").toString()))).isInstanceOf(InvalidRequestException.class);assertThat(m.transaction(tx.id())).isEqualTo(tx);assertThat(db.queryForObject("select count(*) from money_ai_events where user_id=?",Long.class,owner)).isZero();w.saveBookkeeping(tx.id(),new MoneyWebTypes.BookkeepingEdit(0L,0L,Map.of("title","Ordinary inline edit"),0L));assertThat(db.queryForObject("select count(*) from money_ai_events where user_id=?",Long.class,owner)).isZero();var next=preview.preview(new MoneyNonTransactionPreview.Input("TRANSACTION",tx.id(),0L,1L,0L));var saved=ai.decide(new MoneyAiService.Decision(tx.id(),"TRANSACTION","NON_TRANSACTION",0L,1L,0L,null,Map.of(),"Explicit reason",next.get("fingerprint").toString()));assertThat(m.transaction(tx.id()).excluded()).isTrue();assertThat(db.queryForObject("select count(*) from money_ai_events where user_id=? and kind='CONFIRM'",Long.class,owner)).isZero();ai.undo((UUID)saved.get("eventId"));assertThat(m.transaction(tx.id()).excluded()).isFalse();});}
 @Test void unknownAndForeignCurrencyBalancesStayUnknownWithinTheirFinancialScope()throws Exception{fixture.isolated((db,m,p,w,mobile)->{
  var revision=new MoneyWebRevisionService(db,()->MoneyPostgresIntegrationTest.OWNER,m,p,mobile,JsonMapper.builder().build());var unknown=fixture.account(m,AccountRole.SPENDING);var savings=fixture.account(m,AccountRole.SAVINGS);p.checkpoint(savings.id(),new Checkpoint(new BigDecimal("500000"),fixture.at.minusSeconds(100),"Synthetic anchor",savings.version()));
  var currency=(Map<?,?>)((List<?>)revision.currentStock().get("currencies")).getFirst();assertThat(currency.get("currentBalance")).isNull();assertThat(currency.get("includedAssets")).isNull();assertThat((BigDecimal)currency.get("currentSavings")).isEqualByComparingTo("500000");
  p.checkpoint(unknown.id(),new Checkpoint(new BigDecimal("100000"),fixture.at.minusSeconds(100),"Synthetic anchor",unknown.version()));var transaction=p.save(null,new Entry(TransactionType.EXPENSE,unknown.id(),null,new BigDecimal("10"),fixture.at,"Foreign synthetic",null,null,false,null,null));db.update("update money_transactions set currency='USD' where id=?",transaction.id());currency=(Map<?,?>)((List<?>)revision.currentStock().get("currencies")).getFirst();assertThat(currency.get("currentBalance")).isNull();assertThat(m.transaction(transaction.id()).currency()).isEqualTo("USD");assertThat(m.transaction(transaction.id()).amount()).isEqualByComparingTo("10");
  db.update("update money_accounts set include_in_assets=false where id=?",unknown.id());currency=(Map<?,?>)((List<?>)revision.currentStock().get("currencies")).getFirst();assertThat((BigDecimal)currency.get("includedAssets")).isEqualByComparingTo("500000");assertThat((BigDecimal)currency.get("currentBalance")).isEqualByComparingTo("0");
 });}
}
