package com.kafka.backend.money;

import com.kafka.backend.common.InvalidRequestException;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static com.kafka.backend.money.MoneyTypes.*;

class MoneyWebRevisionTest {
 @Test void layoutRequiresCompatibleOrderUniqueRowsAndBoundedCapacity(){var a=UUID.randomUUID();var b=UUID.randomUUID();var layout=new MoneyWebRevisionService.Layout(1,List.of(new MoneyWebRevisionService.LayoutRow("row","생활",List.of(a,b))));MoneyWebRevisionService.validateLayout(layout,List.of(a,b));assertThatThrownBy(()->MoneyWebRevisionService.validateLayout(layout,List.of(b,a))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyWebRevisionService.validateLayout(new MoneyWebRevisionService.Layout(1,List.of(layout.rows().getFirst(),layout.rows().getFirst())),List.of(a,b))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyWebRevisionService.validateLayout(new MoneyWebRevisionService.Layout(1,List.of(new MoneyWebRevisionService.LayoutRow("row",null,List.of(a,b,UUID.randomUUID(),UUID.randomUUID())))),List.of(a,b))).isInstanceOf(InvalidRequestException.class);}
 @Test void representativeLimitRejectsDuplicatesAndNulls(){var ids=new ArrayList<UUID>();for(int i=0;i<10;i++)ids.add(UUID.randomUUID());MoneyWebRevisionService.validateRepresentatives(ids);ids.add(UUID.randomUUID());assertThatThrownBy(()->MoneyWebRevisionService.validateRepresentatives(ids)).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyWebRevisionService.validateRepresentatives(List.of(ids.getFirst(),ids.getFirst()))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyWebRevisionService.validateRepresentatives(Arrays.asList((UUID)null))).isInstanceOf(InvalidRequestException.class);}
 @Test void currentStockKeepsArchivedTotalAndFundScopesIndependent(){var db=mock(JdbcTemplate.class);var product=mock(MoneyProductService.class);var mobile=mock(MoneyMobileService.class);UUID owner=UUID.randomUUID();MoneyAccount living=account(AccountRole.INCOME_HUB,false,true),savings=account(AccountRole.SPENDING,false,true),archived=account(AccountRole.SPENDING,true,true),excluded=account(AccountRole.SPENDING,false,false);when(product.accountBalances(any(Instant.class))).thenReturn(List.of(balance(living,"120"),balance(savings,"350"),balance(archived,"50"),balance(excluded,"900")));when(mobile.funds()).thenReturn(Map.of(living.id(),new MoneyMobileService.Fund("LIVING",null,0),savings.id(),new MoneyMobileService.Fund("SAVINGS","INSTALLMENT",0),archived.id(),new MoneyMobileService.Fund("LIVING",null,1),excluded.id(),new MoneyMobileService.Fund("LIVING",null,2)));when(db.queryForList(anyString(),eq(UUID.class),eq(owner))).thenReturn(List.of());when(db.queryForObject(anyString(),eq(BigDecimal.class),eq(owner))).thenReturn(new BigDecimal("600"));var service=new MoneyWebRevisionService(db,()->owner,mock(MoneyService.class),product,mobile,JsonMapper.builder().build());var result=service.currentStock();var row=(Map<?,?>)((List<?>)result.get("currencies")).getFirst();assertThat(row.get("currentTotal")).isEqualTo(new BigDecimal("-80"));assertThat(row.get("currentBalance")).isEqualTo(new BigDecimal("120"));assertThat(row.get("currentSavings")).isEqualTo(new BigDecimal("350"));assertThat(row.get("totalLoans")).isEqualTo(new BigDecimal("600"));}
 @Test void monthPaceClampsPreviousMonthAndDoesNotUseFutureDays(){assertThat(MoneyWebRevisionService.comparison(LocalDate.parse("2026-03-01"),LocalDate.parse("2026-03-31"),LocalDate.parse("2026-03-30"))).containsExactly(LocalDate.parse("2026-03-30"),LocalDate.parse("2026-02-01"),LocalDate.parse("2026-02-28"));assertThat(MoneyWebRevisionService.comparison(LocalDate.parse("2026-10-03"),LocalDate.parse("2026-10-10"),LocalDate.parse("2026-10-04"))).containsExactly(LocalDate.parse("2026-10-04"),LocalDate.parse("2026-09-25"),LocalDate.parse("2026-09-26"));}
 @Test void amountBoundsAllowInclusiveEqualButRejectInvalidRange(){MoneyWebRevisionService.amountRange(BigDecimal.ZERO,BigDecimal.ZERO);MoneyWebRevisionService.amountRange(new BigDecimal("10000"),new BigDecimal("49999"));assertThatThrownBy(()->MoneyWebRevisionService.amountRange(new BigDecimal("-1"),null)).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyWebRevisionService.amountRange(new BigDecimal("50000"),new BigDecimal("49999"))).isInstanceOf(InvalidRequestException.class);}
 @Test void iconAdapterKeepsLegacyAndRejectsExternalAssetsAndUnknownIds(){assertThat(MoneyCategoryIcons.normalize(null,null,"☕")).isEqualTo(new MoneyCategoryIcons.Icon("EMOJI","☕"));assertThat(MoneyCategoryIcons.normalize("ICON","Coffee",null).type()).isEqualTo("ICON");assertThat(MoneyCategoryIcons.ICONS.size()).isGreaterThanOrEqualTo(80);assertThatThrownBy(()->MoneyCategoryIcons.normalize("ASSET","https://example.com/image.png",null)).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->MoneyCategoryIcons.normalize("ICON","unknown-provider-id",null)).isInstanceOf(InvalidRequestException.class);}
 private MoneyAccount account(AccountRole role,boolean archived,boolean include){return new MoneyAccount(UUID.randomUUID(),"IBK","Fixture",role,null,null,archived,0,null,null,null,include,true);}
 private Map<String,Object> balance(MoneyAccount account,String value){return Map.of("account",account,"balance",new MoneyProductService.Balance(new BigDecimal(value),"CALCULATED",Instant.parse("2026-10-04T00:00:00Z")));}
}
