package com.kafka.backend.money;
import com.kafka.backend.common.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.*;
import static org.assertj.core.api.Assertions.*;
import static com.kafka.backend.money.MoneyTypes.*;
import static com.kafka.backend.money.MoneyProductService.*;
@EnabledIfEnvironmentVariable(named="DEV_DB_URL",matches=".+")
class MoneyProductPostgresTest {
 interface Check{void run(MoneyService m,MoneyProductService p,JdbcTemplate db);}
 void rollback(Check check)throws Exception{try(var c=MoneyPostgresIntegrationTest.connection()){c.setAutoCommit(false);try{var db=new JdbcTemplate(new SingleConnectionDataSource(c,true));var m=MoneyPostgresIntegrationTest.service(db,MoneyPostgresIntegrationTest.OWNER);var p=new MoneyProductService(db,()->MoneyPostgresIntegrationTest.OWNER,m,JsonMapper.builder().build());check.run(m,p,db);}finally{c.rollback();}}}
 MoneyAccount account(MoneyService m,String provider,AccountRole role){return m.createAccount(new AccountInput(provider,"Fixture "+UUID.randomUUID(),role,null,null));}
 static final Instant WHEN=Instant.parse("2026-09-24T01:00:00Z");
 Entry entry(TransactionType type,UUID from,UUID to,int amount,UUID category,UUID refund,Long version){return new Entry(type,from,to,BigDecimal.valueOf(amount),WHEN,"Fixture merchant",category,"Memo",false,refund,version);}
 @Test void manualCashAndHouseholdStatistics()throws Exception{rollback((m,p,db)->{var hub=account(m,"SHINHAN",AccountRole.INCOME_HUB);var cash=account(m,"CASH",AccountRole.CASH);p.save(null,entry(TransactionType.INCOME,null,hub.id(),1000,null,null,null));p.save(null,entry(TransactionType.TRANSFER,hub.id(),cash.id(),300,null,null,null));p.save(null,entry(TransactionType.EXPENSE,cash.id(),null,100,null,null,null));var home=p.dashboard("2026-09");assertThat((BigDecimal)home.get("income")).isEqualByComparingTo("1000");assertThat((BigDecimal)home.get("consumption")).isEqualByComparingTo("100");assertThat(p.balance(cash.id()).amount()).isEqualByComparingTo("200");assertThat(p.accountDetail(hub.id(),"2026-09").outflow()).isEqualByComparingTo("300");});}
 @Test void savingsOnlyCountsFinalDestinationAndWithdrawals()throws Exception{rollback((m,p,db)->{var hub=account(m,"SHINHAN",AccountRole.INCOME_HUB);var gate=account(m,"KAKAO",AccountRole.SAVINGS_GATEWAY);var purpose=account(m,"KAKAO",AccountRole.PURPOSE_SAVINGS);var installment=account(m,"KAKAO",AccountRole.PURPOSE_INSTALLMENT);p.save(null,entry(TransactionType.TRANSFER,hub.id(),gate.id(),500,null,null,null));p.save(null,entry(TransactionType.TRANSFER,gate.id(),purpose.id(),500,null,null,null));p.save(null,entry(TransactionType.TRANSFER,purpose.id(),installment.id(),100,null,null,null));p.save(null,entry(TransactionType.TRANSFER,purpose.id(),gate.id(),50,null,null,null));assertThat((BigDecimal)p.dashboard("2026-09").get("savingsMovement")).isEqualByComparingTo("450");assertThat((BigDecimal)p.dashboard("2026-09").get("consumption")).isZero();});}
 @Test void refundOffsetsConsumptionNeverIncomeAndCannotOverRefund()throws Exception{rollback((m,p,db)->{var a=account(m,"IBK",AccountRole.SPENDING);var category=p.initializeCategories().getFirst();var expense=p.save(null,entry(TransactionType.EXPENSE,a.id(),null,100,category.id(),null,null));var refund=p.save(null,entry(TransactionType.REFUND,null,a.id(),40,null,expense.id(),null));assertThat(refund.categoryId()).isEqualTo(category.id());assertThat((BigDecimal)p.dashboard("2026-09").get("consumption")).isEqualByComparingTo("60");assertThat((BigDecimal)p.dashboard("2026-09").get("income")).isZero();assertThatThrownBy(()->p.save(null,entry(TransactionType.REFUND,null,a.id(),61,null,expense.id(),null))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->p.save(expense.id(),entry(TransactionType.INCOME,null,a.id(),100,null,null,0L))).isInstanceOf(InvalidRequestException.class);});}
 @Test void checkpointKeepsHistoryWithoutFakeTransactions()throws Exception{rollback((m,p,db)->{var a=account(m,"IBK",AccountRole.SPENDING);p.checkpoint(a.id(),new Checkpoint(BigDecimal.valueOf(500),WHEN.minusSeconds(1),"Opening",0L));p.save(null,entry(TransactionType.EXPENSE,a.id(),null,100,null,null,null));assertThat(p.balance(a.id()).amount()).isEqualByComparingTo("400");p.checkpoint(a.id(),new Checkpoint(BigDecimal.valueOf(410),WHEN.plusSeconds(1),"Verified",1L));assertThat(p.balance(a.id()).amount()).isEqualByComparingTo("410");assertThat(p.accountDetail(a.id(),"2026-09").checkpoints()).hasSize(2);assertThat((BigDecimal)p.dashboard("2026-09").get("consumption")).isEqualByComparingTo("100");assertThat(p.transactions(null,null,null,null,null,null,false,50,0).total()).isEqualTo(1);});}
 @Test void explicitRulesFilteringAndVersionedCorrection()throws Exception{rollback((m,p,db)->{var a=account(m,"WOORI",AccountRole.FIXED_SPENDING);var cat=p.initializeCategories().getFirst();var tx=p.save(null,entry(TransactionType.EXPENSE,a.id(),null,100,cat.id(),null,null));assertThat(p.rules()).isEmpty();var rule=p.saveRule(null,new RuleInput(" Fixture Merchant ",cat.id(),null));var auto=p.save(null,entry(TransactionType.EXPENSE,a.id(),null,50,null,null,null));assertThat(auto.categoryId()).isEqualTo(cat.id());assertThat(p.transactions("2026-09-24","2026-09-24",a.id(),cat.id(),TransactionType.EXPENSE,"merchant",false,1,0).total()).isEqualTo(2);assertThat(p.transactions("2026-10-01",null,null,null,null,null,false,50,0).items()).isEmpty();p.save(tx.id(),entry(TransactionType.EXPENSE,a.id(),null,110,cat.id(),null,0L));assertThat(p.corrections(tx.id())).hasSize(1);assertThatThrownBy(()->p.save(tx.id(),entry(TransactionType.EXPENSE,a.id(),null,120,null,null,0L))).isInstanceOf(OptimisticLockConflictException.class);p.deleteRule(rule.id(),0L);assertThat(p.rules()).isEmpty();});}
 @Test void accountLifecycleStructureCyclesAndOwnership()throws Exception{rollback((m,p,db)->{var a=account(m,"IBK",AccountRole.SPENDING);var b=m.createAccount(new AccountInput("KAKAO","Fixture purpose",AccountRole.PURPOSE_INSTALLMENT,null,"9876","🌱",null,a.id()));assertThat(m.account(b.id()).emoji()).isEqualTo("🌱");assertThatThrownBy(()->m.updateAccount(a.id(),new AccountUpdate(0L,new AccountInput("IBK","Cycle",AccountRole.SPENDING,null,null,null,null,b.id())))).isInstanceOf(InvalidRequestException.class);var outsider=new MoneyProductService(db,UUID::randomUUID,m,JsonMapper.builder().build());assertThat(outsider.categories()).isEmpty();var otherMoney=MoneyPostgresIntegrationTest.service(db,UUID.randomUUID());assertThatThrownBy(()->otherMoney.account(a.id())).isInstanceOf(ResourceNotFoundException.class);m.archiveAccount(b.id(),new ArchiveAccount(0L,true));assertThatThrownBy(()->p.save(null,entry(TransactionType.TRANSFER,a.id(),b.id(),100,null,null,null))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->m.createAccount(new AccountInput("IBK","Cash",AccountRole.CASH,null,null))).isInstanceOf(InvalidRequestException.class);});}
 @Test void reviewConfirmExcludeAndReprocessPreserveRaw()throws Exception{rollback((m,p,db)->{var a=account(m,"IBK",AccountRole.SPENDING);var raw=m.ingest(Map.of("postedAt",WHEN.toString(),"text","Fixture unknown notification")).notification();m.finishProcessing(raw.id(),ProcessingState.REVIEW_REQUIRED,"UNKNOWN_FORMAT");raw=m.notification(raw.id());var tx=p.reviewPost(new ReviewPost(entry(TransactionType.EXPENSE,a.id(),null,100,null,null,null),List.of(raw.id()),List.of(raw.processingVersion())));assertThat(tx.sources()).hasSize(1);assertThat(m.notification(raw.id()).text()).isEqualTo("Fixture unknown notification");var id=raw.id();assertThatThrownBy(()->p.reprocess(id,m.notification(id).processingVersion())).isInstanceOf(InvalidRequestException.class);var r2=m.ingest(Map.of("postedAt",WHEN.toString(),"text","Fixture excluded notification")).notification();p.reviewExclude(r2.id(),r2.processingVersion());assertThat(m.notification(r2.id()).processingReason()).isEqualTo("USER_EXCLUDED");assertThat(m.attempts(id)).isEmpty();});}
 @Test void transferLinkUnlinkAndExcludeUseOneCanonicalRow()throws Exception{rollback((m,p,db)->{var a=account(m,"IBK",AccountRole.SPENDING);var b=account(m,"WOORI",AccountRole.SPENDING);var out=p.save(null,entry(TransactionType.EXPENSE,a.id(),null,100,null,null,null));var in=p.save(null,entry(TransactionType.INCOME,null,b.id(),100,null,null,null));var linked=p.link(out.id(),new Pair(in.id(),0L,0L));assertThat(linked.type()).isEqualTo(TransactionType.TRANSFER);assertThat(p.transactions(null,null,null,null,null,null,false,50,0).total()).isEqualTo(1);assertThat((BigDecimal)p.dashboard("2026-09").get("income")).isZero();assertThat((BigDecimal)p.dashboard("2026-09").get("consumption")).isZero();var split=p.unlink(linked.id(),linked.version());assertThat(split).hasSize(2);assertThat(p.transactions(null,null,null,null,null,null,false,50,0).total()).isEqualTo(2);var x=split.getFirst();p.save(x.id(),new Entry(x.type(),x.fromAccountId(),x.toAccountId(),x.amount(),x.occurredAt(),null,null,null,true,null,x.version()));assertThat((BigDecimal)p.dashboard("2026-09").get("consumption")).isZero();});}
}
