package com.kafka.backend.money;
import com.kafka.backend.common.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import static com.kafka.backend.money.MoneyTypes.*;
import static org.assertj.core.api.Assertions.*;

/** Committed, run-owned schema: each save assertion is reread through a different connection. */
@EnabledIfEnvironmentVariable(named="DEV_DB_URL",matches=".+")
@EnabledIfEnvironmentVariable(named="APP_DEV_USER_ID",matches=".+")
class MoneyRecommendationPostgresTest {
 UUID owner=MoneyPostgresIntegrationTest.OWNER,account,category,otherCategory;String schema;
 JdbcTemplate root,db;com.zaxxer.hikari.HikariDataSource pool;MoneyService money;MoneyProductService product;MoneyWebService web;MoneyClassificationService classification;
 JsonMapper json=JsonMapper.builder().build();MoneyCommandService commands;DataSourceTransactionManager manager;
 AtomicInteger calls=new AtomicInteger();MoneyClassificationProvider provider;MoneyRecommendationService service;
 @BeforeEach void create()throws Exception{
  root=new JdbcTemplate(new DriverManagerDataSource(System.getenv("DEV_DB_URL"),System.getenv("DEV_DB_USERNAME"),System.getenv("DEV_DB_PASSWORD")));
  schema="qa_bk_v2_"+UUID.randomUUID().toString().replace("-","");root.execute("create schema "+schema);root.execute("comment on schema "+schema+" is 'owned-bk-v2-qa'");
  String url=System.getenv("DEV_DB_URL")+(System.getenv("DEV_DB_URL").contains("?")?"&":"?")+"currentSchema="+schema+",public";
  pool=new com.zaxxer.hikari.HikariDataSource();pool.setJdbcUrl(url);pool.setUsername(System.getenv("DEV_DB_USERNAME"));pool.setPassword(System.getenv("DEV_DB_PASSWORD"));pool.setMaximumPoolSize(2);pool.setMinimumIdle(0);pool.setConnectionTimeout(20000);pool.setPoolName(schema);db=new JdbcTemplate(pool);
  db.execute("create table qa_fixture_users(id uuid primary key)");db.update("insert into qa_fixture_users values(?)",owner);
  for(String migration:MoneyMobilePostgresTest.MONEY_MIGRATIONS)db.execute(Files.readString(Path.of("src/main/resources/db/migration",migration)).replace("REFERENCES auth.users","REFERENCES "+schema+".qa_fixture_users"));
  manager=new DataSourceTransactionManager(db.getDataSource());commands=new MoneyCommandService(db,json,manager);money=new MoneyService(db,()->owner,json);product=new MoneyProductService(db,()->owner,money,json);web=new MoneyWebService(db,()->owner,money,product,json);
  classification=new MoneyClassificationService(db,()->owner,json,web,new MoneyReviewService(db,()->owner,web,product,new MoneyMeaningService(db,()->owner,json),json),money,commands);
  account=money.createAccount(new AccountInput("IBK","Synthetic private account 123456789",AccountRole.SPENDING,null,null)).id();db.update("insert into money_tracking_settings(user_id) values(?) on conflict do nothing",owner);db.update("insert into money_tracking_accounts(user_id,kind,slot,account_id) values(?,'EXPENSE',1,?)",owner,account);
  category=product.saveCategory(null,new MoneyProductService.CategoryInput("합성 식사","#123456",false,null,"EXPENSE",null,0)).id();otherCategory=product.saveCategory(null,new MoneyProductService.CategoryInput("합성 생활용품","#123456",false,null,"EXPENSE",null,0)).id();
  provider=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return quoteReady();}public Result classify(Map<String,Object> input){calls.incrementAndGet();assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse();assertThat(input.toString()).doesNotContain("123456789","private memo","accountId","rawEventId");return new Result(category,"합성 구매 근거","MOCK","mock",null,100L,30L,"mock-"+UUID.randomUUID());}};
  service=service(provider,new BigDecimal("1"),new BigDecimal("10"),true);
 }
 MoneyClassificationProvider.Quote quoteReady(){return new MoneyClassificationProvider.Quote("MOCK","verified-test",new BigDecimal("0.4"),new BigDecimal("1.6"),1000,500,true);}
 MoneyRecommendationService service(MoneyClassificationProvider p,BigDecimal day,BigDecimal month,boolean worker){return new MoneyRecommendationService(db,()->owner,json,commands,new MoneyClassificationEngine(db,json,commands),p,manager,day,month,worker);}
 @AfterEach void cleanup(){if(schema!=null){if(pool!=null)pool.close();assertThat(root.queryForObject("select obj_description(oid,'pg_namespace') from pg_namespace where nspname=?",String.class,schema)).isEqualTo("owned-bk-v2-qa");root.execute("drop schema "+schema+" cascade");assertThat(root.queryForObject("select count(*) from pg_namespace where nspname=?",Long.class,schema)).isZero();}}
 UUID expense(String title){return product.save(null,new MoneyProductService.Entry(TransactionType.EXPENSE,account,null,new BigDecimal("1000"),Instant.parse("2026-09-15T01:00:00Z"),"합성 카페",null,"private memo",false,null,null,title)).id();}
 MoneyRecommendationService.Filters filters(){return new MoneyRecommendationService.Filters("2026-09-01","2026-09-30","EXPENSE","",false,null,null,null,null,"ALL",null);}
 UUID preview(String scope,List<UUID> ids,String explanation){return (UUID)service.preview(new MoneyRecommendationService.Preview(scope,ids,filters(),explanation)).get("id");}
 UUID start(UUID id){var r=service.run(id);service.start(new MoneyRecommendationService.Start(UUID.randomUUID(),id,r.get("fingerprint").toString(),MoneyRecommendationService.POLICY,true));return id;}
 List<Map<String,Object>> items(UUID run){return (List<Map<String,Object>>)service.items(run,0).get("items");}
 void process(UUID run){for(var item:db.queryForList("select id from money_recommendation_items where run_id=?",run))service.process(owner,(UUID)item.get("id"));}
 Map<String,Object> draft(UUID transaction){return ((List<Map<String,Object>>)service.drafts().get("items")).stream().filter(d->transaction.equals(d.get("transactionId"))).findFirst().orElseThrow();}
 MoneyRecommendationService.SaveItem saveItem(UUID transaction,UUID target){var d=draft(transaction);var active=(Map<String,Object>)d.get("active");return new MoneyRecommendationService.SaveItem(transaction,(UUID)d.get("id"),((Number)d.get("revision")).longValue(),target,active.get("stamp").toString(),false,null,false);}
 Map<String,Object> savedItem(Map<String,Object> saved,UUID transaction){return ((List<Map<String,Object>>)saved.get("items")).stream().filter(i->transaction.equals(i.get("transactionId"))).findFirst().orElseThrow();}
 @Test void bkQ07ConcurrentReadsReuseBoundConnectionsWithTwoConnectionPool()throws Exception{
  UUID id=expense("동시 구매 조회");process(start(preview("ONE",List.of(id),null)));
  var factory=new org.springframework.aop.framework.ProxyFactory(service);factory.setProxyTargetClass(true);
  factory.addAdvice(new org.springframework.transaction.interceptor.TransactionInterceptor(manager,new org.springframework.transaction.annotation.AnnotationTransactionAttributeSource()));
  var entered=new CountDownLatch(2);
  factory.addAdvice((org.aopalliance.intercept.MethodInterceptor) invocation->{assertThat(TransactionSynchronizationManager.isCurrentTransactionReadOnly()).isTrue();entered.countDown();assertThat(entered.await(10,TimeUnit.SECONDS)).isTrue();return invocation.proceed();});
  var reads=(MoneyRecommendationService)factory.getProxy();
  try(var executor=Executors.newFixedThreadPool(2)){
   var current=executor.submit(()->reads.current(id));var drafts=executor.submit(reads::drafts);
   assertThat(current.get(30,TimeUnit.SECONDS)).containsKeys("book","stamp");assertThat(drafts.get(30,TimeUnit.SECONDS).get("total")).isEqualTo(1);
  }
  assertThat(pool.getHikariPoolMXBean().getActiveConnections()).isZero();
 }
 @Test void bkQ01DraftAndAdoptionNeverWriteFactsOrCurrentClassificationBeforeExplicitSave(){UUID id=expense("커피");var fact=money.transaction(id);var book=web.bookkeepingRow(id);UUID run=start(preview("ONE",List.of(id),null));process(run);assertThat(money.transaction(id)).isEqualTo(fact);assertThat(web.bookkeepingRow(id)).isEqualTo(book);assertThat(classification.state(id)).containsEntry("version",0L);assertThat(db.queryForObject("select count(*) from money_review_decisions",Long.class)).isZero();var d=draft(id);assertThat(d).containsEntry("selected",true).containsEntry("saveEligible",true);
  var saved=service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(id,category))));assertThat(savedItem(saved,id)).containsEntry("status","SAVED");assertThat(classification.state(id)).containsEntry("origin","CONFIRMED");assertThat(money.transaction(id)).isEqualTo(fact);assertThat(db.queryForObject("select status from money_classification_drafts where transaction_id=?",String.class,id)).isEqualTo("SAVED");assertThat(db.queryForObject("select evidence::text from money_classification_events where transaction_id=?",String.class,id)).contains("MOCK","BOOKKEEPING_V2_EXPLICIT_SAVE");
 }
 @Test void bkQ02WholeFilterFreezesAllPagesAndProtectsExistingChoices(){db.update("insert into money_transactions(id,user_id,type,from_account_id,amount,occurred_at,counterparty_text,title,memo,manual) select gen_random_uuid(),?,'EXPENSE',?,1000,'2026-09-15T01:00:00Z'::timestamptz,'합성 카페','커피 '||n,'private memo',true from generate_series(1,103) n",owner,account);UUID direct=expense("직접 선택");var book=web.bookkeepingRow(direct);classification.classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(new MoneyClassificationService.Item(direct,((Number)book.get("transactionVersion")).longValue(),0L,((Number)book.get("projectionVersion")).longValue(),0L,category,true,false))));UUID run=preview("FILTER",null,null);assertThat(service.run(run)).containsEntry("total",103L).containsEntry("confirmationRequired",true);assertThatThrownBy(()->{var p=service.run(run);service.start(new MoneyRecommendationService.Start(UUID.randomUUID(),run,p.get("fingerprint").toString(),MoneyRecommendationService.POLICY,false));}).isInstanceOf(InvalidRequestException.class);start(run);expense("늦게 유입");assertThat(db.queryForObject("select count(distinct transaction_id) from money_recommendation_items where run_id=?",Long.class,run)).isEqualTo(103);assertThat(service.run(run).get("excluded")).asList().hasSize(1);assertThatThrownBy(()->service.current(UUID.randomUUID())).isInstanceOf(ResourceNotFoundException.class);
 }
 @Test void bkQ04KnownFailureCommitsOtherItemsAndRetriesOnlyTheFailure(){UUID a=expense("커피 A"),b=expense("커피 B"),c=expense("커피 C");process(start(preview("SELECTED",List.of(a,b,c),null)));
  db.execute("create function qa_fail_one() returns trigger language plpgsql as $$ begin if new.transaction_id='"+b+"' then raise exception 'synthetic known rollback' using errcode='23514'; end if; return new; end $$");db.execute("create trigger qa_fail before insert on money_classification_events for each row execute function qa_fail_one()");var command=new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(a,category),saveItem(b,category),saveItem(c,category)));var saved=service.save(command);assertThat(savedItem(saved,a)).containsEntry("status","SAVED");assertThat(savedItem(saved,b)).containsEntry("status","FAILED_KNOWN");assertThat(savedItem(saved,c)).containsEntry("status","SAVED");assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(2);assertThat(draft(b)).containsEntry("status","ACTIVE");db.execute("drop trigger qa_fail on money_classification_events");var retried=service.retry((UUID)saved.get("id"));assertThat(savedItem(retried,b)).containsEntry("status","SAVED");assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(3);assertThat(classification.state(a)).containsEntry("version",1L);assertThat(classification.state(c)).containsEntry("version",1L);
 }
 @Test void bkQ05ReplayAndLostResponseReturnSameCommittedEvents(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));var cmd=new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(id,category)));var saved=service.save(cmd);assertThat(service.save(cmd)).isEqualTo(saved);assertThat(service.saveOutcome(cmd.requestId())).isEqualTo(saved);assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(1);assertThatThrownBy(()->service.save(new MoneyRecommendationService.Save(cmd.requestId(),List.of(new MoneyRecommendationService.SaveItem(id,null,null,otherCategory,"wrong",false,null,false))))).isInstanceOf(InvalidRequestException.class);
 }
 @Test void bkQ06VersionConflictRequiresExplicitComparisonAndRechecksLatestStamp(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));var stale=saveItem(id,category);var b=web.bookkeepingRow(id);var overrides=new LinkedHashMap<>((Map<String,Object>)b.get("overrides"));overrides.put("memo","later memo");web.saveBookkeeping(id,new MoneyWebTypes.BookkeepingEdit(((Number)b.get("version")).longValue(),((Number)b.get("transactionVersion")).longValue(),overrides,((Number)b.get("projectionVersion")).longValue()));var failed=service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(stale)));assertThat(savedItem(failed,id)).containsEntry("status","STALE_CONFLICT");assertThat(service.retry((UUID)failed.get("id"))).isEqualTo(failed);var current=service.current(id);var compared=new MoneyRecommendationService.SaveItem(id,stale.draftId(),stale.revision(),otherCategory,current.get("stamp").toString(),false,stale.expectedStamp(),true);var saved=service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(compared)));assertThat(savedItem(saved,id)).containsEntry("status","SAVED");assertThat(web.bookkeepingRow(id)).containsEntry("memo","later memo").containsEntry("categoryId",otherCategory);assertThat(classification.state(id)).containsEntry("origin","DIRECT");
 }
 @Test void bkQ07RecoveryPreservesDeselectionAndUnknownLeaseCannotRedispatch(){UUID a=expense("커피 A"),b=expense("커피 B");UUID run=start(preview("SELECTED",List.of(a,b),null));var ids=db.queryForList("select id,transaction_id from money_recommendation_items where run_id=?",run);service.process(owner,(UUID)ids.stream().filter(i->a.equals(i.get("transaction_id"))).findFirst().orElseThrow().get("id"));var d=draft(a);service.selection((UUID)d.get("id"),new MoneyRecommendationService.Selection(((Number)d.get("revision")).longValue(),false));UUID item=(UUID)ids.stream().filter(i->b.equals(i.get("transaction_id"))).findFirst().orElseThrow().get("id");UUID attempt=UUID.randomUUID();db.update("insert into money_recommendation_usage(id,user_id,item_id,model,price_version,reserved_cost,day,month) values(?,?,?,'MOCK','verified',.01,current_date,date_trunc('month',current_date)::date)",attempt,owner,item);db.update("update money_recommendation_items set status='RUNNING',attempt_id=?,lease_until=now()-interval '1 minute' where id=?",attempt,item);service=service(provider,BigDecimal.ONE,BigDecimal.TEN,true);service.runDue();assertThat(draft(a)).containsEntry("selected",false);assertThat(db.queryForObject("select status from money_recommendation_items where id=?",String.class,item)).isEqualTo("EXTERNAL_OUTCOME_UNKNOWN");assertThat(calls.get()).isEqualTo(1);service.runDue();assertThat(calls.get()).isEqualTo(1);
 }
 @Test void bkQ12IdenticalAiInputReusesOnlyCurrentModelPolicyAndDictionary(){
  var model=new AtomicReference<>("MOCK");provider=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return new Quote(model.get(),"verified-test",new BigDecimal("0.4"),new BigDecimal("1.6"),1000,500,true);}public Result classify(Map<String,Object> input){calls.incrementAndGet();return new Result(category,"합성 구매 근거","MOCK",model.get(),null,100L,30L,"mock");}};service=service(provider,BigDecimal.ONE,BigDecimal.TEN,true);
  UUID id=expense("커피");process(start(preview("ONE",List.of(id),"원래 구매 설명")));var original=draft(id);
  UUID reuse=start(preview("REASSESS",List.of(id),"원래 구매 설명"));process(reuse);assertThat(calls.get()).isEqualTo(1);assertThat(service.run(reuse)).containsEntry("cacheTransactions",1L).containsEntry("internalTransactions",0L);assertThat((Map<String,Object>)service.run(reuse).get("usage")).containsEntry("attempts",0L);var d=draft(id);assertThat(d.get("active")).isEqualTo(original.get("active"));var candidate=(Map<String,Object>)d.get("candidate");assertThat(candidate).containsEntry("origin","AI");assertThat((Map<String,Object>)candidate.get("result")).containsEntry("provider","CACHED").containsEntry("originalProvider","MOCK");assertThat(classification.state(id)).containsEntry("version",0L);
  keepCandidate(id);process(start(preview("REASSESS",List.of(id),"다른 구매 설명")));assertThat(calls.get()).isEqualTo(2);keepCandidate(id);
  model.set("OTHER");process(start(preview("REASSESS",List.of(id),"원래 구매 설명")));assertThat(calls.get()).isEqualTo(3);keepCandidate(id);model.set("MOCK");
  db.update("update money_categories set version=version+1 where id=?",category);process(start(preview("REASSESS",List.of(id),"원래 구매 설명")));assertThat(calls.get()).isEqualTo(4);
  // A result from an earlier policy is never reused, even when transaction and model match.
  UUID fresh=expense("다른 커피");process(start(preview("ONE",List.of(fresh),"원래 구매 설명")));db.update("update money_recommendation_runs set policy_version='OLD' where id=(select i.run_id from money_classification_draft_revisions v join money_recommendation_items i on i.id=v.item_id where v.draft_id=? and v.revision=1)",draft(fresh).get("id"));process(start(preview("REASSESS",List.of(fresh),"원래 구매 설명")));assertThat(calls.get()).isEqualTo(6);assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isZero();
 }
 void keepCandidate(UUID id){var d=draft(id);service.decision((UUID)d.get("id"),new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)d.get("revision")).longValue(),((Number)d.get("candidateRevision")).longValue(),d.get("currentStamp").toString(),((Number)d.get("contextVersion")).longValue(),"KEEP"));}
 @Test void bkQ08ReassessmentKeepsOriginalAndAdoptionRemainsUnconfirmed(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));var original=draft(id);UUID run=start(preview("REASSESS",List.of(id),"생활용품 구매"));process(run);var d=draft(id);assertThat(d.get("active")).isEqualTo(original.get("active"));assertThat(d).containsEntry("status","COMPARISON_PENDING");assertThat(classification.state(id)).containsEntry("version",0L);var command=new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)d.get("revision")).longValue(),((Number)d.get("candidateRevision")).longValue(),d.get("currentStamp").toString(),((Number)d.get("contextVersion")).longValue(),"ADOPT");service.decision((UUID)d.get("id"),command);assertThat(draft(id)).containsEntry("status","ACTIVE").containsEntry("saveEligible",true);assertThat(classification.state(id)).containsEntry("version",0L);assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isZero();
 }
 @Test void bkQ09SharedEngineTrustsOnlyLatestValidPurchaseContext(){UUID reference=expense("커피");process(start(preview("ONE",List.of(reference),null)));service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(reference,otherCategory))));UUID target=expense("커피");process(start(preview("ONE",List.of(target),null)));assertThat(((Map<?,?>)draft(target).get("active")).get("origin")).isEqualTo("DIRECT_REFERENCE");assertThat(calls.get()).isEqualTo(1);UUID different=expense("생활용품");process(start(preview("ONE",List.of(different),null)));assertThat(calls.get()).isEqualTo(2);classification.exclude(new MoneyClassificationService.Exclusion(UUID.randomUUID(),reference,1L,true));UUID excluded=expense("커피");process(start(preview("ONE",List.of(excluded),null)));assertThat(calls.get()).isEqualTo(3);
 }
 @Test void bkQ12BudgetIncludesHeldUnknownAndKoreanPeriodBoundary(){UUID id=expense("커피");service=service(provider,new BigDecimal("0.001"),BigDecimal.TEN,true);UUID run=start(preview("ONE",List.of(id),null));process(run);assertThat(calls.get()).isZero();assertThat(items(run).getFirst()).containsEntry("status","BUDGET_WAIT");service=service(provider,BigDecimal.ONE,BigDecimal.TEN,true);service.clock(Clock.fixed(Instant.parse("2026-10-31T15:00:00Z"),ZoneOffset.UTC));process(run);assertThat(calls.get()).isEqualTo(1);assertThat(db.queryForObject("select day::text from money_recommendation_usage",String.class)).isEqualTo("2026-11-01");assertThat(db.queryForObject("select month::text from money_recommendation_usage",String.class)).isEqualTo("2026-11-01");assertThat(db.queryForObject("select status from money_recommendation_usage",String.class)).isEqualTo("ACTUAL");
 }
 @Test void bkQ12AtMostTwoExternalDispatchesReserveBeforeNetworkAndReleaseOwnerLock()throws Exception{var entered=new CountDownLatch(2);var release=new CountDownLatch(1);AtomicInteger calls=new AtomicInteger();MoneyClassificationProvider blocking=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return quoteReady();}public Result classify(Map<String,Object> input){calls.incrementAndGet();entered.countDown();try{assertThat(release.await(20,TimeUnit.SECONDS)).isTrue();}catch(InterruptedException e){throw new RuntimeException(e);}return new Result(category,"mock","MOCK","mock",null,100L,20L,"mock");}};service=service(blocking,BigDecimal.ONE,BigDecimal.TEN,true);UUID run=start(preview("SELECTED",List.of(expense("A"),expense("B"),expense("C")),null));var items=db.queryForList("select id from money_recommendation_items where run_id=? order by id",run);try(var pool=Executors.newFixedThreadPool(3)){var first=pool.submit(()->service.process(owner,(UUID)items.get(0).get("id")));var second=pool.submit(()->service.process(owner,(UUID)items.get(1).get("id")));assertThat(entered.await(20,TimeUnit.SECONDS)).isTrue();var third=pool.submit(()->service.process(owner,(UUID)items.get(2).get("id")));third.get(15,TimeUnit.SECONDS);assertThat(calls.get()).isEqualTo(2);assertThat(db.queryForObject("select count(*) from money_recommendation_usage where status='HELD'",Long.class)).isEqualTo(2);release.countDown();first.get(20,TimeUnit.SECONDS);second.get(20,TimeUnit.SECONDS);}finally{release.countDown();}
 }
 @Test void bkQ09UnclassifiableCandidatePreservesOriginalAndExplicitKeepIsStillSaveable(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));var before=web.bookkeepingRow(id);var original=draft(id);var nullProvider=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return quoteReady();}public Result classify(Map<String,Object> input){return new Result(null,"구매 의미 부족","MOCK","mock",null,100L,30L,"mock");}};service=service(nullProvider,BigDecimal.ONE,BigDecimal.TEN,true);process(start(preview("REASSESS",List.of(id),"구매 구분 불가")));var compared=draft(id);assertThat(compared.get("active")).isEqualTo(original.get("active"));assertThat(((Map<?,?>)compared.get("candidate")).get("categoryId")).isNull();assertThat(web.bookkeepingRow(id)).isEqualTo(before);assertThatThrownBy(()->service.decision((UUID)compared.get("id"),new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)compared.get("revision")).longValue(),((Number)compared.get("candidateRevision")).longValue(),compared.get("currentStamp").toString(),((Number)compared.get("contextVersion")).longValue(),"ADOPT"))).isInstanceOf(InvalidRequestException.class);service.decision((UUID)compared.get("id"),new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)compared.get("revision")).longValue(),((Number)compared.get("candidateRevision")).longValue(),compared.get("currentStamp").toString(),((Number)compared.get("contextVersion")).longValue(),"KEEP"));assertThat(draft(id)).containsEntry("saveEligible",true);assertThat(classification.state(id)).containsEntry("version",0L);
  UUID noDraft=expense("분류 불가");UUID run=start(preview("ONE",List.of(noDraft),null));process(run);assertThat(draft(noDraft)).containsEntry("status","UNCLASSIFIABLE").containsEntry("saveEligible",false);assertThat(items(run).getFirst()).containsEntry("status","UNCLASSIFIABLE");assertThat(web.bookkeepingRow(noDraft)).containsEntry("categoryId",null);
 }
 @Test void bkQ09ThreeDistinctConsistentConfirmationsRequiredAndCategoryVersionInvalidatesTrust(){var engine=new MoneyClassificationEngine(db,json,commands);var confirmed=new ArrayList<UUID>();for(int i=0;i<3;i++){UUID id=expense("커피");confirmed.add(id);process(start(preview("ONE",List.of(id),null)));service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(id,category))));UUID target=expense("커피");var decision=engine.evaluate(owner,target,web.bookkeepingRow(target));assertThat(decision.categoryId()).isEqualTo(i<2?null:category);}UUID changed=expense("커피");db.update("update money_categories set version=version+1 where id=?",category);assertThat(engine.evaluate(owner,changed,web.bookkeepingRow(changed)).categoryId()).isNull();assertThat(db.queryForObject("select count(*) from money_classification_events where origin='CONFIRMED'",Long.class)).isEqualTo(3);
 }
 @Test void bkQ08KnownReassessmentFailureRestoresSaveableOriginalExplanation(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),"원래 커피 구매 설명")));var original=draft(id);var failing=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return quoteReady();}public Result classify(Map<String,Object> input){return new Result(null,"확인된 제공자 거절","MOCK","mock","PROVIDER_HTTP_400");}};service=service(failing,BigDecimal.ONE,BigDecimal.TEN,true);UUID run=start(preview("REASSESS",List.of(id),"새 생활용품 설명"));process(run);assertThat(items(run).getFirst()).containsEntry("status","FAILED_KNOWN");var recovered=draft(id);assertThat(recovered).containsEntry("status","ACTIVE").containsEntry("explanation","원래 커피 구매 설명").containsEntry("saveEligible",true);assertThat(recovered.get("active")).isEqualTo(original.get("active"));assertThat(service.usage().get("items")).asList().isNotEmpty();assertThat(savedItem(service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(id,category)))),id)).containsEntry("status","SAVED");}
 @Test void bkQ10FinancialAndOwnerBoundariesAndBkQ11UndoPreserveLaterText(){UUID a=expense("커피 A"),b=expense("커피 B");var factA=money.transaction(a);var factB=money.transaction(b);process(start(preview("SELECTED",List.of(a,b),null)));var saved=service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(a,category),saveItem(b,category))));var eventA=(UUID)savedItem(saved,a).get("eventId");var eventB=(UUID)savedItem(saved,b).get("eventId");var row=web.bookkeepingRow(a);var overrides=new LinkedHashMap<>((Map<String,Object>)row.get("overrides"));overrides.put("title","나중 제목");web.saveBookkeeping(a,new MoneyWebTypes.BookkeepingEdit(((Number)row.get("version")).longValue(),((Number)row.get("transactionVersion")).longValue(),overrides,((Number)row.get("projectionVersion")).longValue()));var preview=classification.undoPreview(List.of(eventA,eventB));assertThat(preview.get("eligibleEventIds")).asList().contains(eventA,eventB);var undone=classification.undo(new MoneyClassificationService.Undo(UUID.randomUUID(),List.of(eventA,eventB),preview.get("fingerprint").toString()));assertThat(undone).containsEntry("status","APPLIED");assertThat(web.bookkeepingRow(a)).containsEntry("title","나중 제목").containsEntry("categoryId",null);assertThat(money.transaction(a)).isEqualTo(factA);assertThat(money.transaction(b)).isEqualTo(factB);assertThat(db.queryForObject("select count(*) from money_classification_drafts where status not in ('SAVED','EXCLUDED')",Long.class)).isZero();
  UUID excluded=expense("제외");db.update("update money_transactions set excluded=true where id=?",excluded);assertThat(service.run(preview("ONE",List.of(excluded),null))).containsEntry("total",0L);var outsider=new MoneyRecommendationService(db,UUID::randomUUID,json,commands,new MoneyClassificationEngine(db,json,commands),provider,manager,BigDecimal.ONE,BigDecimal.TEN,true);assertThatThrownBy(()->outsider.run((UUID)db.queryForList("select id from money_recommendation_runs").getFirst().get("id"))).isInstanceOf(ResourceNotFoundException.class);assertThat(outsider.drafts().get("items")).asList().isEmpty();
 }

 @Test void bkQ08ChangedExplanationInvalidatesCandidateWithoutWritingClassification(){UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));process(start(preview("REASSESS",List.of(id),"새 구매 설명")));var before=web.bookkeepingRow(id);var d=draft(id);long context=((Number)d.get("contextVersion")).longValue();var edit=new MoneyRecommendationService.ContextEdit(UUID.randomUUID(),context,"다른 구매 설명");var outcome=service.context((UUID)d.get("id"),edit);assertThat(service.context((UUID)d.get("id"),edit)).isEqualTo(outcome);var changed=draft(id);assertThat(changed).containsEntry("contextVersion",context+1).containsEntry("saveEligible",false);assertThat(changed.get("active")).isEqualTo(d.get("active"));assertThat(changed.get("candidate")).isEqualTo(d.get("candidate"));assertThatThrownBy(()->service.decision((UUID)d.get("id"),new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)d.get("revision")).longValue(),((Number)d.get("candidateRevision")).longValue(),d.get("currentStamp").toString(),context+1,"ADOPT"))).isInstanceOf(InvalidRequestException.class);service.decision((UUID)d.get("id"),new MoneyRecommendationService.Decision(UUID.randomUUID(),((Number)d.get("revision")).longValue(),((Number)d.get("candidateRevision")).longValue(),d.get("currentStamp").toString(),context+1,"KEEP"));assertThat(draft(id)).containsEntry("saveEligible",true);assertThat(web.bookkeepingRow(id)).isEqualTo(before);assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isZero();}
 @Test void bkQ08LateReassessmentCannotOverwriteTypedContext()throws Exception{UUID id=expense("커피");process(start(preview("ONE",List.of(id),null)));var entered=new CountDownLatch(1);var release=new CountDownLatch(1);var blocking=new MoneyClassificationProvider(){public Quote quote(Map<String,Object> input){return quoteReady();}public Result classify(Map<String,Object> input){entered.countDown();try{assertThat(release.await(20,TimeUnit.SECONDS)).isTrue();}catch(InterruptedException e){throw new RuntimeException(e);}return new Result(otherCategory,"합성 후보","MOCK","mock",null,100L,20L,"mock");}};service=service(blocking,BigDecimal.ONE,BigDecimal.TEN,true);UUID run=start(preview("REASSESS",List.of(id),"요청 설명"));UUID item=(UUID)db.queryForList("select id from money_recommendation_items where run_id=?",run).getFirst().get("id");try(var executor=Executors.newSingleThreadExecutor()){var future=executor.submit(()->service.process(owner,item));assertThat(entered.await(20,TimeUnit.SECONDS)).isTrue();var d=draft(id);service.context((UUID)d.get("id"),new MoneyRecommendationService.ContextEdit(UUID.randomUUID(),((Number)d.get("contextVersion")).longValue(),"새로 입력한 설명"));release.countDown();future.get(20,TimeUnit.SECONDS);assertThat(draft(id)).containsEntry("explanation","새로 입력한 설명").containsEntry("status","ACTIVE").containsEntry("saveEligible",false).containsEntry("candidateRevision",null);assertThat(items(run).getFirst()).containsEntry("status","STALE_CONFLICT");assertThat(classification.state(id)).containsEntry("version",0L);}finally{release.countDown();}}

 @Test void bkQ07InterruptedSaveUsesOriginalOperationAndNeverRepeatsCommittedEvent(){UUID a=expense("커피 A"),b=expense("커피 B");process(start(preview("SELECTED",List.of(a,b),null)));var saved=service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(saveItem(a,category),saveItem(b,category))));UUID operation=(UUID)saved.get("id");db.update("update money_recommendation_save_items set status='OUTCOME_UNKNOWN' where save_id=?",operation);var recovered=service.reconcileSave(operation);assertThat(((List<Map<String,Object>>)recovered.get("items"))).allSatisfy(item->assertThat(item).containsEntry("status","SAVED").containsEntry("attempts",1));assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(2);assertThat(service.reconcileSave(operation)).isEqualTo(recovered);}
 @Test void bkQ09MerchantOnlyDirectChoiceNeverBecomesPurchaseDefault(){
  UUID reference=expense("구매"),target=expense("구매");
  db.update("update money_transactions set title='쿠팡 결제',counterparty_text='쿠팡',memo=null where id in (?,?)",reference,target);
  var book=web.bookkeepingRow(reference);
  classification.classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(new MoneyClassificationService.Item(reference,((Number)book.get("transactionVersion")).longValue(),0L,((Number)book.get("projectionVersion")).longValue(),0L,otherCategory,false,false))));
  process(start(preview("ONE",List.of(target),null)));
  assertThat(calls.get()).isEqualTo(1);assertThat(((Map<?,?>)draft(target).get("active")).get("origin")).isEqualTo("AI");
 }
 @Test void bkQ10FinancialReviewAndRawBoundariesCannotBeBypassedByRecommendationSave(){
  UUID pair=expense("이체 판단 대기");process(start(preview("ONE",List.of(pair),null)));var command=saveItem(pair,category);var original=money.transaction(pair);
  UUID second=money.createAccount(new AccountInput("IBK","합성 상대 계좌",AccountRole.SPENDING,null,null)).id();
  var income=product.save(null,new MoneyProductService.Entry(TransactionType.INCOME,null,second,new BigDecimal("1000"),original.occurredAt(),"합성 상대",null,null,false,null,null,"이체 후보"));
  assertThat(db.queryForList(MoneyReviewService.QUEUE+"select reason from queue where id=? and kind='TRANSACTION'",owner,pair)).extracting(r->r.get("reason")).contains("POSSIBLE_INTERNAL_TRANSFER");
  assertThat(savedItem(service.save(new MoneyRecommendationService.Save(UUID.randomUUID(),List.of(command))),pair).get("status")).isNotEqualTo("SAVED");assertThat(classification.state(pair)).containsEntry("version",0L);assertThat(money.transaction(pair)).isEqualTo(original);assertThat(db.queryForObject("select count(*) from money_review_decisions",Long.class)).isZero();
  UUID refund=product.save(null,new MoneyProductService.Entry(TransactionType.REFUND,null,account,new BigDecimal("10"),original.occurredAt().plusSeconds(3600),"합성 환불",null,null,false,null,null,"환불 연결 필요")).id();
  UUID linkedRefund=product.save(null,new MoneyProductService.Entry(TransactionType.REFUND,null,account,new BigDecimal("10"),original.occurredAt().plusSeconds(3600),"합성 환불",null,null,false,pair,null,"연결된 환불")).id();
  UUID merged=expense("합쳐진 원본");db.update("update money_transactions set merged_into=? where id=?",pair,merged);
  UUID untracked=product.save(null,new MoneyProductService.Entry(TransactionType.EXPENSE,second,null,new BigDecimal("20"),original.occurredAt().plusSeconds(3600),"합성 소비",null,null,false,null,null,"미추적 계좌")).id();
  UUID transfer=product.save(null,new MoneyProductService.Entry(TransactionType.TRANSFER,account,second,new BigDecimal("30"),original.occurredAt().plusSeconds(3600),"합성 이체",null,null,false,null,null,"확정 이체")).id();
  UUID loan=UUID.randomUUID(),payment=UUID.randomUUID(),raw=UUID.randomUUID();db.update("insert into money_loans(id,user_id,name,lender,type,remaining_principal,payment_account_id) values(?,?, '합성 대출','합성 금융사','TEST',1000,?)",loan,owner,account);
  db.update("insert into money_transactions(id,user_id,type,from_account_id,amount,occurred_at,loan_id,title,manual) values(?,?,'LOAN_PAYMENT',?,50,?,?, '대출 분할 필요',true)",payment,owner,account,java.sql.Timestamp.from(original.occurredAt().plusSeconds(3600)),loan);
  db.update("insert into money_raw_notifications(id,user_id,posted_at,raw_payload,dedupe_key,content_hash,state,processing_reason) values(?,?,now(),'{}',?,?,'REVIEW_REQUIRED','POSSIBLE_DUPLICATE')",raw,owner,raw.toString(),raw.toString());
  UUID currentPair=expense("추가 이체 판단 대기");var boundaries=List.of(currentPair,income.id(),refund,linkedRefund,merged,untracked,transfer,payment,raw,account);var factsBefore=db.queryForList("select to_jsonb(t)::text as fact from money_transactions t order by id");
  var blocked=service.run(preview("SELECTED",boundaries,null));assertThat(blocked).containsEntry("total",0L);assertThat(blocked.get("excluded")).asList().hasSize(boundaries.size());
  assertThat(db.queryForList("select to_jsonb(t)::text as fact from money_transactions t order by id")).isEqualTo(factsBefore);assertThat(db.queryForObject("select state from money_raw_notifications where id=?",String.class,raw)).isEqualTo("REVIEW_REQUIRED");assertThat(db.queryForObject("select principal from money_transactions where id=?",BigDecimal.class,payment)).isNull();assertThat(db.queryForObject("select count(*) from money_classification_events",Long.class)).isZero();
  var outsider=new MoneyRecommendationService(db,UUID::randomUUID,json,commands,new MoneyClassificationEngine(db,json,commands),provider,manager,BigDecimal.ONE,BigDecimal.TEN,true);assertThatThrownBy(()->outsider.current(pair)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->outsider.draftHistory(pair)).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->outsider.saved((UUID)db.queryForList("select id from money_recommendation_saves").getFirst().get("id"))).isInstanceOf(ResourceNotFoundException.class);assertThat(outsider.usage().get("items")).asList().isEmpty();
 }
 @Test void bkQ02RuleProjectionIsNotMistakenForConfirmedUserChoice(){UUID id=expense("커피");db.update("insert into money_rule_projections(user_id,transaction_id,defaults,evidence) values(?,?,cast(? as jsonb),'{}')",owner,id,json.writeValueAsString(Map.of("categoryId",category)));assertThat(web.bookkeepingRow(id)).containsEntry("categoryId",category);assertThat(service.run(preview("ONE",List.of(id),null))).containsEntry("total",1L);assertThat(classification.state(id)).containsEntry("version",0L);}
}
