package com.kafka.backend.money;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.json.JsonMapper;
import java.math.BigDecimal;
import java.util.*;
import static com.kafka.backend.money.MoneyTypes.*;
import static org.assertj.core.api.Assertions.*;

@EnabledIfEnvironmentVariable(named="DEV_DB_URL",matches=".+")
@EnabledIfEnvironmentVariable(named="APP_DEV_USER_ID",matches=".+")
class MoneyClassificationPostgresTest {
 private final MoneyMobilePostgresTest fixture=new MoneyMobilePostgresTest();
 record Context(MoneyClassificationService service,MoneyCommandService commands,MoneyWebService web,MoneyProductService product,MoneyService money,MoneyAccount account,org.springframework.jdbc.core.JdbcTemplate db){}
 interface Scenario{void run(Context c);}
 private void isolated(Scenario scenario)throws Exception{fixture.isolated((db,m,p,w,mobile)->{var manager=new DataSourceTransactionManager(db.getDataSource());var json=JsonMapper.builder().build();var owner=MoneyPostgresIntegrationTest.OWNER;var commands=new MoneyCommandService(db,json,manager);var review=new MoneyReviewService(db,()->owner,w,p,new MoneyMeaningService(db,()->owner,json),json);var service=new MoneyClassificationService(db,()->owner,json,w,review,m,commands);new TransactionTemplate(manager).execute(status->{try{scenario.run(new Context(service,commands,w,p,m,fixture.account(m,AccountRole.SPENDING),db));return null;}finally{status.setRollbackOnly();}});});}
 private MoneyTransaction expense(Context c){return c.product().save(null,new MoneyProductService.Entry(TransactionType.EXPENSE,c.account().id(),null,new BigDecimal("1000"),fixture.at,"Synthetic café",null,"source memo",false,null,null,"source title"));}
 private UUID category(Context c,String name){return c.product().saveCategory(null,new MoneyProductService.CategoryInput(name,"#123456",false,null,"EXPENSE",null,0)).id();}
 private MoneyClassificationService.Item item(Context c,UUID id,UUID category,boolean only){var b=c.web().bookkeepingRow(id);return new MoneyClassificationService.Item(id,((Number)b.get("transactionVersion")).longValue(),((Number)b.get("version")).longValue(),((Number)b.get("projectionVersion")).longValue(),((Number)c.service().state(id).get("version")).longValue(),category,true,only);}
 private Map<String,Object> result(Map<String,Object> outcome){assertThat(outcome.get("status")).isEqualTo("APPLIED");return (Map<String,Object>)outcome.get("result");}
 private MoneyAiWorkspaceService workspace(Context c){var json=JsonMapper.builder().build();return new MoneyAiWorkspaceService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,json,c.commands(),new MoneyMeaningService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,json),c.web(),c.money());}
 private MoneyMeaningService.RuleInput rule(Context c,UUID category,String name){var conditions=new ArrayList<>(List.of(new MoneyRuleEngine.Condition("type","EXACT","EXPENSE"),new MoneyRuleEngine.Condition("accountId","EXACT",c.account().id().toString()),new MoneyRuleEngine.Condition("merchant","EXACT",name)));if(!MoneyClassificationContext.business(name)||MoneyClassificationContext.multiPurpose(name))conditions.add(new MoneyRuleEngine.Condition("title","CONTAINS","source"));return new MoneyMeaningService.RuleInput(name,conditions,category,null,null,"ACTIVE",0L);}
 private UUID draft(Context c,MoneyAiWorkspaceService ws,UUID category,String name,UUID conversation){var saved=result(ws.saveDraft(new MoneyAiWorkspaceService.DraftInput(UUID.randomUUID(),null,null,conversation,null,0L,"모의 초안 "+name,rule(c,category,name))));return UUID.fromString(((Map<?,?>)saved.get("draft")).get("id").toString());}
 @Test void conversationPersistenceReferencesDeletionAndExpiryNeverExecuteRulesOrDeleteOpenDrafts()throws Exception{isolated(c->{var tx=expense(c);UUID category=category(c,"Synthetic food");var ws=workspace(c);var saved=result(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,"선택 거래의 분류 근거를 설명해 주세요.",List.of(tx.id()))));var conversation=(Map<String,Object>)saved.get("conversation");UUID id=UUID.fromString(conversation.get("id").toString());assertThat(ws.readConversation(id).get("messages")).asList().hasSize(2);UUID draft=draft(c,ws,category,"Synthetic café",id);assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isZero();c.db().update("update money_ai_conversations set last_activity_at=now()-interval '91 days' where id=?",id);assertThat(ws.read().get("conversations").toString()).contains("expiredAt");assertThat(ws.readConversation(id).get("messages")).asList().isEmpty();assertThat(ws.retain()).containsEntry("expiredConversations",0);assertThat(ws.read().get("drafts")).asList().hasSize(1);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);assertThat(c.db().queryForObject("select status from money_ai_rule_drafts where id=?",String.class,draft)).isEqualTo("OPEN");});}
 @Test void selectedRuleApprovalIsAtomicCurrentVersionAndFutureOnly()throws Exception{isolated(c->{var tx=expense(c);UUID category=category(c,"Synthetic food");var ws=workspace(c);UUID one=draft(c,ws,category,"Merchant one",null),two=draft(c,ws,category,"Merchant two",null);var selected=List.of(new MoneyAiWorkspaceService.Selection(one,1L),new MoneyAiWorkspaceService.Selection(two,1L));var preview=ws.preview(selected);assertThat(preview).containsEntry("canApply",true);var approved=result(ws.approve(new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),selected,preview.get("fingerprint").toString())));assertThat(((Number)approved.get("applied")).intValue()).isEqualTo(2);assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isEqualTo(2);assertThat(c.web().bookkeepingRow(tx.id()).get("categoryId")).isNull();assertThat(c.money().transaction(tx.id())).isEqualTo(tx);});}
 @Test void ruleBundleFailureAfterFirstWriteRollsBackEveryRuleAndKeepsEveryDraft()throws Exception{isolated(c->{UUID category=category(c,"Synthetic food");var ws=workspace(c);UUID one=draft(c,ws,category,"Merchant one",null);var invalid=new MoneyMeaningService.RuleInput("Second",List.of(new MoneyRuleEngine.Condition("type","EXACT","EXPENSE"),new MoneyRuleEngine.Condition("title","CONTAINS","x".repeat(501))),category,null,null,"ACTIVE",0L);var saved=result(ws.saveDraft(new MoneyAiWorkspaceService.DraftInput(UUID.randomUUID(),null,null,null,null,0L,"Second",invalid)));UUID two=UUID.fromString(((Map<?,?>)saved.get("draft")).get("id").toString());var selected=List.of(new MoneyAiWorkspaceService.Selection(one,1L),new MoneyAiWorkspaceService.Selection(two,1L));var preview=ws.preview(selected);var outcome=ws.approve(new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),selected,preview.get("fingerprint").toString()));assertThat(outcome).containsEntry("status","NOT_APPLIED");assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isZero();assertThat(c.db().queryForObject("select count(*) from money_ai_rule_drafts where status='OPEN'",Long.class)).isEqualTo(2);});}
 @Test void previewSourceOrImpactConflictLeavesSelectedRulesUnapplied()throws Exception{isolated(c->{UUID category=category(c,"Synthetic food");var ws=workspace(c);UUID one=draft(c,ws,category,"Merchant one",null);var selected=List.of(new MoneyAiWorkspaceService.Selection(one,1L));var preview=ws.preview(selected);expense(c);var outcome=ws.approve(new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),selected,preview.get("fingerprint").toString()));assertThat(outcome).containsEntry("status","NOT_APPLIED");assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isZero();});}
 private MoneyClassificationAutomaticService automation(Context c,MoneyClassificationProvider provider){c.db().update("insert into money_tracking_settings(user_id) values(?) on conflict do nothing",MoneyPostgresIntegrationTest.OWNER);c.db().update("insert into money_tracking_accounts(user_id,kind,slot,account_id) values(?,'EXPENSE',1,?) on conflict do nothing",MoneyPostgresIntegrationTest.OWNER,c.account().id());return new MoneyClassificationAutomaticService(c.db(),JsonMapper.builder().build(),c.commands(),provider,new DataSourceTransactionManager(c.db().getDataSource()));}
 @Test void automatedMeaningPersistsAndProviderReceivesOnlyMinimizedInput()throws Exception{isolated(c->{var tx=expense(c);var category=category(c,"Synthetic food");var auto=automation(c,input->{assertThat(input).doesNotContainKeys("amount","accountId","memo","title","body","balance");assertThat(input.toString()).doesNotContain("source memo",c.account().displayName());return new MoneyClassificationProvider.Result(category,"모의 분류 근거","MOCK","synthetic",null);});assertThat(auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false)).isTrue();assertThat(c.service().state(tx.id())).containsEntry("origin","AI").containsEntry("directProtected",false);assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("categoryId",category).containsEntry("classificationJobStatus","SUCCEEDED");assertThat(c.money().transaction(tx.id())).isEqualTo(tx);});}
 @Test void providerFailureLeavesEligibleUncategorizedFactAndReviewPending()throws Exception{isolated(c->{var tx=expense(c);automation(c,input->new MoneyClassificationProvider.Result(null,"모의 시간 초과","MOCK",null,"TIMEOUT")).run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false);assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("categoryId",null).containsEntry("classificationJobStatus","FAILED");assertThat(c.db().queryForObject("select count(*) from money_review_decisions",Long.class)).isZero();assertThat(c.money().transaction(tx.id())).isEqualTo(tx);});}
 @Test void lateProviderCannotOverwriteDirectChoiceOrLatestTitle()throws Exception{isolated(c->{var tx=expense(c);UUID predicted=category(c,"Synthetic food"),direct=category(c,"Synthetic transport");automation(c,input->{var b=c.web().bookkeepingRow(tx.id());result(c.service().edit(new MoneyClassificationService.Edit(UUID.randomUUID(),tx.id(),0L,((Number)b.get("version")).longValue(),0L,Map.of("title","Latest purchase","categoryId",direct.toString()),List.of())));return new MoneyClassificationProvider.Result(predicted,"늦은 모의 결과","MOCK",null,null);}).run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false);assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("title","Latest purchase").containsEntry("categoryId",direct);assertThat(c.service().state(tx.id())).containsEntry("origin","DIRECT");assertThat(c.db().queryForObject("select count(*) from money_classification_events where origin='AI'",Long.class)).isZero();});}
 @Test void directReferenceIsContextScopedAndStickyExclusionSurvivesResave()throws Exception{isolated(c->{var source=expense(c);var target=expense(c);var category=category(c,"Synthetic food");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,source.id(),category,true)))));result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,source.id(),category,false)))));assertThat(c.service().state(source.id())).containsEntry("futureReferenceExcluded",true);var calls=new java.util.concurrent.atomic.AtomicInteger();var auto=automation(c,input->{calls.incrementAndGet();return new MoneyClassificationProvider.Result(null,"모의 미분류","MOCK",null,"NO_RESULT");});auto.run(MoneyPostgresIntegrationTest.OWNER,target.id(),false);assertThat(calls.get()).isEqualTo(1);var state=c.service().state(source.id());result(c.service().exclude(new MoneyClassificationService.Exclusion(UUID.randomUUID(),source.id(),((Number)state.get("version")).longValue(),false)));auto.run(MoneyPostgresIntegrationTest.OWNER,target.id(),true);assertThat(calls.get()).isEqualTo(1);assertThat(c.service().state(target.id())).containsEntry("origin","DIRECT_REFERENCE");assertThat(c.web().bookkeepingRow(source.id())).containsEntry("categoryId",category);});}
 @Test void ownerUndoIsNotImmediatelyReappliedAndConfirmationIsNotHumanCorrection()throws Exception{isolated(c->{var tx=expense(c);var category=category(c,"Synthetic food");var calls=new java.util.concurrent.atomic.AtomicInteger();var auto=automation(c,input->{calls.incrementAndGet();return new MoneyClassificationProvider.Result(category,"모의","MOCK",null,null);});auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false);UUID event=(UUID)c.service().state(tx.id()).get("eventId");var preview=c.service().undoPreview(List.of(event));result(c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),List.of(event),preview.get("fingerprint").toString())));c.db().update("update money_classification_jobs set status='QUEUED' where transaction_id=?",tx.id());auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false);assertThat(calls.get()).isEqualTo(1);assertThat(c.web().bookkeepingRow(tx.id()).get("categoryId")).isNull();});}
 @Test void finalClassificationPersistsWithProvenanceCompletesReviewAndReplaysExactRequest()throws Exception{isolated(c->{var tx=expense(c);UUID category=category(c,"Synthetic food"),request=UUID.randomUUID();var bundle=new MoneyClassificationService.Bundle(request,List.of(item(c,tx.id(),category,true)));var outcome=c.service().classify(bundle);result(outcome);assertThat(c.service().classify(bundle)).isEqualTo(outcome);assertThat(c.service().outcome(request)).isEqualTo(outcome);assertThat(c.web().bookkeepingRow(tx.id()).get("categoryId")).isEqualTo(category);assertThat(c.service().state(tx.id())).containsEntry("origin","DIRECT").containsEntry("futureReferenceExcluded",true);assertThat(c.db().queryForObject("select count(*) from money_review_decisions where transaction_id=?",Long.class,tx.id())).isEqualTo(1L);assertThat(c.db().queryForObject("select count(*) from money_classification_events where transaction_id=?",Long.class,tx.id())).isEqualTo(1L);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);});}
 @Test void oneStaleRowLeavesEntireExplicitBundleUnapplied()throws Exception{isolated(c->{var one=expense(c);var two=expense(c);var category=category(c,"Synthetic food");var stale=new MoneyClassificationService.Item(two.id(),0L,99L,0L,0L,category,true,false);var outcome=c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,one.id(),category,false),stale)));assertThat(outcome.get("status")).isEqualTo("NOT_APPLIED");assertThat(c.web().bookkeepingRow(one.id()).get("categoryId")).isNull();assertThat(c.web().bookkeepingRow(two.id()).get("categoryId")).isNull();assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isZero();});}
 @Test void titleMemoOnlyNeverCompletesAndUndoPreservesLaterTextAndReferenceExclusion()throws Exception{isolated(c->{var tx=expense(c);var category=category(c,"Synthetic food");result(c.service().edit(new MoneyClassificationService.Edit(UUID.randomUUID(),tx.id(),0L,0L,0L,Map.of("title","First title"),List.of())));assertThat(c.db().queryForObject("select count(*) from money_review_decisions",Long.class)).isZero();var saved=result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),category,true)))));UUID event=UUID.fromString(((Map<?,?>)((List<?>)saved.get("items")).getFirst()).get("eventId").toString());var book=c.web().bookkeepingRow(tx.id());result(c.service().edit(new MoneyClassificationService.Edit(UUID.randomUUID(),tx.id(),0L,((Number)book.get("version")).longValue(),0L,Map.of("memo","Later unrelated memo"),List.of())));var preview=c.service().undoPreview(List.of(event));assertThat((List<?>)preview.get("excluded")).isEmpty();result(c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),List.of(event),preview.get("fingerprint").toString())));assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("title","First title").containsEntry("memo","Later unrelated memo").containsEntry("categoryId",null);assertThat(c.service().state(tx.id()).get("futureReferenceExcluded")).isEqualTo(true);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);});}
 @Test void undoPreviewProtectsLaterClassificationsAndNewConflictAppliesNothing()throws Exception{isolated(c->{var one=expense(c);var two=expense(c);UUID a=category(c,"Synthetic food"),b=category(c,"Synthetic transport");var saved=result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,one.id(),a,false),item(c,two.id(),a,false)))));var events=((List<Map<String,Object>>)saved.get("items")).stream().map(row->UUID.fromString(row.get("eventId").toString())).toList();var preview=c.service().undoPreview(events);result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,two.id(),b,false)))));var failed=c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),events,preview.get("fingerprint").toString()));assertThat(failed.get("status")).isEqualTo("NOT_APPLIED");assertThat(c.web().bookkeepingRow(one.id()).get("categoryId")).isEqualTo(a);var latest=c.service().undoPreview(events);assertThat((List<?>)latest.get("eligibleEventIds")).hasSize(1);assertThat((List<?>)latest.get("excluded")).hasSize(1);});}

 private MoneyMerchantLinkService links(Context c){return new MoneyMerchantLinkService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,c.money(),c.commands(),JsonMapper.builder().build());}
 private MoneyMerchantLinkService.Input linkInput(Context c,UUID transaction,UUID merchant,String scope,String fingerprint){var book=c.web().bookkeepingRow(transaction);return new MoneyMerchantLinkService.Input(UUID.randomUUID(),transaction,((Number)book.get("transactionVersion")).longValue(),((Number)book.get("merchantLinkVersion")).longValue(),merchant,merchant==null?null:c.db().queryForObject("select version from money_ai_merchants where id=?",Long.class,merchant),"모의 카페","모의 지점",false,scope,fingerprint);}
 @Test void merchantDefaultOnlyLinksSelectedFactAndDescriptorWideConflictLeavesAllUnapplied()throws Exception{isolated(c->{var one=expense(c);var two=expense(c);var service=links(c);var before=c.money().transaction(one.id());var input=linkInput(c,one.id(),null,"ONE_TRANSACTION",null);var preview=service.preview(input);assertThat(preview).containsEntry("count",1);result(service.apply(linkInput(c,one.id(),null,"ONE_TRANSACTION",preview.get("fingerprint").toString())));assertThat(c.web().bookkeepingRow(one.id()).get("merchantIdentityId")).isNotNull();assertThat(c.web().bookkeepingRow(two.id()).get("merchantIdentityId")).isNull();assertThat(c.web().bookkeepingRow(one.id()).get("categoryId")).isNull();assertThat(c.money().transaction(one.id())).isEqualTo(before);var all=service.preview(linkInput(c,two.id(),null,"DESCRIPTOR_ALL",null));expense(c);assertThat(service.apply(linkInput(c,two.id(),null,"DESCRIPTOR_ALL",all.get("fingerprint").toString()))).containsEntry("status","NOT_APPLIED");assertThat(c.db().queryForObject("select count(*) from money_ai_transaction_merchants",Long.class)).isEqualTo(1);});}
 @Test void merchantChangeDuringProviderProtectsLatestIdentityAndKeepsFinancialOriginal()throws Exception{isolated(c->{var transaction=expense(c);var category=category(c,"Synthetic food");automation(c,input->{var service=links(c);var preview=service.preview(linkInput(c,transaction.id(),null,"ONE_TRANSACTION",null));result(service.apply(linkInput(c,transaction.id(),null,"ONE_TRANSACTION",preview.get("fingerprint").toString())));return new MoneyClassificationProvider.Result(category,"늦은 모의 판단","MOCK",null,null);}).run(MoneyPostgresIntegrationTest.OWNER,transaction.id(),false);assertThat(c.web().bookkeepingRow(transaction.id())).containsEntry("classificationJobStatus","PROTECTED").containsEntry("categoryId",null);assertThat(c.money().transaction(transaction.id())).isEqualTo(transaction);});}
 private MoneyAiHistoryService history(Context c){return new MoneyAiHistoryService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,JsonMapper.builder().build(),c.commands(),new MoneyMeaningService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,JsonMapper.builder().build()),c.web(),c.service(),new DataSourceTransactionManager(c.db().getDataSource()));}
 @Test void historicalScopeProtectsDirectChoicesResumesAndNeverRepeatsAppliedItems()throws Exception{isolated(c->{var one=expense(c);var two=expense(c);var three=expense(c);UUID category=category(c,"Synthetic food");automation(c,input->null);result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,two.id(),category,false)))));var meaning=new MoneyMeaningService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,JsonMapper.builder().build());var rule=meaning.saveRule(null,rule(c,category,"Synthetic café"));var service=history(c);var scope=new MoneyAiHistoryService.Scope((UUID)rule.get("id"),((Number)rule.get("version")).longValue(),"2026-09-01","2026-09-30",c.account().id());var preview=service.preview(scope);assertThat(preview).containsEntry("eligible",2L).containsEntry("protected",1L);var started=result(service.start(new MoneyAiHistoryService.Start(UUID.randomUUID(),scope,preview.get("fingerprint").toString())));var run=(Map<String,Object>)started.get("run");UUID id=UUID.fromString(run.get("id").toString());result(service.control(new MoneyAiHistoryService.Control(UUID.randomUUID(),id,((Number)run.get("version")).longValue(),true,false)));assertThatThrownBy(()->service.advance(id)).hasMessageContaining("진행");var paused=(Map<String,Object>)service.read(id,0).get("run");result(service.control(new MoneyAiHistoryService.Control(UUID.randomUUID(),id,((Number)paused.get("version")).longValue(),false,false)));result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,three.id(),category,false)))));var finalState=service.advance(id);assertThat(finalState.get("items").toString()).contains("APPLIED");assertThat(c.service().state(one.id())).containsEntry("origin","APPROVED_RULE");assertThat(c.service().state(three.id())).containsEntry("origin","DIRECT");long events=c.db().queryForObject("select count(*) from money_classification_events",Long.class);assertThatThrownBy(()->service.advance(id)).hasMessageContaining("진행");assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(events);assertThat(c.money().transaction(one.id())).isEqualTo(one);});}
 @Test void explicitTwentyRowBundleIsAtomicAndIndependentAutomationKeepsSeventeenSuccessThreeFailures()throws Exception{isolated(c->{UUID category=category(c,"Synthetic food");var transactions=new ArrayList<MoneyTransaction>();for(int i=0;i<20;i++)transactions.add(expense(c));var items=transactions.stream().map(t->item(c,t.id(),category,false)).toList();var stale=new ArrayList<>(items);var old=stale.getLast();stale.set(19,new MoneyClassificationService.Item(old.id(),old.transactionVersion(),99L,old.projectionVersion(),old.classificationVersion(),category,true,false));assertThat(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),stale))).containsEntry("status","NOT_APPLIED");assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isZero();var calls=new java.util.concurrent.atomic.AtomicInteger();var auto=automation(c,input->{int n=calls.incrementAndGet();return new MoneyClassificationProvider.Result(n<=17?category:null,"모의 결과","MOCK",null,n<=17?null:"TIMEOUT");});for(var transaction:transactions)auto.run(MoneyPostgresIntegrationTest.OWNER,transaction.id(),false);assertThat(c.db().queryForObject("select count(*) from money_classification_jobs where status='SUCCEEDED'",Long.class)).isEqualTo(17);assertThat(c.db().queryForObject("select count(*) from money_classification_jobs where status='FAILED'",Long.class)).isEqualTo(3);var failed=c.db().queryForList("select transaction_id from money_classification_jobs where status='FAILED'",UUID.class);var retryCalls=new java.util.concurrent.atomic.AtomicInteger();var retry=automation(c,input->{retryCalls.incrementAndGet();return new MoneyClassificationProvider.Result(category,"명시적 실패 항목 재요청","MOCK",null,null);});for(UUID id:failed)retry.run(MoneyPostgresIntegrationTest.OWNER,id,true);assertThat(retryCalls.get()).isEqualTo(3);assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isEqualTo(20);for(var transaction:transactions)assertThat(c.money().transaction(transaction.id())).isEqualTo(transaction);});}

 @Test void conversationMockCreatesOnlyUnappliedDraftAndRejectsLateCurrentSource()throws Exception{isolated(c->{var transaction=expense(c);var category=category(c,"Synthetic food");var workspace=workspace(c);workspace.provider(input->{assertThat(input.toString()).doesNotContain("source memo",c.account().displayName());return new MoneyConversationProvider.Result("이 범위의 규칙 초안을 검토해 주세요.",List.of(new MoneyConversationProvider.Proposal(null,0L,"모의 분류 초안",rule(c,category,"Synthetic café"))),"MOCK","synthetic",null);});var saved=result(workspace.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,"선택한 카페 규칙 초안을 만들어 주세요.",List.of(transaction.id()))));assertThat(saved.get("generatedDrafts")).asList().hasSize(1);assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isZero();assertThat(c.money().transaction(transaction.id())).isEqualTo(transaction);workspace.provider(input->{var book=c.web().bookkeepingRow(transaction.id());result(c.service().edit(new MoneyClassificationService.Edit(UUID.randomUUID(),transaction.id(),0L,((Number)book.get("version")).longValue(),0L,Map.of("memo","새로운 구매 맥락"),List.of())));return new MoneyConversationProvider.Result("늦은 설명",List.of(),"MOCK","synthetic",null);});assertThat(workspace.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,"현재 근거를 설명해 주세요.",List.of(transaction.id())))).containsEntry("status","NOT_APPLIED");assertThat(c.db().queryForObject("select count(*) from money_ai_conversations",Long.class)).isEqualTo(1);});}
 @Test void twentyItemUndoProtectsTwoLaterChoicesAndRestoresOnlyEighteen()throws Exception{isolated(c->{
  UUID initial=category(c,"Initial food"),later=category(c,"Later transport");var transactions=new ArrayList<MoneyTransaction>();for(int i=0;i<20;i++)transactions.add(expense(c));
  var saved=result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),transactions.stream().map(t->item(c,t.id(),initial,false)).toList())));
  var events=((List<Map<String,Object>>)saved.get("items")).stream().map(e->UUID.fromString(e.get("eventId").toString())).toList();
  for(int i=0;i<2;i++)result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,transactions.get(i).id(),later,false)))));
  var preview=c.service().undoPreview(events);assertThat(preview.get("excluded")).asList().hasSize(2);var eligible=(List<UUID>)preview.get("eligibleEventIds");assertThat(eligible).hasSize(18);
  result(c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),eligible,preview.get("fingerprint").toString())));
  for(int i=0;i<20;i++){assertThat(c.web().bookkeepingRow(transactions.get(i).id()).get("categoryId")).isEqualTo(i<2?later:null);assertThat(c.money().transaction(transactions.get(i).id())).isEqualTo(transactions.get(i));}
 });}
 @Test void changedPurchaseMeaningDoesNotBecomeAHumanCorrectionAndInvalidChildrenNeverReturn()throws Exception{isolated(c->{
  var source=expense(c);UUID food=category(c,"Food"),transport=category(c,"Transport");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,source.id(),food,false)))));
  var b=c.web().bookkeepingRow(source.id());result(c.service().edit(new MoneyClassificationService.Edit(UUID.randomUUID(),source.id(),0L,((Number)b.get("version")).longValue(),0L,Map.of("title","교통 여행"),List.of())));
  var auto=automation(c,input->new MoneyClassificationProvider.Result(transport,"모의 구매 맥락","MOCK",null,null));auto.run(MoneyPostgresIntegrationTest.OWNER,source.id(),false);assertThat(c.web().bookkeepingRow(source.id()).get("categoryId")).isEqualTo(food);
  var target=expense(c);auto.run(MoneyPostgresIntegrationTest.OWNER,target.id(),false);assertThat(c.service().state(target.id())).containsEntry("origin","AI");assertThat(c.web().bookkeepingRow(target.id()).get("categoryId")).isEqualTo(transport);
  var root=c.product().saveCategory(null,new MoneyProductService.CategoryInput("Archived root","#123456",false,null,"EXPENSE",null,0));var child=c.product().saveCategory(null,new MoneyProductService.CategoryInput("Archived child","#123456",false,null,"EXPENSE",null,0,root.id(),false));c.db().update("update money_categories set archived=true,version=version+1 where id=?",root.id());
  var third=expense(c);automation(c,input->new MoneyClassificationProvider.Result(child.id(),"모의 잘못된 분류","MOCK",null,null)).run(MoneyPostgresIntegrationTest.OWNER,third.id(),false);assertThat(c.web().bookkeepingRow(third.id())).containsEntry("categoryId",null).containsEntry("classificationJobStatus","FAILED");
 });}
 @Test void retainedAuditExpiryDoesNotDeleteCurrentMeaningAndUndoPreservesLaterDeferredReview()throws Exception{isolated(c->{
  var tx=expense(c);UUID category=category(c,"Food");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),category,false)))));UUID event=(UUID)c.service().state(tx.id()).get("eventId");
  var json=JsonMapper.builder().build();var owner=MoneyPostgresIntegrationTest.OWNER;var meaning=new MoneyMeaningService(c.db(),()->owner,json);var review=new MoneyReviewService(c.db(),()->owner,c.web(),c.product(),meaning,json);var ai=new MoneyAiService(c.db(),()->owner,json,review,c.web(),c.product(),c.money(),meaning);var book=c.web().bookkeepingRow(tx.id());
  UUID defer=(UUID)ai.decide(new MoneyAiService.Decision(tx.id(),"TRANSACTION","DEFER",((Number)book.get("transactionVersion")).longValue(),((Number)book.get("version")).longValue(),((Number)book.get("projectionVersion")).longValue(),null,Map.of(),"Independent later review")).get("eventId");String originalDefer=c.db().queryForObject("select payload::text from money_ai_events where id=?",String.class,defer);
  long decisions=c.db().queryForObject("select count(*) from money_review_decisions",Long.class);var preview=c.service().undoPreview(List.of(event));assertThat(preview.get("eligibleEventIds")).asList().containsExactly(event);assertThat(preview.get("excluded")).asList().isEmpty();result(c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),List.of(event),preview.get("fingerprint").toString())));
  assertThat(ai.item(tx.id(),"TRANSACTION",false)).containsEntry("state","DEFERRED").containsEntry("canUndo",true);assertThat(c.db().queryForObject("select payload::text from money_ai_events where id=?",String.class,defer)).isEqualTo(originalDefer);assertThat(c.db().queryForObject("select count(*) from money_review_decisions",Long.class)).isEqualTo(decisions);assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("categoryId",null);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
  result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),category,false)))));event=(UUID)c.service().state(tx.id()).get("eventId");c.db().update("update money_classification_events set created_at=now()-interval '367 days' where id=?",event);workspace(c).retain();assertThat(c.service().history(0).toString()).contains("EXPIRED");assertThat(c.service().undoPreview(List.of(event)).get("eligibleEventIds")).asList().isEmpty();assertThat(c.web().bookkeepingRow(tx.id()).get("categoryId")).isEqualTo(category);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
 });}
 @Test void explicitHistoricalTwoHundredFactsStaySeparateFromFutureRuleApprovalAndResumeInFiftyItemSteps()throws Exception{isolated(c->{
  automation(c,input->null);UUID category=category(c,"Two hundred category");UUID owner=MoneyPostgresIntegrationTest.OWNER;c.db().update("insert into money_transactions(id,user_id,type,from_account_id,amount,currency,occurred_at,counterparty_text,title,manual) select gen_random_uuid(),?,'EXPENSE',?,1000,'KRW',?,'Synthetic café','source title',true from generate_series(1,200)",owner,c.account().id(),java.sql.Timestamp.from(fixture.at));
  var meaning=new MoneyMeaningService(c.db(),()->owner,JsonMapper.builder().build());var rule=meaning.saveRule(null,rule(c,category,"Synthetic café"));assertThat(c.db().queryForObject("select count(*) from money_transactions where category_id is not null",Long.class)).isZero();assertThat(c.db().queryForObject("select count(*) from money_classification_state",Long.class)).isZero();
  var history=history(c);var scope=new MoneyAiHistoryService.Scope((UUID)rule.get("id"),((Number)rule.get("version")).longValue(),"2026-09-01","2026-09-30",c.account().id());var preview=history.preview(scope);assertThat(preview).containsEntry("eligible",200L);var started=result(history.start(new MoneyAiHistoryService.Start(UUID.randomUUID(),scope,preview.get("fingerprint").toString())));UUID id=UUID.fromString(((Map<?,?>)started.get("run")).get("id").toString());assertThat(started.get("items")).asList().hasSize(50);history.advance(id);assertThat(c.db().queryForObject("select count(*) from money_ai_history_items where run_id=? and status='APPLIED'",Long.class,id)).isEqualTo(50);
  var run=(Map<String,Object>)history.read(id,0).get("run");result(history.control(new MoneyAiHistoryService.Control(UUID.randomUUID(),id,((Number)run.get("version")).longValue(),true,false)));assertThatThrownBy(()->history.advance(id)).hasMessageContaining("진행");run=(Map<String,Object>)history.read(id,0).get("run");result(history.control(new MoneyAiHistoryService.Control(UUID.randomUUID(),id,((Number)run.get("version")).longValue(),false,false)));
  for(int i=0;i<3;i++)history.advance(id);assertThat(((Map<?,?>)history.read(id,0).get("run")).get("status")).isEqualTo("COMPLETED");assertThat(c.db().queryForObject("select count(*) from money_ai_history_items where run_id=? and status='APPLIED'",Long.class,id)).isEqualTo(200);assertThat(c.db().queryForObject("select count(*) from money_transactions where amount<>1000 or currency<>'KRW' or category_id is not null or from_account_id<>?",Long.class,c.account().id())).isZero();
 });}
 @Test void newestValidSameContextDirectCorrectionWinsAndLiveLeasePreventsDuplicateProviderCall()throws Exception{isolated(c->{
  var one=expense(c);var two=expense(c);UUID a=category(c,"Earlier category"),b=category(c,"Latest category");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,one.id(),a,false)))));result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,two.id(),b,false)))));c.db().update("update money_classification_events set created_at=clock_timestamp() where transaction_id=?",two.id());var target=expense(c);var calls=new java.util.concurrent.atomic.AtomicInteger();var auto=automation(c,input->{calls.incrementAndGet();return new MoneyClassificationProvider.Result(a,"모의 AI","MOCK",null,null);});auto.run(MoneyPostgresIntegrationTest.OWNER,target.id(),false);assertThat(calls.get()).isZero();assertThat(c.web().bookkeepingRow(target.id()).get("categoryId")).isEqualTo(b);assertThat(c.service().state(target.id())).containsEntry("origin","DIRECT_REFERENCE");
  var pending=expense(c);c.db().update("update money_classification_jobs set status='RUNNING',due_at=now()+interval '1 minute',requested=false where transaction_id=?",pending.id());assertThat(auto.run(MoneyPostgresIntegrationTest.OWNER,pending.id(),false)).isFalse();assertThat(calls.get()).isZero();
 });}
 @Test void conversationRuleReferencesAreOwnedCurrentPersistentAndStaleRequestsHaveDurableOutcomes()throws Exception{isolated(c->{
  UUID category=category(c,"Selected rule category");var meaning=new MoneyMeaningService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,JsonMapper.builder().build());var selected=meaning.saveRule(null,rule(c,category,"Selected café"));var unselected=meaning.saveRule(null,rule(c,category,"Other café"));var workspace=workspace(c);var calls=new java.util.concurrent.atomic.AtomicInteger();workspace.provider(input->{calls.incrementAndGet();assertThat(input.get("rules")).asList().hasSize(1);assertThat(input.get("rules").toString()).contains(selected.get("id").toString()).doesNotContain(unselected.get("id").toString());return new MoneyConversationProvider.Result("선택한 현재 규칙의 내부 설명입니다.",List.of(),"MOCK","synthetic",null);});
  var references=List.of(new MoneyAiWorkspaceService.RuleReference((UUID)selected.get("id"),((Number)selected.get("version")).longValue()));var saved=result(workspace.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,"참고 규칙을 설명해 주세요.",List.of(),references)));var conversation=(Map<String,Object>)saved.get("conversation");UUID id=UUID.fromString(conversation.get("id").toString());assertThat(workspace.readConversation(id).get("ruleReferences").toString()).contains(selected.get("id").toString());
  UUID request=UUID.randomUUID();c.db().update("update money_category_rules set version=version+1 where id=?",selected.get("id"));var stale=new MoneyAiWorkspaceService.Message(request,id,((Number)conversation.get("version")).longValue(),"현재 버전 설명을 이어 주세요.",List.of(),references);var rejected=workspace.message(stale);assertThat(rejected).containsEntry("status","NOT_APPLIED");assertThat(c.service().outcome(request)).isEqualTo(rejected);assertThat(calls.get()).isEqualTo(1);assertThat(workspace.readConversation(id).get("messages")).asList().hasSize(2);assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isZero();
 });}

 @Test void selectedDraftOnlyReplaysApprovalAndConversationDeletionPreservesRulesAndOtherDrafts()throws Exception{isolated(c->{
  var tx=expense(c);UUID category=category(c,"Future food");var ws=workspace(c);var saved=result(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,"현재 규칙을 설명해 주세요.",List.of(tx.id()))));var conversation=(Map<String,Object>)saved.get("conversation");UUID conversationId=UUID.fromString(conversation.get("id").toString());UUID one=draft(c,ws,category,"One café",conversationId),two=draft(c,ws,category,"Two café",conversationId);var selected=List.of(new MoneyAiWorkspaceService.Selection(one,1L));var preview=ws.preview(selected);var approval=new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),selected,preview.get("fingerprint").toString());var outcome=ws.approve(approval);result(outcome);assertThat(ws.approve(approval)).isEqualTo(outcome);assertThat(c.service().outcome(approval.requestId())).isEqualTo(outcome);assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isEqualTo(1);assertThat(c.db().queryForObject("select status from money_ai_rule_drafts where id=?",String.class,two)).isEqualTo("OPEN");
  result(ws.changeConversation(new MoneyAiWorkspaceService.ConversationChange(UUID.randomUUID(),conversationId,((Number)conversation.get("version")).longValue(),List.of(),true)));assertThat(ws.readConversation(conversationId).get("messages")).asList().isEmpty();result(ws.discard(new MoneyAiWorkspaceService.Discard(UUID.randomUUID(),two,1L)));assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isEqualTo(1);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
  UUID overlapOne=draft(c,ws,category,"Overlap café",null),overlapTwo=draft(c,ws,category,"Overlap café",null);var overlap=List.of(new MoneyAiWorkspaceService.Selection(overlapOne,1L),new MoneyAiWorkspaceService.Selection(overlapTwo,1L));assertThat(ws.preview(overlap)).containsEntry("canApply",false);assertThat(ws.approve(new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),overlap,"invalid"))).containsEntry("status","NOT_APPLIED");
 });}
 @Test void legacyAliasIdentityIsReusedExplicitUnlinkWinsAndWholeAliasRelinkIsOnlyMeaning()throws Exception{isolated(c->{
  var one=expense(c);var alias=c.product().save(null,new MoneyProductService.Entry(TransactionType.EXPENSE,c.account().id(),null,new BigDecimal("2300"),fixture.at,"Synthetic café alias",null,null,false,null,null,"other purchase"));UUID identity=UUID.randomUUID(),replacement=UUID.randomUUID();c.db().update("insert into money_ai_merchants(id,user_id,descriptor,name,aliases,version) values(?,?,'Synthetic café','Known café','[\"Synthetic café alias\"]',1)",identity,MoneyPostgresIntegrationTest.OWNER);c.db().update("insert into money_ai_merchants(id,user_id,descriptor,name,aliases,version) values(?,?,'Replacement café','Replacement café','[]',1)",replacement,MoneyPostgresIntegrationTest.OWNER);assertThat(c.web().bookkeepingRow(one.id()).get("merchantIdentityId")).isEqualTo(identity);assertThat(c.web().bookkeepingRow(alias.id()).get("merchantIdentityId")).isEqualTo(identity);var service=links(c);
  var input=new MoneyMerchantLinkService.Input(UUID.randomUUID(),one.id(),0L,0L,null,null,null,null,true,"ONE_TRANSACTION",null);var preview=service.preview(input);result(service.apply(new MoneyMerchantLinkService.Input(input.requestId(),one.id(),0L,0L,null,null,null,null,true,"ONE_TRANSACTION",preview.get("fingerprint").toString())));assertThat(c.web().bookkeepingRow(one.id()).get("merchantIdentityId")).isNull();assertThat(c.web().bookkeepingRow(alias.id()).get("merchantIdentityId")).isEqualTo(identity);
  var whole=linkInput(c,alias.id(),replacement,"DESCRIPTOR_ALL",null);var all=service.preview(whole);assertThat(all).containsEntry("count",2);result(service.apply(linkInput(c,alias.id(),replacement,"DESCRIPTOR_ALL",all.get("fingerprint").toString())));assertThat(c.web().bookkeepingRow(one.id()).get("merchantIdentityId")).isEqualTo(replacement);assertThat(c.web().bookkeepingRow(alias.id()).get("merchantIdentityId")).isEqualTo(replacement);assertThat(c.money().transaction(one.id())).isEqualTo(one);assertThat(c.money().transaction(alias.id())).isEqualTo(alias);assertThat(c.db().queryForObject("select count(*) from money_category_rules",Long.class)).isZero();
 });}
 @Test void externalSearchOffAndExpiredCacheNeverSupplyNewClassificationButHistoricalEvidenceStaysReadable()throws Exception{isolated(c->{
  var tx=c.product().save(null,new MoneyProductService.Entry(TransactionType.EXPENSE,c.account().id(),null,new BigDecimal("1000"),fixture.at,"합성 카페",null,null,false,null,null,"커피"));UUID category=category(c,"카페");automation(c,input->null);var json=JsonMapper.builder().build();var meaning=new MoneyMeaningService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,json);var review=new MoneyReviewService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,c.web(),c.product(),meaning,json);var ai=new MoneyAiService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,json,review,c.web(),c.product(),c.money(),meaning);String url="https://synthetic.example/cafe";var evidence=Map.of("available",true,"retrievedAt",java.time.Instant.now().toString(),"sources",List.of(Map.of("url",url)),"candidates",List.of(Map.of("name","합성 카페","industry","카페","sourceUrls",List.of(url))));c.db().update("insert into money_ai_lookups(id,user_id,query,status,result) values(?,?,'합성 카페 | ','SUCCEEDED',cast(? as jsonb))",UUID.randomUUID(),MoneyPostgresIntegrationTest.OWNER,json.writeValueAsString(evidence));
  var off=ai.item(tx.id(),"TRANSACTION",false);assertThat(((Map<?,?>)off.get("proposal")).get("basis")).isEqualTo("NONE");assertThat(((Map<?,?>)off.get("evidence")).get("external")).asList().hasSize(1);ai.settings(new MoneyAiService.SettingsInput(0L,false,true));var on=ai.item(tx.id(),"TRANSACTION",false);assertThat(((Map<?,?>)on.get("proposal")).get("categoryId")).isEqualTo(category);c.db().update("update money_ai_lookups set created_at=now()-interval '25 hours'");var expired=ai.item(tx.id(),"TRANSACTION",false);assertThat(((Map<?,?>)expired.get("proposal")).get("basis")).isEqualTo("NONE");assertThat(((Map<?,?>)expired.get("evidence")).get("external")).asList().hasSize(1);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
 });}

 @Test void lookupPermissionCacheAndTenPerDayQuotaAreGuardedWithoutAnyProviderRequest()throws Exception{isolated(c->{
  var json=JsonMapper.builder().build();var lookup=new MoneyAiLookupService(c.db(),()->MoneyPostgresIntegrationTest.OWNER,json,new DataSourceTransactionManager(c.db().getDataSource()),"SYNTHETIC_NOT_SENT","MOCK",99);var evidence=Map.of("available",true,"sources",List.of(Map.of("url","https://synthetic.example/evidence")));c.db().update("insert into money_ai_lookups(id,user_id,query,status,result) values(?,?,'합성 카페 | 합성 지점','SUCCEEDED',cast(? as jsonb))",UUID.randomUUID(),MoneyPostgresIntegrationTest.OWNER,json.writeValueAsString(evidence));assertThat(lookup.lookup("합성 카페","합성 지점")).containsEntry("errorCode","LOOKUP_DISABLED");
  c.db().update("insert into money_ai_settings(user_id,external_lookup) values(?,true)",MoneyPostgresIntegrationTest.OWNER);assertThat(lookup.status()).containsEntry("dailyLimit",10).containsEntry("timeoutSeconds",25).containsEntry("automaticRetries",0);assertThat(lookup.lookup("합성 카페","합성 지점")).containsEntry("cached",true);assertThat(c.db().queryForObject("select count(*) from money_ai_lookups",Long.class)).isEqualTo(1);
  c.db().update("insert into money_ai_lookups(id,user_id,query,status,result) select gen_random_uuid(),?,'Synthetic quota '||n,'FAILED','{}' from generate_series(1,9) n",MoneyPostgresIntegrationTest.OWNER);assertThat(c.db().queryForObject("select count(*) from money_ai_lookups",Long.class)).isEqualTo(10);assertThat(lookup.lookup("새 합성 카페",null)).containsEntry("errorCode","DAILY_LIMIT");assertThat(c.db().queryForObject("select count(*) from money_ai_lookups",Long.class)).isEqualTo(10);
 });}


 @Test void followUpUsesBoundedMinimizedConversationContextAndProtectsLatestVersion()throws Exception{isolated(c->{
  var tx=expense(c);var ws=workspace(c);var calls=new java.util.concurrent.atomic.AtomicInteger();ws.provider(input->{int call=calls.incrementAndGet();assertThat(input.toString()).doesNotContain(c.account().displayName(),"source memo");if(call==2){assertThat(input.get("history")).asList().hasSize(2);assertThat(input.get("history").toString()).contains("구독");}return new MoneyConversationProvider.Result("구독 구매 맥락을 참고했습니다.",List.of(),"MOCK","synthetic",null);});
  var first=(Map<String,Object>)result(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),null,0L,c.account().displayName()+"의 구독 구매 맥락을 설명해 주세요.",List.of(tx.id())))).get("conversation");UUID id=UUID.fromString(first.get("id").toString());long version=((Number)first.get("version")).longValue();result(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),id,version,"그 맥락으로 이어서 설명해 주세요.",List.of(tx.id()))));
  assertThat(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),id,version,"오래된 후속 질문",List.of(tx.id())))).containsEntry("status","NOT_APPLIED");assertThat(calls.get()).isEqualTo(2);assertThat(ws.readConversation(id).get("messages")).asList().hasSize(4);ws.provider(input->{assertThat(input.get("history")).asList().isEmpty();assertThat(input.get("references")).asList().isEmpty();return new MoneyConversationProvider.Result("제거된 참고 자료는 새 요청에 사용하지 않습니다.",List.of(),"MOCK","synthetic",null);});var current=ws.readConversation(id);result(ws.message(new MoneyAiWorkspaceService.Message(UUID.randomUUID(),id,((Number)current.get("version")).longValue(),"참고를 제거한 새 질문",List.of())));assertThat(ws.readConversation(id).get("messages")).asList().hasSize(6);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
 });}

 @Test void workspaceApprovalRecordsAiProvenanceAndRequiresScopedPermissionAndCurrentVersion()throws Exception{isolated(c->{
  var tx=expense(c);UUID category=category(c,"Approved food");var ws=workspace(c);UUID draft=draft(c,ws,category,"Synthetic café",null);var selected=List.of(new MoneyAiWorkspaceService.Selection(draft,1L));var preview=ws.preview(selected);var approved=result(ws.approve(new MoneyAiWorkspaceService.Approval(UUID.randomUUID(),selected,preview.get("fingerprint").toString())));var rule=(Map<String,Object>)((List<?>)approved.get("rules")).getFirst();UUID id=UUID.fromString(rule.get("id").toString());long version=((Number)rule.get("version")).longValue();assertThat(rule).containsEntry("origin","AI_APPROVED");var json=JsonMapper.builder().build();assertThat(MoneyApprovedRuleGuard.current(c.db(),json,MoneyPostgresIntegrationTest.OWNER,id,version,tx.id())).isFalse();
  c.db().update("insert into money_ai_settings(user_id,automatic_rules) values(?,true) on conflict(user_id) do update set automatic_rules=true",MoneyPostgresIntegrationTest.OWNER);assertThat(MoneyApprovedRuleGuard.current(c.db(),json,MoneyPostgresIntegrationTest.OWNER,id,version,tx.id())).isTrue();c.db().update("update money_category_rules set version=version+1 where id=?",id);assertThat(MoneyApprovedRuleGuard.current(c.db(),json,MoneyPostgresIntegrationTest.OWNER,id,version+1,tx.id())).isFalse();assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
  var invalid=new MoneyMeaningService.RuleInput("개인 상대방 전체",List.of(new MoneyRuleEngine.Condition("type","EXACT","EXPENSE"),new MoneyRuleEngine.Condition("merchant","EXACT","김개인")),category,null,null,"ACTIVE",0L);UUID privateDraft=UUID.fromString(((Map<?,?>)result(ws.saveDraft(new MoneyAiWorkspaceService.DraftInput(UUID.randomUUID(),null,null,null,null,0L,"개인 맥락 검토",invalid))).get("draft")).get("id").toString());assertThatThrownBy(()->ws.preview(List.of(new MoneyAiWorkspaceService.Selection(privateDraft,1L)))).isInstanceOf(com.kafka.backend.common.InvalidRequestException.class);
 });}

 @Test void historyLoadsFiftyPerPageWithoutTreatingListLimitAsRetention()throws Exception{isolated(c->{
  var tx=expense(c);UUID category=category(c,"Paged food");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),category,false)))));for(int i=0;i<66;i++)c.db().update("insert into money_classification_events(id,user_id,transaction_id,bundle_id,origin,category_id,previous_value,next_value,evidence,active,created_at) values(?,?,?,?,'AI',?,'{}','{}','{\"reason\":\"isolated historical evidence\"}',false,now()-interval '400 days'+?*interval '1 second')",UUID.randomUUID(),MoneyPostgresIntegrationTest.OWNER,tx.id(),UUID.randomUUID(),category,i);
  var one=c.service().history(0);var two=c.service().history(50);assertThat(one).containsEntry("total",67L);assertThat(one.get("items")).asList().hasSize(50);assertThat(two.get("items")).asList().hasSize(17);var ids=new HashSet<String>();for(var event:(List<Map<String,Object>>)one.get("items"))ids.add(event.get("id").toString());for(var event:(List<Map<String,Object>>)two.get("items"))assertThat(ids).doesNotContain(event.get("id").toString());workspace(c).retain();assertThat(c.service().history(0)).containsEntry("total",67L);assertThat(c.web().bookkeepingRow(tx.id()).get("categoryId")).isEqualTo(category);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
 });}

 @Test void classificationUndoPreservesLaterDeferOrReopenAndProtectsLaterDirectClassification()throws Exception{isolated(c->{
  var json=JsonMapper.builder().build();var owner=MoneyPostgresIntegrationTest.OWNER;var meaning=new MoneyMeaningService(c.db(),()->owner,json);var review=new MoneyReviewService(c.db(),()->owner,c.web(),c.product(),meaning,json);var ai=new MoneyAiService(c.db(),()->owner,json,review,c.web(),c.product(),c.money(),meaning);
  UUID target=category(c,"Synthetic food");for(String kind:List.of("DEFER","REOPEN")){var tx=expense(c);var saved=result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),target,false)))));UUID event=UUID.fromString(((Map<?,?>)((List<?>)saved.get("items")).getFirst()).get("eventId").toString());var book=c.web().bookkeepingRow(tx.id());var after=Map.of("transactionVersion",book.get("transactionVersion"),"overrideVersion",book.get("version"),"projectionVersion",book.get("projectionVersion"));
   c.db().update("insert into money_ai_events(id,user_id,subject_id,kind,payload,created_at) values(?,?,?,?,cast(? as jsonb),clock_timestamp())",UUID.randomUUID(),owner,tx.id(),kind,json.writeValueAsString(Map.of("kind","TRANSACTION","after",after)));if(kind.equals("REOPEN"))c.db().update("delete from money_review_decisions where transaction_id=?",tx.id());
   var preview=c.service().undoPreview(List.of(event));assertThat(preview.get("excluded")).asList().isEmpty();result(c.service().undo(new MoneyClassificationService.Undo(UUID.randomUUID(),List.of(event),preview.get("fingerprint").toString())));assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("categoryId",null).containsEntry("title","source title").containsEntry("memo","source memo");assertThat(ai.item(tx.id(),"TRANSACTION",false).get("state")).isEqualTo(kind.equals("DEFER")?"DEFERRED":"PENDING");assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
  }
  var tx=expense(c);result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),target,false)))));UUID event=(UUID)c.service().state(tx.id()).get("eventId");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),category(c,"Later direct"),false)))));assertThat(c.service().undoPreview(List.of(event)).get("excluded")).asList().hasSize(1);
 });}
 @Test void singleRequestExplanationIsMinimizedAndSharedReadFiltersUseRealClassificationHistory()throws Exception{isolated(c->{
  var tx=expense(c);UUID category=category(c,"Food");var request=new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),null,false)),c.account().displayName()+"에서 커피 구독을 샀어요. 01012345678");result(c.service().request(request));
  var auto=automation(c,input->{assertThat(input.get("purchaseExplanation").toString()).contains("커피 구독").doesNotContain(c.account().displayName(),"01012345678");return new MoneyClassificationProvider.Result(category,"커피 구독 구매 맥락","MOCK",null,null);});auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),true);
  var history=c.service().history(0,tx.id(),null,"커피",c.account().id(),"2026-09-01","2026-10-31","ACTIVE");assertThat(history).containsEntry("total",1L);assertThat(history.get("items").toString()).contains("source title","Synthetic café","커피 구독 구매 맥락");
  assertThat(c.web().bookkeeping("2026-09-01","2026-09-30","EXPENSE",null,50,0,false,null,null,null,null,"RECENT_AUTO","AI")).containsEntry("total",1L);
  assertThat(c.web().bookkeeping("2026-09-01","2026-09-30","EXPENSE",null,50,0,false,null,null,null,null,"UNCLASSIFIED",null)).containsEntry("total",0L);
  var merchants=links(c).list(null,0,c.account().id(),"EXPENSE");assertThat(merchants).containsEntry("total",1L);assertThat(merchants.get("items").toString()).contains("classificationOrigin=AI",category.toString());
 });}

 @Test void failedAndProtectedJobsRemainReadableWithoutFabricatedClassificationEvents()throws Exception{isolated(c->{
  var tx=expense(c);var auto=automation(c,input->new MoneyClassificationProvider.Result(null,"Mock timeout","MOCK",null,"TIMEOUT"));auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),false);
  var failed=c.service().history(0,tx.id(),null,null,c.account().id(),null,null,"FAILED");assertThat(failed).containsEntry("total",1L);var row=(Map<String,Object>)((List<?>)failed.get("items")).getFirst();assertThat(row).containsEntry("sourceKind","JOB").containsEntry("eventId",null).containsEntry("active",false).containsEntry("currentCategoryId",null);assertThat(c.db().queryForObject("select count(*) from money_classification_events",Long.class)).isZero();
  UUID direct=category(c,"Protected direct");result(c.service().classify(new MoneyClassificationService.Bundle(UUID.randomUUID(),List.of(item(c,tx.id(),direct,false)))));auto.run(MoneyPostgresIntegrationTest.OWNER,tx.id(),true);
  var protectedRows=c.service().history(0,tx.id(),null,null,null,null,null,"PROTECTED");assertThat(protectedRows).containsEntry("total",1L);var protectedRow=(Map<String,Object>)((List<?>)protectedRows.get("items")).getFirst();assertThat(protectedRow).containsEntry("sourceKind","JOB").containsEntry("currentCategoryId",direct);assertThat(c.web().bookkeepingRow(tx.id())).containsEntry("categoryId",direct);assertThat(c.money().transaction(tx.id())).isEqualTo(tx);
 });}
}
