"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {attentionApi,type AttentionItem,type AttentionLane,type AttentionMutation,type AttentionSnapshot} from '@/lib/api/attention';
import {ApiError} from '@/lib/api/client';
import {useWorkflow} from '../WorkflowContext';
import './attention.css';
import AttentionConnections from './AttentionConnections';

export default function AttentionPage(){
 const workflow=useWorkflow(),[snapshot,setSnapshot]=useState<AttentionSnapshot|null>(null),[mode,setMode]=useState<'STACK'|'LANE'>('STACK'),[history,setHistory]=useState<AttentionItem[]>([]),[historyStatus,setHistoryStatus]=useState('COMPLETED'),[showHistory,setShowHistory]=useState(false),[search,setSearch]=useState(''),[cursor,setCursor]=useState<string|null>(null);
 const [error,setError]=useState(''),[offline,setOffline]=useState(false),[busy,setBusy]=useState(false),[capture,setCapture]=useState(false),[settings,setSettings]=useState(false),[draft,setDraft]=useState({action:'',projectId:'',projectLabel:'',workTaskId:'',url:''}),[edit,setEdit]=useState<AttentionItem|null>(null),[editAction,setEditAction]=useState(''),[undo,setUndo]=useState<{item:AttentionItem;until:number}|null>(null),[incoming,setIncoming]=useState<AttentionSnapshot|null>(null),[recovery,setRecovery]=useState<AttentionItem|null>(null);
 const current=useRef(snapshot),interaction=useRef(false),drag=useRef<{item:AttentionItem;queueRevision:number}|null>(null),pendingMove=useRef<(()=>Promise<AttentionMutation>)|undefined>(undefined);current.current=snapshot;
 const refresh=useCallback(async(force=false)=>{try{const next=await attentionApi.snapshot();setOffline(false);if(!force&&interaction.current&&current.current&&next.queueRevision!==current.current.queueRevision)setIncoming(next);else setSnapshot(next);}catch{setOffline(true);}},[]);
 useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{await refresh();if(!stopped)timer=setTimeout(poll,document.visibilityState==='visible'?3000:10000);};void poll();const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{stopped=true;clearTimeout(timer);window.removeEventListener('focus',focus);};},[refresh]);
 useEffect(()=>{if(!undo)return;const timer=setTimeout(()=>setUndo(null),Math.max(0,undo.until-Date.now()));return()=>clearTimeout(timer);},[undo]);
 const loadHistory=useCallback(async(nextCursor='',append=false)=>{try{const result=await attentionApi.history(historyStatus,search,nextCursor);setHistory(old=>append?[...old,...result.items]:result.items);setCursor(result.nextCursor??null);}catch{setError('기록을 불러오지 못했습니다.');}},[historyStatus,search]);
 useEffect(()=>{if(showHistory)void loadHistory();},[showHistory,loadHistory]);
 async function mutate(work:()=>Promise<AttentionMutation>){if(busy||offline)return null;setBusy(true);setError('');try{const result=await work();await refresh(true);if(showHistory)await loadHistory();return result;}catch(e){setError(e instanceof ApiError&&e.status===409?'다른 곳에서 바뀌었습니다. 새로 확인한 뒤 다시 시도해 주세요.':'저장하지 못했습니다. 연결 상태를 확인해 주세요.');await refresh(true);return null;}finally{setBusy(false);}}
 async function complete(item:AttentionItem){const result=await mutate(()=>attentionApi.command(item.id,'complete',{operationId:crypto.randomUUID(),expectedRevision:item.revision,expectedGeneration:item.source.generation}));if(result?.item)setUndo({item:result.item,until:Date.now()+8000});}
 async function reopen(item:AttentionItem){return mutate(()=>attentionApi.command(item.id,'reopen',{operationId:crypto.randomUUID(),expectedRevision:item.revision,expectedGeneration:item.source.generation}));}
 function openSource(item:AttentionItem){const url=item.source.url;try{if(url&&new URL(url).protocol==='https:'){window.open(url,'_blank','noopener,noreferrer');return;}}catch{}setRecovery(item);}
 async function submit(event:FormEvent){event.preventDefault();const id=crypto.randomUUID(),task=workflow.tasks.find(t=>t.id===draft.workTaskId),projectId=task?.projectId??(draft.projectId||undefined);const result=await mutate(()=>attentionApi.create({operationId:crypto.randomUUID(),id,action:draft.action,projectId,projectLabel:draft.projectLabel,workTaskId:draft.workTaskId||undefined,source:{kind:task?'POS':draft.url?'WEB':'LOCAL_APP',reference:task?.id??id,url:draft.url||undefined,producer:'MANUAL',intent:'manual-'+id,generation:'manual-1',completionPolicy:'ACK_ONLY'}}));if(result){setCapture(false);setDraft({action:'',projectId:'',projectLabel:'',workTaskId:'',url:''});}}
 async function move(before:string|null,laneId?:string){const selected=drag.current;if(!selected)return;const work=()=>attentionApi.command(selected.item.id,'move',{operationId:crypto.randomUUID(),expectedRevision:selected.item.revision,expectedQueueRevision:selected.queueRevision,mode,laneId,beforeItemId:before});pendingMove.current=()=>{const fresh=current.current,item=fresh?.items.find(item=>item.id===selected.item.id);if(!fresh||!item)throw new ApiError(409,'이동할 항목을 다시 확인해 주세요.');return attentionApi.command(item.id,'move',{operationId:crypto.randomUUID(),expectedRevision:item.revision,expectedQueueRevision:fresh.queueRevision,mode,laneId,beforeItemId:before});};drag.current=null;interaction.current=false;if(await mutate(work))pendingMove.current=undefined;}
 function row(item:AttentionItem,isHistory=false){return <div className="aq-row" key={item.id} data-attention-id={item.id} onDragOver={event=>{if(drag.current){event.preventDefault();event.dataTransfer.dropEffect='move';}}} onDrop={event=>{event.preventDefault();event.stopPropagation();void move(item.id,mode==='LANE'?item.laneId:undefined);}}>
  {isHistory?<button className="aq-check" aria-label={`${item.action} 다시 열기`} disabled={busy||offline} onClick={()=>void reopen(item)}>↶</button>:<input type="checkbox" aria-label={`${item.action} 확인 완료`} checked={false} disabled={busy||offline} onChange={()=>void complete(item)}/>}
  <button className="aq-title" onClick={()=>openSource(item)} onKeyDown={event=>{if(event.key===' '&&!event.nativeEvent.isComposing&&!isHistory){event.preventDefault();void complete(item);}}} title={item.displayTitle}>{item.projectLabel&&<span className="aq-project">{item.projectLabel} · </span>}{item.action}</button>
  <span className="aq-source">{item.source.kind==='CHATGPT'?'GPT':item.source.kind==='CODEX_DESKTOP'?'Codex':item.source.kind==='TEAM_KAFKA'?'TK':item.source.kind==='LOCAL_APP'?'메모':item.source.kind}</span>
  <button className="aq-row-action" aria-label={`${item.action} 이름 수정`} onClick={()=>{setEdit(item);setEditAction(item.action);}}>⋯</button>
  {!isHistory&&<button className="aq-row-action" aria-label={`${item.action} 순서 이동`} draggable={!busy&&!offline} onDragStart={event=>{drag.current={item,queueRevision:snapshot!.queueRevision};interaction.current=true;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',item.id);}} onDragEnd={()=>{drag.current=null;interaction.current=false;}}>⠿</button>}
 </div>;}
 const groups=mode==='STACK'?[{id:'stack',name:'확인할 항목',order:0,revision:0}]:snapshot?.lanes??[];
 return <main className="aq-page"><header className="aq-heading"><div><h1>WORK QUEUE</h1><span>확인할 것만 모아 두세요.</span></div><div><button onClick={()=>setCapture(true)}>＋ 빠른 추가</button><button aria-label="WORK QUEUE 설정" onClick={()=>setSettings(!settings)}>⚙</button></div></header>
  <div className="aq-toolbar"><div role="group" aria-label="보기 방식"><button aria-pressed={mode==='STACK'} onClick={()=>setMode('STACK')}>Stack</button><button aria-pressed={mode==='LANE'} onClick={()=>setMode('LANE')}>Split Group</button></div><span>{incoming?<button className="aq-incoming" onClick={()=>{setSnapshot(incoming);setIncoming(null);}}>목록 변경 · 표시</button>:<>{snapshot?.items.length??0}개</>}</span><button onClick={()=>setShowHistory(!showHistory)}>{showHistory?'기록 닫기':'완료 기록'}</button></div>
  {offline&&<p className="aq-status" role="status">연결이 끊겼습니다. 마지막 목록을 보고 있습니다.</p>}{error&&<p className="aq-error" role="alert">{error}{pendingMove.current&&<button onClick={()=>void mutate(pendingMove.current!)}>이동 다시 시도</button>}</p>}
  {settings&&<section className="aq-settings"><h2>개인 그룹</h2>{snapshot?.lanes.map((lane,index)=><div key={lane.id}><input aria-label={`${lane.name} 그룹 이름`} defaultValue={lane.name} maxLength={20} onBlur={event=>{if(event.target.value.trim()!==lane.name)void mutate(()=>attentionApi.lane('rename',lane.id,{operationId:crypto.randomUUID(),expectedRevision:lane.revision,name:event.target.value}));}}/><button disabled={index===0||busy||offline} aria-label={`${lane.name} 앞으로`} onClick={()=>void mutate(()=>{const ids=snapshot.lanes.map(l=>l.id);[ids[index-1],ids[index]]=[ids[index],ids[index-1]];return attentionApi.lane('order',undefined,{operationId:crypto.randomUUID(),expectedQueueRevision:snapshot.queueRevision,laneIds:ids});})}>↑</button><button disabled={snapshot.lanes.length<2||busy||offline} onClick={()=>void mutate(()=>attentionApi.lane('remove',lane.id,{operationId:crypto.randomUUID(),expectedQueueRevision:snapshot.queueRevision,destinationLaneId:snapshot.lanes.find(l=>l.id!==lane.id)!.id}))}>다른 그룹으로 합치기</button></div>)}<button disabled={!snapshot||snapshot.lanes.length>=3||busy||offline} onClick={()=>void mutate(()=>attentionApi.lane('create',undefined,{operationId:crypto.randomUUID(),expectedQueueRevision:snapshot!.queueRevision,name:'새 그룹'}))}>＋ 그룹 추가</button><p>Windows 앱의 트레이·단축키·자동 시작은 앱 설정에서 관리합니다.</p><AttentionConnections/></section>}
  {!snapshot?<p className="aq-empty">불러오는 중…</p>:<div className={`aq-list ${mode==='LANE'?'aq-split':''}`} onPointerEnter={()=>{interaction.current=true;}} onPointerLeave={()=>{if(!drag.current)interaction.current=false;}} onFocusCapture={()=>{interaction.current=true;}} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node))interaction.current=false;}}>{groups.map((lane:AttentionLane)=><section className="aq-lane" key={lane.id} onDragOver={event=>{if(drag.current)event.preventDefault();}} onDrop={event=>{event.preventDefault();void move(null,mode==='LANE'?lane.id:undefined);}}><h2>{lane.name}</h2>{snapshot.items.filter(item=>mode==='STACK'||item.laneId===lane.id).sort((a,b)=>mode==='STACK'?a.stackOrder-b.stackOrder:a.laneOrder-b.laneOrder).map(item=>row(item))}{!snapshot.items.some(item=>mode==='STACK'||item.laneId===lane.id)&&<p className="aq-empty">확인할 항목이 없습니다.</p>}</section>)}</div>}
  <footer className="aq-footer">{undo?<><span>확인 완료</span><button onClick={async()=>{if(await reopen(undo.item))setUndo(null);}}>되돌리기</button></>:<span>체크는 이 목록에서만 완료됩니다.</span>}<button onClick={()=>void refresh(true)}>새로고침</button></footer>
  {showHistory&&<section className="aq-history"><header><h2>기록</h2><select aria-label="기록 상태" value={historyStatus} onChange={event=>setHistoryStatus(event.target.value)}><option value="COMPLETED">완료</option><option value="DISMISSED">숨김</option></select><input aria-label="기록 검색" placeholder="검색" value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/></header>{history.map(item=>row(item,true))}{cursor&&<button onClick={()=>void loadHistory(cursor,true)}>더 보기</button>}</section>}
  {capture&&<div className="aq-overlay"><form className="aq-dialog" onSubmit={event=>void submit(event)}><h2>빠른 추가</h2><label>확인할 일<input autoFocus required maxLength={100} value={draft.action} onChange={event=>setDraft({...draft,action:event.target.value})}/></label><label>프로젝트<select value={draft.projectId} onChange={event=>setDraft({...draft,projectId:event.target.value,workTaskId:''})}><option value="">직접 입력</option>{workflow.projects.map(project=><option key={project.id} value={project.id}>{project.title}</option>)}</select></label>{!draft.projectId&&<input aria-label="프로젝트 이름" maxLength={40} placeholder="프로젝트 이름 (선택)" value={draft.projectLabel} onChange={event=>setDraft({...draft,projectLabel:event.target.value})}/>}<label>연결할 작업<select value={draft.workTaskId} onChange={event=>setDraft({...draft,workTaskId:event.target.value})}><option value="">없음</option>{workflow.tasks.filter(task=>!draft.projectId||task.projectId===draft.projectId).map(task=><option key={task.id} value={task.id}>{task.title}</option>)}</select></label><label>출처 URL<input type="url" pattern="https://.*" placeholder="https://… (선택)" value={draft.url} onChange={event=>setDraft({...draft,url:event.target.value})}/></label><div className="aq-dialog-buttons"><button type="button" onClick={()=>setCapture(false)}>취소</button><button type="submit" disabled={busy||offline}>추가</button></div></form></div>}
  {edit&&<div className="aq-overlay"><form className="aq-dialog" onSubmit={async event=>{event.preventDefault();if(await mutate(()=>attentionApi.edit(edit.id,{operationId:crypto.randomUUID(),expectedRevision:edit.revision,action:editAction})))setEdit(null);}}><h2>확인 항목</h2><input autoFocus aria-label="확인할 일 수정" required maxLength={100} value={editAction} onChange={event=>setEditAction(event.target.value)}/><div className="aq-dialog-buttons"><button type="button" onClick={()=>setEdit(null)}>취소</button>{edit.status==='OPEN'&&<button type="button" onClick={async()=>{const result=await mutate(()=>attentionApi.command(edit.id,'dismiss',{operationId:crypto.randomUUID(),expectedRevision:edit.revision,expectedGeneration:edit.source.generation}));if(result?.item){setEdit(null);setUndo({item:result.item,until:Date.now()+8000});}}}>숨기기</button>}<button type="submit" disabled={busy||offline}>저장</button></div></form></div>}
  {recovery&&<div className="aq-overlay"><section className="aq-dialog"><h2>출처 다시 연결</h2><p>{recovery.source.kind.includes('CODEX')?'브라우저에서 이 Codex 세션을 정확히 열 수 없습니다. Windows 앱에서 작업 폴더 또는 세션 ID로 돌아갈 수 있습니다.':'저장된 출처 URL이 없습니다. 출처 주소를 다시 연결해 주세요.'}</p>{recovery.source.reference&&<button onClick={()=>void navigator.clipboard.writeText(recovery.source.reference!)}>참조 ID 복사</button>}<button onClick={()=>setRecovery(null)}>닫기</button></section></div>}
 </main>;
}
