package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.scheduling.annotation.Scheduled;
import tools.jackson.databind.ObjectMapper;
import java.util.*;
import java.math.BigDecimal;
import java.time.*;
import static com.kafka.backend.money.MoneyService.require;

/** Durable meaning-only operations. Network dispatch, item commits and recovery are separate boundaries. */
@Service
public class MoneyRecommendationService {
 public static final String POLICY="BK-V2-006-20261008";
 private final JdbcTemplate db;private final CurrentUserProvider users;private final ObjectMapper json;private final MoneyCommandService commands;
 private final MoneyClassificationEngine engine;private final MoneyClassificationProvider provider;private final TransactionTemplate tx;
 private final BigDecimal daily,monthly;private final boolean workerEnabled;
 private Clock clock=Clock.system(ZoneId.of("Asia/Seoul"));
 void clock(Clock value){clock=value;}
 public MoneyRecommendationService(JdbcTemplate db,CurrentUserProvider users,ObjectMapper json,MoneyCommandService commands,MoneyClassificationEngine engine,MoneyClassificationProvider provider,PlatformTransactionManager manager,
  @Value("${money.ai.bookkeeping-daily-usd:1}") BigDecimal daily,@Value("${money.ai.bookkeeping-monthly-usd:10}") BigDecimal monthly,@Value("${money.ai.bookkeeping-worker-enabled:true}") boolean workerEnabled){
  this.db=db;this.users=users;this.json=json;this.commands=commands;this.engine=engine;this.provider=provider;this.tx=new TransactionTemplate(manager);this.daily=daily.max(BigDecimal.ZERO).min(BigDecimal.ONE);this.monthly=monthly.max(BigDecimal.ZERO).min(BigDecimal.TEN);this.workerEnabled=workerEnabled;
 }
 public record Filters(String from,String to,String kind,String search,boolean includeExcluded,String accountIds,String categoryIds,BigDecimal minAmount,BigDecimal maxAmount,String classificationState,String classificationOrigin){}
 public record Preview(String scope,List<UUID> ids,Filters filters,String explanation){}
 public record Start(UUID requestId,UUID snapshotId,String fingerprint,String policyVersion,boolean confirmed){}
 public record SaveItem(UUID id,UUID draftId,Long revision,UUID categoryId,String expectedStamp,boolean thisTransactionOnly,String originalStamp,boolean compared){}
 public record Save(UUID requestId,List<SaveItem> items){}
 public record Decision(UUID requestId,long revision,Long candidateRevision,String expectedStamp,long contextVersion,String action){}
 public record Selection(long revision,boolean selected){}
 public record Recovery(UUID requestId,String action){}
 public record ContextEdit(UUID requestId,long expectedContextVersion,String explanation){}
 private UUID owner(){return users.getCurrentUserId();}
 private static long n(Object v){return v instanceof Number number?number.longValue():0;}
 private static UUID uuid(Object v){return v==null?null:UUID.fromString(v.toString());}
 @SuppressWarnings("unchecked") private Map<String,Object> object(Object v){return v==null?new LinkedHashMap<>():v instanceof Map<?,?>?(Map<String,Object>)v:json.readValue(v.toString(),Map.class);}
 private Object canonical(Object value){if(value instanceof Map<?,?> map){var ordered=new TreeMap<String,Object>();map.forEach((key,item)->ordered.put(key.toString(),canonical(item)));return ordered;}if(value instanceof List<?> list)return list.stream().map(this::canonical).toList();if(value instanceof Number number)return new BigDecimal(number.toString()).stripTrailingZeros();return value;}
 private String fingerprint(Object value){return commands.fingerprint(canonical(json.readValue(json.writeValueAsString(value),Object.class)));}
 private void lock(UUID owner){db.queryForObject("select pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,"money:"+owner);}
 private MoneyWebService web(UUID owner){var money=new MoneyService(db,()->owner,json);var product=new MoneyProductService(db,()->owner,money,json);return new MoneyWebService(db,()->owner,money,product,json);}
 private MoneyClassificationService classification(UUID owner){var money=new MoneyService(db,()->owner,json);var product=new MoneyProductService(db,()->owner,money,json);var web=new MoneyWebService(db,()->owner,money,product,json);return new MoneyClassificationService(db,()->owner,json,web,new MoneyReviewService(db,()->owner,web,product,new MoneyMeaningService(db,()->owner,json),json),money,commands);}
 private Map<String,Object> one(String sql,Object... args){var rows=db.queryForList(sql,args);if(rows.isEmpty())throw new ResourceNotFoundException("소유한 추천 작업을 찾을 수 없습니다.");return rows.getFirst();}
 private List<Map<String,Object>> reasons(UUID owner,UUID id){return db.queryForList(MoneyReviewService.QUEUE+"select reason,state from queue where id=? and kind='TRANSACTION' order by reason",owner,id);}
 private Map<String,Object> eligible(UUID owner,UUID id){
  var money=new MoneyService(db,()->owner,json);var fact=money.transaction(id);var row=web(owner).bookkeepingRow(id);
  require(Set.of(MoneyTypes.TransactionType.EXPENSE,MoneyTypes.TransactionType.INCOME).contains(fact.type())&&!fact.excluded()&&fact.mergedInto()==null&&!Boolean.TRUE.equals(row.get("excluded")),"전용 금융 확인 또는 가계부 제외 내역입니다.");
  require(reasons(owner,id).stream().noneMatch(r->!"CATEGORY_UNCONFIRMED".equals(r.get("reason"))),"금융 확인이 먼저 필요합니다.");
  require(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_tracking_accounts t join money_accounts a on a.user_id=t.user_id and a.id=t.account_id where t.user_id=? and t.account_id=? and t.kind=? and not a.archived)",Boolean.class,owner,row.get("trackingAccountId"),row.get("type"))),"현재 추적 계좌 범위 밖입니다.");
  return row;
 }
 private String stamp(UUID owner,UUID id){
  return stamp(owner,id,web(owner).bookkeepingRow(id));
 }
 private String stamp(UUID owner,UUID id,Map<String,Object> row){
  var capture=new LinkedHashMap<String,Object>();
  for(String key:List.of("id","transactionVersion","version","projectionVersion","classificationVersion","categoryId","type","excluded","source","overrides","ruleDefaults"))capture.put(key,row.get(key));
  capture.put("context",MoneyClassificationContext.local(row));capture.put("dictionary",engine.dictionary(owner));
  capture.put("account",db.queryForList("select id,version,archived from money_accounts where user_id=? and id=?",owner,row.get("trackingAccountId")));
  capture.put("reasons",reasons(owner,id));capture.put("state",classification(owner).state(id));
  return fingerprint(capture);
 }
 private Map<String,Object> draft(UUID owner,UUID id){var rows=db.queryForList("select * from money_classification_drafts where user_id=? and transaction_id=?",owner,id);return rows.isEmpty()?null:rows.getFirst();}
 private String protection(UUID owner,UUID id,boolean reassess){
  Map<String,Object> row;try{row=eligible(owner,id);}catch(InvalidRequestException|ResourceNotFoundException error){return "FINANCIAL_OR_SCOPE_INELIGIBLE";}
  var state=classification(owner).state(id);
  String origin=Objects.toString(state.get("origin"),"");boolean explicitCategory=row.get("categoryId")!=null&&!Set.of("AI","APPROVED_RULE","DIRECT_REFERENCE").contains(origin)&&(object(row.get("overrides")).get("categoryId")!=null||object(row.get("source")).get("categoryId")!=null);
  if(!reassess&&(Boolean.TRUE.equals(state.get("directProtected"))||Set.of("DIRECT","CONFIRMED").contains(origin)||explicitCategory))return "CONFIRMED_CHOICE";
  var d=draft(owner,id);if(d!=null&&!Set.of("SAVED","EXCLUDED").contains(d.get("status"))&&(!reassess||Set.of("REASSESSING","COMPARISON_PENDING").contains(d.get("status"))))return "EXISTING_DRAFT_OR_COMPARISON";
  if(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_recommendation_items i join money_recommendation_runs r on r.id=i.run_id and r.user_id=i.user_id where i.user_id=? and i.transaction_id=? and i.status in ('QUEUED','RUNNING','EXTERNAL_OUTCOME_UNKNOWN','BUDGET_WAIT') and r.status<>'PREVIEW_REQUIRED')",Boolean.class,owner,id)))return "IN_FLIGHT";
  return null;
 }
 private Map<String,Object> minimized(UUID owner,Map<String,Object> book,String explanation){var input=new LinkedHashMap<>(book);var labels=db.queryForList("select display_name from money_accounts where user_id=? and id=?",String.class,owner,book.get("accountId"));if(!labels.isEmpty())input.put("accountName",labels.getFirst());input.put("requestExplanation",explanation);return MoneyClassificationContext.minimized(input,engine.dictionary(owner).stream().filter(c->Objects.equals(c.get("kind"),book.get("type"))).map(c->{var safe=new LinkedHashMap<String,Object>();for(String k:List.of("id","name","kind","parentId"))safe.put(k,c.get(k));return (Map<String,Object>)safe;}).toList());}
 private BigDecimal bound(MoneyClassificationProvider.Quote q){return q.inputPerMillion().multiply(BigDecimal.valueOf(q.maxInputTokens())).add(q.outputPerMillion().multiply(BigDecimal.valueOf(q.maxOutputTokens()))).movePointLeft(6);}
 private String priceStamp(Object value){var quote=object(json.readValue(json.writeValueAsString(value),Object.class));quote.remove("ready");return fingerprint(quote);}
 public Map<String,Object> preview(Preview input){return tx.execute(status->{UUID owner=owner();lock(owner);require(input!=null&&Set.of("ONE","SELECTED","FILTER","REASSESS").contains(input.scope()),"추천 범위를 확인해 주세요.");String explanation=Objects.toString(input.explanation(),"").strip();require(explanation.length()<=500,"구매 설명은 500자 이하입니다.");var ids=new LinkedHashSet<UUID>();
  if("FILTER".equals(input.scope())){require(input.filters()!=null,"전체 조건이 필요합니다.");var f=input.filters();int offset=0;while(true){var page=web(owner).bookkeeping(f.from(),f.to(),f.kind(),f.search(),200,offset,f.includeExcluded(),f.accountIds(),f.categoryIds(),f.minAmount(),f.maxAmount(),Objects.toString(f.classificationState(),"ALL"),f.classificationOrigin());var rows=(List<Map<String,Object>>)page.get("items");rows.forEach(r->ids.add(uuid(r.get("id"))));offset+=rows.size();if(offset>=n(page.get("total"))||rows.isEmpty())break;}}
  else{require(input.ids()!=null&&!input.ids().isEmpty()&&new HashSet<>(input.ids()).size()==input.ids().size(),"서로 다른 거래를 선택해 주세요.");require(!Set.of("ONE","REASSESS").contains(input.scope())||input.ids().size()==1,"단일 거래를 선택해 주세요.");ids.addAll(input.ids());}
  UUID run=UUID.randomUUID();var excluded=new ArrayList<Map<String,Object>>();var targets=new ArrayList<Map<String,Object>>();BigDecimal max=BigDecimal.ZERO;
  for(UUID id:ids){String reason=protection(owner,id,"REASSESS".equals(input.scope()));if(reason!=null){excluded.add(Map.of("id",id,"reason",reason));continue;}var book=web(owner).bookkeepingRow(id);var target=new LinkedHashMap<String,Object>();target.put("id",id);target.put("snapshot",book);target.put("stamp",stamp(owner,id,book));target.put("contextVersion",draft(owner,id)==null?0:n(draft(owner,id).get("context_version")));targets.add(target);var quote=provider.quote(minimized(owner,book,explanation));book.put("recommendationQuote",quote);max=max.add(bound(quote));}
  String fingerprint=fingerprint(Arrays.asList(input,targets,POLICY,max));boolean confirmation=targets.size()>100||max.compareTo(new BigDecimal("0.25"))>0;
  db.update("insert into money_recommendation_runs(id,user_id,scope,filters,fingerprint,policy_version,excluded,confirmation_required,max_cost) values(?,?,?,cast(? as jsonb),?,?,cast(? as jsonb),?,?)",run,owner,input.scope(),json.writeValueAsString(input),fingerprint,POLICY,json.writeValueAsString(excluded),confirmation,max);
  for(var target:targets)db.update("insert into money_recommendation_items(id,user_id,run_id,transaction_id,snapshot,stamp,explanation,context_version) values(?,?,?,?,cast(? as jsonb),?,?,?)",UUID.randomUUID(),owner,run,target.get("id"),json.writeValueAsString(target.get("snapshot")),target.get("stamp"),explanation,target.get("contextVersion"));
  return run(owner,run);
 });}
 public Map<String,Object> start(Start input){return tx.execute(status->{UUID owner=owner();lock(owner);require(input!=null&&input.requestId()!=null,"실행 요청 식별자가 필요합니다.");String hash=fingerprint(input);var replay=db.queryForList("select id,request_hash from money_recommendation_runs where user_id=? and request_id=?",owner,input.requestId());if(!replay.isEmpty()){require(hash.equals(replay.getFirst().get("request_hash")),"같은 요청 식별자의 내용이 다릅니다.");return run(owner,uuid(replay.getFirst().get("id")));}
  var r=one("select * from money_recommendation_runs where user_id=? and id=?",owner,input.snapshotId());require("PREVIEW_REQUIRED".equals(r.get("status"))&&input.fingerprint().equals(r.get("fingerprint"))&&POLICY.equals(input.policyVersion()),"추천 대상 미리보기를 다시 확인해 주세요.");require(!Boolean.TRUE.equals(r.get("confirmation_required"))||input.confirmed(),"고정 대상과 비용 상한의 명시 확인이 필요합니다.");
  db.update("update money_recommendation_runs set request_id=?,request_hash=?,status='QUEUED',updated_at=now() where user_id=? and id=?",input.requestId(),hash,owner,input.snapshotId());
  if("REASSESS".equals(r.get("scope"))){for(var item:db.queryForList("select * from money_recommendation_items where user_id=? and run_id=?",owner,input.snapshotId())){UUID id=uuid(item.get("transaction_id"));require(Objects.equals(item.get("stamp"),stamp(owner,id)),"거래가 변경되었습니다. 재검토 미리보기를 다시 확인해 주세요.");var d=draft(owner,id);long context=n(item.get("context_version"))+1;if(d==null)db.update("insert into money_classification_drafts(id,user_id,transaction_id,status,context_version,explanation) values(?,?,?,'REASSESSING',?,?)",UUID.randomUUID(),owner,id,context,item.get("explanation"));else{require(n(d.get("context_version"))==n(item.get("context_version")),"설명 맥락이 변경되었습니다.");db.update("update money_classification_drafts set status='REASSESSING',context_version=?,explanation=?,updated_at=now() where user_id=? and id=?",context,item.get("explanation"),owner,d.get("id"));}db.update("update money_recommendation_items set context_version=? where user_id=? and id=?",context,owner,item.get("id"));}}
  return run(owner,input.snapshotId());
 });}
 public Map<String,Object> runs(){return Map.of("items",db.queryForList("select id,status,scope,created_at from money_recommendation_runs where user_id=? and status<>'PREVIEW_REQUIRED' order by created_at desc limit 30",owner()));}
 public Map<String,Object> run(UUID id){return run(owner(),id);}
 private Map<String,Object> run(UUID owner,UUID id){var row=one("select id,scope,status,fingerprint,policy_version as \"policyVersion\",confirmation_required as \"confirmationRequired\",max_cost as \"maxCost\",excluded::text,created_at from money_recommendation_runs where user_id=? and id=?",owner,id);row.put("excluded",json.readValue(row.get("excluded").toString(),List.class));var counts=db.queryForList("select status,count(*) count from money_recommendation_items where user_id=? and run_id=? group by status",owner,id);var progress=new LinkedHashMap<String,Long>();counts.forEach(r->progress.put(r.get("status").toString(),n(r.get("count"))));row.put("counts",progress);row.put("total",progress.values().stream().mapToLong(Long::longValue).sum());if(!"PREVIEW_REQUIRED".equals(row.get("status")))row.put("status",progress.getOrDefault("RUNNING",0L)+progress.getOrDefault("QUEUED",0L)>0?"RUNNING":progress.getOrDefault("BUDGET_WAIT",0L)>0?"BUDGET_WAIT":progress.getOrDefault("EXTERNAL_OUTCOME_UNKNOWN",0L)>0?"OUTCOME_RECONCILIATION":"COMPLETE");row.put("usage",db.queryForList("select count(distinct i.transaction_id) external_transactions,count(u.id) attempts,coalesce(sum(u.input_tokens),0) input_tokens,coalesce(sum(u.output_tokens),0) output_tokens,coalesce(sum(case when u.status in ('HELD','UNCERTAIN') then u.reserved_cost else 0 end),0) reserved_cost,coalesce(sum(u.actual_cost),0) actual_cost from money_recommendation_usage u join money_recommendation_items i on i.id=u.item_id and i.user_id=u.user_id where u.user_id=? and i.run_id=?",owner,id).getFirst());row.put("internalTransactions",db.queryForObject("select count(distinct transaction_id) from money_recommendation_items where user_id=? and run_id=? and attempt_id is null and status in ('DRAFT_READY','UNCLASSIFIABLE') and result->>'cached' is distinct from 'true'",Long.class,owner,id));row.put("cacheTransactions",db.queryForObject("select count(distinct transaction_id) from money_recommendation_items where user_id=? and run_id=? and status in ('DRAFT_READY','UNCLASSIFIABLE') and result->>'cached'='true'",Long.class,owner,id));return row;}
 @Transactional(readOnly=true) public Map<String,Object> items(UUID id,int offset){one("select id from money_recommendation_runs where user_id=? and id=?",owner(),id);require(offset>=0,"페이지를 확인해 주세요.");var rows=db.queryForList("select id,transaction_id as \"transactionId\",status,result::text,snapshot::text from money_recommendation_items where user_id=? and run_id=? order by created_at,id limit 50 offset ?",owner(),id,offset);rows.forEach(r->{r.put("result",object(r.get("result")));r.put("snapshot",object(r.get("snapshot")));});return Map.of("items",rows);}
 @Transactional(readOnly=true) public Map<String,Object> drafts(){var rows=db.queryForList("select * from money_classification_drafts where user_id=? and status not in ('SAVED','EXCLUDED') order by created_at,id",owner());var items=new ArrayList<Map<String,Object>>();for(var d:rows)items.add(draftView(owner(),d));return Map.of("items",items,"total",items.size());}
 private Map<String,Object> draftView(UUID owner,Map<String,Object> d){var view=new LinkedHashMap<String,Object>();for(String k:List.of("id","revision","status","selected","explanation"))view.put(k,d.get(k));view.put("transactionId",d.get("transaction_id"));view.put("contextVersion",d.get("context_version"));view.put("candidateRevision",d.get("candidate_revision"));UUID id=uuid(d.get("transaction_id"));try{var book=web(owner).bookkeepingRow(id);view.put("book",book);view.put("currentStamp",stamp(owner,id,book));}catch(ResourceNotFoundException e){view.put("currentStamp",null);}
  view.put("active",revision(owner,uuid(d.get("id")),n(d.get("revision"))));view.put("candidate",d.get("candidate_revision")==null?null:revision(owner,uuid(d.get("id")),n(d.get("candidate_revision"))));var active=object(view.get("active"));boolean current=Objects.equals(view.get("currentStamp"),active.get("stamp"));view.put("saveEligible","ACTIVE".equals(d.get("status"))&&current&&active.get("categoryId")!=null&&Objects.equals(Objects.toString(object(active.get("snapshot")).get("requestExplanation"),""),Objects.toString(d.get("explanation"),"")));view.put("conflict",!active.isEmpty()&&!current);return view;}
 private Map<String,Object> revision(UUID owner,UUID id,long rev){var rows=db.queryForList("select revision,category_id as \"categoryId\",origin,result::text,snapshot::text,stamp,context_version as \"contextVersion\",disposition from money_classification_draft_revisions where user_id=? and draft_id=? and revision=?",owner,id,rev);if(rows.isEmpty())return Map.of();var r=rows.getFirst();r.put("result",object(r.get("result")));r.put("snapshot",object(r.get("snapshot")));return r;}
 public Map<String,Object> selection(UUID id,Selection input){return tx.execute(status->{lock(owner());var d=one("select * from money_classification_drafts where user_id=? and id=?",owner(),id);MoneyMeaningService.version(n(d.get("revision")),input.revision());db.update("update money_classification_drafts set selected=? where user_id=? and id=?",input.selected(),owner(),id);d.put("selected",input.selected());return draftView(owner(),d);});}
 public Map<String,Object> decision(UUID id,Decision input){return tx.execute(status->{UUID owner=owner();lock(owner);String hash=fingerprint(Arrays.asList(id,input));var replay=db.queryForList("select request_hash,result::text from money_recommendation_decisions where user_id=? and request_id=?",owner,input.requestId());if(!replay.isEmpty()){require(hash.equals(replay.getFirst().get("request_hash")),"다른 결정에 사용한 요청 ID입니다.");return object(replay.getFirst().get("result"));}var d=one("select * from money_classification_drafts where user_id=? and id=?",owner,id);MoneyMeaningService.version(n(d.get("revision")),input.revision());MoneyMeaningService.version(n(d.get("context_version")),input.contextVersion());UUID transaction=uuid(d.get("transaction_id"));require(Set.of("KEEP","ADOPT","EXCLUDE","KEEP_LATEST").contains(input.action()),"초안 결정을 확인해 주세요.");if(!Objects.equals(input.expectedStamp(),stamp(owner,transaction)))throw new OptimisticLockConflictException("비교 이후 거래가 다시 변경되었습니다.");
  long next=n(d.get("revision"));String state="ACTIVE";if(Set.of("EXCLUDE","KEEP_LATEST").contains(input.action()))state="EXCLUDED";else{require("COMPARISON_PENDING".equals(d.get("status"))&&input.candidateRevision()!=null,"완료된 새 후보와 비교해 주세요.");require(Objects.equals(input.candidateRevision(),d.get("candidate_revision")==null?null:n(d.get("candidate_revision"))),"비교 후보가 변경되었습니다.");if("ADOPT".equals(input.action())){require(input.candidateRevision()!=null,"채택할 후보가 없습니다.");var candidate=revision(owner,id,input.candidateRevision());require(candidate.get("categoryId")!=null&&Objects.equals(candidate.get("stamp"),input.expectedStamp())&&n(candidate.get("contextVersion"))==input.contextVersion(),"오래되거나 분류 불가인 후보입니다.");next=input.candidateRevision();}if("KEEP".equals(input.action())){var active=revision(owner,id,next);require(!active.isEmpty()&&Objects.equals(active.get("stamp"),input.expectedStamp()),"기존 초안이 최신 거래와 다릅니다. 최신 값 비교가 필요합니다.");long context=input.contextVersion()+1;long copy=db.queryForObject("select max(revision)+1 from money_classification_draft_revisions where user_id=? and draft_id=?",Long.class,owner,id);db.update("insert into money_classification_draft_revisions(user_id,draft_id,revision,item_id,category_id,origin,result,snapshot,stamp,context_version,disposition) select user_id,draft_id,?,item_id,category_id,origin,result,snapshot,stamp,?,'KEPT_OLD' from money_classification_draft_revisions where user_id=? and draft_id=? and revision=?",copy,context,owner,id,next);var oldSnapshot=object(active.get("snapshot"));db.update("update money_classification_drafts set context_version=?,explanation=? where user_id=? and id=?",context,Objects.toString(oldSnapshot.get("requestExplanation"),""),owner,id);next=copy;}if(input.candidateRevision()!=null)db.update("update money_classification_draft_revisions set disposition=? where user_id=? and draft_id=? and revision=?","ADOPT".equals(input.action())?"ADOPTED":"KEPT_OLD",owner,id,input.candidateRevision());}
  db.update("update money_classification_drafts set revision=?,candidate_revision=null,status=?,updated_at=now() where user_id=? and id=?",next,state,owner,id);var result=Map.<String,Object>of("draftId",id,"action",input.action(),"confirmed",false);db.update("insert into money_recommendation_decisions(id,user_id,request_id,request_hash,draft_id,decision,result) values(?,?,?,?,?,?,cast(? as jsonb))",UUID.randomUUID(),owner,input.requestId(),hash,id,input.action(),json.writeValueAsString(result));return result;
 });}
 @Transactional(readOnly=true) public Map<String,Object> current(UUID id){UUID owner=owner();var book=eligible(owner,id);return Map.of("book",book,"stamp",stamp(owner,id,book));}
 public Map<String,Object> context(UUID id,ContextEdit input){require(input!=null&&input.explanation()!=null&&input.explanation().length()<=500,"구매 설명은 500자 이하입니다.");return commands.execute(owner(),input.requestId(),"BOOKKEEPING_DRAFT_CONTEXT",Arrays.asList(id,input),()->{var d=one("select * from money_classification_drafts where user_id=? and id=?",owner(),id);MoneyMeaningService.version(n(d.get("context_version")),input.expectedContextVersion());if(!Objects.equals(input.explanation(),d.get("explanation")))db.update("update money_classification_drafts set context_version=context_version+1,explanation=?,status=case when status='REASSESSING' then 'ACTIVE' else status end,updated_at=now() where user_id=? and id=?",input.explanation(),owner(),id);return Map.of("contextVersion",n(one("select context_version from money_classification_drafts where user_id=? and id=?",owner(),id).get("context_version")),"classificationWrites",0);});}
 public Map<String,Object> recover(UUID id,Recovery input){require(input!=null&&Set.of("RETRY_KNOWN_FAILURE","KEEP_CURRENT_UNKNOWN").contains(input.action()),"복구 동작을 확인해 주세요.");return commands.execute(owner(),input.requestId(),"BOOKKEEPING_RECOMMENDATION_RECOVERY",Arrays.asList(id,input),()->{var item=one("select * from money_recommendation_items where user_id=? and id=?",owner(),id);if("RETRY_KNOWN_FAILURE".equals(input.action())){require("FAILED_KNOWN".equals(item.get("status")),"확인된 실패만 재시도합니다.");require(Objects.equals(item.get("stamp"),stamp(owner(),uuid(item.get("transaction_id")))),"거래가 변경되어 새 미리보기가 필요합니다.");db.update("update money_recommendation_items set status='QUEUED',attempt_id=null,updated_at=now() where user_id=? and id=?",owner(),id);if("REASSESS".equals(one("select scope from money_recommendation_runs where user_id=? and id=?",owner(),item.get("run_id")).get("scope")))db.update("update money_classification_drafts set status='REASSESSING',explanation=? where user_id=? and transaction_id=? and context_version=?",item.get("explanation"),owner(),item.get("transaction_id"),item.get("context_version"));}else{require("EXTERNAL_OUTCOME_UNKNOWN".equals(item.get("status")),"불명확 외부 작업만 현재 값 유지로 닫습니다.");itemStatus(owner(),id,"PROTECTED",Map.of("reason","소유자가 현재 값 유지 선택: 외부 비용 불명확 예약은 유지","reconciled",true));restoreReassessment(owner(),uuid(item.get("transaction_id")));}return Map.of("itemId",id,"action",input.action(),"classificationWrites",0);});}
 private void itemStatus(UUID owner,UUID id,String status,Map<String,Object> result){db.update("update money_recommendation_items set status=?,result=cast(? as jsonb),lease_until=null,updated_at=now() where user_id=? and id=?",status,json.writeValueAsString(result),owner,id);}
 private record Dispatch(UUID owner,UUID item,UUID transaction,UUID attempt,Map<String,Object> book,Map<String,Object> input,MoneyClassificationProvider.Quote quote,MoneyClassificationEngine.Decision internal,String stamp,long context,boolean reassess){}
 private MoneyClassificationEngine.Decision reusable(UUID owner,Map<String,Object> d,String stamp,String explanation,String model){
  if(d==null||n(d.get("revision"))==0)return null;var active=revision(owner,uuid(d.get("id")),n(d.get("revision")));var evidence=object(active.get("result"));
  if(!"AI".equals(active.get("origin"))||active.get("categoryId")==null||!Objects.equals(stamp,active.get("stamp"))||!Objects.equals(explanation,Objects.toString(object(active.get("snapshot")).get("requestExplanation"),""))||!Objects.equals(model,evidence.get("model")))return null;
  if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_classification_draft_revisions v join money_recommendation_items i on i.user_id=v.user_id and i.id=v.item_id join money_recommendation_runs r on r.user_id=i.user_id and r.id=i.run_id where v.user_id=? and v.draft_id=? and v.revision=? and r.policy_version=?)",Boolean.class,owner,d.get("id"),d.get("revision"),POLICY)))return null;
  var cached=new LinkedHashMap<String,Object>(evidence);cached.put("cached",true);cached.put("cachedFromRevision",active.get("revision"));cached.put("originalProvider",evidence.getOrDefault("originalProvider",evidence.get("provider")));
  return new MoneyClassificationEngine.Decision(uuid(active.get("categoryId")),"AI",cached);
 }
 private Dispatch claim(UUID owner,UUID id){return tx.execute(status->{lock(owner);var item=one("select i.*,r.scope,r.status run_status from money_recommendation_items i join money_recommendation_runs r on r.user_id=i.user_id and r.id=i.run_id where i.user_id=? and i.id=?",owner,id);if(!Set.of("QUEUED","BUDGET_WAIT").contains(item.get("status"))||"PREVIEW_REQUIRED".equals(item.get("run_status")))return null;
  UUID transaction=uuid(item.get("transaction_id"));boolean reassess="REASSESS".equals(item.get("scope"));Map<String,Object> book;
  try{book=eligible(owner,transaction);}catch(InvalidRequestException|ResourceNotFoundException e){itemStatus(owner,id,"PROTECTED",Map.of("reason","현재 금융 상태 또는 추적 범위에서 제외"));return null;}
  if(!Objects.equals(item.get("stamp"),stamp(owner,transaction,book))){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","미리보기 이후 거래·사전·버전 변경"));return null;}
  var d=draft(owner,transaction);var state=classification(owner).state(transaction);
  if(!reassess&&(Boolean.TRUE.equals(state.get("directProtected"))||d!=null&&!Set.of("SAVED","EXCLUDED").contains(d.get("status")))){itemStatus(owner,id,"PROTECTED",Map.of("reason","사용자 선택 또는 기존 초안 보호"));return null;}
  if(reassess&&(d==null||n(d.get("context_version"))!=n(item.get("context_version"))||!"REASSESSING".equals(d.get("status")))){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","재검토 설명이 변경됨"));return null;}
  book=new LinkedHashMap<>(book);book.put("requestExplanation",item.get("explanation"));var internal=engine.evaluate(owner,transaction,book);var input=minimized(owner,book,Objects.toString(item.get("explanation"),""));var quote=provider.quote(input);UUID attempt=null;
  if(reassess&&internal.categoryId()==null){var cached=reusable(owner,d,item.get("stamp").toString(),Objects.toString(item.get("explanation"),""),quote.model());if(cached!=null)internal=cached;}
  if(internal.categoryId()==null){var frozen=object(item.get("snapshot")).get("recommendationQuote");if(!priceStamp(frozen).equals(priceStamp(quote))){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","모델 또는 비용 정책 변경: 새 미리보기 필요"));restoreReassessment(owner,transaction);return null;}if(!quote.ready()){itemStatus(owner,id,"FAILED_KNOWN",Map.of("reason","외부 추천 설정 확인 필요: 제공자 활성화·기존 API 키·지원 모델/단가·입력 상한을 확인해 주세요. 내부 근거와 직접 분류는 사용할 수 있습니다.","code","PROVIDER_NOT_READY"));restoreReassessment(owner,transaction);return null;}
   var today=LocalDate.now(clock.withZone(ZoneId.of("Asia/Seoul")));var month=today.withDayOfMonth(1);var reserve=bound(quote);
   long held=db.queryForObject("select count(*) from money_recommendation_usage where user_id=? and status='HELD'",Long.class,owner);
   if(held>=2)return null;
   var spent=db.queryForList("select coalesce(sum(case when day=? then case when status='ACTUAL' then actual_cost else reserved_cost end else 0 end),0) day_cost,coalesce(sum(case when status='ACTUAL' then actual_cost else reserved_cost end),0) month_cost from money_recommendation_usage where user_id=? and month=? and status in ('HELD','ACTUAL','UNCERTAIN')",today,owner,month).getFirst();
   if(new BigDecimal(spent.get("day_cost").toString()).add(reserve).compareTo(daily)>0||new BigDecimal(spent.get("month_cost").toString()).add(reserve).compareTo(monthly)>0){itemStatus(owner,id,"BUDGET_WAIT",Map.of("reason","일 $1 또는 월 $10 비용 예약 한도 대기"));return null;}
   attempt=UUID.randomUUID();db.update("insert into money_recommendation_usage(id,user_id,item_id,model,price_version,reserved_cost,day,month) values(?,?,?,?,?,?,?,?)",attempt,owner,id,quote.model(),quote.priceVersion(),reserve,today,month);
  }
  db.update("update money_recommendation_items set status='RUNNING',attempt_id=?,lease_until=now()+interval '2 minutes',updated_at=now() where user_id=? and id=?",attempt,owner,id);
  return new Dispatch(owner,id,transaction,attempt,book,input,quote,internal,item.get("stamp").toString(),n(item.get("context_version")),reassess);
 });}
 private void restoreReassessment(UUID owner,UUID transaction){restoreReassessment(owner,transaction,null);}
 private void restoreReassessment(UUID owner,UUID transaction,Long expectedContext){db.update("update money_classification_drafts d set status=case when revision>0 then 'ACTIVE' else 'UNCLASSIFIABLE' end,explanation=coalesce((select r.snapshot->>'requestExplanation' from money_classification_draft_revisions r where r.user_id=d.user_id and r.draft_id=d.id and r.revision=d.revision),''),updated_at=now() where user_id=? and transaction_id=? and status='REASSESSING' and (?::bigint is null or context_version=?)",owner,transaction,expectedContext,expectedContext);}
 /** No transaction or owner lock crosses the provider boundary. Unknown delivery is never automatically resent. */
 public void process(UUID owner,UUID id){var dispatch=claim(owner,id);if(dispatch==null)return;MoneyClassificationProvider.Result result;
  if(dispatch.attempt()==null)result=new MoneyClassificationProvider.Result(dispatch.internal().categoryId(),Objects.toString(dispatch.internal().evidence().get("reason"),"내부 구매 맥락 판단"),Boolean.TRUE.equals(dispatch.internal().evidence().get("cached"))?"CACHED":"INTERNAL",Boolean.TRUE.equals(dispatch.internal().evidence().get("cached"))?dispatch.quote().model():null,null);
  else try{result=provider.classify(dispatch.input());}catch(Exception failure){result=new MoneyClassificationProvider.Result(null,"외부 결과 확인 필요","EXTERNAL",dispatch.quote().model(),"DELIVERY_UNKNOWN");}
  final var resolved=result;tx.executeWithoutResult(status->{lock(owner);var item=one("select * from money_recommendation_items where user_id=? and id=?",owner,id);if(!"RUNNING".equals(item.get("status"))||!Objects.equals(dispatch.attempt(),item.get("attempt_id")))return;
   if(dispatch.attempt()!=null){boolean measured=resolved.inputTokens()!=null&&resolved.outputTokens()!=null;boolean rejected=resolved.errorCode()!=null&&resolved.errorCode().matches("PROVIDER_HTTP_4[0-9]{2}");BigDecimal actual=measured?dispatch.quote().inputPerMillion().multiply(BigDecimal.valueOf(resolved.inputTokens())).add(dispatch.quote().outputPerMillion().multiply(BigDecimal.valueOf(resolved.outputTokens()))).movePointLeft(6):null;
    db.update("update money_recommendation_usage set status=?,actual_cost=?,input_tokens=?,output_tokens=?,provider_request_id=? where user_id=? and id=?",measured?"ACTUAL":rejected?"RELEASED":"UNCERTAIN",actual,resolved.inputTokens(),resolved.outputTokens(),resolved.providerRequestId(),owner,dispatch.attempt());
    if(!measured&&!rejected){itemStatus(owner,id,"EXTERNAL_OUTCOME_UNKNOWN",Map.of("reason","전달·비용 결과 불명확: 같은 작업 조회로 복구","attemptId",dispatch.attempt()));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}
   }
   if(resolved.errorCode()!=null){itemStatus(owner,id,"FAILED_KNOWN",Map.of("reason",resolved.reason(),"code",resolved.errorCode()));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}
   if(!Objects.equals(dispatch.stamp(),stamp(owner,dispatch.transaction()))){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","판단 중 거래·사전 변경"));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}
   var d=draft(owner,dispatch.transaction());if(dispatch.reassess()&&(d==null||n(d.get("context_version"))!=dispatch.context()||!"REASSESSING".equals(d.get("status")))){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","설명 맥락 변경"));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}
   if(dispatch.attempt()==null){var current=engine.evaluate(owner,dispatch.transaction(),dispatch.book());boolean cached=Boolean.TRUE.equals(dispatch.internal().evidence().get("cached"));boolean changed=cached?current.categoryId()!=null||d==null||n(d.get("revision"))!=n(dispatch.internal().evidence().get("cachedFromRevision")):!Objects.equals(current,dispatch.internal());if(changed){itemStatus(owner,id,"STALE_CONFLICT",Map.of("reason","내부 근거 변경"));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}}
   if(resolved.categoryId()!=null&&!engine.dictionary(owner).stream().anyMatch(c->resolved.categoryId().equals(c.get("id"))&&Objects.equals(c.get("kind"),dispatch.book().get("type")))){itemStatus(owner,id,"FAILED_KNOWN",Map.of("reason","현재 허용 사전 밖의 결과"));restoreReassessment(owner,dispatch.transaction(),dispatch.context());return;}
   var evidence=new LinkedHashMap<String,Object>(dispatch.internal().evidence());evidence.put("reason",resolved.reason());evidence.put("provider",resolved.provider());evidence.put("model",resolved.model());evidence.put("categoryId",resolved.categoryId());evidence.put("originalTransactionId",dispatch.transaction());evidence.put("contextVersion",dispatch.context());
   if(d==null){UUID draftId=UUID.randomUUID();db.update("insert into money_classification_drafts(id,user_id,transaction_id,context_version,explanation) values(?,?,?,?,?)",draftId,owner,dispatch.transaction(),dispatch.context(),item.get("explanation"));d=draft(owner,dispatch.transaction());}
   UUID draftId=uuid(d.get("id"));long rev=db.queryForObject("select coalesce(max(revision),0)+1 from money_classification_draft_revisions where user_id=? and draft_id=?",Long.class,owner,draftId);
   db.update("insert into money_classification_draft_revisions(user_id,draft_id,revision,item_id,category_id,origin,result,snapshot,stamp,context_version) values(?,?,?,?,?,?,cast(? as jsonb),cast(? as jsonb),?,?)",owner,draftId,rev,id,resolved.categoryId(),dispatch.internal().origin(),json.writeValueAsString(evidence),json.writeValueAsString(dispatch.book()),dispatch.stamp(),dispatch.context());
   if(dispatch.reassess())db.update("update money_classification_drafts set candidate_revision=?,status='COMPARISON_PENDING',updated_at=now() where user_id=? and id=?",rev,owner,draftId);
   else db.update("update money_classification_drafts set revision=?,candidate_revision=null,status=?,selected=true,updated_at=now() where user_id=? and id=?",rev,resolved.categoryId()==null?"UNCLASSIFIABLE":"ACTIVE",owner,draftId);
   itemStatus(owner,id,resolved.categoryId()==null?"UNCLASSIFIABLE":"DRAFT_READY",evidence);
  });}
 @Scheduled(fixedDelayString="${money.ai.bookkeeping-poll-ms:3000}") public void runDue(){if(!workerEnabled)return;
  // A lease identifies an abandoned dispatch, not permission to dispatch it again.
  for(var old:db.queryForList("select user_id,id,transaction_id,attempt_id from money_recommendation_items where status='RUNNING' and lease_until<now() limit 20"))tx.executeWithoutResult(status->{UUID owner=uuid(old.get("user_id"));lock(owner);var current=db.queryForList("select id from money_recommendation_items where user_id=? and id=? and status='RUNNING' and lease_until<now()",owner,old.get("id"));if(current.isEmpty())return;if(old.get("attempt_id")!=null){db.update("update money_recommendation_usage set status='UNCERTAIN' where user_id=? and id=? and status='HELD'",owner,old.get("attempt_id"));itemStatus(owner,uuid(old.get("id")),"EXTERNAL_OUTCOME_UNKNOWN",Map.of("reason","중단된 외부 호출의 결과 확인 필요"));restoreReassessment(owner,uuid(old.get("transaction_id")));}else db.update("update money_recommendation_items set status='QUEUED',lease_until=null where user_id=? and id=? and status='RUNNING'",owner,old.get("id"));});
  for(var row:db.queryForList("select i.user_id,i.id from money_recommendation_items i join money_recommendation_runs r on r.user_id=i.user_id and r.id=i.run_id where i.status in ('QUEUED','BUDGET_WAIT') and r.status<>'PREVIEW_REQUIRED' order by i.created_at,i.id limit 20"))process(uuid(row.get("user_id")),uuid(row.get("id")));
 }
 public Map<String,Object> usage(){UUID owner=owner();var today=LocalDate.now(clock.withZone(ZoneId.of("Asia/Seoul")));return Map.of("items",db.queryForList("select u.status,count(*) attempts,count(distinct i.transaction_id) transactions,coalesce(sum(case when u.status in ('HELD','UNCERTAIN') then u.reserved_cost else 0 end),0) reserved,coalesce(sum(u.actual_cost),0) actual,coalesce(sum(u.input_tokens),0) input_tokens,coalesce(sum(u.output_tokens),0) output_tokens from money_recommendation_usage u join money_recommendation_items i on i.id=u.item_id and i.user_id=u.user_id where u.user_id=? and u.month=? group by u.status",owner,today.withDayOfMonth(1)),"day",today,"dailyLimit",daily,"monthlyLimit",monthly);}
 public Map<String,Object> save(Save input){UUID owner=owner();require(input!=null&&input.requestId()!=null&&input.items()!=null&&!input.items().isEmpty()&&input.items().stream().map(SaveItem::id).distinct().count()==input.items().size(),"서로 다른 저장 항목과 요청 ID가 필요합니다.");UUID save=tx.execute(status->{lock(owner);String hash=fingerprint(input);var prior=db.queryForList("select id,request_hash from money_recommendation_saves where user_id=? and request_id=?",owner,input.requestId());if(!prior.isEmpty()){require(hash.equals(prior.getFirst().get("request_hash")),"같은 요청 ID의 저장 내용이 다릅니다.");return uuid(prior.getFirst().get("id"));}UUID id=UUID.randomUUID();db.update("insert into money_recommendation_saves(id,user_id,request_id,request_hash) values(?,?,?,?)",id,owner,input.requestId(),hash);for(var item:input.items()){web(owner).bookkeepingRow(item.id());db.update("insert into money_recommendation_save_items(id,user_id,save_id,transaction_id,command) values(?,?,?,?,cast(? as jsonb))",UUID.randomUUID(),owner,id,item.id(),json.writeValueAsString(item));}return id;});
  for(var row:db.queryForList("select id from money_recommendation_save_items where user_id=? and save_id=? and status='QUEUED' order by id",owner,save))saveOne(owner,uuid(row.get("id")));return saved(owner,save);
 }
 private void saveOne(UUID owner,UUID id){try{tx.executeWithoutResult(status->{lock(owner);var row=one("select * from money_recommendation_save_items where user_id=? and id=?",owner,id);if(!"QUEUED".equals(row.get("status")))return;var input=json.readValue(row.get("command").toString(),SaveItem.class);UUID transaction=input.id();var book=eligible(owner,transaction);if(!Objects.equals(input.expectedStamp(),stamp(owner,transaction,book)))throw new OptimisticLockConflictException("표시 후 거래가 변경되었습니다. 최신 값과 비교해 주세요.");require(input.categoryId()!=null&&engine.dictionary(owner).stream().anyMatch(c->input.categoryId().equals(c.get("id"))&&Objects.equals(c.get("kind"),book.get("type"))),"유효한 최종 카테고리를 선택해 주세요.");
   var d=draft(owner,transaction);Map<String,Object> original=Map.of();if(input.draftId()!=null){require(d!=null&&input.draftId().equals(d.get("id")),"현재 초안이 다릅니다.");MoneyMeaningService.version(n(d.get("revision")),input.revision());require(Set.of("ACTIVE","UNCLASSIFIABLE").contains(d.get("status")),"비교·대기 중인 초안은 저장할 수 없습니다.");original=revision(owner,input.draftId(),input.revision());if(!(input.compared()?Objects.equals(original.get("stamp"),input.originalStamp()):Objects.equals(original.get("stamp"),input.expectedStamp())))throw new OptimisticLockConflictException("오래된 초안을 최신 카테고리와 비교해 주세요.");require(Objects.equals(Objects.toString(object(original.get("snapshot")).get("requestExplanation"),""),Objects.toString(d.get("explanation"),"")),"구매 설명이 변경되어 재판단이 필요합니다.");}
   else require(d==null||Set.of("SAVED","EXCLUDED").contains(d.get("status")),"기존 초안을 먼저 확인해 주세요.");
   boolean unchanged=input.draftId()!=null&&Objects.equals(input.categoryId(),original.get("categoryId"));if(d!=null)book.put("requestExplanation",d.get("explanation"));var evidence=new LinkedHashMap<String,Object>();evidence.put("requestExplanation",d==null?"":d.get("explanation"));evidence.put("source","BOOKKEEPING_V2_EXPLICIT_SAVE");evidence.put("draft",original);evidence.put("dictionary",engine.dictionary(owner));var outcome=classification(owner).persistRecommendation(transaction,input.categoryId(),unchanged?"CONFIRMED":"DIRECT",input.thisTransactionOnly(),uuid(row.get("save_id")),book,evidence);
   db.update("update money_recommendation_save_items set status='SAVED',result=cast(? as jsonb),event_id=?,attempts=attempts+1,updated_at=now() where user_id=? and id=?",json.writeValueAsString(outcome),outcome.get("eventId"),owner,id);if(d!=null)db.update("update money_classification_drafts set status='SAVED',saved_event_id=?,selected=false,updated_at=now() where user_id=? and id=?",outcome.get("eventId"),owner,d.get("id"));
  });}catch(InvalidRequestException|ResourceNotFoundException|OptimisticLockConflictException|org.springframework.dao.DataIntegrityViolationException known){tx.executeWithoutResult(status->{lock(owner);db.update("update money_recommendation_save_items set status=?,result=cast(? as jsonb),attempts=attempts+1,updated_at=now() where user_id=? and id=? and status='QUEUED'",known instanceof OptimisticLockConflictException?"STALE_CONFLICT":"FAILED_KNOWN",json.writeValueAsString(Map.of("reason",known instanceof org.springframework.dao.DataIntegrityViolationException?"저장 조건을 충족하지 않아 이 항목을 커밋하지 않았습니다.":known.getMessage())),owner,id);});}catch(RuntimeException unknown){/* Commit ambiguity: lookup is authoritative; never repeat a possibly applied item. */try{tx.executeWithoutResult(status->{lock(owner);db.update("update money_recommendation_save_items set status='OUTCOME_UNKNOWN',updated_at=now() where user_id=? and id=? and status='QUEUED'",owner,id);});}catch(RuntimeException unavailable){/* durable command remains recoverable after DB availability */}}
 }
 private Map<String,Object> saved(UUID owner,UUID id){one("select id from money_recommendation_saves where user_id=? and id=?",owner,id);var rows=db.queryForList("select id,transaction_id as \"transactionId\",status,result::text,event_id as \"eventId\",attempts from money_recommendation_save_items where user_id=? and save_id=? order by id",owner,id);rows.forEach(r->r.put("result",object(r.get("result"))));return Map.of("id",id,"items",rows);}
 public Map<String,Object> saved(UUID id){return saved(owner(),id);}
 public Map<String,Object> reconcileSave(UUID id){UUID owner=owner();saved(owner,id);tx.executeWithoutResult(status->{lock(owner);for(var row:db.queryForList("select id,transaction_id from money_recommendation_save_items where user_id=? and save_id=? and status in ('QUEUED','OUTCOME_UNKNOWN')",owner,id)){var committed=db.queryForList("select id from money_classification_events where user_id=? and transaction_id=? and bundle_id=?",owner,row.get("transaction_id"),id);require(committed.size()<=1,"저장 이력이 중복되어 조회 확인이 필요합니다.");if(!committed.isEmpty())db.update("update money_recommendation_save_items set status='SAVED',event_id=?,updated_at=now() where user_id=? and id=?",committed.getFirst().get("id"),owner,row.get("id"));else db.update("update money_recommendation_save_items set status='QUEUED',updated_at=now() where user_id=? and id=?",owner,row.get("id"));}});for(var row:db.queryForList("select id from money_recommendation_save_items where user_id=? and save_id=? and status='QUEUED'",owner,id))saveOne(owner,uuid(row.get("id")));return saved(owner,id);}
 @Transactional(readOnly=true) public Map<String,Object> saves(){
  UUID owner=owner();var groups=new LinkedHashMap<UUID,List<Map<String,Object>>>();
  for(var row:db.queryForList("select id from money_recommendation_saves where user_id=? order by created_at desc,id desc limit 20",owner))groups.put(uuid(row.get("id")),new ArrayList<>());
  if(!groups.isEmpty())for(var row:db.queryForList("select id,save_id,transaction_id as \"transactionId\",status,result::text,event_id as \"eventId\",attempts from money_recommendation_save_items where user_id=? and save_id=any(?) order by id",owner,groups.keySet().toArray(UUID[]::new))){UUID save=uuid(row.remove("save_id"));row.put("result",object(row.get("result")));groups.get(save).add(row);}
  return Map.of("items",groups.entrySet().stream().map(group->Map.<String,Object>of("id",group.getKey(),"items",group.getValue())).toList());
 }
 @Transactional(readOnly=true) public Map<String,Object> draftHistory(UUID transaction){new MoneyService(db,()->owner(),json).transaction(transaction);var rows=db.queryForList("select r.revision,r.origin,r.category_id as \"categoryId\",r.disposition,r.context_version as \"contextVersion\",r.created_at as \"createdAt\",r.result::text from money_classification_draft_revisions r join money_classification_drafts d on d.user_id=r.user_id and d.id=r.draft_id where r.user_id=? and d.transaction_id=? order by r.revision desc",owner(),transaction);rows.forEach(row->row.put("result",object(row.get("result"))));return Map.of("items",rows);}
 public Map<String,Object> saveOutcome(UUID requestId){var rows=db.queryForList("select id from money_recommendation_saves where user_id=? and request_id=?",owner(),requestId);return rows.isEmpty()?Map.of("status","NOT_FOUND"):saved(owner(),uuid(rows.getFirst().get("id")));}
 public Map<String,Object> retry(UUID id){UUID owner=owner();saved(owner,id);tx.executeWithoutResult(status->{lock(owner);db.update("update money_recommendation_save_items set status='QUEUED' where user_id=? and save_id=? and status='FAILED_KNOWN'",owner,id);});for(var row:db.queryForList("select id from money_recommendation_save_items where user_id=? and save_id=? and status='QUEUED'",owner,id))saveOne(owner,uuid(row.get("id")));return saved(owner,id);}
}
