package com.kafka.backend.money;
import com.kafka.backend.common.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.util.*;
import static com.kafka.backend.money.MoneyService.*;

/** Transaction-scoped identity by default. Explicit descriptor-wide relinking is previewed separately. */
@Service
public class MoneyMerchantLinkService {
 private final JdbcTemplate db;private final CurrentUserProvider users;private final MoneyService money;private final MoneyCommandService commands;private final ObjectMapper json;
 public MoneyMerchantLinkService(JdbcTemplate db,CurrentUserProvider users,MoneyService money,MoneyCommandService commands,ObjectMapper json){this.db=db;this.users=users;this.money=money;this.commands=commands;this.json=json;}
 private UUID owner(){return users.getCurrentUserId();}
 private static long number(Object value){return value==null?0:((Number)value).longValue();}
 private List<Map<String,Object>> rows(String sql,Object...args){var rows=db.queryForList(sql,args);for(var row:rows)row.replaceAll((key,value)->value instanceof Timestamp t?t.toInstant():value);return rows;}
 private Map<String,Object> identity(UUID id){if(id==null)return Map.of();var rows=rows("select id,descriptor,name,region,version,evidence::text from money_ai_merchants where user_id=? and id=?",owner(),id);if(rows.isEmpty())throw new ResourceNotFoundException("소유한 거래처를 찾을 수 없습니다.");return rows.getFirst();}
 @Transactional(readOnly=true) public Map<String,Object> list(String search,int offset){require(offset>=0,"조회 위치를 확인해 주세요.");text(search,200,false,"거래처 검색");String filter=" where t.user_id=? and not t.excluded and t.merged_into is null and position(lower(?) in lower(coalesce(t.counterparty_text,'')||' '||coalesce(t.title,'')||' '||coalesce(mi.name,'')))>0";var items=rows("select t.id,t.title,t.counterparty_text as descriptor,t.type,t.amount,t.currency,t.occurred_at as \"occurredAt\",t.version as \"transactionVersion\",coalesce(l.version,0) as \"linkVersion\",mi.id as \"merchantId\",mi.name,mi.region,coalesce(mi.version,0) as \"merchantVersion\",l.evidence::text from money_transactions t left join money_ai_transaction_merchants l on l.user_id=t.user_id and l.transaction_id=t.id"+MoneyMerchantResolution.join("l")+filter+" order by t.occurred_at desc,t.id limit 50 offset ?",owner(),Objects.toString(search,""),offset);long total=db.queryForObject("select count(*) from money_transactions t left join money_ai_transaction_merchants l on l.user_id=t.user_id and l.transaction_id=t.id"+MoneyMerchantResolution.join("l")+filter,Long.class,owner(),Objects.toString(search,""));return Map.of("items",items,"total",total,"identities",rows("select id,name,region,version from money_ai_merchants where user_id=? order by name,id",owner()));}
 public record Input(UUID requestId,UUID transactionId,Long transactionVersion,Long expectedVersion,UUID merchantId,Long merchantVersion,String name,String region,boolean unlink,String scope,String fingerprint){}
 private List<Map<String,Object>> affected(Input input){var fact=money.transaction(input.transactionId());MoneyMeaningService.version(fact.version(),input.transactionVersion());require(!fact.excluded()&&fact.mergedInto()==null,"현재 소유 금융 거래를 선택해 주세요.");boolean all="DESCRIPTOR_ALL".equals(input.scope());require(all||"ONE_TRANSACTION".equals(input.scope()),"이번 거래 또는 같은 결제명 전체 범위를 선택해 주세요.");if(all){text(fact.counterpartyText(),500,true,"전체 연결 대상 결제명");require(!MoneyAiService.intermediary(fact.counterpartyText()),"중개 결제명 전체를 하나의 거래처로 고정할 수 없습니다.");}
  var labels=new LinkedHashSet<String>();if(all){labels.add(fact.counterpartyText().toLowerCase(Locale.ROOT));var identities=rows("select descriptor,aliases::text from money_ai_merchants where user_id=? and (lower(descriptor)=lower(?) or exists(select 1 from jsonb_array_elements_text(aliases) a where lower(a)=lower(?)))",owner(),fact.counterpartyText(),fact.counterpartyText());require(identities.size()<=1,"기존 별칭이 중복되어 있습니다. 이번 거래만 확인해 주세요.");if(identities.size()==1){labels.add(identities.getFirst().get("descriptor").toString().toLowerCase(Locale.ROOT));for(Object alias:json.readValue(identities.getFirst().get("aliases").toString(),List.class))labels.add(alias.toString().toLowerCase(Locale.ROOT));}}
  return rows("select t.id,t.version as \"transactionVersion\",coalesce(l.version,0) as \"linkVersion\",l.merchant_id as \"merchantId\",t.counterparty_text as descriptor from money_transactions t left join money_ai_transaction_merchants l on l.user_id=t.user_id and l.transaction_id=t.id where t.user_id=? and not t.excluded and t.merged_into is null and "+(all?"lower(t.counterparty_text)=any(?)":"t.id=?")+" order by t.id limit 10001",owner(),all?labels.toArray(new String[0]):fact.id());
 }
 @Transactional(readOnly=true) public Map<String,Object> preview(Input input){var affected=affected(input);require(affected.size()<=10000,"대상 결제명 범위를 좁혀 주세요.");var merchant=identity(input.merchantId());if(input.merchantId()!=null)MoneyMeaningService.version(number(merchant.get("version")),input.merchantVersion());var descriptors=affected.stream().map(row->row.get("descriptor")).filter(Objects::nonNull).map(value->value.toString().toLowerCase(Locale.ROOT)).distinct().toArray(String[]::new);var rules=rows("select r.id,r.name,r.version,r.status from money_category_rules r where r.user_id=? and (lower(r.merchant)=any(?) or exists(select 1 from jsonb_array_elements(coalesce(r.conditions,'[]')) c where c->>'field'='merchant' and lower(c->>'value')=any(?))) order by r.id",owner(),descriptors,descriptors);var signature=new LinkedHashMap<String,Object>();signature.put("affected",affected);signature.put("identity",merchant);signature.put("relatedRules",rules);signature.put("scope",input.scope());signature.put("name",input.name());signature.put("region",input.region());signature.put("unlink",input.unlink());return Map.of("transactions",affected,"count",affected.size(),"relatedRules",rules,"fingerprint",commands.fingerprint(signature),"financialChanges",0,"classificationChanges",0,"ruleChanges",0,"scope",input.scope());}
 public Map<String,Object> apply(Input input){return commands.execute(owner(),input.requestId(),"MERCHANT_LINK",input,()->{var preview=preview(input);if(!Objects.equals(preview.get("fingerprint"),input.fingerprint()))throw new OptimisticLockConflictException("결제명·거래처·관련 규칙 또는 대상 버전이 변경되었습니다. 다시 영향 검토해 주세요.");var selected=((List<Map<String,Object>>)preview.get("transactions")).stream().filter(row->input.transactionId().equals(row.get("id"))).findFirst().orElseThrow(()->new InvalidRequestException("대상 거래를 다시 확인해 주세요."));MoneyMeaningService.version(number(selected.get("linkVersion")),input.expectedVersion());UUID merchant=input.merchantId();if(!input.unlink()&&merchant==null){text(input.name(),160,true,"거래처 이름");text(input.region(),120,false,"지역");merchant=UUID.randomUUID();String descriptor="거래별 확인 · "+merchant;db.update("insert into money_ai_merchants(id,user_id,descriptor,name,region,evidence,version) values(?,?,?,?,?,cast(? as jsonb),1)",merchant,owner(),descriptor,input.name().strip(),input.region(),json.writeValueAsString(Map.of("origin","OWNER_CONFIRMED","scope","ONE_TRANSACTION")));}if(input.unlink())merchant=null;
  UUID bundle=UUID.randomUUID();for(var row:(List<Map<String,Object>>)preview.get("transactions")){db.update("insert into money_ai_transaction_merchants(user_id,transaction_id,merchant_id,evidence) values(?,?,?,cast(? as jsonb)) on conflict(user_id,transaction_id) do update set merchant_id=excluded.merchant_id,evidence=excluded.evidence,version=money_ai_transaction_merchants.version+1,updated_at=now()",owner(),row.get("id"),merchant,json.writeValueAsString(Map.of("origin","OWNER_CONFIRMED","scope",input.scope(),"bundleId",bundle)));var evidence=new LinkedHashMap<String,Object>();evidence.put("previousMerchantId",row.get("merchantId"));evidence.put("merchantId",merchant);evidence.put("scope",input.scope());evidence.put("financialChanges",0);evidence.put("classificationChanges",0);db.update("insert into money_ai_events(id,user_id,subject_id,kind,payload) values(?,?,?,'MERCHANT_LINK',cast(? as jsonb))",UUID.randomUUID(),owner(),row.get("id"),json.writeValueAsString(evidence));}
  return Map.of("linked",preview.get("count"),"scope",input.scope(),"financialChanges",0,"classificationChanges",0,"ruleChanges",0,"futureRuleEligibility","CURRENT_APPROVAL_SOURCE_REQUIRED");});}
}
