package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import static com.kafka.backend.money.MoneyService.*;
import static com.kafka.backend.money.MoneyTypes.*;

/** Meaning-only classification commands. Financial facts and title/memo fields are outside classification/undo. */
@Service
public class MoneyClassificationService {
 private final JdbcTemplate db;private final CurrentUserProvider users;private final ObjectMapper json;
 private final MoneyWebService web;private final MoneyReviewService review;private final MoneyService money;private final MoneyCommandService commands;
 public MoneyClassificationService(JdbcTemplate db,CurrentUserProvider users,ObjectMapper json,MoneyWebService web,MoneyReviewService review,MoneyService money,MoneyCommandService commands){this.db=db;this.users=users;this.json=json;this.web=web;this.review=review;this.money=money;this.commands=commands;}
 private UUID owner(){return users.getCurrentUserId();}
 private static long number(Object value){return value==null?0:((Number)value).longValue();}
 private Map<String,Object> object(Object value){return value==null?new LinkedHashMap<>():json.readValue(value.toString(),Map.class);}
 private void lock(){db.queryForObject("select pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,"money:"+owner());}
 private UUID category(Object value){return value==null?null:UUID.fromString(value.toString());}
 public record Item(UUID id,Long transactionVersion,Long overrideVersion,Long projectionVersion,Long classificationVersion,UUID categoryId,boolean directCorrection,boolean thisTransactionOnly){}
 public record Bundle(UUID requestId,List<Item> items,String explanation){public Bundle(UUID requestId,List<Item> items){this(requestId,items,null);}}
 public record Edit(UUID requestId,UUID id,Long transactionVersion,Long overrideVersion,Long projectionVersion,Map<String,Object> patch,List<String> resetFields){}
 public record Exclusion(UUID requestId,UUID id,Long expectedVersion,boolean excluded){}
 public record Undo(UUID requestId,List<UUID> eventIds,String fingerprint){}
 public Map<String,Object> request(Bundle input){require(input!=null,"요청할 거래가 필요합니다.");return commands.execute(owner(),input.requestId(),"RECLASSIFY_REQUEST",input,()->{
  require(input.items()!=null&&!input.items().isEmpty()&&input.items().size()<=50&&input.items().stream().map(Item::id).distinct().count()==input.items().size(),"현재 페이지의 1–50개 내역을 선택해 주세요.");text(input.explanation(),1000,false,"구매 설명");require(input.explanation()==null||input.explanation().isBlank()||input.items().size()==1,"구매 설명은 선택한 한 거래에만 사용합니다.");
  var books=new ArrayList<Map<String,Object>>();for(var item:input.items()){eligible(item.id());var book=web.bookkeepingRow(item.id());versions(item,book);var safeBook=new LinkedHashMap<>(book);var accountNames=db.queryForList("select display_name from money_accounts where user_id=? and id=?::uuid",String.class,owner(),book.get("accountId"));if(!accountNames.isEmpty())safeBook.put("accountName",accountNames.getFirst());books.add(safeBook);}
  String explanation=MoneyClassificationContext.conversationText(input.explanation(),books,List.of());var result=explanation.isBlank()?Map.of():Map.of("requestExplanation",explanation);
  for(var item:input.items())db.update("insert into money_classification_jobs(user_id,transaction_id,requested,result) values(?,?,true,cast(? as jsonb)) on conflict(user_id,transaction_id) do update set version=money_classification_jobs.version+1,status='QUEUED',requested=true,result=excluded.result,due_at=now(),updated_at=now()",owner(),item.id(),json.writeValueAsString(result));return Map.of("queued",input.items().size(),"scope","INDEPENDENT_TRANSACTION_OUTCOMES");
 });}
 public Map<String,Object> outcome(UUID id){return commands.outcome(owner(),id);}
 @Transactional(readOnly=true) public Map<String,Object> state(UUID id){
  money.transaction(id);var found=db.queryForList("select version,decision_version as \"decisionVersion\",event_id as \"eventId\",origin,category_id as \"categoryId\",direct_protected as \"directProtected\",future_reference_excluded as \"futureReferenceExcluded\",context_key as \"contextKey\",context_summary::text as \"contextSummary\",last_input_key as \"lastInputKey\",undone_input_key as \"undoneInputKey\" from money_classification_state where user_id=? and transaction_id=?",owner(),id);
  if(found.isEmpty())return new LinkedHashMap<>(Map.of("version",0L,"decisionVersion",0L,"directProtected",false,"futureReferenceExcluded",false));var row=found.getFirst();row.put("contextSummary",object(row.get("contextSummary")));return row;
 }
 private void versions(Item item,Map<String,Object> book){MoneyMeaningService.version(number(book.get("transactionVersion")),item.transactionVersion());MoneyMeaningService.version(number(book.get("version")),item.overrideVersion());MoneyMeaningService.version(number(book.get("projectionVersion")),item.projectionVersion());MoneyMeaningService.version(number(state(item.id()).get("version")),item.classificationVersion());}
 private void eligible(UUID id){var fact=money.transaction(id);require(Set.of(TransactionType.EXPENSE,TransactionType.INCOME).contains(fact.type())&&!fact.excluded()&&fact.mergedInto()==null,"원문·이체·환불·대출 구성은 전용 금융 확인이 필요합니다.");var book=web.bookkeepingRow(id);require(!Boolean.TRUE.equals(book.get("excluded")),"가계부 제외 내역입니다.");var queue=db.queryForList(MoneyReviewService.QUEUE+"select reason from queue where id=? and kind='TRANSACTION'",owner(),id);require(queue.stream().noneMatch(row->Set.of("POSSIBLE_INTERNAL_TRANSFER","REFUND_LINK_REQUIRED","LOAN_SPLIT_REQUIRED").contains(row.get("reason"))),"이체 후보·정정 필요 내역은 먼저 금융 확인해 주세요.");}
 @Transactional(readOnly=true) public Map<String,Object> eligibility(List<UUID> ids){require(ids!=null&&ids.size()<=50&&new HashSet<>(ids).size()==ids.size(),"현재 페이지의 서로 다른 최대 50건을 선택해 주세요.");var items=new ArrayList<Map<String,Object>>();for(UUID id:ids){var row=new LinkedHashMap<String,Object>();row.put("id",id);try{eligible(id);var book=web.bookkeepingRow(id);require(Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_tracking_accounts t join money_accounts a on a.user_id=t.user_id and a.id=t.account_id where t.user_id=? and t.account_id=? and t.kind=? and not a.archived)",Boolean.class,owner(),book.get("trackingAccountId"),book.get("type"))),"현재 가계부 추적 범위 밖입니다.");row.put("requestEligible",true);row.put("completeEligible",book.get("categoryId")!=null&&activeCategory(category(book.get("categoryId")),Objects.toString(book.get("type"))));row.put("reason",Boolean.TRUE.equals(row.get("completeEligible"))?"완료 가능":"현재 유효한 최종 분류를 선택해 주세요.");}catch(InvalidRequestException|ResourceNotFoundException error){row.put("requestEligible",false);row.put("completeEligible",false);row.put("reason",error instanceof ResourceNotFoundException?"소유 금융 내역 또는 전용 금융 확인 경로가 필요합니다.":error.getMessage());}items.add(row);}return Map.of("items",items);}
 private boolean activeCategory(UUID id,String type){return id==null||Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_categories c left join money_categories p on p.id=c.parent_id and p.user_id=c.user_id where c.user_id=? and c.id=? and c.kind=? and not c.archived and not coalesce(p.archived,false))",Boolean.class,owner(),id,type));}
 public Map<String,Object> classify(Bundle input){require(input!=null,"분류 변경이 필요합니다.");return commands.execute(owner(),input.requestId(),"CLASSIFY",input,()->{
  require(input.items()!=null&&!input.items().isEmpty()&&input.items().size()<=50&&input.items().stream().map(Item::id).distinct().count()==input.items().size(),"현재 페이지의 서로 다른 1–50개 내역을 선택해 주세요.");
  var books=new LinkedHashMap<UUID,Map<String,Object>>();for(var item:input.items()){eligible(item.id());var book=web.bookkeepingRow(item.id());versions(item,book);require(item.categoryId()!=null&&activeCategory(item.categoryId(),Objects.toString(book.get("type"))),"현재 유효한 최종 분류를 선택해 주세요.");books.put(item.id(),book);}
  var events=new ArrayList<Map<String,Object>>();for(var item:input.items())events.add(persist(item.id(),item.categoryId(),item.directCorrection()?"DIRECT":"CONFIRMED",item.thisTransactionOnly(),input.requestId(),books.get(item.id()),Map.of("source","OWNER_SELECTION"),true));
  return Map.of("bundleId",input.requestId(),"completed",events.size(),"items",events);
 });}
 @SuppressWarnings("unchecked") Map<String,Object> persist(UUID id,UUID categoryId,String origin,boolean only,UUID bundle,Map<String,Object> book,Map<String,Object> evidence,boolean complete){
  var old=state(id);var before=new LinkedHashMap<String,Object>();before.put("categoryId",book.get("categoryId"));before.put("hasOverride",((Map<?,?>)book.get("overrides")).containsKey("categoryId"));before.put("overrideCategory",((Map<?,?>)book.get("overrides")).get("categoryId"));before.put("state",old);
  var decision=db.queryForList("select displayed::text,completed_at from money_review_decisions where user_id=? and transaction_id=?",owner(),id);before.put("review",decision.isEmpty()?null:Map.of("completedAt",((Timestamp)decision.getFirst().get("completed_at")).toInstant()));
  var patch=new LinkedHashMap<String,Object>();patch.put("categoryId",categoryId==null?null:categoryId.toString());
  if(complete)review.complete(new MoneyReviewService.Complete(List.of(new MoneyReviewService.Completion(id,number(book.get("transactionVersion")),number(book.get("version")),number(book.get("projectionVersion")),patch))));
  else{var overrides=new LinkedHashMap<>((Map<String,Object>)book.get("overrides"));overrides.putAll(patch);web.saveBookkeeping(id,new MoneyWebTypes.BookkeepingEdit(number(book.get("version")),number(book.get("transactionVersion")),overrides,number(book.get("projectionVersion"))));db.update("delete from money_review_decisions where user_id=? and transaction_id=?",owner(),id);}
  var saved=web.bookkeepingRow(id);var context=MoneyClassificationContext.local(saved);String contextKey=commands.fingerprint(context),inputKey=contextKey;UUID eventId=UUID.randomUUID();
  boolean protect=Set.of("DIRECT","CONFIRMED").contains(origin),excluded=only||Boolean.TRUE.equals(old.get("futureReferenceExcluded"));long nextVersion=number(old.get("version"))+1;
  var next=new LinkedHashMap<String,Object>();next.put("categoryId",categoryId);next.put("version",nextVersion);next.put("decisionVersion",number(old.get("decisionVersion"))+1);next.put("origin",origin);next.put("review",complete);next.put("overrideVersion",saved.get("version"));next.put("transactionVersion",saved.get("transactionVersion"));next.put("projectionVersion",saved.get("projectionVersion"));
  var completed=db.queryForList("select completed_at from money_review_decisions where user_id=? and transaction_id=?",owner(),id);next.put("reviewCompletedAt",completed.isEmpty()?null:((Timestamp)completed.getFirst().get("completed_at")).toInstant());
  db.update("insert into money_classification_events(id,user_id,transaction_id,bundle_id,origin,category_id,previous_value,next_value,input_key,evidence) values(?,?,?,?,?,?,cast(? as jsonb),cast(? as jsonb),?,cast(? as jsonb))",eventId,owner(),id,bundle,origin,categoryId,json.writeValueAsString(before),json.writeValueAsString(next),inputKey,json.writeValueAsString(evidence));
  db.update("insert into money_classification_state(user_id,transaction_id,version,decision_version,event_id,origin,category_id,direct_protected,future_reference_excluded,context_key,context_summary,last_input_key) values(?,?,?,?,?,?,?,?,?,?,cast(? as jsonb),?) on conflict(user_id,transaction_id) do update set version=excluded.version,decision_version=excluded.decision_version,event_id=excluded.event_id,origin=excluded.origin,category_id=excluded.category_id,direct_protected=excluded.direct_protected,future_reference_excluded=excluded.future_reference_excluded,context_key=excluded.context_key,context_summary=excluded.context_summary,last_input_key=excluded.last_input_key,undone_input_key=null,updated_at=now()",owner(),id,nextVersion,number(old.get("decisionVersion"))+1,eventId,origin,categoryId,protect,excluded,contextKey,json.writeValueAsString(context),inputKey);
  return Map.of("id",id,"eventId",eventId,"classification",state(id),"book",web.bookkeepingRow(id));
 }
 public Map<String,Object> edit(Edit input){require(input!=null&&input.id()!=null&&input.patch()!=null,"저장할 내역과 변경값이 필요합니다.");return commands.execute(owner(),input.requestId(),"EDIT",input,()->{
  var book=web.bookkeepingRow(input.id());MoneyMeaningService.version(number(book.get("transactionVersion")),input.transactionVersion());MoneyMeaningService.version(number(book.get("version")),input.overrideVersion());MoneyMeaningService.version(number(book.get("projectionVersion")),input.projectionVersion());
  var overrides=new LinkedHashMap<String,Object>((Map<String,Object>)book.get("overrides"));if(input.resetFields()!=null)input.resetFields().forEach(overrides::remove);overrides.putAll(input.patch());
  boolean categoryEdited=input.patch().containsKey("categoryId")||input.resetFields()!=null&&input.resetFields().contains("categoryId");
  if(categoryEdited){eligible(input.id());UUID target=category(input.patch().containsKey("categoryId")?input.patch().get("categoryId"):((Map<String,Object>)book.get("ruleDefaults")).getOrDefault("categoryId",((Map<?,?>)book.get("source")).get("categoryId")));require(activeCategory(target,Objects.toString(book.get("type"))),"현재 유효한 분류를 선택해 주세요.");
   // Save other fields first within the same atomic command, then finalize classification with its current versions.
   var withoutCategory=new LinkedHashMap<>(overrides);var oldOverrides=(Map<String,Object>)book.get("overrides");if(oldOverrides.containsKey("categoryId"))withoutCategory.put("categoryId",oldOverrides.get("categoryId"));else withoutCategory.remove("categoryId");
   if(!withoutCategory.equals(oldOverrides))book=web.saveBookkeeping(input.id(),new MoneyWebTypes.BookkeepingEdit(number(book.get("version")),number(book.get("transactionVersion")),withoutCategory,number(book.get("projectionVersion"))));
   return persist(input.id(),target,"DIRECT",false,input.requestId(),book,Map.of("source","OWNER_EDIT"),target!=null);
  }
  var saved=web.saveBookkeeping(input.id(),new MoneyWebTypes.BookkeepingEdit(input.overrideVersion(),input.transactionVersion(),overrides,input.projectionVersion()));
  // An unrelated text edit preserves a previously completed classification; it never creates a completion.
  if(Objects.equals(book.get("categoryId"),saved.get("categoryId")))db.update("update money_review_decisions set override_version=?,displayed=cast(? as jsonb) where user_id=? and transaction_id=? and transaction_version=? and override_version=? and projection_version=?",saved.get("version"),json.writeValueAsString(saved),owner(),input.id(),book.get("transactionVersion"),book.get("version"),book.get("projectionVersion"));
  return Map.of("id",input.id(),"book",saved,"classification",state(input.id()));
 });}
 public Map<String,Object> exclude(Exclusion input){require(input!=null,"참고 제외 상태가 필요합니다.");return commands.execute(owner(),input.requestId(),"REFERENCE_EXCLUSION",input,()->{var old=state(input.id());MoneyMeaningService.version(number(old.get("version")),input.expectedVersion());db.update("insert into money_classification_state(user_id,transaction_id,version,future_reference_excluded) values(?,?,1,?) on conflict(user_id,transaction_id) do update set version=money_classification_state.version+1,future_reference_excluded=excluded.future_reference_excluded,updated_at=now()",owner(),input.id(),input.excluded());return Map.of("classification",state(input.id()),"scope","FUTURE_ONLY");});}
 @Transactional(readOnly=true) public Map<String,Object> history(int offset){return history(offset,null,null,null,null,null,null,null);}
 @Transactional(readOnly=true) public Map<String,Object> history(int offset,UUID transactionId,UUID contextTransactionId,String search,UUID accountId,String from,String to,String status){
  require(offset>=0&&offset<=100000,"이력 위치를 확인해 주세요.");text(search,200,false,"이력 검색");require(status==null||Set.of("ACTIVE","UNDONE","FAILED","PROTECTED").contains(status),"이력 상태를 확인해 주세요.");if(transactionId!=null)money.transaction(transactionId);if(accountId!=null)money.account(accountId);
  String base=MoneyWebService.BOOK_BASE+"""
   , history_rows as (
    select e.id,e.id as "eventId",'EVENT'::text as "sourceKind",e.transaction_id as "transactionId",e.bundle_id as "bundleId",e.origin,e.category_id as "categoryId",e.previous_value::text as "previousValue",e.next_value::text as "nextValue",e.evidence::text,e.active,e.created_at as "createdAt",
     coalesce(b.title,t.title) title,coalesce(b."counterpartyText",t.counterparty_text) merchant,coalesce(b."accountId",t.from_account_id,t.to_account_id) as "accountId",coalesce(b."occurredAt",t.occurred_at) as "occurredAt",t.type,t.amount,t.currency,
     case when b.id is not null then b."categoryId" else t.category_id end as "currentCategoryId",(e.previous_value->>'categoryId')::uuid as "previousCategoryId",e.category_id as "resultCategoryId",
     coalesce(e.evidence->>'reason',case e.origin when 'DIRECT' then '직접 분류 수정' when 'CONFIRMED' then '사용자가 확인한 분류' when 'DIRECT_REFERENCE' then '같은 구매 맥락의 직접 수정 참고' when 'APPROVED_RULE' then '승인된 분류 규칙' else '자동 분류 결과' end) as reason,
     case when e.active then 'ACTIVE' else 'UNDONE' end status,e.input_key as "inputKey",b."classificationJobStatus"
    from money_classification_events e join money_transactions t on t.user_id=e.user_id and t.id=e.transaction_id left join effective b on b.id=t.id where e.user_id=?
    union all
    select t.id,null::uuid,'JOB',t.id,null::uuid,'AI',null::uuid,'{}','{}',coalesce(j.result,'{}')::text,false,j.updated_at,coalesce(b.title,t.title),coalesce(b."counterpartyText",t.counterparty_text),coalesce(b."accountId",t.from_account_id,t.to_account_id),coalesce(b."occurredAt",t.occurred_at),t.type,t.amount,t.currency,
     case when b.id is not null then b."categoryId" else t.category_id end,null::uuid,null::uuid,
     case j.status when 'PROTECTED' then '현재 직접 수정 또는 변경된 근거를 보호하여 분류를 적용하지 않았습니다.' else '자동 분류 결과를 적용하지 못했습니다. 현재 분류는 유지됩니다.' end,
     j.status,j.input_key,j.status
    from money_classification_jobs j join money_transactions t on t.user_id=j.user_id and t.id=j.transaction_id left join effective b on b.id=t.id where j.user_id=? and j.status in ('FAILED','PROTECTED')
   )
   """;
  var args=new ArrayList<Object>(List.of(owner(),owner(),owner()));String filter=" from history_rows where true";
  if(transactionId!=null){filter+=" and \"transactionId\"=?";args.add(transactionId);}
  if(contextTransactionId!=null){var context=MoneyClassificationContext.local(web.bookkeepingRow(contextTransactionId));filter+=" and \"inputKey\"=? and \"transactionId\"<>?";args.add(commands.fingerprint(context));args.add(contextTransactionId);}
  if(accountId!=null){filter+=" and \"accountId\"=?";args.add(accountId);}
  if(search!=null&&!search.isBlank()){filter+=" and position(lower(?) in lower(coalesce(title,'')||' '||coalesce(merchant,'')||' '||coalesce(reason,'')))>0";args.add(search);}
  var zone=java.time.ZoneId.of("Asia/Seoul");if(from!=null){filter+=" and \"createdAt\" >=?";args.add(Timestamp.from(java.time.LocalDate.parse(from).atStartOfDay(zone).toInstant()));}if(to!=null){filter+=" and \"createdAt\" <?";args.add(Timestamp.from(java.time.LocalDate.parse(to).plusDays(1).atStartOfDay(zone).toInstant()));}if(status!=null){filter+=" and status=?";args.add(status);}
  long total=db.queryForObject(base+"select count(*)"+filter,Long.class,args.toArray());var listArgs=new ArrayList<>(args);listArgs.add(offset);var events=db.queryForList(base+"select *"+filter+" order by \"createdAt\" desc,id desc limit 50 offset ?",listArgs.toArray());
  for(var event:events){for(String field:List.of("previousValue","nextValue","evidence"))event.put(field,object(event.get(field)));event.replaceAll((k,v)->v instanceof Timestamp t?t.toInstant():v);}return Map.of("items",events,"total",total);
 }
 private List<Map<String,Object>> undoRows(List<UUID> ids){require(ids!=null&&!ids.isEmpty()&&ids.size()<=50&&new HashSet<>(ids).size()==ids.size(),"서로 다른 1–50개 변경을 선택해 주세요.");var rows=db.queryForList("select id,transaction_id,previous_value::text,next_value::text,input_key,active,created_at from money_classification_events where user_id=? and id=any(?) order by id",owner(),ids.toArray(new UUID[0]));require(rows.size()==ids.size(),"소유한 변경 이력만 복구할 수 있습니다.");return rows;}
 private String undoReason(Map<String,Object> event){if(!Boolean.TRUE.equals(event.get("active")))return "이미 실행 취소된 변경";if(!object(event.get("previous_value")).containsKey("state"))return "복구 근거의 보관이 종료됨";UUID id=(UUID)event.get("transaction_id");var state=state(id);var after=object(event.get("next_value"));if(!event.get("id").equals(state.get("eventId"))||number(state.get("decisionVersion"))!=number(after.get("decisionVersion")))return "이후 분류 변경";Map<String,Object> book;try{book=web.bookkeepingRow(id);}catch(ResourceNotFoundException e){return "현재 금융·가계부 범위에서 복구 불가";}if(!Objects.equals(category(book.get("categoryId")),category(after.get("categoryId")))||number(book.get("transactionVersion"))!=number(after.get("transactionVersion"))||number(book.get("projectionVersion"))!=number(after.get("projectionVersion")))return "이후 분류·금융 또는 규칙 변경";var before=object(event.get("previous_value"));if(!activeCategory(category(before.get("categoryId")),Objects.toString(book.get("type"))))return "이전 분류가 비활성 또는 삭제됨";return null;}
 @Transactional(readOnly=true) public Map<String,Object> undoPreview(List<UUID> ids){var eligible=new ArrayList<UUID>();var excluded=new ArrayList<Map<String,Object>>();var stamps=new ArrayList<Object>();for(var event:undoRows(ids)){String reason=undoReason(event);if(reason==null){eligible.add((UUID)event.get("id"));stamps.add(Arrays.asList(event.get("id"),state((UUID)event.get("transaction_id")).get("decisionVersion"),object(event.get("next_value"))));}else excluded.add(Map.of("eventId",event.get("id"),"reason",reason));}return Map.of("eligibleEventIds",eligible,"excluded",excluded,"fingerprint",commands.fingerprint(stamps));}
 public Map<String,Object> undo(Undo input){require(input!=null,"복구 범위를 확인해 주세요.");return commands.execute(owner(),input.requestId(),"UNDO_CLASSIFICATION",input,()->{
  var preview=undoPreview(input.eventIds());require(((List<?>)preview.get("excluded")).isEmpty(),"복구 범위에 이후 수정 또는 복구 불가 항목이 있습니다. 범위를 다시 확인해 주세요.");if(!Objects.equals(preview.get("fingerprint"),input.fingerprint()))throw new OptimisticLockConflictException("복구 미리보기 이후 분류가 변경되었습니다. 전체 묶음을 적용하지 않았습니다.");
  for(var event:undoRows(input.eventIds())){UUID id=(UUID)event.get("transaction_id");var before=object(event.get("previous_value"));var oldState=(Map<String,Object>)before.get("state");var now=state(id);var book=web.bookkeepingRow(id);var overrides=new LinkedHashMap<>((Map<String,Object>)book.get("overrides"));if(Boolean.TRUE.equals(before.get("hasOverride")))overrides.put("categoryId",before.get("overrideCategory"));else overrides.remove("categoryId");var saved=web.saveBookkeeping(id,new MoneyWebTypes.BookkeepingEdit(number(book.get("version")),number(book.get("transactionVersion")),overrides,number(book.get("projectionVersion"))));
   // Restore review only while it still belongs to this classification event; separate owner review actions survive.
   var after=object(event.get("next_value"));var currentDecision=db.queryForList("select override_version,transaction_version,projection_version,completed_at from money_review_decisions where user_id=? and transaction_id=?",owner(),id);
   boolean separateReview=Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_ai_events where user_id=? and subject_id=? and active and created_at>? and kind in('DEFER','REOPEN','UNDO'))",Boolean.class,owner(),id,event.get("created_at")));
   boolean linkedReview=!separateReview&&!currentDecision.isEmpty()&&number(currentDecision.getFirst().get("override_version"))==number(book.get("version"))&&number(currentDecision.getFirst().get("transaction_version"))==number(after.get("transactionVersion"))&&number(currentDecision.getFirst().get("projection_version"))==number(after.get("projectionVersion"))&&(after.get("reviewCompletedAt")==null||((Timestamp)currentDecision.getFirst().get("completed_at")).toInstant().equals(Instant.parse(after.get("reviewCompletedAt").toString())));
   if(linkedReview){if(before.get("review")==null)db.update("delete from money_review_decisions where user_id=? and transaction_id=?",owner(),id);else{var previous=(Map<String,Object>)before.get("review");db.update("update money_review_decisions set override_version=?,projection_version=?,displayed=cast(? as jsonb),completed_at=? where user_id=? and transaction_id=?",saved.get("version"),saved.get("projectionVersion"),json.writeValueAsString(saved),Timestamp.from(Instant.parse(previous.get("completedAt").toString())),owner(),id);}}
   if(!linkedReview&&!currentDecision.isEmpty()&&number(currentDecision.getFirst().get("override_version"))==number(book.get("version")))db.update("update money_review_decisions set override_version=?,displayed=cast(? as jsonb) where user_id=? and transaction_id=?",saved.get("version"),json.writeValueAsString(saved),owner(),id);
   // Append preservation evidence instead of rewriting the owner's original review event.
   var reviewEvents=db.queryForList("select id,kind,payload::text from money_ai_events where user_id=? and subject_id=? and active and kind in('DEFER','REOPEN','UNDO') and created_at>? order by created_at desc,id desc limit 1",owner(),id,event.get("created_at"));
   if(!reviewEvents.isEmpty()){var r=reviewEvents.getFirst();var payload=object(r.get("payload"));var prior=(Map<String,Object>)payload.get("after");if(prior!=null&&number(prior.get("transactionVersion"))==number(book.get("transactionVersion"))&&number(prior.get("overrideVersion"))==number(book.get("version"))&&number(prior.get("projectionVersion"))==number(book.get("projectionVersion"))){var nextReview=new LinkedHashMap<>(prior);nextReview.put("overrideVersion",saved.get("version"));payload.put("after",nextReview);payload.put("preservedReviewEventId",r.get("id"));payload.put("preservationReason","CLASSIFICATION_UNDO");db.update("insert into money_ai_events(id,user_id,subject_id,kind,payload,created_at) values(?,?,?,?,cast(? as jsonb),clock_timestamp())",UUID.randomUUID(),owner(),id,r.get("kind"),json.writeValueAsString(payload));}}
   var currentContext=MoneyClassificationContext.local(saved);String undoneKey=commands.fingerprint(currentContext);
   db.update("update money_classification_state set version=version+1,decision_version=decision_version+1,event_id=?::uuid,origin=?,category_id=?::uuid,direct_protected=?,context_key=?,context_summary=cast(? as jsonb),last_input_key=?,undone_input_key=?,updated_at=now() where user_id=? and transaction_id=?",oldState.get("eventId"),oldState.get("origin"),before.get("categoryId"),Boolean.TRUE.equals(oldState.get("directProtected")),undoneKey,json.writeValueAsString(currentContext),oldState.get("lastInputKey"),undoneKey,owner(),id);
   db.update("update money_classification_events set active=false where user_id=? and id=?",owner(),event.get("id"));db.update("update money_classification_jobs set status='UNDONE',input_key=?,result=cast(? as jsonb),updated_at=now() where user_id=? and transaction_id=?",undoneKey,json.writeValueAsString(Map.of("reason","OWNER_UNDO","eventId",event.get("id"))),owner(),id);
  }return Map.of("restored",input.eventIds().size(),"eventIds",input.eventIds());
 });}
}
