package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import static com.kafka.backend.money.MoneyService.*;

/** Explicit historical scope, durable independent outcomes and resumable foreground processing. */
@Service
public class MoneyAiHistoryService {
 private final JdbcTemplate db;private final CurrentUserProvider users;private final ObjectMapper json;private final MoneyCommandService commands;private final MoneyMeaningService meaning;private final MoneyWebService web;private final MoneyClassificationService classification;private final TransactionTemplate tx;
 public MoneyAiHistoryService(JdbcTemplate db,CurrentUserProvider users,ObjectMapper json,MoneyCommandService commands,MoneyMeaningService meaning,MoneyWebService web,MoneyClassificationService classification,PlatformTransactionManager manager){this.db=db;this.users=users;this.json=json;this.commands=commands;this.meaning=meaning;this.web=web;this.classification=classification;this.tx=new TransactionTemplate(manager);}
 private UUID owner(){return users.getCurrentUserId();}private static long number(Object n){return n==null?0:((Number)n).longValue();}
 private Map<String,Object> object(Object value){return value==null?Map.of():json.readValue(value.toString(),Map.class);}
 private void lock(){db.queryForObject("select pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,"money:"+owner());}
 public record Scope(UUID ruleId,Long ruleVersion,String from,String to,UUID accountId){}
 public record Start(UUID requestId,Scope scope,String fingerprint){}
 public record Control(UUID requestId,UUID id,Long expectedVersion,boolean pause,boolean retryFailed){}
 private Map<String,Object> rule(Scope scope){return meaning.rules().stream().filter(r->Objects.equals(r.get("id"),scope.ruleId())&&"ACTIVE".equals(r.get("status"))).findFirst().map(r->{MoneyMeaningService.version(number(r.get("version")),scope.ruleVersion());require(r.get("categoryId")!=null,"분류가 있는 현재 승인 규칙을 선택해 주세요.");return r;}).orElseThrow(()->new InvalidRequestException("현재 활성 규칙을 다시 확인해 주세요."));}
 private String protectedReason(Map<String,Object> book){
  if(Boolean.TRUE.equals(book.get("excluded")))return "가계부 제외";
  if(Boolean.TRUE.equals(book.get("directProtected"))||((Map<?,?>)book.get("source")).get("categoryId")!=null||((Map<?,?>)book.get("overrides")).containsKey("categoryId")&&book.get("classificationOrigin")==null)return "현재 직접 지정 보호";
  if(!Boolean.TRUE.equals(db.queryForObject("select exists(select 1 from money_tracking_accounts t join money_accounts a on a.user_id=t.user_id and a.id=t.account_id where t.user_id=? and t.account_id=? and t.kind=? and not a.archived)",Boolean.class,owner(),book.get("trackingAccountId"),book.get("type"))))return "현재 추적 범위 제외";
  if(db.queryForObject(MoneyReviewService.QUEUE+"select count(*) from queue where id=? and kind='TRANSACTION' and reason in('POSSIBLE_INTERNAL_TRANSFER','REFUND_LINK_REQUIRED','LOAN_SPLIT_REQUIRED')",Long.class,owner(),book.get("id"))>0)return "금융 확인 필요";
  return null;
 }
 private Map<String,Object> snapshot(Map<String,Object> book){return Map.of("transactionVersion",book.get("transactionVersion"),"overrideVersion",book.get("version"),"projectionVersion",book.get("projectionVersion"),"classificationVersion",book.get("classificationVersion"),"contextKey",commands.fingerprint(MoneyClassificationContext.local(book)));}
 private boolean sameSnapshot(Map<String,Object> current,Map<String,Object> saved){return List.of("transactionVersion","overrideVersion","projectionVersion","classificationVersion").stream().allMatch(key->number(current.get(key))==number(saved.get(key)))&&Objects.equals(current.get("contextKey"),saved.get("contextKey"));}
 @Transactional(readOnly=true) public Map<String,Object> preview(Scope scope){require(scope!=null,"과거 적용 범위를 확인해 주세요.");var from=LocalDate.parse(scope.from());var to=LocalDate.parse(scope.to());require(!from.isAfter(to)&&java.time.temporal.ChronoUnit.DAYS.between(from,to)<=366,"최대 367일 범위를 선택해 주세요.");var rule=rule(scope);var conditions=json.readValue(json.writeValueAsString(rule.get("conditions")),MoneyRuleEngine.Condition[].class);
  var books=db.queryForList(MoneyWebService.BOOK_BASE+"select * from effective where \"occurredAt\">=? and \"occurredAt\"<? and (?::uuid is null or \"accountId\"=?::uuid) and type in('EXPENSE','INCOME') order by id limit 10001",owner(),Timestamp.from(from.atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()),Timestamp.from(to.plusDays(1).atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()),scope.accountId(),scope.accountId());require(books.size()<=10000,"과거 적용 범위를 좁혀 주세요. 최대 10,000건입니다.");
  var tracked=new HashSet<>(db.queryForList("select t.account_id,t.kind from money_tracking_accounts t join money_accounts a on a.user_id=t.user_id and a.id=t.account_id where t.user_id=? and not a.archived",owner()).stream().map(t->t.get("account_id")+":"+t.get("kind")).toList());var financial=new HashSet<>(db.queryForList(MoneyReviewService.QUEUE+"select id from queue where kind='TRANSACTION' and reason in('POSSIBLE_INTERNAL_TRANSFER','REFUND_LINK_REQUIRED','LOAN_SPLIT_REQUIRED')",UUID.class,owner()));boolean approved=MoneyApprovedRuleGuard.current(db,json,owner(),scope.ruleId(),scope.ruleVersion(),null);
  var items=new ArrayList<Map<String,Object>>();for(var raw:books){UUID id=(UUID)raw.get("id");var facts=new LinkedHashMap<>(raw);facts.put("merchant",raw.get("counterpartyText"));facts.put("accountId",Objects.toString(raw.get("accountId"),""));if(!Arrays.stream(conditions).allMatch(c->MoneyRuleEngine.matches(facts,c)))continue;var book=web.decodeBook(raw);String reason=Boolean.TRUE.equals(book.get("excluded"))?"가계부 제외":Boolean.TRUE.equals(book.get("directProtected"))||((Map<?,?>)book.get("source")).get("categoryId")!=null||((Map<?,?>)book.get("overrides")).containsKey("categoryId")&&book.get("classificationOrigin")==null?"현재 직접 지정 보호":!tracked.contains(book.get("trackingAccountId")+":"+book.get("type"))?"현재 추적 범위 제외":financial.contains(id)?"금융 확인 필요":null;if(reason==null&&(!approved||"AI_APPROVED".equals(rule.get("origin"))&&!MoneyApprovedRuleGuard.current(db,json,owner(),scope.ruleId(),scope.ruleVersion(),id)))reason="규칙 승인 근거 또는 권한 변경";if(reason==null&&Objects.equals(book.get("categoryId"),rule.get("categoryId")))reason="현재 분류와 동일";var item=new LinkedHashMap<String,Object>();item.put("id",id);item.put("beforeCategoryId",book.get("categoryId"));item.put("categoryId",rule.get("categoryId"));item.put("snapshot",snapshot(book));item.put("status",reason==null?"PENDING":"PROTECTED");item.put("reason",reason);items.add(item);}
  var dictionary=db.queryForList("select id,version,archived,parent_id from money_categories where user_id=? order by id",owner());String fingerprint=commands.fingerprint(Arrays.asList(scope,rule,items,dictionary));return Map.of("items",items,"eligible",items.stream().filter(i->"PENDING".equals(i.get("status"))).count(),"protected",items.stream().filter(i->"PROTECTED".equals(i.get("status"))).count(),"fingerprint",fingerprint,"scope","EXPLICIT_HISTORICAL_INDEPENDENT_OUTCOMES");
 }
 public Map<String,Object> start(Start input){return commands.execute(owner(),input.requestId(),"HISTORY_START",input,()->{var preview=preview(input.scope());if(!Objects.equals(preview.get("fingerprint"),input.fingerprint()))throw new OptimisticLockConflictException("규칙·대상 또는 입력이 변경되었습니다. 다시 미리보기 해 주세요.");UUID id=UUID.randomUUID();db.update("insert into money_ai_history_runs(id,user_id,rule_id,rule_version,scope,fingerprint) values(?,?,?,?,cast(? as jsonb),?)",id,owner(),input.scope().ruleId(),input.scope().ruleVersion(),json.writeValueAsString(input.scope()),input.fingerprint());for(var item:(List<Map<String,Object>>)preview.get("items"))db.update("insert into money_ai_history_items(run_id,user_id,transaction_id,status,snapshot,result) values(?,?,?,?,cast(? as jsonb),cast(? as jsonb))",id,owner(),item.get("id"),item.get("status"),json.writeValueAsString(item.get("snapshot")),json.writeValueAsString(item));return read(id,0);});}
 private Map<String,Object> run(UUID id){var rows=db.queryForList("select id,version,status,rule_id,rule_version,scope::text from money_ai_history_runs where user_id=? and id=?",owner(),id);if(rows.isEmpty())throw new ResourceNotFoundException("과거 적용 작업을 찾을 수 없습니다.");return rows.getFirst();}
 @Transactional(readOnly=true) public Map<String,Object> read(UUID id,int offset){require(offset>=0,"조회 위치를 확인해 주세요.");var run=run(id);var items=db.queryForList("select transaction_id as \"transactionId\",status,result::text from money_ai_history_items where user_id=? and run_id=? order by transaction_id limit 50 offset ?",owner(),id,offset);items.forEach(i->i.put("result",object(i.get("result"))));return Map.of("run",run,"items",items,"counts",db.queryForList("select status,count(*) as count from money_ai_history_items where user_id=? and run_id=? group by status order by status",owner(),id),"total",db.queryForObject("select count(*) from money_ai_history_items where user_id=? and run_id=?",Long.class,owner(),id));}
 @Transactional(readOnly=true) public List<Map<String,Object>> list(){return db.queryForList("select id,version,status,scope,created_at from money_ai_history_runs where user_id=? order by created_at desc,id limit 50",owner());}
 public Map<String,Object> control(Control input){return commands.execute(owner(),input.requestId(),"HISTORY_CONTROL",input,()->{var run=run(input.id());MoneyMeaningService.version(number(run.get("version")),input.expectedVersion());if(input.retryFailed())db.update("update money_ai_history_items set status='PENDING',updated_at=now() where user_id=? and run_id=? and status='FAILED'",owner(),input.id());db.update("update money_ai_history_runs set status=?,version=version+1,updated_at=now() where user_id=? and id=?",input.pause()?"PAUSED":"RUNNING",owner(),input.id());return read(input.id(),0);});}
 /** Every item has its own transaction; a lost HTTP response is resolved by reading the run, never replaying applied items. */
 public Map<String,Object> advance(UUID id){var run=run(id);require("RUNNING".equals(run.get("status")),"진행 중인 작업만 처리할 수 있습니다.");var ids=db.queryForList("select transaction_id from money_ai_history_items where user_id=? and run_id=? and status='PENDING' order by transaction_id limit 50",owner(),id);for(var item:ids){UUID transaction=(UUID)item.get("transaction_id");try{tx.executeWithoutResult(status->applyItem(id,transaction));}catch(RuntimeException error){tx.executeWithoutResult(status->{lock();boolean changed=error instanceof InvalidRequestException||error instanceof ResourceNotFoundException||error instanceof OptimisticLockConflictException;db.update("update money_ai_history_items set status=?,result=jsonb_build_object('reason',?::text),updated_at=now() where user_id=? and run_id=? and transaction_id=? and status='PENDING'",changed?"PROTECTED":"FAILED",changed?"현재 원본·분류 또는 적용 범위 변경":"APPLY_FAILED",owner(),id,transaction);});}}
  tx.executeWithoutResult(status->{lock();db.update("update money_ai_history_runs r set status='COMPLETED',version=version+1,updated_at=now() where r.user_id=? and r.id=? and status='RUNNING' and not exists(select 1 from money_ai_history_items i where i.user_id=r.user_id and i.run_id=r.id and i.status='PENDING')",owner(),id);});return read(id,0);
 }
 private void applyItem(UUID id,UUID transaction){lock();var run=run(id);if(!"RUNNING".equals(run.get("status")))return;var items=db.queryForList("select status,snapshot::text from money_ai_history_items where user_id=? and run_id=? and transaction_id=? for update",owner(),id,transaction);if(items.isEmpty()||!"PENDING".equals(items.getFirst().get("status")))return;var scope=json.readValue(run.get("scope").toString(),Scope.class);var rule=rule(scope);var book=web.bookkeepingRow(transaction);String reason=protectedReason(book);if(reason==null&&!sameSnapshot(snapshot(book),object(items.getFirst().get("snapshot"))))reason="이후 입력·분류 변경";if(reason==null&&!MoneyApprovedRuleGuard.current(db,json,owner(),scope.ruleId(),scope.ruleVersion(),transaction))reason="규칙 승인 근거 또는 권한 변경";
  if(reason!=null){db.update("update money_ai_history_items set status='PROTECTED',result=jsonb_build_object('reason',?::text),updated_at=now() where user_id=? and run_id=? and transaction_id=?",reason,owner(),id,transaction);return;}
  var saved=classification.persist(transaction,(UUID)rule.get("categoryId"),"APPROVED_RULE",false,id,book,Map.of("reason","명시 승인한 과거 범위 적용","ruleId",scope.ruleId(),"ruleVersion",scope.ruleVersion(),"historyRunId",id),true);db.update("update money_ai_history_items set status='APPLIED',result=cast(? as jsonb),updated_at=now() where user_id=? and run_id=? and transaction_id=?",json.writeValueAsString(Map.of("eventId",saved.get("eventId"),"categoryId",rule.get("categoryId"))),owner(),id,transaction);
 }
}
