package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.springframework.stereotype.Service;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import static com.kafka.backend.money.MoneyService.*;

/** Conversations and unapplied proposals never execute rules. Approval is a separate durable atomic command. */
@Service
public class MoneyAiWorkspaceService {
 private final JdbcTemplate db;private final CurrentUserProvider users;private final ObjectMapper json;private final MoneyCommandService commands;private final MoneyMeaningService meaning;private final MoneyWebService web;private final MoneyService money;
 public MoneyAiWorkspaceService(JdbcTemplate db,CurrentUserProvider users,ObjectMapper json,MoneyCommandService commands,MoneyMeaningService meaning,MoneyWebService web,MoneyService money){this.db=db;this.users=users;this.json=json;this.commands=commands;this.meaning=meaning;this.web=web;this.money=money;}
 private MoneyConversationProvider provider=input->new MoneyConversationProvider.Result("",List.of(),"INTERNAL",null,"PROVIDER_NOT_READY");
 @org.springframework.beans.factory.annotation.Autowired void provider(MoneyConversationProvider value){provider=value;}
 private UUID owner(){return users.getCurrentUserId();}
 private static long number(Object value){return value==null?0:((Number)value).longValue();}
 private Map<String,Object> object(Object value){return value==null?new LinkedHashMap<>():json.readValue(value.toString(),Map.class);}
 private List<Map<String,Object>> rows(String sql,Object...args){var rows=db.queryForList(sql,args);for(var row:rows)row.replaceAll((k,v)->v instanceof Timestamp t?t.toInstant():v);return rows;}
 private Map<String,Object> conversation(UUID id){var rows=rows("select id,title,version,messages::text,references_json::text as references,last_activity_at as \"lastActivityAt\",expired_at as \"expiredAt\" from money_ai_conversations where user_id=? and id=?",owner(),id);if(rows.isEmpty())throw new ResourceNotFoundException("대화를 찾을 수 없습니다.");var row=rows.getFirst();for(String field:List.of("messages","references"))row.put(field,json.readValue(row.get(field).toString(),List.class));var ownerMessages=((List<Map<String,Object>>)row.get("messages")).stream().filter(m->"OWNER".equals(m.get("role"))).toList();row.put("ruleReferences",ownerMessages.isEmpty()?List.of():ownerMessages.getLast().getOrDefault("ruleReferences",List.of()));return row;}
 @Transactional public Map<String,Object> read(){retain();return Map.of("conversations",rows("select id,title,version,last_activity_at as \"lastActivityAt\",expired_at as \"expiredAt\" from money_ai_conversations where user_id=? order by last_activity_at desc,id limit 100",owner()),"drafts",drafts(),"retention",Map.of("conversationDays",90,"unappliedDrafts","UNTIL_EXPLICIT_DISCARD","auditDaysMinimum",365),"answerMode","CURRENT_INTERNAL_EVIDENCE");}
 @Transactional public Map<String,Object> readConversation(UUID id){retain();return conversation(id);}
 public record RuleReference(UUID id,Long version){}
 public record Message(UUID requestId,UUID conversationId,Long expectedVersion,String text,List<UUID> references,List<RuleReference> ruleReferences){
  public Message(UUID requestId,UUID conversationId,Long expectedVersion,String text,List<UUID> references){this(requestId,conversationId,expectedVersion,text,references,List.of());}
 }
 private List<Map<String,Object>> referencedRules(List<RuleReference> references,List<Map<String,Object>> rules){
  if(references==null)return List.of();require(references.size()<=10&&references.stream().map(RuleReference::id).distinct().count()==references.size(),"참고 규칙은 서로 다른 최대 10개입니다.");
  return references.stream().map(reference->{var rule=rules.stream().filter(r->reference.id().equals(r.get("id"))).findFirst().orElseThrow(()->new ResourceNotFoundException("소유한 참고 규칙을 찾을 수 없습니다."));MoneyMeaningService.version(number(rule.get("version")),reference.version());return rule;}).toList();
 }
 public Map<String,Object> message(Message input){
 try{
  text(input.text(),4000,true,"대화 내용");require(input.references()!=null&&input.references().size()<=10&&new HashSet<>(input.references()).size()==input.references().size(),"참고 거래는 서로 다른 최대 10개입니다.");if(!"UNKNOWN".equals(commands.outcome(owner(),input.requestId()).get("status")))return commands.execute(owner(),input.requestId(),"AI_CONVERSATION",input,Map::of);
  Map<String,Object> prior=input.conversationId()==null?null:conversation(input.conversationId());if(prior!=null){MoneyMeaningService.version(number(prior.get("version")),input.expectedVersion());require(prior.get("expiredAt")==null&&!((Instant)prior.get("lastActivityAt")).isBefore(Instant.now().minus(java.time.Duration.ofDays(90))),"보관 기간이 지난 대화입니다. 새 대화를 시작해 주세요.");}
  var initialBooks=input.references().stream().map(web::bookkeepingRow).toList();var initialRules=meaning.rules();var selectedRules=referencedRules(input.ruleReferences(),initialRules);String source=commands.fingerprint(Arrays.asList(initialBooks,initialRules));var allowedCategories=db.queryForList("select c.id,c.name,c.kind,c.parent_id from money_categories c left join money_categories p on p.id=c.parent_id and p.user_id=c.user_id where c.user_id=? and not c.archived and not coalesce(p.archived,false) order by c.id",owner());var safeBooks=new ArrayList<Map<String,Object>>();for(var book:initialBooks){var safe=new LinkedHashMap<>(MoneyClassificationContext.minimized(book,List.of()));safe.put("accountId",book.get("accountId"));safe.put("categoryId",book.get("categoryId"));safe.put("origin",book.get("classificationOrigin"));safeBooks.add(safe);}
  var privacyBooks=new ArrayList<Map<String,Object>>(initialBooks);privacyBooks.addAll(db.queryForList("select display_name as \"accountDisplayName\" from money_accounts where user_id=?",owner()));
  if(prior!=null)for(Object reference:(List<?>)prior.get("references")){try{privacyBooks.add(web.bookkeepingRow(UUID.fromString(reference.toString())));}catch(ResourceNotFoundException ignored){/* Removed financial references are not provider context. */}}
  var history=new ArrayList<Map<String,Object>>();boolean keepHistory=prior!=null&&((List<?>)prior.get("references")).stream().allMatch(ref->input.references().stream().anyMatch(id->id.toString().equals(ref.toString())))&&((List<Map<String,Object>>)prior.get("ruleReferences")).stream().allMatch(ref->input.ruleReferences()!=null&&input.ruleReferences().stream().anyMatch(rule->rule.id().toString().equals(ref.get("id").toString())));if(keepHistory){var previous=(List<Map<String,Object>>)prior.get("messages");for(var message:previous.subList(Math.max(0,previous.size()-8),previous.size()))history.add(Map.of("role",message.get("role"),"text",MoneyClassificationContext.conversationText(Objects.toString(message.get("text"),""),privacyBooks,selectedRules)));}
  String question=MoneyClassificationContext.conversationText(input.text(),privacyBooks,selectedRules);var response=provider.answer(Map.of("question",question,"history",history,"references",safeBooks,"categories",allowedCategories,"rules",selectedRules.stream().map(r->{var safe=new LinkedHashMap<String,Object>();for(String key:List.of("id","version","conditions","categoryId","status"))safe.put(key,r.get(key));safe.put("conditions",((List<Map<String,Object>>)json.readValue(json.writeValueAsString(r.get("conditions")),List.class)).stream().map(c->{var condition=new LinkedHashMap<>(c);if(c.get("value")instanceof String value)condition.put("value",MoneyClassificationContext.conversationText(value,privacyBooks,selectedRules));if("merchant".equals(c.get("field"))&&!MoneyClassificationContext.business(Objects.toString(c.get("value"))))condition.put("value","개인 또는 확인되지 않은 상대방");return condition;}).toList());return safe;}).toList()));
  return commands.execute(owner(),input.requestId(),"AI_CONVERSATION",input,()->{
  text(input.text(),4000,true,"대화 내용");require(input.references()!=null&&input.references().size()<=10&&new HashSet<>(input.references()).size()==input.references().size(),"참고 거래는 서로 다른 최대 10개입니다.");var books=new ArrayList<Map<String,Object>>();for(UUID id:input.references())books.add(web.bookkeepingRow(id));
  UUID id=input.conversationId();List<Map<String,Object>> messages=new ArrayList<>();if(id!=null){var old=conversation(id);MoneyMeaningService.version(number(old.get("version")),input.expectedVersion());require(old.get("expiredAt")==null,"보관 기간이 지난 대화입니다. 새 대화를 시작해 주세요.");messages.addAll((List<Map<String,Object>>)old.get("messages"));require(messages.size()<200,"대화가 길어졌습니다. 새 대화에서 이어가 주세요.");}else{id=UUID.randomUUID();db.update("insert into money_ai_conversations(id,user_id,title) values(?,?,?)",id,owner(),input.text().strip().substring(0,Math.min(80,input.text().strip().length())));}
  if(!source.equals(commands.fingerprint(Arrays.asList(books,meaning.rules()))))throw new OptimisticLockConflictException("참고 거래 또는 규칙이 응답 도중 변경되었습니다. 입력을 보존하고 최신 근거로 다시 요청해 주세요.");
  String answer=response.errorCode()==null?"현재 내부 근거의 설명·미적용 제안입니다. 실행한 규칙과 거래 변경은 없습니다.\n"+response.text():answer(input.text(),books)+"\n"+("PROVIDER_NOT_READY".equals(response.errorCode())?"대화 AI 제공자가 준비되지 않아 현재 내부 자료로 설명했습니다.":"대화 AI 응답을 가져오지 못해 현재 내부 자료로 설명했습니다. 초안은 자동 실행하지 않았습니다.");
  var generated=new ArrayList<Map<String,Object>>();if(response.errorCode()==null)for(var proposal:response.proposals()){require(generated.size()<3,"초안은 최대 3개입니다.");validate(proposal.rule(),db.queryForList("select id,parent_id,kind,archived,version from money_categories where user_id=?",owner()),db.queryForList("select id,archived,version from money_accounts where user_id=?",owner()));var saved=saveDraft(new DraftInput(UUID.randomUUID(),null,null,id,proposal.targetRuleId(),proposal.sourceVersion(),proposal.summary(),proposal.rule()));require("APPLIED".equals(saved.get("status")),"생성한 초안의 현재 원본을 확인해 주세요.");generated.add((Map<String,Object>)((Map<String,Object>)saved.get("result")).get("draft"));}
  referencedRules(input.ruleReferences(),meaning.rules());messages.add(Map.of("role","OWNER","text",input.text().strip(),"at",Instant.now(),"ruleReferences",input.ruleReferences()==null?List.of():input.ruleReferences()));messages.add(Map.of("role","ASSISTANT","text",answer,"at",Instant.now(),"source",response.errorCode()==null?"AI_INTERNAL_CONTEXT":"CURRENT_INTERNAL_EVIDENCE"));
  db.update("update money_ai_conversations set messages=cast(? as jsonb),references_json=cast(? as jsonb),version=version+1,last_activity_at=now() where user_id=? and id=?",json.writeValueAsString(messages),json.writeValueAsString(input.references()),owner(),id);return Map.of("conversation",conversation(id),"executedRules",0,"changedTransactions",0,"generatedDrafts",generated,"answerSource",response.errorCode()==null?"AI_INTERNAL_CONTEXT":"CURRENT_INTERNAL_EVIDENCE");
 });}catch(OptimisticLockConflictException|InvalidRequestException|ResourceNotFoundException error){return commands.execute(owner(),input.requestId(),"AI_CONVERSATION",input,()->{throw error;});}
 }
 private String answer(String question,List<Map<String,Object>> books){
  if(books.isEmpty())return "현재 활성 분류 규칙은 "+meaning.rules().stream().filter(r->"ACTIVE".equals(r.get("status"))).count()+"개입니다. 설명할 거래를 참고 항목에 추가하시거나 규칙 초안의 거래처·유형·계좌·최종 분류를 지정해 주세요. 대화 저장만으로 규칙이나 거래를 변경하지 않습니다.";
  var categories=db.queryForList("select id,name,parent_id from money_categories where user_id=?",owner());var names=new HashMap<String,String>();for(var category:categories)names.put(category.get("id").toString(),category.get("name").toString());
  var lines=new ArrayList<String>();for(var book:books){String origin=Objects.toString(book.get("classificationOrigin"),"현재 저장값");lines.add(Objects.toString(book.get("title"),"선택 거래")+": "+(book.get("categoryId")==null?"아직 분류되지 않았습니다":names.getOrDefault(book.get("categoryId").toString(),"분류 근거 확인 필요"))+" · 출처 "+Map.of("DIRECT","직접 수정","CONFIRMED","직접 확인","DIRECT_REFERENCE","동일 구매 맥락의 직접 수정 참고","APPROVED_RULE","승인 규칙","AI","AI 판단").getOrDefault(origin,origin)+(Boolean.TRUE.equals(book.get("futureReferenceExcluded"))?" · 향후 참고 제외":"")+" · 작업 "+Objects.toString(book.get("classificationJobStatus"),"이력 없음"));}
  return String.join("\n",lines)+"\n분류 변경은 금융 금액·일시·계좌를 바꾸지 않습니다. 규칙 변경은 아래 초안을 작성한 뒤 최신 영향 검토에서 별도로 승인해 주세요.";
 }
 public record ConversationChange(UUID requestId,UUID id,Long expectedVersion,List<UUID> references,boolean delete){}
 public Map<String,Object> changeConversation(ConversationChange input){return commands.execute(owner(),input.requestId(),"CONVERSATION_CHANGE",input,()->{var old=conversation(input.id());MoneyMeaningService.version(number(old.get("version")),input.expectedVersion());require(input.delete()||input.references()!=null&&input.references().size()<=10,"참고 범위를 확인해 주세요.");if(!input.delete())for(UUID id:input.references())web.bookkeepingRow(id);db.update("update money_ai_conversations set title=case when ? then '삭제한 대화' else title end,references_json=cast(? as jsonb),messages=case when ? then '[]'::jsonb else messages end,expired_at=case when ? then now() else expired_at end,version=version+1,last_activity_at=now() where user_id=? and id=?",input.delete(),json.writeValueAsString(input.delete()?List.of():input.references()),input.delete(),input.delete(),owner(),input.id());retain();return Map.of("conversation",conversation(input.id()),"financialChanges",0,"ruleChanges",0);});}
 private Map<String,Object> draft(UUID id){var rows=rows("select id,conversation_id as \"conversationId\",version,status,target_rule_id as \"targetRuleId\",source_version as \"sourceVersion\",summary,rule_input::text as rule,updated_at as \"updatedAt\" from money_ai_rule_drafts where user_id=? and id=?",owner(),id);if(rows.isEmpty())throw new ResourceNotFoundException("규칙 초안을 찾을 수 없습니다.");var row=rows.getFirst();row.put("rule",object(row.get("rule")));return row;}
 private List<Map<String,Object>> drafts(){return db.queryForList("select id from money_ai_rule_drafts where user_id=? and status='OPEN' order by updated_at desc,id",owner()).stream().map(row->draft((UUID)row.get("id"))).toList();}
 public record DraftInput(UUID requestId,UUID id,Long expectedVersion,UUID conversationId,UUID targetRuleId,Long sourceVersion,String summary,MoneyMeaningService.RuleInput rule){}
 public Map<String,Object> saveDraft(DraftInput input){return commands.execute(owner(),input.requestId(),"RULE_DRAFT",input,()->{text(input.summary(),500,true,"초안 설명");require(input.rule()!=null,"규칙 초안이 필요합니다.");if(input.conversationId()!=null)conversation(input.conversationId());long source=0;if(input.targetRuleId()!=null){var rule=meaning.rules().stream().filter(r->input.targetRuleId().equals(r.get("id"))).findFirst().orElseThrow(()->new ResourceNotFoundException("원본 규칙을 찾을 수 없습니다."));source=number(rule.get("version"));MoneyMeaningService.version(source,input.sourceVersion());}UUID id=input.id();if(id==null){id=UUID.randomUUID();db.update("insert into money_ai_rule_drafts(id,user_id,conversation_id,target_rule_id,source_version,summary,rule_input) values(?,?,?,?,?,?,cast(? as jsonb))",id,owner(),input.conversationId(),input.targetRuleId(),source,input.summary(),json.writeValueAsString(input.rule()));}else{var old=draft(id);MoneyMeaningService.version(number(old.get("version")),input.expectedVersion());require("OPEN".equals(old.get("status")),"미적용 초안만 수정할 수 있습니다.");db.update("update money_ai_rule_drafts set conversation_id=?,target_rule_id=?,source_version=?,summary=?,rule_input=cast(? as jsonb),version=version+1,updated_at=now() where user_id=? and id=?",input.conversationId(),input.targetRuleId(),source,input.summary(),json.writeValueAsString(input.rule()),owner(),id);}return Map.of("draft",draft(id),"executedRules",0);});}
 public record Selection(UUID id,Long version){}
 public record Approval(UUID requestId,List<Selection> selected,String fingerprint){}
 private List<Map<String,Object>> selection(List<Selection> selected){require(selected!=null&&!selected.isEmpty()&&selected.size()<=50&&selected.stream().map(Selection::id).distinct().count()==selected.size(),"서로 다른 1–50개 미적용 초안을 선택해 주세요.");var result=new ArrayList<Map<String,Object>>();for(var s:selected){var row=draft(s.id());MoneyMeaningService.version(number(row.get("version")),s.version());require("OPEN".equals(row.get("status")),"이미 적용 또는 폐기된 초안입니다.");if(row.get("targetRuleId")!=null){var current=meaning.rules().stream().filter(r->r.get("id").equals(row.get("targetRuleId"))).findFirst().orElseThrow(()->new ResourceNotFoundException("원본 규칙을 찾을 수 없습니다."));MoneyMeaningService.version(number(current.get("version")),number(row.get("sourceVersion")));row.put("before",current);}else row.put("before",Map.of());result.add(row);}return result;}
 private MoneyMeaningService.RuleInput rule(Map<String,Object> draft){var rule=json.readValue(json.writeValueAsString(draft.get("rule")),MoneyMeaningService.RuleInput.class);return new MoneyMeaningService.RuleInput(rule.name(),rule.conditions(),rule.categoryId(),rule.titleDefault(),rule.memoDefault(),rule.status(),number(draft.get("sourceVersion")));}
 @Transactional(readOnly=true) public Map<String,Object> preview(List<Selection> selected){var drafts=selection(selected);var rules=meaning.rules();var categories=db.queryForList("select id,parent_id,kind,archived,version from money_categories where user_id=? order by id",owner());var accounts=db.queryForList("select id,archived,version from money_accounts where user_id=? order by id",owner());var books=rows(MoneyWebService.BOOK_BASE+"select * from effective order by id limit 10001",owner());require(books.size()<=10000,"규칙 영향 범위를 좁혀 주세요. 현재 최대 10,000개 거래를 검토할 수 있습니다.");
  var changes=new ArrayList<Map<String,Object>>();var conflicts=new ArrayList<String>();var targets=new HashSet<Object>();
  for(var draft:drafts){if(draft.get("targetRuleId")!=null&&!targets.add(draft.get("targetRuleId")))conflicts.add("같은 원본 규칙을 여러 초안이 수정합니다.");var rule=rule(draft);validate(rule,categories,accounts);var affected=new ArrayList<UUID>();long protectedCount=0;for(var book:books){var facts=new LinkedHashMap<>(book);facts.put("merchant",book.get("counterpartyText"));facts.put("accountId",Objects.toString(book.get("accountId"),""));if(rule.conditions().stream().allMatch(c->MoneyRuleEngine.matches(facts,c))){if(Boolean.TRUE.equals(book.get("directProtected"))||object(book.get("overrides")).containsKey("categoryId"))protectedCount++;else affected.add((UUID)book.get("id"));}}var change=new LinkedHashMap<>(draft);change.put("futureOnly",true);change.put("existingMatching",affected.size()+protectedCount);change.put("directEditsProtected",protectedCount);change.put("historicalChanges",0);changes.add(change);}
  for(int i=0;i<drafts.size();i++)for(int j=i+1;j<drafts.size();j++)if("ACTIVE".equals(rule(drafts.get(i)).status())&&"ACTIVE".equals(rule(drafts.get(j)).status())&&overlap(rule(drafts.get(i)).conditions(),rule(drafts.get(j)).conditions()))conflicts.add("선택 초안의 적용 조건이 겹칩니다. 하나의 초안으로 정리해 주세요.");
  String fingerprint=commands.fingerprint(Arrays.asList(changes,rules,categories,accounts,books,db.queryForList("select id,version,descriptor,aliases from money_ai_merchants where user_id=? order by id",owner()),db.queryForList("select version,automatic_rules,external_lookup from money_ai_settings where user_id=?",owner())));
  return Map.of("changes",changes,"conflicts",conflicts,"canApply",conflicts.isEmpty(),"fingerprint",fingerprint,"scope","FUTURE_RULES_ONLY");
 }
 private boolean overlap(List<MoneyRuleEngine.Condition> a,List<MoneyRuleEngine.Condition> b){for(var left:a)for(var right:b)if(left.field().equals(right.field())){String x=left.value().toLowerCase(Locale.ROOT),y=right.value().toLowerCase(Locale.ROOT);if("EXACT".equals(left.operator())&&"EXACT".equals(right.operator())&&!x.equals(y))return false;if("EXACT".equals(left.operator())&&!("CONTAINS".equals(right.operator())?x.contains(y):"STARTS_WITH".equals(right.operator())?x.startsWith(y):true))return false;if("EXACT".equals(right.operator())&&!("CONTAINS".equals(left.operator())?y.contains(x):"STARTS_WITH".equals(left.operator())?y.startsWith(x):true))return false;if("STARTS_WITH".equals(left.operator())&&"STARTS_WITH".equals(right.operator())&&!x.startsWith(y)&&!y.startsWith(x))return false;}return true;}
 private void validate(MoneyMeaningService.RuleInput rule,List<Map<String,Object>> categories,List<Map<String,Object>> accounts){text(rule.name(),120,true,"규칙 이름");require(rule.conditions()!=null&&!rule.conditions().isEmpty()&&rule.conditions().size()<=8,"규칙의 1–8개 조건을 확인해 주세요.");require(Set.of("ACTIVE","PAUSED","INACTIVE").contains(rule.status()),"규칙 상태를 확인해 주세요.");for(var c:rule.conditions()){require(Set.of("type","accountId","merchant","title").contains(c.field())&&Set.of("EXACT","CONTAINS","STARTS_WITH").contains(c.operator())&&c.value()!=null&&!c.value().isBlank(),"규칙 조건을 확인해 주세요.");if(c.field().equals("accountId"))require(c.operator().equals("EXACT")&&accounts.stream().anyMatch(a->a.get("id").toString().equals(c.value())&&!Boolean.TRUE.equals(a.get("archived"))),"활성 소유 계좌 조건이 필요합니다.");}require(rule.categoryId()!=null,"유효한 최종 분류를 선택해 주세요.");var category=categories.stream().filter(c->c.get("id").equals(rule.categoryId())).findFirst().orElseThrow(()->new InvalidRequestException("분류를 찾을 수 없습니다."));require(!Boolean.TRUE.equals(category.get("archived"))&&categories.stream().noneMatch(c->c.get("id").equals(category.get("parent_id"))&&Boolean.TRUE.equals(c.get("archived"))),"비활성 분류는 적용할 수 없습니다.");require(rule.conditions().stream().anyMatch(c->"type".equals(c.field())&&"EXACT".equals(c.operator())&&Objects.equals(c.value(),category.get("kind"))),"분류와 일치하는 거래 유형이 필요합니다.");for(var condition:rule.conditions())if("merchant".equals(condition.field())&&(!MoneyClassificationContext.business(condition.value())||MoneyClassificationContext.multiPurpose(condition.value())))require(rule.conditions().stream().anyMatch(c->"title".equals(c.field())),"개인·미확인·다품목 거래처 규칙에는 구매 맥락 제목 조건이 필요합니다.");require(rule.titleDefault()==null&&rule.memoDefault()==null,"이 규칙 묶음은 분류만 변경합니다. 제목·메모 변경은 별도로 실행해 주세요.");}
 public Map<String,Object> approve(Approval input){return commands.execute(owner(),input.requestId(),"APPROVE_RULE_BUNDLE",input,()->{var preview=preview(input.selected());require(Boolean.TRUE.equals(preview.get("canApply")),"겹치는 초안을 정리한 뒤 다시 검토해 주세요.");if(!Objects.equals(preview.get("fingerprint"),input.fingerprint()))throw new OptimisticLockConflictException("원본·조건·권한 또는 영향이 변경되었습니다. 전체 규칙 묶음을 적용하지 않았습니다.");var results=new ArrayList<Map<String,Object>>();for(var draft:selection(input.selected())){var saved=meaning.saveRule((UUID)draft.get("targetRuleId"),rule(draft));db.update("update money_category_rules set origin='AI_APPROVED' where user_id=? and id=?",owner(),saved.get("id"));saved.put("origin","AI_APPROVED");var identities=db.queryForList("select id,descriptor,version from money_ai_merchants where user_id=? order by id",owner()).stream().filter(identity->rule(draft).conditions().stream().anyMatch(condition->"merchant".equals(condition.field())&&MoneyRuleEngine.matches(Map.of("merchant",identity.get("descriptor")),condition))).toList();db.update("insert into money_ai_events(id,user_id,subject_id,kind,payload) values(?,?,?,'WORKSPACE_RULE_APPROVED',cast(? as jsonb))",UUID.randomUUID(),owner(),saved.get("id"),json.writeValueAsString(Map.of("rule",saved,"identities",identities,"draftId",draft.get("id"),"scope","FUTURE_ONLY")));results.add(saved);db.update("update money_ai_rule_drafts set status='APPLIED',version=version+1,updated_at=now() where user_id=? and id=?",owner(),draft.get("id"));}return Map.of("rules",results,"applied",results.size(),"historicalChanges",0);});}
 public record Discard(UUID requestId,UUID id,Long expectedVersion){}
 public Map<String,Object> discard(Discard input){return commands.execute(owner(),input.requestId(),"DISCARD_RULE_DRAFT",input,()->{var old=draft(input.id());MoneyMeaningService.version(number(old.get("version")),input.expectedVersion());require("OPEN".equals(old.get("status")),"미적용 초안만 폐기할 수 있습니다.");db.update("update money_ai_rule_drafts set status='DISCARDED',version=version+1,updated_at=now() where user_id=? and id=?",owner(),input.id());return Map.of("discarded",true,"financialChanges",0,"ruleChanges",0);});}
 /** Idempotent lifecycle cleanup; no financial, category or current classification row is deleted. */
 @Transactional public Map<String,Integer> retain(){int conversations=db.update("update money_ai_conversations set title='보관 기간이 지난 대화',messages='[]',references_json='[]',expired_at=now(),version=version+1 where user_id=? and expired_at is null and last_activity_at<now()-interval '90 days'",owner());db.update("update money_command_outcomes o set result=jsonb_set(result,'{conversation}',jsonb_build_object('id',result->'conversation'->'id','expired',true,'messages','[]'::jsonb,'references','[]'::jsonb)) where o.user_id=? and command in('AI_CONVERSATION','CONVERSATION_CHANGE') and exists(select 1 from money_ai_conversations c where c.user_id=o.user_id and c.id::text=o.result->'conversation'->>'id' and c.expired_at is not null)",owner());int evidence=db.update("update money_classification_events set evidence=jsonb_build_object('retention','EXPIRED'),previous_value=jsonb_build_object('categoryId',previous_value->'categoryId') where user_id=? and created_at<now()-interval '1 year' and evidence->>'retention' is distinct from 'EXPIRED'",owner());return Map.of("expiredConversations",conversations,"expiredAuditEvidence",evidence);}
}
