package com.kafka.backend.money;

import com.kafka.backend.common.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import static com.kafka.backend.money.MoneyService.*;
import static com.kafka.backend.money.MoneyTypes.*;

/** Additive owner presentation settings and current financial scopes; tracking and ledger facts stay independent. */
@Service
@Transactional
public class MoneyWebRevisionService {
 private final JdbcTemplate db;private final CurrentUserProvider users;private final MoneyService money;private final MoneyProductService product;private final MoneyMobileService mobile;private final ObjectMapper json;
 public MoneyWebRevisionService(JdbcTemplate db,CurrentUserProvider users,MoneyService money,MoneyProductService product,MoneyMobileService mobile,ObjectMapper json){this.db=db;this.users=users;this.money=money;this.product=product;this.mobile=mobile;this.json=json;}
 private UUID owner(){return users.getCurrentUserId();}
 private void lock(){db.queryForObject("select pg_advisory_xact_lock(hashtextextended(?,0))",Object.class,"money:"+owner());}
 private static void version(long actual,Long expected){if(expected==null||actual!=expected)throw new OptimisticLockConflictException("기록이 변경되었습니다. 새로고침하세요.");}
 private void audit(UUID id,String action,Object before,Object after){db.update("insert into money_meaning_audit(id,user_id,subject_id,action,previous_value,next_value) values(?,?,?,?,cast(? as jsonb),cast(? as jsonb))",UUID.randomUUID(),owner(),id,action,json.writeValueAsString(before),json.writeValueAsString(after));}
 public record Group(UUID id,String name,String kind,int sortOrder,long version,boolean archived,String iconType,String iconValue){}
 public record GroupInput(String name,String kind,Integer sortOrder,Long expectedVersion,Boolean archived,String iconType,String iconValue){}
 public record GroupMapping(UUID groupId,Long expectedVersion){}
 public record Order(List<UUID> ids,Map<UUID,Long> versions){}
 @Transactional(readOnly=true) public List<Group> groups(){return db.query("select * from money_category_groups where user_id=? order by kind,sort_order,name,id",(r,n)->new Group(r.getObject("id",UUID.class),r.getString("name"),r.getString("kind"),r.getInt("sort_order"),r.getLong("version"),r.getBoolean("archived"),r.getString("icon_type"),r.getString("icon_value")),owner());}
 private Group group(UUID id){return groups().stream().filter(g->g.id().equals(id)).findFirst().orElseThrow(()->new ResourceNotFoundException("Structural group not found"));}
 public Group saveGroup(UUID id,GroupInput input){lock();require(input!=null,"Group required");text(input.name(),80,true,"Name");var old=id==null?null:group(id);String kind=input.kind()==null&&old!=null?old.kind():input.kind();require(Set.of("INCOME","EXPENSE").contains(Objects.toString(kind,"")),"Group kind required");if(old!=null){version(old.version(),input.expectedVersion());require(kind.equals(old.kind()),"Group kind is immutable");}
  int order=input.sortOrder()==null?(old==null?0:old.sortOrder()):input.sortOrder();require(order>=0,"Invalid order");var icon=input.iconType()==null&&old!=null?new MoneyCategoryIcons.Icon(old.iconType(),old.iconValue()):MoneyCategoryIcons.normalize(input.iconType(),input.iconValue(),null);boolean archived=input.archived()==null?old!=null&&old.archived():input.archived();UUID key=id==null?UUID.randomUUID():id;
  if(old==null)db.update("insert into money_category_groups(id,user_id,name,kind,sort_order,archived,icon_type,icon_value) values(?,?,?,?,?,?,?,?)",key,owner(),input.name().strip(),kind,order,archived,icon.type(),icon.value());else db.update("update money_category_groups set name=?,sort_order=?,archived=?,icon_type=?,icon_value=?,version=version+1 where user_id=? and id=?",input.name().strip(),order,archived,icon.type(),icon.value(),owner(),key);var next=group(key);audit(key,"CATEGORY_GROUP_SAVE",old,next);return next;
 }
 public List<Group> orderGroups(Order input){lock();require(input!=null&&input.ids()!=null&&!input.ids().isEmpty()&&input.versions()!=null,"Order required");var first=group(input.ids().getFirst());var siblings=groups().stream().filter(g->g.kind().equals(first.kind())).toList();require(input.ids().size()==siblings.size()&&new HashSet<>(input.ids()).equals(new HashSet<>(siblings.stream().map(Group::id).toList())),"Include every group of this kind exactly once");for(var g:siblings)version(g.version(),input.versions().get(g.id()));for(int i=0;i<input.ids().size();i++)db.update("update money_category_groups set sort_order=?,version=version+1 where user_id=? and id=?",i,owner(),input.ids().get(i));audit(first.id(),"CATEGORY_GROUP_ORDER",siblings,input.ids());return groups();}
 public MoneyProductService.Category mapGroup(UUID id,GroupMapping input){lock();require(input!=null,"Mapping required");var categories=new MoneyCategories(db,owner(),json);var category=categories.get(id);version(category.version(),input.expectedVersion());require(category.parentId()==null,"Only existing root categories can join a structural group");if(input.groupId()!=null){var g=group(input.groupId());require(g.kind().equals(category.kind())&&!g.archived(),"Active same-kind group required");}db.update("update money_categories set structural_group_id=?,version=version+1 where user_id=? and id=?",input.groupId(),owner(),id);var next=categories.get(id);audit(id,"CATEGORY_GROUP_MAPPING",category,next);return next;}
 public record Preferences(List<UUID> accountIds,long version){}
 public record PreferencesInput(List<UUID> accountIds,Long expectedVersion){}
 @Transactional(readOnly=true) public Preferences preferences(){var rows=db.query("select account_ids,version from money_overview_preferences where user_id=?",(r,n)->{var a=r.getArray("account_ids");var ids=new ArrayList<UUID>();for(var value:(Object[])a.getArray())ids.add(UUID.fromString(value.toString()));return new Preferences(ids,r.getLong("version"));},owner());return rows.isEmpty()?new Preferences(List.of(),0):rows.getFirst();}
 static void validateRepresentatives(List<UUID> ids){require(ids!=null&&ids.size()<=10&&ids.stream().allMatch(Objects::nonNull)&&new HashSet<>(ids).size()==ids.size(),"Choose up to 10 different representative accounts");}
 public Preferences savePreferences(PreferencesInput input){lock();require(input!=null,"Preferences required");validateRepresentatives(input.accountIds());var old=preferences();version(old.version(),input.expectedVersion());for(var id:input.accountIds()){var a=money.account(id);require(!a.archived()||old.accountIds().contains(id),"New representative accounts must be active");}db.update("insert into money_overview_preferences(user_id,account_ids,version) values(?,?,1) on conflict(user_id) do update set account_ids=excluded.account_ids,version=money_overview_preferences.version+1,updated_at=now()",owner(),input.accountIds().toArray(new UUID[0]));var next=preferences();audit(owner(),"OVERVIEW_PREFERENCES",old,next);return next;}
 public MoneyMobileService.FundAccount saveFund(UUID id,MoneyMobileService.FundInput input){return mobile.saveFund(id,input);}
 static void amountRange(BigDecimal min,BigDecimal max){require(min==null||min.signum()>=0&&min.stripTrailingZeros().scale()<=0,"Minimum must be a nonnegative KRW integer");require(max==null||max.signum()>=0&&max.stripTrailingZeros().scale()<=0&&(min==null||max.compareTo(min)>=0),"Invalid amount range");}
 @Transactional(readOnly=true) public Map<String,Object> currentStock(){Instant asOf=Instant.now();var balances=product.accountBalances(asOf);var funds=mobile.funds();var unsupported=new HashSet<>(db.queryForList("select distinct a.id from money_accounts a join money_transactions t on t.user_id=a.user_id and (t.from_account_id=a.id or t.to_account_id=a.id) where a.user_id=? and not t.excluded and t.merged_into is null and t.currency<>'KRW'",UUID.class,owner()));BigDecimal assets=BigDecimal.ZERO,living=BigDecimal.ZERO,savings=BigDecimal.ZERO;long unknown=0;for(var row:balances){var a=(MoneyAccount)row.get("account");var b=(MoneyProductService.Balance)row.get("balance");if(!a.includeInAssets())continue;if(unsupported.contains(a.id())){unknown++;continue;}assets=assets.add(b.amount());if(b.asOf()==null)unknown++;if(!a.archived()){String group=funds.get(a.id()).fundGroup();if(group.equals("LIVING"))living=living.add(b.amount());if(group.equals("SAVINGS"))savings=savings.add(b.amount());}}
  BigDecimal loans=db.queryForObject("select coalesce(sum(remaining_principal),0) from money_loans where user_id=? and status='ACTIVE' and not deleted",BigDecimal.class,owner());return Map.of("asOf",asOf,"currencies",List.of(Map.of("currency","KRW","currentTotal",assets.subtract(loans),"currentBalance",living,"currentSavings",savings,"totalLoans",loans,"includedAssets",assets,"unknownBalanceCount",unknown)),"hasUnsupportedCurrencies",!unsupported.isEmpty(),"unsupportedCurrencyAccountIds",unsupported,"scopes",Map.of("currentTotal","INCLUDED_ASSETS_INCLUDING_ARCHIVED_MINUS_ACTIVE_LOANS","currentBalance","ACTIVE_INCLUDED_LIVING","currentSavings","ACTIVE_INCLUDED_SAVINGS","totalLoans","ACTIVE_CONFIRMED_PRINCIPAL"));
 }
 static LocalDate[] comparison(LocalDate from,LocalDate to,LocalDate today){require(!from.isAfter(to),"Start must precede end");LocalDate end=to.isAfter(today)?today:to;boolean calendar=from.getDayOfMonth()==1&&to.equals(from.withDayOfMonth(from.lengthOfMonth()));LocalDate previousFrom=calendar?from.minusMonths(1):from.minusDays(ChronoUnit.DAYS.between(from,to)+1);LocalDate previousTo=calendar?previousFrom.withDayOfMonth(Math.min(Math.max(1,end.getDayOfMonth()),previousFrom.lengthOfMonth())):previousFrom.plusDays(Math.max(0,ChronoUnit.DAYS.between(from,end)));return new LocalDate[]{end,previousFrom,previousTo};}
 private record Daily(LocalDate date,BigDecimal amount,long unresolved){}
 private List<Daily> daily(LocalDate from,LocalDate to){if(from.isAfter(to))return List.of();return db.query(MoneyAnalysis.FACTS+" select (occurred_at at time zone 'Asia/Seoul')::date as pace_date,coalesce(sum(consumption),0) as amount,count(*) filter(where type='LOAN_PAYMENT' and principal is null) as unresolved from facts where currency='KRW' group by 1 order by 1",(r,n)->new Daily(r.getObject("pace_date",LocalDate.class),r.getBigDecimal("amount"),r.getLong("unresolved")),owner(),owner(),Timestamp.from(from.atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()),Timestamp.from(to.plusDays(1).atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()));}
 @Transactional(readOnly=true) public Map<String,Object> spendingPace(String fromText,String toText){LocalDate from=LocalDate.parse(fromText),to=LocalDate.parse(toText),today=LocalDate.now(ZoneId.of("Asia/Seoul"));var comparison=comparison(from,to,today);require(ChronoUnit.DAYS.between(from,to)<=3660,"Period too long");var currentRows=daily(from,comparison[0]);var previousRows=from.isAfter(today)?List.<Daily>of():daily(comparison[1],comparison[2]);Map<String,BigDecimal> currentDaily=new HashMap<>(),previousDaily=new HashMap<>();currentRows.forEach(r->currentDaily.put(r.date().toString(),r.amount()));previousRows.forEach(r->previousDaily.put(r.date().toString(),r.amount()));BigDecimal current=BigDecimal.ZERO,previous=BigDecimal.ZERO;var buckets=new ArrayList<Map<String,Object>>();for(int i=0;!from.plusDays(i).isAfter(comparison[0]);i++){current=current.add(currentDaily.getOrDefault(from.plusDays(i).toString(),BigDecimal.ZERO));LocalDate prior=comparison[1].plusDays(i);if(!prior.isAfter(comparison[2]))previous=previous.add(previousDaily.getOrDefault(prior.toString(),BigDecimal.ZERO));buckets.add(Map.of("day",i+1,"date",from.plusDays(i),"current",current,"previous",previous));}var currencyRows=db.queryForList(MoneyAnalysis.FACTS+" select distinct currency from facts order by currency",String.class,owner(),owner(),Timestamp.from(comparison[1].atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()),Timestamp.from(comparison[0].plusDays(1).atStartOfDay(ZoneId.of("Asia/Seoul")).toInstant()));boolean unsupported=currencyRows.stream().anyMatch(c->!"KRW".equals(c));long unresolved=currentRows.stream().mapToLong(Daily::unresolved).sum();var result=new LinkedHashMap<String,Object>();result.putAll(Map.of("from",from,"to",comparison[0],"comparisonFrom",comparison[1],"comparisonTo",comparison[2],"asOf",Instant.now(),"current",current,"previous",previous,"delta",current.subtract(previous),"buckets",buckets,"unresolvedLoanPayments",unresolved));result.put("currencies",currencyRows);result.put("hasMixedCurrencies",unsupported);result.put("analyticsUnavailable",unsupported);return result;}
}
