import { test } from "node:test";
import assert from "node:assert/strict";
import {categoryIndex,categoryTotals,toggleCategoryFilter,categoryTree,categoryFilterMatches,categoryFilterIds,categoryFilterFromIds,normalizeCategoryFilter,assertFinalCategory,categoryMergeTargets,UNGROUPED,type CategoryGroup} from "./categories";
import type {Category} from "./model";
const row=(id:string,name:string,parentId:string|null=null,archived=false):Category=>({id,name,parentId,archived,kind:"EXPENSE",color:"#123456",version:0});
const cats=[row("food","식비"),row("delivery","배달","food"),row("meal","식사","food",true),row("life","생활")];
test("one category identity derives a path and effective activity",()=>{const tree=categoryIndex(cats);assert.equal(tree.path("food"),"식비");assert.equal(tree.path("delivery"),"식비 > 배달");assert.equal(tree.active(cats[2]),false);assert.equal(categoryIndex([{...cats[0],archived:true},cats[1]]).active(cats[1]),false);});
test("parent totals include inactive children and virtual direct bucket, amount ordered",()=>{const [g]=categoryTotals(cats,[{categoryId:"food",amount:100},{categoryId:"delivery",amount:300},{categoryId:"meal",amount:200},{categoryId:"delivery",amount:-50}]);assert.equal(g.amount,550);assert.deepEqual(g.children.map(c=>[c.id,c.amount]),[["delivery",250],["meal",200],["direct:food",100]]);assert.equal(g.children.reduce((n,c)=>n+c.amount,0),g.amount);});
test("moving a child updates historical aggregate without rewriting meaning IDs",()=>{const facts=[{categoryId:"delivery",amount:300}];const moved=cats.map(c=>c.id==="delivery"?{...c,parentId:"life"}:c);assert.equal(categoryTotals(moved,facts)[0].id,"life");assert.equal(facts[0].categoryId,"delivery");});
test("selecting a bucket replaces its parent total, independent paths survive",()=>{assert.deepEqual(toggleCategoryFilter(cats,["food","life"],"delivery"),["life","delivery"]);assert.deepEqual(toggleCategoryFilter(cats,["direct:food","delivery","life"],"food"),["life","food"]);assert.deepEqual(toggleCategoryFilter(cats,["food"],"direct:food"),["direct:food"]);assert.deepEqual(toggleCategoryFilter(cats,["delivery"],"delivery"),[]);});

const groups:CategoryGroup[]=[{id:"daily",name:"일상",kind:"EXPENSE",sortOrder:0,version:0},{id:"housing",name:"주거",kind:"EXPENSE",sortOrder:1,version:0}];
const grouped=[{...cats[0],structuralGroupId:"daily"},cats[1],cats[2],{...cats[3],structuralGroupId:"housing"},row("bus","버스","life"),row("old","미배치")];
test("structural groups preserve every real ID and unmapped fallback",()=>{const tree=categoryTree(grouped,groups);assert.deepEqual(tree.rootsFor(["daily","housing"]).map(c=>c.id),["food","life"]);assert.deepEqual(tree.rootsFor([UNGROUPED]).map(c=>c.id),["old"]);assert.equal(categoryTree(grouped).rootsFor([UNGROUPED]).length,3);assert.equal(tree.path("delivery"),"일상 / 식비 / 배달");assert.equal(assertFinalCategory(grouped,"food"),"food");assert.equal(assertFinalCategory(grouped,"delivery"),"delivery");assert.throws(()=>assertFinalCategory(grouped,"daily"));assert.throws(()=>assertFinalCategory(grouped,"direct:food"));assert.throws(()=>assertFinalCategory(grouped,"meal"));});
test("multiple structural groups union downstream candidates, active stages AND",()=>{const selection={groups:["daily","housing"],roots:["food","life"],finals:["delivery","bus"],uncategorized:false};assert.deepEqual(categoryFilterIds(grouped,groups,selection),["delivery","bus"]);assert.equal(categoryFilterMatches(grouped,groups,selection,"delivery"),true);assert.equal(categoryFilterMatches(grouped,groups,selection,"bus"),true);assert.equal(categoryFilterMatches(grouped,groups,selection,"food"),false);const cleaned=normalizeCategoryFilter(grouped,groups,{...selection,groups:["daily"]});assert.deepEqual(cleaned.roots,["food"]);assert.deepEqual(cleaned.finals,["delivery"]);});
test("root subtree, exact direct root, null OR and empty stages keep query semantics",()=>{const base={groups:[],roots:["food"],finals:[],uncategorized:false};assert.equal(categoryFilterMatches(grouped,groups,base,"food"),true);assert.equal(categoryFilterMatches(grouped,groups,base,"delivery"),true);assert.equal(categoryFilterMatches(grouped,groups,{...base,finals:["direct:food"]},"delivery"),false);assert.equal(categoryFilterMatches(grouped,groups,{...base,finals:["direct:food"],uncategorized:true},null),true);assert.deepEqual(categoryFilterIds(grouped,groups,{groups:[],roots:[],finals:[],uncategorized:true}),["uncategorized"]);assert.equal(categoryFilterIds(grouped,groups,{groups:[],roots:[],finals:[],uncategorized:false}),null);});
test("legacy mixed subtree and child buckets roundtrip without restricting the subtree",()=>{const selected=categoryFilterFromIds(grouped,["food","bus","uncategorized"]);assert.equal(categoryFilterMatches(grouped,groups,selected,"food"),true);assert.equal(categoryFilterMatches(grouped,groups,selected,"delivery"),true);assert.equal(categoryFilterMatches(grouped,groups,selected,"meal"),true);assert.equal(categoryFilterMatches(grouped,groups,selected,"bus"),true);assert.equal(categoryFilterMatches(grouped,groups,selected,"life"),false);});
test("archive only blocks new assignment, historic filter and child IDs stay available",()=>{const archived=grouped.map(c=>c.id==="food"?{...c,archived:true}:c);assert.throws(()=>assertFinalCategory(archived,"delivery"));assert.equal(categoryFilterMatches(archived,groups,{groups:["daily"],roots:[],finals:[],uncategorized:false},"delivery"),true);});
test("safe merge offers same-kind same-parent active leaves only",()=>{const nodes=[...grouped,row("snack","간식","food"),{...row("income","급여","food"),kind:"INCOME" as const},row("other","다른 부모","life")];assert.deepEqual(categoryMergeTargets(nodes,"delivery").map(c=>c.id),["snack"]);assert.deepEqual(categoryMergeTargets(nodes,"food"),[]);assert.deepEqual(categoryMergeTargets(nodes,"meal"),[]);});
