import assert from "node:assert/strict";
import { test } from "node:test";
import React,{act} from "react";
import { createRoot } from "react-dom/client";
import { JSDOM } from "jsdom";
import { TimeGrid } from "./TimeGrid";
import { actualConflict,conflictMessage,movedStart,scheduledPlacement } from "./actualDrag";
import { groupsVisible,readPreferences } from "./appearance";
import type { CalendarUnscheduledActualDto } from "@/lib/api/types";
import type { GridBlock } from "./gridTypes";
import { newVisualGroup, type CalendarVisualGroup } from "./visualGroups";
Object.assign(globalThis,{React});
const block:GridBlock={id:"same-id",sourceType:"WORK_TIME_ENTRY",domainType:"WORK",title:"Work",startAt:"2026-09-14T14:05:00",endAt:"2026-09-14T14:40:00",activityCategoryId:"root",lifeCategoryId:null,phaseId:null,memo:"preserve"};
const item:CalendarUnscheduledActualDto={...block,sourceType:"WORK_TIME_ENTRY",date:"2026-09-14",sourceId:block.id,durationMinutes:35};
test("date-only drag keeps 5-minute offsets; meaningful vertical moves keep exact duration",()=>{
  assert.equal(movedStart(845,35,15,180,9,true),845);
  assert.equal(movedStart(845,35,30,180,30,true),875);
  assert.equal(movedStart(845,35,15,0,15,false),860);
  assert.deepEqual(scheduledPlacement(item,837),{start:840,end:875});
  assert.equal(scheduledPlacement(item,1425),null);
});
test("all Actual domains participate in conflict feedback, source identities remain distinct",()=>{
  const life={...block,sourceType:"LIFE_TIME_ENTRY" as const,domainType:"LIFE" as const};
  const start=new Date(block.startAt),end=new Date(block.endAt);
  assert.equal(actualConflict(block,start,end,[block]),undefined);
  assert.equal(actualConflict(block,start,end,[life]),life);
  assert.equal(conflictMessage(life),"14:05–14:40 기존 LIFE 기록과 겹칩니다.");
  assert.equal(actualConflict(undefined,end,new Date("2026-09-14T15:00:00"),[block]),undefined);
});
test("group visibility defaults by mode and round-trips per-mode preferences",()=>{
  const defaults=readPreferences(null);
  assert.equal(groupsVisible(defaults,"plan"),true);assert.equal(groupsVisible(defaults,"actual"),true);assert.equal(groupsVisible(defaults,"compare"),false);
  const stored=readPreferences(JSON.stringify({groupVisibility:{plan:false,compare:true,actual:"bad"}}));
  assert.equal(groupsVisible(stored,"plan"),false);assert.equal(groupsVisible(stored,"compare"),true);assert.equal(groupsVisible(stored,"actual"),true);
});
test("pointer gestures schedule exact source/duration, cross date, reject conflict and unschedule into date bucket",async t=>{
  const dom=new JSDOM('<div id="root"></div>',{url:"http://localhost"});
  Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true,requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{}});
  dom.window.HTMLElement.prototype.setPointerCapture=()=>{};
  const scheduled:unknown[][]=[],moved:unknown[][]=[],unscheduled:unknown[][]=[],errors:string[]=[],groupMoves:CalendarVisualGroup[]=[];
  const group={...newVisualGroup("2026-09-14",780,960),id:"group",title:"Context"};
  const root=createRoot(document.getElementById("root")!);
  t.after(async()=>{await act(()=>root.unmount());dom.window.close();});
  let conflicts:GridBlock[]=[];
  const render=()=>root.render(<TimeGrid days={[new Date(2026,8,14),new Date(2026,8,15)]} blocks={[block]} colorMode="ACTIVITY" projects={[]} phases={[]} interactionMode="actual" onBlockClick={()=>{}} onBlockTimeChange={(...args)=>moved.push(args)} onScheduleActual={(...args)=>scheduled.push(args)} onUnscheduleActual={(...args)=>unscheduled.push(args)} onInvalidDrop={message=>errors.push(message)} unscheduledItems={[item]} conflictBlocks={conflicts} visualGroups={[group]} onGroupChange={(original,transform)=>groupMoves.push(transform(original))}/>);
  await act(render);
  const cols=Array.from(document.querySelectorAll<HTMLElement>('[data-calendar-date]'));
  const content=cols[0].parentElement!;
  content.getBoundingClientRect=()=>({top:0,left:0,bottom:1440,right:248,width:248,height:1440,x:0,y:0,toJSON(){}});
  cols.forEach((col,i)=>{col.getBoundingClientRect=()=>({top:0,left:48+i*100,right:148+i*100,bottom:1440,width:100,height:1440,x:48+i*100,y:0,toJSON(){}});});
  document.elementsFromPoint=(x,y)=>y>=1500 ? [document.querySelectorAll('[data-unscheduled-date]')[x>=148 ? 1 : 0]] : [];
  const pointer=async(el:Element,type:string,x:number,y:number)=>{await act(()=>{el.dispatchEvent(new dom.window.MouseEvent(type,{bubbles:true,button:0,clientX:x,clientY:y}));});};
  await pointer(document.querySelector('[data-unscheduled-source]')!,"pointerdown",90,1510);
  await pointer(content,"pointermove",190,840);await pointer(content,"pointerup",190,840);
  assert.equal(scheduled.length,1);assert.equal(scheduled[0][0],item);
  assert.equal((scheduled[0][1] as Date).getDate(),15);assert.equal(((scheduled[0][2] as Date).getTime()-(scheduled[0][1] as Date).getTime())/60000,35);
  await pointer(document.querySelector('[data-calendar-block]')!,"pointerdown",90,850);
  await pointer(content,"pointermove",190,859);await pointer(content,"pointerup",190,859);
  assert.equal(moved.length,1);assert.equal((moved[0][1] as Date).getMinutes(),5);assert.equal((moved[0][1] as Date).getHours(),14);
  conflicts=[{...block,id:"collision",domainType:"LIFE",sourceType:"LIFE_TIME_ENTRY",startAt:"2026-09-15T14:00:00",endAt:"2026-09-15T15:00:00"}];await act(render);
  await pointer(document.querySelector('[data-calendar-block]')!,"pointerdown",90,850);
  await pointer(content,"pointermove",190,850);await pointer(content,"pointerup",190,850);
  assert.equal(moved.length,1);assert.match(errors[0],/14:00–15:00 기존 LIFE/);
  await pointer(document.querySelector('[data-calendar-block]')!,"pointerdown",90,850);
  await pointer(content,"pointermove",190,1510);await pointer(content,"pointerup",190,1510);
  assert.deepEqual(unscheduled,[[block,"2026-09-15"]]);
  const activityStyle=document.querySelector('[data-calendar-block]')!.getAttribute('style');
  await pointer(document.querySelector('[aria-label="Context 그룹 블록 열기"]')!,"pointerdown",90,780);
  await pointer(content,"pointermove",190,810);await pointer(content,"pointerup",190,810);
  assert.equal(groupMoves.length,1);assert.equal(groupMoves[0].startDate,"2026-09-15");assert.equal(groupMoves[0].startTime,"13:30");
  assert.equal(moved.length,1);assert.equal(document.querySelector('[data-calendar-block]')!.getAttribute('style'),activityStyle);
  await pointer(document.querySelector('[aria-label="Context 종료 조절"]')!,"pointerdown",90,960);
  await pointer(content,"pointermove",90,990);await pointer(content,"pointerup",90,990);
  assert.equal(groupMoves[1].endTime,"16:30");assert.equal(moved.length,1);
});
