import assert from 'node:assert/strict';
import {newBlock,normalize,enterBlock,boundaryDelete,replaceTextRange,dropBlocks,copyBlocks,cloneBlocks,indentBlocks,numberedOrdinals,markdownStart,blockText,textBlocks} from './workpad';
const h=newBlock('H1','Heading'),t=newBlock('TEXT','Body'),c=newBlock('CHECKLIST','Child',t.id);
let rows=normalize([h,t,c]);
assert.equal(enterBlock(rows,h.id,3).blocks[1].type,'H1');
assert.equal(enterBlock(rows,h.id,7).blocks[1].type,'TEXT');
assert.equal(boundaryDelete(rows,c.id,true)!.blocks.find(b=>b.id===c.id)!.parentId,null);
let check=newBlock('CHECKLIST','Keep');
assert.equal(boundaryDelete([check],check.id,true)!.blocks[0].type,'TEXT');
let merged=boundaryDelete(rows,t.id,true)!;
assert.equal(merged.blocks[0].content,'HeadingBody');assert.equal(merged.blocks[1].parentId,h.id);
assert.equal(dropBlocks(rows,[t.id],c.id,'child'),rows,'circular drop is unchanged');
let moved=dropBlocks(rows,[t.id,c.id],h.id,'child');
assert.equal(moved.find(b=>b.id===t.id)!.parentId,h.id);assert.equal(moved.length,3);
assert.equal(copyBlocks(rows,[t.id,c.id]).length,2);
assert.equal(new Set(cloneBlocks(rows).map(b=>b.id)).size,3);
assert.equal(replaceTextRange(rows,h.id,3,t.id,2).find(b=>b.id===c.id)!.parentId,h.id);
assert.equal(replaceTextRange(rows,h.id,3,t.id,2)[0].content,'Heady');
assert.equal(markdownStart('## Heading')!.type,'H2');assert.equal(markdownStart('- [x] done')!.checked,true);
const list=normalize([newBlock('NUMBERED','One'),newBlock('NUMBERED','Two'),newBlock('TEXT','Break'),newBlock('NUMBERED','Three')]);
assert.deepEqual([...numberedOrdinals(list).values()],[1,2,1]);
assert.match(blockText(list),/1\. One\n2\. Two/);
assert.equal(textBlocks('# title\n- [x] done\nplain')[1].checked,true);
assert.equal(indentBlocks(rows,[h.id])[0].parentId,null);
console.log('PASS R4 editor structure, range, Markdown, clipboard and drop invariants');
