import java.nio.file.*;
import java.sql.*;
import java.util.*;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationInfo;

/** Explicit release utility. Only the reviewed additive V79 may migrate; no repair, clean or data fixtures. */
public class MoneyBookkeepingMigration {
 private static final String VERSION="79",SCRIPT="V79__money_bookkeeping_recommendations.sql";
 private static final Set<String> MODES=Set.of("preflight","migrate","verify");
 private static final class Gate extends RuntimeException {Gate(String code){super(code);}}
 private static void require(boolean value,String code){if(!value)throw new Gate(code);}
 private static String env(String key){String value=System.getenv(key);require(value!=null&&!value.isBlank(),"ENV_REQUIRED_"+key);return value;}
 private static String mode(String[] args){require(args.length==1&&MODES.contains(args[0]),"MODE_REQUIRED_PREFLIGHT_MIGRATE_VERIFY");return args[0];}
 private static Properties properties(){Properties p=new Properties();p.setProperty("user",env("BK_DB_USERNAME"));p.setProperty("password",env("BK_DB_PASSWORD"));p.setProperty("ApplicationName","pos-qa-money-revision-v79");p.setProperty("connectTimeout","15");p.setProperty("socketTimeout","60");return p;}
 private static String url(){require(Set.of("DEV","PROD").contains(env("BK_ENVIRONMENT")),"ENVIRONMENT_IDENTITY_REQUIRED");String url=env("BK_DB_URL");require(url.startsWith("jdbc:postgresql://"),"DEV_POSTGRES_URL_REQUIRED");require(env("BK_VERIFIED_PROJECT_REF").matches("[a-z0-9]{20}"),"TARGET_IDENTITY_REJECTED");
  try{var uri=java.net.URI.create(url.substring(5));require(uri.getUserInfo()==null,"URL_CREDENTIALS_REJECTED");if(uri.getRawQuery()!=null)for(String item:uri.getRawQuery().split("&")){var pair=item.split("=",2);String key=java.net.URLDecoder.decode(pair[0],java.nio.charset.StandardCharsets.UTF_8),value=pair.length==2?java.net.URLDecoder.decode(pair[1],java.nio.charset.StandardCharsets.UTF_8):"";require(!Set.of("user","password").contains(key.toLowerCase(Locale.ROOT)),"URL_CREDENTIALS_REJECTED");if(key.equalsIgnoreCase("currentSchema"))require(value.equals("public"),"PUBLIC_SCHEMA_REQUIRED");}}catch(IllegalArgumentException e){throw new Gate("DEV_POSTGRES_URL_INVALID");}return url;
 }
 private static String readOnly(String url){return url+(url.contains("?")?"&":"?")+"options=-c%20default_transaction_read_only%3Don&connectTimeout=15&socketTimeout=60";}
 private static Flyway flyway(String url,Properties p,Path migrations,boolean target){var configuration=Flyway.configure().dataSource(url,p.getProperty("user"),p.getProperty("password")).locations("filesystem:"+migrations).defaultSchema("public").schemas("public").createSchemas(false).cleanDisabled(true).baselineOnMigrate(false).outOfOrder(false).validateOnMigrate(true).ignoreMigrationPatterns("*:pending");if(target)configuration.target(VERSION);return configuration.load();}
 private static void history(String url,Properties p,String label)throws Exception{try(var c=DriverManager.getConnection(readOnly(url),p)){c.setReadOnly(true);try(var s=c.createStatement()){s.setQueryTimeout(15);try(var rows=s.executeQuery("select installed_rank,version,script,checksum,success from public.flyway_schema_history order by installed_rank")){while(rows.next())System.out.println("QA_V79_HISTORY_"+label+"="+rows.getInt(1)+"|"+Objects.toString(rows.getString(2),"REPEATABLE")+"|"+rows.getString(3)+"|"+Objects.toString(rows.getObject(4),"NULL")+"|"+rows.getBoolean(5));}}}}
 private static void validate(Flyway flyway){flyway.validate();System.out.println("QA_V79_CHECKSUM_VALIDATION=PASS");}
 private static void preflight(Flyway flyway){validate(flyway);var info=flyway.info();var pending=info.pending();require(pending.length==1&&VERSION.equals(pending[0].getVersion().getVersion())&&SCRIPT.equals(pending[0].getScript()),"ONLY_PENDING_V79_EXPECTED");var current=info.current();require(current!=null&&"78".equals(current.getVersion().getVersion()),"APPLIED_V78_BASELINE_REQUIRED");for(var migration:info.all()){String state=migration.getState().name();require(!state.contains("FAILED")&&!state.startsWith("FUTURE")&&!state.startsWith("MISSING"),"UNEXPECTED_HISTORY_STATE");}System.out.println("QA_V79_PENDING="+pending[0].getVersion()+"|"+pending[0].getScript()+"|"+pending[0].getChecksum());System.out.println("QA_V79_PREFLIGHT=PASS");}
 private static void verify(Flyway flyway){validate(flyway);var info=flyway.info();require(info.pending().length==0,"UNEXPECTED_PENDING_MIGRATIONS");var current=info.current();require(current!=null&&VERSION.equals(current.getVersion().getVersion())&&SCRIPT.equals(current.getScript())&&current.getState().name().equals("SUCCESS"),"SUCCESSFUL_V79_REQUIRED");for(MigrationInfo migration:info.all()){String state=migration.getState().name();require(!state.contains("FAILED")&&!state.startsWith("FUTURE")&&!state.startsWith("MISSING"),"UNEXPECTED_HISTORY_STATE");}System.out.println("QA_V79_VERIFY=PASS");}
 private static void run(String[] args)throws Exception{String mode=mode(args);String url=url();var p=properties();String configured=System.getenv("QA_MIGRATIONS");Path migrations=Path.of(configured==null||configured.isBlank()?"src/main/resources/db/migration":configured).toAbsolutePath().normalize();require(Files.isRegularFile(migrations.resolve(SCRIPT)),"V79_SOURCE_REQUIRED");var audit=flyway(readOnly(url),p,migrations,false);history(url,p,"BEFORE");if(mode.equals("verify")){verify(audit);return;}preflight(audit);if(mode.equals("preflight"))return;
  try(var lock=DriverManager.getConnection(url,p)){try(var statement=lock.createStatement()){statement.setQueryTimeout(15);try(var acquired=statement.executeQuery("select pg_try_advisory_lock(hashtextextended('pos-central-qa-money-v79',0))")){acquired.next();require(acquired.getBoolean(1),"MIGRATION_UTILITY_BUSY");}}preflight(audit);var result=flyway(url,p,migrations,true).migrate();require(result.migrationsExecuted==1,"ONE_V79_MIGRATION_EXPECTED");System.out.println("QA_V79_MIGRATIONS_EXECUTED="+result.migrationsExecuted);}
  history(url,p,"AFTER");verify(flyway(readOnly(url),p,migrations,false));
 }
 public static void main(String[] args){try{run(args);}catch(Gate e){System.err.println("QA_V79_BLOCKED="+e.getMessage());System.exit(1);}catch(Exception e){System.err.println("QA_V79_FAILED="+e.getClass().getSimpleName()+"; inspect with the existing credential-redacted QA diagnostics");System.exit(1);}}
}
