import {randomUUID,createHash} from 'node:crypto';
import {test,expect} from '../../helpers/browser.mjs';
const base='/api/workflow/attention';
const operationId=()=>randomUUID();
const source=(ref=randomUUID(),intent='review',generation='v1',producer='MANUAL',policy='ACK_ONLY')=>({kind:producer==='MANUAL'?'WEB':'TEAM_KAFKA',reference:ref,url:'https://example.com/work-queue/'+ref,producer,intent,generation,completionPolicy:policy});
async function api(request,path,options={}){const response=await request.fetch(process.env.QA_API_URL+path,options);expect(response.ok(),`${options.method??'GET'} ${path}: ${response.status()}`).toBeTruthy();return response.status()===204?null:response.json();}
async function create(request,extra={}){return api(request,base+'/items',{method:'POST',data:{operationId:operationId(),id:randomUUID(),action:'WORK QUEUE QA '+randomUUID().slice(0,8),projectLabel:'QA',source:source(),...extra}});}
const command=(item)=>({operationId:operationId(),expectedRevision:item.revision,expectedGeneration:item.source.generation});

test('attention.routes',async({page})=>{await page.goto('/workflow/attention');await expect(page.getByRole('heading',{name:'WORK QUEUE',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Stack',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByText('체크는 이 목록에서만 완료됩니다.')).toBeVisible();await page.getByRole('button',{name:'Waiting',exact:true}).click();await expect(page).toHaveURL(/\/workflow\/waiting/);});
test('attention.create-persist',async({page,request})=>{const label='브라우저 QA '+randomUUID().slice(0,8);await page.goto('/workflow/attention');await page.getByRole('button',{name:'＋ 빠른 추가',exact:true}).click();await page.getByLabel('확인할 일',{exact:true}).fill(label);await page.getByRole('button',{name:'추가',exact:true}).click();await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();const snap=await api(request,base+'/snapshot');expect(snap.items.find(item=>item.action===label)?.sourceKey.length).toBe(64);});
test('attention.ack-only',async({request})=>{const workflow=await api(request,'/api/workflow');const task=workflow.tasks.find(task=>!task.archivedAt);test.skip(!task,'No existing read-only owner WorkTask available');const project=workflow.projects.find(project=>project.id===task.projectId);const created=await create(request,{projectId:task.projectId,workTaskId:task.id,projectLabel:'QA linked'});const done=await api(request,base+'/items/'+created.item.id+'/complete',{method:'POST',data:command(created.item)});const reopened=await api(request,base+'/items/'+created.item.id+'/reopen',{method:'POST',data:command(done.item)});await api(request,base+'/items/'+created.item.id+'/dismiss',{method:'POST',data:command(reopened.item)});const after=await api(request,'/api/workflow');const final=after.tasks.find(row=>row.id===task.id);expect([final.status,final.revision]).toEqual([task.status,task.revision]);if(project){const p=after.projects.find(row=>row.id===project.id);expect([p.status,p.revision]).toEqual([project.status,project.revision]);}});
test('attention.dedupe',async({request})=>{const s=source();const a=await create(request,{source:s});const done=await api(request,base+'/items/'+a.item.id+'/complete',{method:'POST',data:command(a.item)});const duplicate=await create(request,{source:s});expect([duplicate.item.id,duplicate.item.status,duplicate.queueRevision]).toEqual([a.item.id,'COMPLETED',done.queueRevision]);const other=await create(request,{source:{...s,intent:'another'}});expect(other.item.id===a.item.id).toBe(false);const next=await create(request,{source:{...s,generation:'v2'}});expect(next.item.id===a.item.id).toBe(false);});
test('attention.operation-replay',async({request})=>{const data={operationId:operationId(),id:randomUUID(),action:'Replay QA',projectLabel:'QA',source:source()};const a=await api(request,base+'/items',{method:'POST',data});const b=await api(request,base+'/items',{method:'POST',data});expect(b).toEqual(a);const mismatch=await request.post(process.env.QA_API_URL+base+'/items',{data:{...data,action:'Different'}});expect(mismatch.status()).toBe(409);expect((await mismatch.json()).code).toBe('IDEMPOTENCY_MISMATCH');});
test('attention.revision-conflicts',async({request})=>{const a=await create(request);const done=await api(request,base+'/items/'+a.item.id+'/complete',{method:'POST',data:command(a.item)});await api(request,base+'/items/'+a.item.id+'/reopen',{method:'POST',data:command(done.item)});const stale=await request.post(process.env.QA_API_URL+base+'/items/'+a.item.id+'/complete',{data:command(a.item)});expect(stale.status()).toBe(409);expect((await stale.json()).code).toBe('REVISION_CONFLICT');const fresh=await api(request,base+'/items/'+a.item.id);const wrong=await request.post(process.env.QA_API_URL+base+'/items/'+a.item.id+'/complete',{data:{...command(fresh),expectedGeneration:'wrong'}});expect(wrong.status()).toBe(409);expect((await wrong.json()).code).toBe('GENERATION_CHANGED');});
test('attention.orders',async({request})=>{const a=await create(request),b=await create(request);let snap=await api(request,base+'/snapshot');const beforeLane=a.item.laneOrder;await api(request,base+'/items/'+a.item.id+'/move',{method:'POST',data:{operationId:operationId(),expectedRevision:a.item.revision,expectedQueueRevision:snap.queueRevision,mode:'STACK',beforeItemId:b.item.id}});snap=await api(request,base+'/snapshot');expect(snap.items[0].id).toBe(a.item.id);const moved=snap.items.find(item=>item.id===a.item.id);expect(moved.laneOrder).toBe(beforeLane+1);const destination=snap.lanes[1].id;await api(request,base+'/items/'+a.item.id+'/move',{method:'POST',data:{operationId:operationId(),expectedRevision:moved.revision,expectedQueueRevision:snap.queueRevision,mode:'LANE',laneId:destination,beforeItemId:null}});const final=await api(request,base+'/snapshot');expect(final.items[0].id).toBe(a.item.id);expect(final.items[0].laneId).toBe(destination);});
test('attention.lanes',async({request})=>{let snap=await api(request,base+'/snapshot');const removed=snap.lanes[2],destination=snap.lanes[0];await api(request,base+'/lanes/'+removed.id+'/remove',{method:'POST',data:{operationId:operationId(),expectedQueueRevision:snap.queueRevision,destinationLaneId:destination.id}});snap=await api(request,base+'/snapshot');expect(snap.lanes.length).toBe(2);await api(request,base+'/lanes',{method:'POST',data:{operationId:operationId(),expectedQueueRevision:snap.queueRevision,name:'QA 새 그룹'}});snap=await api(request,base+'/snapshot');expect(snap.lanes.length).toBe(3);const limit=await request.post(process.env.QA_API_URL+base+'/lanes',{data:{operationId:operationId(),expectedQueueRevision:snap.queueRevision,name:'초과'}});expect(limit.status()).toBe(409);});
test('attention.history',async({request})=>{const s=await create(request,{action:'History '+randomUUID()});const done=await api(request,base+'/items/'+s.item.id+'/complete',{method:'POST',data:command(s.item)});const history=await api(request,base+'/items?status=COMPLETED&q='+encodeURIComponent(s.item.action));expect(history.items.map(row=>row.id)).toContain(s.item.id);const open=await api(request,base+'/items/'+s.item.id+'/reopen',{method:'POST',data:command(done.item)});expect(open.item.sourceKey).toBe(s.item.sourceKey);const snapshot=await api(request,base+'/snapshot');expect(snapshot.items[0].id).toBe(s.item.id);});
test('attention.pairing',async({request})=>{const verifier='v'.repeat(43),state='s'.repeat(43),installId=randomUUID(),challenge=createHash('sha256').update(verifier).digest('base64url');const a=await api(request,base+'/device-authorizations',{method:'POST',data:{challenge,state,redirectUri:'http://127.0.0.1:49152/callback',installId,deviceName:'QA Windows'}});const exchange=()=>request.post(process.env.QA_API_URL+base+'/device-exchange',{data:{code:a.code,verifier,state,installId}});const response=await exchange();expect(response.ok()).toBe(true);const device=await response.json();expect(device.token.startsWith('aqd_')).toBe(true);const headers={Authorization:'Bearer '+device.token};expect((await request.get(process.env.QA_API_URL+base+'/snapshot',{headers})).ok()).toBe(true);expect((await request.get(process.env.QA_API_URL+'/api/workflow',{headers})).status()).toBe(403);expect((await exchange()).status()).toBe(401);await api(request,base+'/devices/'+device.credentialId,{method:'DELETE'});expect((await request.get(process.env.QA_API_URL+base+'/snapshot',{headers})).status()).toBe(401);});
test('attention.producer',async({request})=>{const credential=await api(request,base+'/producer-credentials',{method:'POST',data:{name:'QA TK',namespace:'team-kafka'}});const headers={Authorization:'Bearer '+credential.token};const s=source(randomUUID(),'approval','cycle1','team-kafka','SOURCE_RESOLVED');const a=await api(request,base+'/items',{method:'POST',headers,data:{operationId:operationId(),action:'QA TK 확인',projectLabel:'QA',source:s}});const resolve=()=>api(request,base+'/source-resolution',{method:'POST',headers,data:{operationId:operationId(),sourceKey:a.item.sourceKey,generation:'cycle1',resolvedSourceRevision:'tk1'}});const done=await resolve();expect(done.item.status).toBe('COMPLETED');await api(request,base+'/items/'+a.item.id+'/reopen',{method:'POST',data:command(done.item)});expect((await resolve()).item.status).toBe('OPEN');expect((await request.get(process.env.QA_API_URL+base+'/snapshot',{headers})).status()).toBe(403);expect((await request.post(process.env.QA_API_URL+base+'/items/'+a.item.id+'/complete',{headers,data:command(a.item)})).status()).toBe(403);await api(request,base+'/devices/'+credential.credentialId,{method:'DELETE'});});
test('attention.nearby-workflow',async({request})=>{for(const path of ['/api/workflow','/api/workflow/preferences','/api/workflow/project-profiles'])expect((await request.get(process.env.QA_API_URL+path)).ok()).toBe(true);});
