import java.nio.file.*;
import java.sql.*;
import java.util.*;
import org.flywaydb.core.Flyway;

/** Explicit root-owned forward DEV migration utility. Default preflight/verify are read-only. */
public class AttentionMigration {
 private static final String VERSION="72",SCRIPT="V72__workflow_attention_queue.sql",BASELINE="71";
 private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}
 private static String env(String key){String v=System.getenv(key);require(v!=null&&!v.isBlank(),"ENV_REQUIRED_"+key);return v;}
 private static String url(){String value=env("DEV_DB_URL");require(value.startsWith("jdbc:postgresql://")&&!value.equals(System.getenv("PROD_DB_URL")),"DEV_DATABASE_REQUIRED");try{var uri=java.net.URI.create(value.substring(5));require(uri.getUserInfo()==null,"URL_CREDENTIALS_REJECTED");if(uri.getRawQuery()!=null)for(String part:uri.getRawQuery().split("&")){var pair=part.split("=",2);String key=java.net.URLDecoder.decode(pair[0],java.nio.charset.StandardCharsets.UTF_8),v=pair.length==2?java.net.URLDecoder.decode(pair[1],java.nio.charset.StandardCharsets.UTF_8):"";require(!Set.of("user","password").contains(key.toLowerCase(Locale.ROOT)),"URL_CREDENTIALS_REJECTED");if(key.equalsIgnoreCase("currentSchema"))require(v.equals("public"),"PUBLIC_SCHEMA_REQUIRED");}}catch(IllegalArgumentException e){throw new IllegalStateException("DEV_URL_INVALID");}return value;}
 private static String readOnly(String url){return url+(url.contains("?")?"&":"?")+"options=-c%20default_transaction_read_only%3Don&connectTimeout=15&socketTimeout=60";}
 private static Flyway flyway(String url,Properties p,Path migrations,boolean targeted){var config=Flyway.configure().dataSource(url,p.getProperty("user"),p.getProperty("password")).locations("filesystem:"+migrations).schemas("public").defaultSchema("public").createSchemas(false).cleanDisabled(true).baselineOnMigrate(false).outOfOrder(false).validateOnMigrate(true).ignoreMigrationPatterns("*:pending");if(targeted)config.target(VERSION);return config.load();}
 private static void history(String url,Properties p)throws Exception{try(var c=DriverManager.getConnection(readOnly(url),p)){c.setReadOnly(true);try(var s=c.createStatement()){s.setQueryTimeout(15);try(var rows=s.executeQuery("select version,script,checksum,success from public.flyway_schema_history where version is not null order by installed_rank")){while(rows.next())System.out.println("QA_ATTENTION_HISTORY="+rows.getString(1)+"|"+rows.getString(2)+"|"+rows.getInt(3)+"|"+rows.getBoolean(4));}}}}
 private static void states(Flyway f){for(var migration:f.info().all()){String state=migration.getState().name();require(!state.contains("FAILED")&&!state.startsWith("FUTURE")&&!state.startsWith("MISSING"),"UNEXPECTED_HISTORY_STATE");}}
 private static void preflight(Flyway f){f.validate();states(f);var info=f.info();var pending=info.pending();require(info.current()!=null&&BASELINE.equals(info.current().getVersion().getVersion()),"APPLIED_V71_REQUIRED");require(pending.length==1&&VERSION.equals(pending[0].getVersion().getVersion())&&SCRIPT.equals(pending[0].getScript()),"ONLY_CANONICAL_V72_PENDING_REQUIRED");System.out.println("QA_ATTENTION_PENDING="+pending[0].getVersion()+"|"+pending[0].getScript()+"|"+pending[0].getChecksum());System.out.println("QA_ATTENTION_PREFLIGHT=PASS");}
 private static void verify(Flyway f){f.validate();states(f);var info=f.info();require(info.pending().length==0&&info.current()!=null&&VERSION.equals(info.current().getVersion().getVersion())&&SCRIPT.equals(info.current().getScript())&&info.current().getState().name().equals("SUCCESS"),"SUCCESSFUL_V72_REQUIRED");System.out.println("QA_ATTENTION_VERIFY=PASS");}
 public static void main(String[] args){try{require(args.length==1&&Set.of("preflight","migrate","verify").contains(args[0]),"MODE_REQUIRED");String mode=args[0],url=url();Properties p=new Properties();p.setProperty("user",env("DEV_DB_USERNAME"));p.setProperty("password",env("DEV_DB_PASSWORD"));p.setProperty("connectTimeout","15");p.setProperty("socketTimeout","60");p.setProperty("ApplicationName","pos-qa-attention-v72");Path migrations=Path.of(Objects.requireNonNullElse(System.getenv("QA_MIGRATIONS"),"src/main/resources/db/migration")).toAbsolutePath().normalize();require(Files.isRegularFile(migrations.resolve(SCRIPT)),"CANONICAL_V72_SOURCE_REQUIRED");var audit=flyway(readOnly(url),p,migrations,false);history(url,p);if(mode.equals("verify")){verify(audit);return;}preflight(audit);if(mode.equals("preflight"))return;
 require("true".equals(System.getenv("QA_SHARED_LOCK_HELD")),"ROOT_SHARED_QA_LOCK_REQUIRED");
 try(var c=DriverManager.getConnection(url,p);var s=c.createStatement()){s.setQueryTimeout(15);try(var acquired=s.executeQuery("select pg_try_advisory_lock(hashtextextended('pos-central-qa-schema',0))")){acquired.next();require(acquired.getBoolean(1),"SCHEMA_MIGRATION_BUSY");}preflight(audit);var result=flyway(url,p,migrations,true).migrate();require(result.migrationsExecuted==1,"EXACTLY_ONE_V72_REQUIRED");System.out.println("QA_ATTENTION_MIGRATIONS_EXECUTED=1");}history(url,p);verify(flyway(readOnly(url),p,migrations,false));
 }catch(Exception e){System.err.println("QA_ATTENTION_MIGRATION_BLOCKED="+(e instanceof IllegalStateException?e.getMessage():e.getClass().getSimpleName())+"; use credential-redacted diagnostics");System.exit(1);}}
}
