// Attendance refinement batch §3/§20: the annual donut's "elapsed days"
// value must equal the real calendar day-of-year (Seoul-local), never a
// count of resolved-status WorkRecord rows. The bug was in
// AnnualAttendanceSummary.tsx's own re-aggregation of MonthlyAttendanceCounts
// (it summed only the 7 real-status buckets, silently excluding 미입력 —
// undercounting on every date with no WorkRecord at all). The fix is for
// that component's DONUT_ORDER to include 미입력, so summing every bucket in
// MonthlyAttendanceCounts again equals exactly the day-by-day elapsed count
// aggregateYearlyAttendance itself already produces correctly. This file
// tests that invariant directly against aggregateYearlyAttendance (the real
// production function, not a parallel reimplementation) rather than
// rendering the .tsx component, following the same no-test-runner
// standalone-script convention as latenessSummary.test.ts.
import assert from "node:assert/strict";
import { register } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { WorkLogRecord } from "./mockData";

const frontendRoot = pathToFileURL(path.resolve(import.meta.dirname, "../..") + "/").href;
const loaderSource = `
export async function resolve(specifier, context, nextResolve) {
  if (specifier.startsWith("@/")) {
    return nextResolve(new URL(specifier.slice(2) + ".ts", ${JSON.stringify(frontendRoot)}).href, context);
  }
  if ((specifier.startsWith("./") || specifier.startsWith("../")) && !/\\.[a-zA-Z0-9]+$/.test(specifier)) {
    return nextResolve(specifier + ".ts", context);
  }
  return nextResolve(specifier, context);
}
`;
register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url);

const { aggregateYearlyAttendance } = await import("./attendance.ts");

function test(name: string, fn: () => void) {
  try {
    fn();
    console.log(`ok - ${name}`);
  } catch (err) {
    console.error(`FAIL - ${name}`);
    console.error(err);
    process.exitCode = 1;
  }
}

// Same "daysElapsed" formula as the fixed AnnualAttendanceSummary.tsx —
// summing every bucket, including 미입력, rather than excluding it.
function elapsedDays(counts: ReturnType<typeof aggregateYearlyAttendance>): number {
  return counts.근무 + counts.휴일 + counts.연차 + counts.병가 + counts.조퇴 + counts.반차 + counts.결근 + counts.미입력;
}

function record(date: Date, status: WorkLogRecord["status"]): WorkLogRecord {
  return {
    id: `r-${date.toISOString()}`,
    date,
    status,
    location: "",
    clockIn: null,
    clockOut: null,
    appliedStartTime: null,
    basicWorkMinutes: null,
    workTimeEntries: [],
    score: null,
    memo: "",
    isOnTimeOverride: false,
    absenceAutoGenerated: false,
    absenceCorrectedAt: null,
    version: 1,
  };
}

test("the confirmed 2026-08-30 example: 242 elapsed days out of 365 (non-leap year)", () => {
  const referenceDate = new Date(2026, 7, 30);
  const counts = aggregateYearlyAttendance([], new Date(2026, 0, 1), referenceDate);
  assert.equal(elapsedDays(counts), 242);
});

test("ordinary (non-leap) year: elapsed days equals the actual day-of-year regardless of how many WorkRecords exist", () => {
  const referenceDate = new Date(2026, 5, 15); // June 15, 2026 -> day 166
  const records = [record(new Date(2026, 0, 5), "근무"), record(new Date(2026, 2, 1), "휴일")];
  const counts = aggregateYearlyAttendance(records, new Date(2026, 0, 1), referenceDate);
  assert.equal(elapsedDays(counts), 166);
  // Only 2 of those 166 days have a real record — the rest fall into 미입력,
  // confirming this was never a WorkRecord-count-based total.
  assert.equal(counts.미입력, 164);
});

test("leap year: February 29 is counted, elapsed days matches day-of-year through the leap day and beyond", () => {
  const referenceDate = new Date(2024, 2, 1); // March 1, 2024 (leap year) -> day 61
  const counts = aggregateYearlyAttendance([], new Date(2024, 0, 1), referenceDate);
  assert.equal(elapsedDays(counts), 61);
});

test("year start: January 1 itself counts as exactly 1 elapsed day", () => {
  const referenceDate = new Date(2026, 0, 1);
  const counts = aggregateYearlyAttendance([], new Date(2026, 0, 1), referenceDate);
  assert.equal(elapsedDays(counts), 1);
});

test("future dates are never tallied in any bucket, not even 미입력", () => {
  const referenceDate = new Date(2026, 0, 10); // day 10
  const counts = aggregateYearlyAttendance([], new Date(2026, 0, 1), referenceDate);
  assert.equal(elapsedDays(counts), 10);
  // Sanity: the year has 365 days total, so 355 future days must be excluded.
  assert.equal(365 - elapsedDays(counts), 355);
});

test("today with no WorkRecord counts as 미입력, never fabricated as 결근 or skipped", () => {
  const referenceDate = new Date(2026, 3, 20); // April 20, 2026, no record for it
  const counts = aggregateYearlyAttendance([], new Date(2026, 0, 1), referenceDate);
  assert.equal(counts.미입력 > 0, true);
  assert.equal(counts.결근, 0);
});

test("a past date with no matching record is 미입력, distinct from an explicit 결근 row", () => {
  const referenceDate = new Date(2026, 3, 20);
  const records = [record(new Date(2026, 3, 18), "결근")]; // explicit absence, 2 days before reference
  const counts = aggregateYearlyAttendance(records, new Date(2026, 0, 1), referenceDate);
  assert.equal(counts.결근, 1); // only the explicit row
  assert.equal(counts.미입력, elapsedDays(counts) - 1); // every other elapsed day is 미입력
});
