// Attendance follow-up refinement — calendar grid geometry (§2/§6/§23),
// multi-selection range semantics (§5/§21), and the true calendar-week
// actual-work total (§7). Standalone assert-based script, same convention
// as the other worklog *.test.ts files: no test runner installed, run
// directly via `node app/worklog/attendanceCalendarLogic.test.ts`
// (Node 22.6+).
import assert from "node:assert/strict";
import { register } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { WorkLogRecord } from "./mockData";
import type { AttendancePlanDto, PlannableAttendanceStatus, PlannedTimeBlock } from "@/lib/api/types";

const frontendRoot = pathToFileURL(path.resolve(import.meta.dirname, "../..") + "/").href;
const loaderSource = `
export async function resolve(specifier, context, nextResolve) {
  if (specifier.startsWith("@/")) {
    return nextResolve(new URL(specifier.slice(2) + ".ts", ${JSON.stringify(frontendRoot)}).href, context);
  }
  if ((specifier.startsWith("./") || specifier.startsWith("../")) && !/\\.[a-zA-Z0-9]+$/.test(specifier)) {
    return nextResolve(specifier + ".ts", context);
  }
  return nextResolve(specifier, context);
}
`;
register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url);

const { computeGridDates, dateRangeKeys, sundayWeekNetMinutes, buildClipboardSnapshot } = await import("./attendanceCalendarLogic.ts");

function test(name: string, fn: () => void) {
  try {
    fn();
    console.log(`ok - ${name}`);
  } catch (err) {
    console.error(`FAIL - ${name}`);
    console.error(err);
    process.exitCode = 1;
  }
}

function dateKey(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// --- computeGridDates (§2/§6) ---

test("August 2026 (starts Saturday) leads with the prior week's Mon-Fri and trails into September", () => {
  const grid = computeGridDates(new Date(2026, 7, 1));
  // Aug 1 2026 is a Saturday -> Monday-start leading = Mon 7/27..Fri 7/31 (5 days).
  assert.equal(dateKey(grid[0]), "2026-07-27");
  assert.equal(dateKey(grid[4]), "2026-07-31");
  assert.equal(dateKey(grid[5]), "2026-08-01");
  assert.equal(dateKey(grid[grid.length - 1]).startsWith("2026-09"), true);
});

test("grid length is always a whole number of 7-day weeks", () => {
  for (let month = 0; month < 12; month++) {
    const grid = computeGridDates(new Date(2026, month, 1));
    assert.equal(grid.length % 7, 0);
  }
});

test("grid dates are always exactly consecutive calendar days, no gaps or duplicates", () => {
  const grid = computeGridDates(new Date(2026, 1, 1)); // February
  for (let i = 1; i < grid.length; i++) {
    const diffDays = Math.round((grid[i].getTime() - grid[i - 1].getTime()) / 86400000);
    assert.equal(diffDays, 1);
  }
});

test("a month that starts on Monday has zero leading days", () => {
  // 2026-06-01 is a Monday.
  const grid = computeGridDates(new Date(2026, 5, 1));
  assert.equal(dateKey(grid[0]), "2026-06-01");
});

test("December -> January grid trails into the next calendar year", () => {
  const grid = computeGridDates(new Date(2026, 11, 1));
  const last = grid[grid.length - 1];
  if (last.getMonth() === 0) {
    assert.equal(last.getFullYear(), 2027);
  }
});

// --- dateRangeKeys (§5/§21) ---

test("a range against itself is a single-date set", () => {
  const d = new Date(2026, 7, 15);
  const keys = dateRangeKeys(d, d);
  assert.deepEqual([...keys], ["2026-08-15"]);
});

test("range order doesn't matter — same result whichever end is passed first", () => {
  const a = new Date(2026, 7, 10);
  const b = new Date(2026, 7, 13);
  const forward = [...dateRangeKeys(a, b)].sort();
  const backward = [...dateRangeKeys(b, a)].sort();
  assert.deepEqual(forward, backward);
  assert.deepEqual(forward, ["2026-08-10", "2026-08-11", "2026-08-12", "2026-08-13"]);
});

test("range crosses a month boundary correctly", () => {
  const keys = dateRangeKeys(new Date(2026, 7, 30), new Date(2026, 8, 2));
  assert.deepEqual([...keys].sort(), ["2026-08-30", "2026-08-31", "2026-09-01", "2026-09-02"]);
});

test("range crosses a year boundary correctly", () => {
  const keys = dateRangeKeys(new Date(2026, 11, 30), new Date(2027, 0, 2));
  assert.deepEqual([...keys].sort(), ["2026-12-30", "2026-12-31", "2027-01-01", "2027-01-02"]);
});

// --- sundayWeekNetMinutes (§7) ---

function record(date: Date, netMinutesViaEntries: number): WorkLogRecord {
  return {
    id: `r-${dateKey(date)}`,
    date,
    status: "근무",
    location: "",
    clockIn: null,
    clockOut: null,
    appliedStartTime: null,
    basicWorkMinutes: null,
    workTimeEntries: netMinutesViaEntries > 0 ? [{ id: "e1", categoryId: "c1", item: "work", minutes: netMinutesViaEntries }] : [],
    score: null,
    memo: "",
    isOnTimeOverride: false,
    absenceAutoGenerated: false,
    absenceCorrectedAt: null,
    version: 1,
  };
}

test("sums a full Monday-Sunday week entirely within one month", () => {
  const recordByDate = new Map<string, WorkLogRecord>();
  for (let d = 3; d <= 9; d++) recordByDate.set(`2026-08-${String(d).padStart(2, "0")}`, record(new Date(2026, 7, d), 60));
  // 2026-08-09 is a Sunday.
  const total = sundayWeekNetMinutes(new Date(2026, 7, 9), recordByDate);
  assert.equal(total, 60 * 7);
});

test("a week crossing a month boundary sums all seven real dates, not just the visible month's", () => {
  const recordByDate = new Map<string, WorkLogRecord>();
  // Week Mon 2026-07-27 .. Sun 2026-08-02.
  const days = [
    new Date(2026, 6, 27),
    new Date(2026, 6, 28),
    new Date(2026, 6, 29),
    new Date(2026, 6, 30),
    new Date(2026, 6, 31),
    new Date(2026, 7, 1),
    new Date(2026, 7, 2),
  ];
  for (const d of days) recordByDate.set(dateKey(d), record(d, 30));
  const total = sundayWeekNetMinutes(new Date(2026, 7, 2), recordByDate);
  assert.equal(total, 30 * 7);
});

test("a week crossing the Dec 31 / Jan 1 year boundary sums all seven real dates", () => {
  const recordByDate = new Map<string, WorkLogRecord>();
  // Week Mon 2026-12-28 .. Sun 2027-01-03.
  const days = [
    new Date(2026, 11, 28),
    new Date(2026, 11, 29),
    new Date(2026, 11, 30),
    new Date(2026, 11, 31),
    new Date(2027, 0, 1),
    new Date(2027, 0, 2),
    new Date(2027, 0, 3),
  ];
  for (const d of days) recordByDate.set(dateKey(d), record(d, 45));
  const total = sundayWeekNetMinutes(new Date(2027, 0, 3), recordByDate);
  assert.equal(total, 45 * 7);
});

test("a day with no matching record contributes zero, never fabricated", () => {
  const recordByDate = new Map<string, WorkLogRecord>();
  recordByDate.set("2026-08-09", record(new Date(2026, 7, 9), 60));
  const total = sundayWeekNetMinutes(new Date(2026, 7, 9), recordByDate);
  assert.equal(total, 60);
});

test("a non-workday-status record in the week is excluded from the total", () => {
  const recordByDate = new Map<string, WorkLogRecord>();
  const workday = record(new Date(2026, 7, 5), 60);
  const holiday = { ...record(new Date(2026, 7, 6), 0), status: "휴일" as const };
  recordByDate.set(dateKey(workday.date), workday);
  recordByDate.set(dateKey(holiday.date), holiday);
  const total = sundayWeekNetMinutes(new Date(2026, 7, 9), recordByDate);
  assert.equal(total, 60);
});

// --- buildClipboardSnapshot (§8/§10/§16 dormant-vs-effective copy filter) ---

function plan(status: PlannableAttendanceStatus, plannedNetWorkMinutes: number | null = null, startTimeCriterionId: string | null = "criterion-1"): AttendancePlanDto {
  return { id: "plan-1", planDate: "2026-04-28", plannedStatus: status, startTimeCriterionId, plannedNetWorkMinutes };
}

function block(date: Date, startHour: number, endHour: number): PlannedTimeBlock {
  const pad = (n: number) => String(n).padStart(2, "0");
  return {
    id: `block-${startHour}`,
    title: `블록 ${startHour}`,
    startAt: `${dateKey(date)}T${pad(startHour)}:00:00`,
    endAt: `${dateKey(date)}T${pad(endHour)}:00:00`,
    categoryId: "cat-1",
    memo: null,
  };
}

test("buildClipboardSnapshot carries an effective (WORK) plan's status, criterion, planned net work, and blocks", () => {
  const d = new Date(2026, 3, 28);
  const snap = buildClipboardSnapshot(d, 0, plan("WORK", 360), [block(d, 15, 17)]);
  assert.deepEqual(snap.plan, { status: "WORK", startTimeCriterionId: "criterion-1", plannedNetWorkMinutes: 360 });
  assert.equal(snap.blocks.length, 1);
  assert.equal(snap.blocks[0].startMinutes, 15 * 60);
});

test("buildClipboardSnapshot excludes dormant PlannedTimeBlocks and plannedNetWorkMinutes for a non-work plan status", () => {
  const d = new Date(2026, 3, 28);
  const snap = buildClipboardSnapshot(d, 0, plan("PAID_LEAVE", 360, null), [block(d, 15, 17)]);
  assert.ok(snap.plan);
  assert.equal(snap.plan.status, "PAID_LEAVE");
  assert.equal(snap.plan.plannedNetWorkMinutes, null);
  assert.deepEqual(snap.blocks, []);
});

test("buildClipboardSnapshot still includes orphaned blocks when there is no plan at all for that date", () => {
  const d = new Date(2026, 3, 28);
  const snap = buildClipboardSnapshot(d, 0, undefined, [block(d, 15, 17)]);
  assert.equal(snap.plan, null);
  assert.equal(snap.blocks.length, 1);
});

test("buildClipboardSnapshot preserves the given offsetDays verbatim", () => {
  const d = new Date(2026, 3, 28);
  const snap = buildClipboardSnapshot(d, 5, plan("WORK"), []);
  assert.equal(snap.offsetDays, 5);
});

test("buildClipboardSnapshot only includes blocks matching that exact date, not other dates", () => {
  const d = new Date(2026, 3, 28);
  const otherDay = new Date(2026, 3, 29);
  const snap = buildClipboardSnapshot(d, 0, plan("WORK"), [block(d, 15, 17), block(otherDay, 9, 10)]);
  assert.equal(snap.blocks.length, 1);
});
