// Deterministic verification for the FINAL GAP CHECK lateness UX
// (weekly "지각 n회", Daily Work 지각 횟수/총 지각 시간/평균 지각 시간).
// Same rationale as criteriaSave.test.ts: no test runner is installed in
// this frontend, so this is a small assert-based script runnable directly
// via `node app/worklog/latenessSummary.test.ts` (Node 22.6+), exercising
// the exact countLateRecords/summarizeDailyLateness/getDailyWorkPoints
// functions the UI calls — not a parallel reimplementation of lateness
// semantics (both derive from the single shared getEffectiveLateness).
import assert from "node:assert/strict";
import { register } from "node:module";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { DailyWorkPoint } from "./selectors.ts";
import type { WorkLogRecord } from "./mockData.ts";
import type { AppliedStartTime } from "./startTimeCriterion.ts";

// selectors.ts imports "@/lib/date" (the frontend's bundler-only path
// alias, resolved by Next.js/tsconfig — not something plain Node ESM
// understands). Rather than duplicate selectors.ts's logic into this
// alias-free test file, or introduce a project-wide test-loader dependency,
// register a tiny inline resolve hook — scoped to this one script's own
// process — that rewrites "@/..." to the real frontend-root file before
// dynamically importing selectors.ts below.
// Also rewrites *every* extensionless relative import ("./foo", "../foo")
// across the transitive dependency graph the same way — bundler-style
// resolution (matching tsconfig's moduleResolution: "bundler") that plain
// Node ESM doesn't do on its own, needed because selectors.ts's own
// same-route dependencies (attendance.ts, format.ts, workTimeEntry.ts, ...)
// all use this codebase's normal extensionless import style.
const frontendRoot = pathToFileURL(path.resolve(import.meta.dirname, "../..") + "/").href;
const loaderSource = `
export async function resolve(specifier, context, nextResolve) {
  if (specifier.startsWith("@/")) {
    return nextResolve(new URL(specifier.slice(2) + ".ts", ${JSON.stringify(frontendRoot)}).href, context);
  }
  if ((specifier.startsWith("./") || specifier.startsWith("../")) && !/\\.[a-zA-Z0-9]+$/.test(specifier)) {
    return nextResolve(specifier + ".ts", context);
  }
  return nextResolve(specifier, context);
}
`;
register(`data:text/javascript,${encodeURIComponent(loaderSource)}`, import.meta.url);

const { countLateRecords, getDailyWorkPoints, summarizeDailyLateness } = await import("./selectors.ts");

function test(name: string, fn: () => void) {
  try {
    fn();
    console.log(`ok - ${name}`);
  } catch (err) {
    console.error(`FAIL - ${name}`);
    console.error(err);
    process.exitCode = 1;
  }
}

const CRITERION: AppliedStartTime = { criterionId: "c1", criterionName: "기본 출근", startTime: "09:00", graceMinutes: 10 };

function record(overrides: Partial<WorkLogRecord>): WorkLogRecord {
  return {
    id: "r1",
    date: new Date(2026, 7, 24),
    status: "근무",
    location: "",
    clockIn: null,
    clockOut: null,
    appliedStartTime: null,
    basicWorkMinutes: null,
    workTimeEntries: [],
    score: null,
    memo: "",
    isOnTimeOverride: false,
    absenceAutoGenerated: false,
    absenceCorrectedAt: null,
    version: 1,
    ...overrides,
  };
}

// clockIn 09:25 vs threshold 09:00 + 10 grace = 09:10 -> 15 minutes late.
const lateRecord = record({ clockIn: "09:25", appliedStartTime: CRITERION });
// clockIn 09:05 -> within grace -> on time.
const onTimeRecord = record({ clockIn: "09:05", appliedStartTime: CRITERION });
// Late arrival, but manually overridden to on-time for analytics.
const overriddenRecord = record({ clockIn: "09:25", appliedStartTime: CRITERION, isOnTimeOverride: true });
// Non-workday status must never count, even with a clock-in-shaped field left over.
const nonWorkdayRecord = record({ status: "연차", clockIn: "09:25", appliedStartTime: CRITERION });

test("countLateRecords counts only records whose effective lateness is late", () => {
  assert.equal(countLateRecords([lateRecord, onTimeRecord]), 1);
});

test("countLateRecords excludes a manually on-time-overridden late arrival", () => {
  assert.equal(countLateRecords([lateRecord, overriddenRecord]), 1);
});

test("countLateRecords excludes non-workday statuses regardless of clock-in", () => {
  assert.equal(countLateRecords([nonWorkdayRecord]), 0);
});

test("countLateRecords returns 0 for an empty or all-on-time week", () => {
  assert.equal(countLateRecords([onTimeRecord, overriddenRecord]), 0);
  assert.equal(countLateRecords([]), 0);
});

function point(lateness: DailyWorkPoint["lateness"]): DailyWorkPoint {
  return { date: new Date(2026, 7, 24), label: "8/24", stayMinutes: null, netWorkMinutes: null, score: null, lateness };
}

test("summarizeDailyLateness aggregates count/total/average from late points only", () => {
  const points = [
    point({ status: "late", minutes: 15 }),
    point({ status: "late", minutes: 5 }),
    point({ status: "on-time" }),
    point({ status: "not-applicable" }),
  ];
  const summary = summarizeDailyLateness(points);
  assert.equal(summary.count, 2);
  assert.equal(summary.totalMinutes, 20);
  assert.equal(summary.averageMinutes, 10);
});

test("summarizeDailyLateness reports a null average (never a fake 0) when nothing is late", () => {
  const summary = summarizeDailyLateness([point({ status: "on-time" }), point({ status: "not-applicable" })]);
  assert.equal(summary.count, 0);
  assert.equal(summary.totalMinutes, 0);
  assert.equal(summary.averageMinutes, null);
});

test("summarizeDailyLateness rounds a non-integer average", () => {
  const points = [point({ status: "late", minutes: 10 }), point({ status: "late", minutes: 15 }), point({ status: "late", minutes: 10 })];
  // (10+15+10)/3 = 11.666... -> rounds to 12.
  assert.equal(summarizeDailyLateness(points).averageMinutes, 12);
});

test("getDailyWorkPoints marks a late workday and excludes non-applicable days from the marker", () => {
  const weekStart = new Date(2026, 7, 24);
  const weekEnd = new Date(2026, 7, 30);
  const records = [
    record({ date: new Date(2026, 7, 24), clockIn: "09:25", appliedStartTime: CRITERION }), // late
    record({ date: new Date(2026, 7, 25), clockIn: "09:05", appliedStartTime: CRITERION }), // on time
    record({ date: new Date(2026, 7, 26), status: "휴일" }), // non-applicable
  ];

  const points = getDailyWorkPoints(weekStart, weekEnd, records);

  assert.equal(points[0].lateness.status, "late");
  assert.equal(points[1].lateness.status, "on-time");
  assert.equal(points[2].lateness.status, "not-applicable");
  // A day with no record at all is also not-applicable, never a fabricated status.
  assert.equal(points[3].lateness.status, "not-applicable");
});
