// Bidirectional mapping between the real backend contract
// (lib/api/types.ts's WorkRecordDto/StartTimeCriterionDto/etc.) and this
// route's own frontend shapes (mockData.ts's WorkLogRecord,
// startTimeCriterion.ts's StartTimeCriterion/AppliedStartTime,
// workTimeEntry.ts's WorkTimeEntry). Kept as one file so every field
// correspondence is visible in one place rather than scattered across
// components.

import type {
  StartTimeCriterionDto,
  StartTimeCriterionInput,
  WorkAttendanceStatus,
  WorkRecordDto,
  WorkRecordInput,
  WorkTimeEntryDto,
  WorkTimeEntryItemInput,
} from "@/lib/api/types";
import { toDateKey } from "@/lib/date";
import type { AttendanceStatus, WorkLogRecord } from "./mockData";
import type { AppliedStartTime, StartTimeCriterion } from "./startTimeCriterion";
import type { WorkTimeEntry } from "./workTimeEntry";

const STATUS_FROM_BACKEND: Record<WorkAttendanceStatus, AttendanceStatus> = {
  WORK: "근무",
  EARLY_LEAVE: "조퇴",
  DAY_OFF: "휴일",
  PAID_LEAVE: "연차",
  SICK_LEAVE: "병가",
  ABSENT: "결근",
};

const STATUS_TO_BACKEND: Record<AttendanceStatus, WorkAttendanceStatus> = {
  근무: "WORK",
  조퇴: "EARLY_LEAVE",
  휴일: "DAY_OFF",
  연차: "PAID_LEAVE",
  병가: "SICK_LEAVE",
  결근: "ABSENT",
};

export function mapStatusFromBackend(status: WorkAttendanceStatus): AttendanceStatus {
  return STATUS_FROM_BACKEND[status];
}

export function mapStatusToBackend(status: AttendanceStatus): WorkAttendanceStatus {
  return STATUS_TO_BACKEND[status];
}

// Backend LocalTime serializes as "HH:mm:ss" (sometimes just "HH:mm");
// every clock-time/start-time field in this route is stored/edited as
// "HH:MM" — strip a trailing ":ss" rather than reformatting, so an
// unexpected extra precision never silently corrupts the value.
function stripSeconds(value: string): string {
  return value.length >= 5 ? value.slice(0, 5) : value;
}

function mapClockTimeFromBackend(value: string | null): string | null {
  return value == null ? null : stripSeconds(value);
}

// "HH:MM" is valid input to the backend's LocalTime parser as-is (seconds
// are optional in ISO-8601 local time) — no reformatting needed on the way in.
function normalizeClockTimeInput(value: string | null): string | null {
  if (value == null) return null;
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

function mapAppliedStartTimeFromDto(dto: WorkRecordDto): AppliedStartTime | null {
  if (!dto.appliedCriterionId || !dto.appliedCriterionName || !dto.appliedStartTime) return null;
  return {
    criterionId: dto.appliedCriterionId,
    criterionName: dto.appliedCriterionName,
    startTime: stripSeconds(dto.appliedStartTime),
  };
}

export function mapWorkTimeEntryFromDto(dto: WorkTimeEntryDto): WorkTimeEntry {
  return {
    id: dto.id,
    categoryId: dto.categoryId,
    item: dto.item,
    minutes: dto.minutes,
    memo: dto.memo ?? undefined,
  };
}

export function mapWorkTimeEntryToInput(entry: WorkTimeEntry): WorkTimeEntryItemInput {
  return {
    id: entry.id,
    categoryId: entry.categoryId,
    item: entry.item,
    minutes: entry.minutes,
    memo: entry.memo ?? null,
  };
}

export function mapWorkRecordFromDto(dto: WorkRecordDto, date: Date): WorkLogRecord {
  return {
    id: dto.id,
    date,
    status: mapStatusFromBackend(dto.status),
    location: dto.workLocation ?? "",
    clockIn: mapClockTimeFromBackend(dto.clockIn),
    clockOut: mapClockTimeFromBackend(dto.clockOut),
    appliedStartTime: mapAppliedStartTimeFromDto(dto),
    basicWorkMinutes: dto.basicWorkMinutes,
    workTimeEntries: dto.workTimeEntries.map(mapWorkTimeEntryFromDto),
    score: dto.workScore,
    memo: dto.memo ?? "",
    isOnTimeOverride: dto.isOnTimeOverride,
    absenceAutoGenerated: dto.absenceAutoGenerated,
    absenceCorrectedAt: dto.absenceCorrectedAt,
    version: dto.version,
  };
}

// A local-only placeholder for a date with no backend row yet — e.g. today
// before the user has done anything. `id: ""` / `version: null` mark it as
// not-yet-created; see mockData.ts's WorkLogRecord doc. Defaults mirror the
// backend entity's own constructor defaults (status WORK) so the very first
// real save is a natural continuation of what's already on screen.
export function buildDraftRecord(date: Date): WorkLogRecord {
  return {
    id: "",
    date,
    status: "근무",
    location: "",
    clockIn: null,
    clockOut: null,
    appliedStartTime: null,
    basicWorkMinutes: null,
    workTimeEntries: [],
    score: null,
    memo: "",
    isOnTimeOverride: false,
    absenceAutoGenerated: false,
    absenceCorrectedAt: null,
    version: null,
  };
}

export function isDraftRecord(record: WorkLogRecord): boolean {
  return record.id === "";
}

// Builds the full-state PUT/absence-correction body from a record's current
// (possibly in-progress-edited) field values — every Work Log write is a
// full replace, never a partial patch, matching the backend contract.
export function mapWorkRecordToInput(record: {
  status: AttendanceStatus;
  clockIn: string | null;
  clockOut: string | null;
  location: string;
  score: number | null;
  memo: string;
  appliedStartTime: AppliedStartTime | null;
  isOnTimeOverride: boolean;
  workTimeEntries: WorkTimeEntry[];
  version: number | null;
}): WorkRecordInput {
  return {
    status: mapStatusToBackend(record.status),
    clockIn: normalizeClockTimeInput(record.clockIn),
    clockOut: normalizeClockTimeInput(record.clockOut),
    workLocation: record.location.trim() === "" ? null : record.location,
    workScore: record.score,
    memo: record.memo.trim() === "" ? null : record.memo,
    appliedCriterionId: record.appliedStartTime?.criterionId ?? null,
    expectedVersion: record.version,
    workTimeEntries: record.workTimeEntries.map(mapWorkTimeEntryToInput),
    isOnTimeOverride: record.isOnTimeOverride,
  };
}

export function mapCriterionFromDto(dto: StartTimeCriterionDto): StartTimeCriterion {
  return {
    id: dto.id,
    name: dto.name,
    startTime: stripSeconds(dto.startTime),
    active: dto.isActive,
  };
}

export function mapCriterionToInput(criterion: { name: string; startTime: string; active: boolean | null }): StartTimeCriterionInput {
  return {
    name: criterion.name,
    startTime: criterion.startTime,
    isActive: criterion.active,
  };
}

// yyyy-MM-dd, timezone-naive (browser-local wall-clock fields), matching
// what every Work Log endpoint expects for a {date} path segment or a
// from/to range-query parameter — never toISOString(), which would shift
// across a UTC day boundary depending on the browser's own offset.
export function toApiDateKey(date: Date): string {
  return toDateKey(date);
}
