// Canonical Work Log domain types.
//
// This file used to also hold the local mock-data generators
// (getWeekRecords/getMonthRecords/buildTrendHistoryWeekRecords) that stood
// in for the backend before the Work Log MVP integration. Those are gone —
// the real backend (see lib/api/workRecords.ts and app/worklog/mapping.ts)
// is now the only source of WorkLogRecord data on the actual Work Log
// route. The file is kept (name included) purely for import-path stability:
// ~20 files in this route import the types below from "./mockData".

import type { WorkTimeEntry } from "./workTimeEntry";
import type { AppliedStartTime } from "./startTimeCriterion";

// The six attendance statuses. 결근 (ABSENT) was added during the Work Log
// MVP integration — the backend's confirmed policy (docs/product/work-log-policy.md)
// establishes ABSENT as a real, displayable, persisted status (written by
// the absence-backfill scheduler, or directly by a user/future-flow), which
// supersedes the older 5-status-only frontend spec this list used to cite.
export const ATTENDANCE_STATUSES = ["근무", "휴일", "연차", "병가", "조퇴", "결근"] as const;
export type AttendanceStatus = (typeof ATTENDANCE_STATUSES)[number];

export interface WorkLogRecord {
  /**
   * The backend WorkRecord's id, or `""` for a date with no backend row yet
   * (a local-only "draft" representing defaults — e.g. today before the
   * user has done anything). Never a client-generated fake id otherwise —
   * see app/worklog/mapping.ts's `buildDraftRecord`.
   */
  id: string;
  date: Date;
  status: AttendanceStatus;
  location: string;
  clockIn: string | null; // "HH:MM"
  clockOut: string | null; // "HH:MM"
  /**
   * Frozen lateness-calculation source — a snapshot of a saved
   * StartTimeCriterion, never a live reference. `null` when no start-time
   * basis has been applied yet. Lateness itself is never stored — always
   * derive it via selectors.ts's `getLateness`.
   */
  appliedStartTime: AppliedStartTime | null;
  /** 체류 시간, in minutes. Server-computed from clock in/out. */
  basicWorkMinutes: number | null;
  /**
   * Additive daily work-time entries. `실근무` is always derived from this
   * list via `getNetWorkMinutes` (selectors.ts) — never read a
   * `netWorkMinutes` field directly, even though the backend also returns
   * one (computed the same way, exposed for other potential consumers).
   */
  workTimeEntries: WorkTimeEntry[];
  /** 0–100. Whether lateness/early-leave affects this is an explicitly deferred rule. */
  score: number | null;
  memo: string;
  /**
   * Record-level on-time override ("정시 출근 처리", backend field
   * `isOnTimeOverride`) — layers over the raw clockIn/appliedStartTime-derived
   * lateness for display only; never mutates clockIn, appliedStartTime, or
   * the raw calculation itself. No source/audit metadata — just this one
   * boolean, matching the backend's own MVP scope for the field.
   */
  isOnTimeOverride: boolean;
  /** True only for an ABSENT row the backend's absence-backfill scheduler
   *  created — never true for any other status or origin. */
  absenceAutoGenerated: boolean;
  /** Non-null once 결근 정정 (absence correction) has been applied at least
   *  once to this record; never cleared by an ordinary later edit. ISO
   *  instant string as returned by the backend, or null. */
  absenceCorrectedAt: string | null;
  /** Optimistic-lock version. `null` for a not-yet-created draft (see `id`). */
  version: number | null;
}
