import assert from "node:assert/strict";
import { test } from "node:test";
import React, { act } from "react";
import { JSDOM } from "jsdom";
import type { Project, Phase, WorkTask, TodoPreferences } from "../../lib/api/workflow";

test("Projects CRUD, phase/task drops, Today identity and isolated To-do preferences persist through remount", async () => {
  const dom = new JSDOM("<div id='root'></div>", { url: "http://localhost/workflow/projects" });
  Object.assign(globalThis, { React, window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, Element: dom.window.Element, Node: dom.window.Node, IS_REACT_ACT_ENVIRONMENT: true });
  const { createRoot } = await import("react-dom/client");
  const { workflowApi } = await import("../../lib/api/workflow");
  const { WorkflowProvider } = await import("./WorkflowContext");
  const { default: Projects } = await import("./Projects");
  const { default: Todo } = await import("./Todo");
  const { defaultTodoPreferences } = await import("./projects-todo-utils");
  const original = { ...workflowApi };
  let projects: Project[] = [], phases: Phase[] = [], tasks: WorkTask[] = [];
  let preferences: TodoPreferences = structuredClone(defaultTodoPreferences);
  const linkedTaskIds: string[] = [], preferenceWrites: TodoPreferences[] = [];
  let counter = 0;
  workflowApi.get = async () => structuredClone({ projects, phases, tasks });
  workflowApi.saveProject = async input => { const value = { ...input, id: input.id || `p${++counter}` }; projects = [...projects.filter(item => item.id !== value.id), value]; return value; };
  workflowApi.savePhase = async input => { const value = { ...input, id: input.id || `f${++counter}` }; phases = [...phases.filter(item => item.id !== value.id), value]; return value; };
  workflowApi.saveTask = async input => { const value = { ...input, id: input.id || `t${++counter}` }; tasks = [...tasks.filter(item => item.id !== value.id), value]; return value; };
  workflowApi.addToToday = async (id, date) => { linkedTaskIds.push(id); return { date, revision: 1, blocks: [] }; };
  workflowApi.getPreferences = async () => structuredClone(preferences);
  workflowApi.savePreferences = async input => { preferences = structuredClone(input); preferenceWrites.push(preferences); return preferences; };
  workflowApi.deleteTask = async id => { tasks = tasks.filter(task => task.id !== id); };
  const root = createRoot(document.getElementById("root")!);
  const byLabel = <T extends Element>(label: string) => document.querySelector<T>(`[aria-label="${label}"]`)!;
  const button = (text: string, scope: ParentNode = document) => Array.from(scope.querySelectorAll<HTMLButtonElement>("button")).find(node => node.textContent === text)!;
  const input = async (node: HTMLInputElement, value: string) => { assert.ok(node); await act(async () => { Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype, "value")!.set!.call(node, value); node.dispatchEvent(new dom.window.Event("input", { bubbles: true })); }); };
  const select = async (node: HTMLSelectElement, value: string) => { await act(async () => { node.value = value; node.dispatchEvent(new dom.window.Event("change", { bubbles: true })); }); };
  const submit = async (node: HTMLFormElement) => { await act(async () => { node.dispatchEvent(new dom.window.Event("submit", { bubbles: true, cancelable: true })); }); };
  const click = async (node: HTMLElement) => { assert.ok(node); await act(async () => node.click()); };
  const drop = async (node: Element, kind: string, id: string) => { await act(async () => { const event = new dom.window.Event("drop", { bubbles: true, cancelable: true }); Object.defineProperty(event, "dataTransfer", { value: { types: [kind], getData: (type: string) => type === kind ? id : "" } }); node.dispatchEvent(event); }); };
  try {
    await act(async () => root.render(<WorkflowProvider><Projects/></WorkflowProvider>));
    await click(button("+ 프로젝트"));
    await input(byLabel("새 프로젝트 제목"), "Alpha");
    await submit(document.querySelector(".wf-project-create")!);
    assert.equal(projects.length, 1);
    const projectId = projects[0].id;
    for (const title of ["Build", "Ship"]) { await input(byLabel("새 Phase 제목"), title); await submit(document.querySelector(".wf-add-phase")!); }
    assert.deepEqual(phases.map(item => item.title), ["Build", "Ship"]);
    const buildId = phases[0].id, shipId = phases[1].id;
    const build = () => byLabel<HTMLElement>("Build");
    await input(build().querySelector('[aria-label="새 작업 제목"]')!, "First task");
    await submit(build().querySelector("form")!);
    assert.equal(tasks.length, 1); assert.equal(tasks[0].phaseId, buildId);
    await act(async () => { button("First task").dispatchEvent(new dom.window.MouseEvent("dblclick", { bubbles: true })); });
    await input(byLabel("작업 이름 편집"), "Renamed task");
    await act(async () => { byLabel<HTMLInputElement>("작업 이름 편집").dispatchEvent(new dom.window.FocusEvent("focusout", { bubbles: true })); });
    assert.equal(tasks[0].title, "Renamed task");
    const taskId = tasks[0].id;
    await drop(byLabel("Ship"), "application/workflow-task", taskId);
    assert.equal(tasks[0].phaseId, shipId);
    await drop(byLabel("미분류 작업"), "application/workflow-task", taskId);
    assert.equal(tasks[0].phaseId, null); assert.equal(tasks[0].id, taskId);
    await drop(build(), "application/workflow-phase", shipId);
    assert.deepEqual([...phases].sort((a, b) => a.order - b.order).map(phase => phase.id), [shipId, buildId]);
    await select(byLabel("프로젝트 상태"), "DONE");
    assert.equal(projects[0].status, "DONE"); assert.equal(tasks[0].status, "TODO");
    assert.match(document.querySelector(".wf-project-main .wf-warning")!.textContent!, /미완료/);
    await click(button("오늘에 추가"));
    assert.deepEqual(linkedTaskIds, [taskId]); assert.equal(tasks.length, 1);
    await act(async () => root.render(<WorkflowProvider key="todo"><Todo/></WorkflowProvider>));
    await click(button("⚙ 보기 설정"));
    const dialog = byLabel<HTMLElement>("To-do 보기 설정");
    await click(byLabel("프로젝트 없음 위로"));
    await select(byLabel("작업 정렬 기준"), "PRIORITY");
    const completed = [...dialog.querySelectorAll<HTMLLabelElement>("label")].find(label => label.textContent === "완료 항목 표시")!;
    await click(completed.querySelector("input")!);
    await submit(dialog as HTMLFormElement);
    assert.equal(preferences.sort, "PRIORITY"); assert.equal(preferences.showCompleted, false);
    assert.deepEqual(preferences.projectOrder, ["unassigned", projectId]);
    assert.equal(projects[0].order, 0); assert.equal(preferenceWrites.length, 1);
    await act(async () => root.render(<WorkflowProvider key="todo-reload"><Todo/></WorkflowProvider>));
    await click(button("⚙ 보기 설정"));
    assert.equal(byLabel<HTMLSelectElement>("작업 정렬 기준").value, "PRIORITY");
    assert.equal(byLabel("To-do 보기 설정").querySelector(".wf-group-order li")?.textContent?.includes("프로젝트 없음"), true);
    await click(button("취소", byLabel("To-do 보기 설정")));
    await click(button("오늘에 추가"));
    assert.deepEqual(linkedTaskIds, [taskId, taskId]); assert.equal(tasks.length, 1);
    await click(button("Renamed task"));
    await select(byLabel("Renamed task 상태"), "DONE");
    assert.equal(tasks[0].status, "DONE");
    assert.equal(document.querySelectorAll(".wf-task-row").length, 0);
  } finally { Object.assign(workflowApi, original); await act(async () => root.unmount()); dom.window.close(); }
});
