import assert from "node:assert/strict";
import { createRequire } from "node:module";
import React, { act } from "react";
import { JSDOM } from "jsdom";
import type { WorkpadDay, WorkTask } from "../../lib/api/workflow";

async function main() {
  const require = createRequire(import.meta.url);
  require.extensions[".css"] = () => {};
  const dom = new JSDOM("<div id='root'></div>", { url: "https://orbit.local/workflow/today?date=2026-09-14", pretendToBeVisual: true });
  const win = dom.window;
  Object.assign(globalThis, { React, window: win, document: win.document, localStorage: win.localStorage, HTMLElement: win.HTMLElement, HTMLTextAreaElement: win.HTMLTextAreaElement, Element: win.Element, Node: win.Node, IS_REACT_ACT_ENVIRONMENT: true });
  Object.defineProperty(globalThis, "navigator", { value: win.navigator, configurable: true });
  globalThis.requestAnimationFrame = callback => { callback(0); return 0; };
  win.HTMLElement.prototype.scrollIntoView = () => {};
  win.HTMLElement.prototype.setPointerCapture = () => {};
  const { createRoot } = await import("react-dom/client");
  const { AppRouterContext } = await import("next/dist/shared/lib/app-router-context.shared-runtime");
  const { PathnameContext, SearchParamsContext } = await import("next/dist/shared/lib/hooks-client-context.shared-runtime");
  const { workflowApi } = await import("../../lib/api/workflow");
  const { newBlock, cloneBlocks } = await import("../../lib/workflow/workpad");
  const { default: Today } = await import("./Today");
  const { WorkflowProvider } = await import("./WorkflowContext");
  const { GlobalTabsProvider, useGlobalTabs } = await import("../../components/GlobalTabs");
  const first = newBlock("TEXT", "Plan"), second = newBlock("BULLET", "Evidence"); second.order = 1;
  const days: Record<string, WorkpadDay> = { "2026-09-14": { date: "2026-09-14", revision: 0, blocks: [first, second] } };
  let workTasks: WorkTask[] = [], saves = 0, promotions = 0, uploads = 0, saveFails = false, titleSaveFails = false;
  let uploadGate: Promise<void> | null = null;
  let carryRequest: { from: string; ids: string[]; to: string } | null = null;
  const routes: string[] = [];
  workflowApi.get = async () => ({ projects: [], phases: [], tasks: structuredClone(workTasks) });
  workflowApi.getDay = async date => structuredClone(days[date] ?? { date, revision: 0, blocks: [] });
  workflowApi.saveDay = async (date, day) => {
    if (saveFails) throw new Error("Offline: keep draft");
    assert.equal(day.revision, days[date]?.revision ?? 0, "autosave uses latest server revision");
    saves++; days[date] = { date, revision: day.revision + 1, blocks: structuredClone(day.blocks) }; return structuredClone(days[date]);
  };
  workflowApi.promote = async (date, blockId) => {
    promotions++;
    const block = days[date].blocks.find(b => b.id === blockId)!;
    const task: WorkTask = { id: crypto.randomUUID(), title: block.content, status: "TODO", projectId: null, phaseId: null, priority: "NORMAL", startDate: null, dueDate: null, memo: null, order: 0 };
    workTasks.push(task); block.workTaskId = task.id; block.type = "CHECKLIST"; days[date].revision++;
    return task;
  };
  workflowApi.saveTask = async task => { if (titleSaveFails) throw new Error("Task title save failed"); const saved = task as WorkTask; workTasks = workTasks.map(t => t.id === task.id ? saved : t); return saved; };
  workflowApi.uploadImage = async () => { if (uploadGate) await uploadGate; return { id: `image-${++uploads}`, width: 400, height: 200 }; };
  workflowApi.getImage = async () => new Blob(["image"], { type: "image/png" });
  workflowApi.carry = async (from, ids, to) => {
    carryRequest = { from, ids, to };
    const source = days[from].blocks.filter(b => ids.includes(b.id));
    const blocks = cloneBlocks(source).map((b, i) => ({ ...b, sourceDate: from, sourceBlockId: source[i].id }));
    days[to] = { date: to, revision: 1, blocks }; return structuredClone(days[to]);
  };
  function Leave() { const shell = useGlobalTabs(); return <button onClick={() => shell?.navigate("/worklog")}>Leave workpad</button>; }
  const router = { push: (route: string) => routes.push(route) } as unknown as React.ContextType<typeof AppRouterContext>;
  const root = createRoot(document.getElementById("root")!);
  let params = new URLSearchParams("date=2026-09-14");
  const render = async () => act(async () => root.render(<AppRouterContext.Provider value={router}><PathnameContext.Provider value="/workflow/today"><SearchParamsContext.Provider value={params}><GlobalTabsProvider><WorkflowProvider><Leave/><Today/></WorkflowProvider></GlobalTabsProvider></SearchParamsContext.Provider></PathnameContext.Provider></AppRouterContext.Provider>));
  const settle = async () => act(async () => { await new Promise(resolve => setTimeout(resolve, 5)); });
  const buttons = () => Array.from(document.querySelectorAll<HTMLButtonElement>("button"));
  const button = (label: string) => { const b = buttons().find(b => b.getAttribute("aria-label") === label || b.textContent?.includes(label)); assert.ok(b, `button ${label} exists`); return b; };
  const click = async (label: string) => { await act(async () => button(label).click()); await settle(); };
  const textareas = () => Array.from(document.querySelectorAll<HTMLTextAreaElement>(".wp-block-body > textarea"));
  const input = async (element: HTMLTextAreaElement | HTMLInputElement, value: string) => {
    await act(async () => {
      const proto = element instanceof win.HTMLTextAreaElement ? win.HTMLTextAreaElement.prototype : win.HTMLInputElement.prototype;
      Object.getOwnPropertyDescriptor(proto, "value")!.set!.call(element, value);
      element.dispatchEvent(new win.Event("input", { bubbles: true }));
      element.dispatchEvent(new win.Event("change", { bubbles: true }));
    });
  };
  const key = async (element: HTMLElement, key: string, options: KeyboardEventInit = {}) => {
    const event = new win.KeyboardEvent("keydown", { key, bubbles: true, cancelable: true, ...options });
    await act(async () => element.dispatchEvent(event)); await settle(); return event;
  };
  let checked = 0;
  const pass = (label: string) => { checked++; console.log(`PASS UI ${label}`); };
  await render(); await settle();
  assert.equal(textareas().length, 2);
  await act(async () => { textareas()[0].focus(); textareas()[0].setSelectionRange(4, 4); });
  await key(textareas()[0], "Enter");
  assert.equal(textareas().length, 3); pass("Enter creates same-level block");
  let editing = textareas()[1];
  await input(editing, "Ship change");
  assert.equal(editing.value, "Ship change");
  await key(editing, "Tab");
  assert.equal(editing.closest<HTMLElement>(".wp-block")!.style.marginLeft, "24px");
  await key(editing, "Tab", { shiftKey: true });
  assert.equal(editing.closest<HTMLElement>(".wp-block")!.style.marginLeft, "0px");
  assert.equal((await key(editing, "Enter", { shiftKey: true })).defaultPrevented, false);
  pass("Tab, Shift Tab and Shift Enter");
  await key(editing, "Enter", { ctrlKey: true });
  assert.ok(document.querySelector('[aria-label="Complete Ship change"]'));
  await key(editing, "Enter", { ctrlKey: true, shiftKey: true });
  assert.equal(promotions, 1); assert.equal(workTasks.length, 1);
  editing = textareas()[1]; await key(editing, "Enter", { metaKey: true, shiftKey: true });
  assert.equal(promotions, 1); assert.match(document.body.textContent!, /Already linked/);
  pass("Checklist shortcut and promotion without duplicate tasks");
  await input(editing, "Ship updated");
  await key(editing, "z", { ctrlKey: true }); assert.equal(editing.value, "Ship change");
  await key(editing, "z", { ctrlKey: true, shiftKey: true }); assert.equal(editing.value, "Ship updated");
  assert.equal(workTasks[0].title, "Ship updated");
  pass("Linked title undo/redo restores visible draft and task title");
  await key(editing, "Enter", { ctrlKey: true });
  assert.equal(workTasks[0].status, "DONE");
  await key(editing, "z", { ctrlKey: true }); assert.equal(workTasks[0].status, "TODO");
  await key(editing, "z", { ctrlKey: true, shiftKey: true }); assert.equal(workTasks[0].status, "DONE");
  pass("Linked checkbox status with undo/redo");

  await input(textareas()[2], "/h2");
  assert.ok(document.querySelector('[aria-label="Quick commands"]'));
  await key(textareas()[2], "Enter");
  assert.ok(textareas()[2].closest(".wp-h2")); pass("Slash command opens and executes");
  await input(textareas()[2], "Results");
  await act(async () => textareas()[0].dispatchEvent(new win.MouseEvent("click", { bubbles: true })));
  await act(async () => { textareas()[2].focus(); textareas()[2].dispatchEvent(new win.MouseEvent("click", { bubbles: true, shiftKey: true })); });
  assert.equal(document.querySelectorAll(".wp-selected").length, 3);
  await click("Clear");
  const handles = () => Array.from(document.querySelectorAll<HTMLButtonElement>(".wp-grip"));
  await act(async () => handles()[0].click());
  await act(async () => handles()[2].dispatchEvent(new win.MouseEvent("click", { bubbles: true, shiftKey: true })));
  assert.equal(document.querySelectorAll(".wp-selected").length, 3);
  const copied = new Map<string, string>();
  const clip = new win.Event("copy", { bubbles: true, cancelable: true });
  Object.defineProperty(clip, "clipboardData", { value: { setData: (type: string, value: string) => copied.set(type, value) } });
  await act(async () => document.querySelector(".wp-main")!.dispatchEvent(clip));
  assert.ok(copied.get("application/x-personal-os-workpad"));
  const paste = new win.Event("paste", { bubbles: true, cancelable: true });
  Object.defineProperty(paste, "clipboardData", { value: { files: [], getData: (type: string) => copied.get(type) ?? "" } });
  await act(async () => textareas()[2].dispatchEvent(paste));
  assert.equal(textareas().length, 6); assert.equal(workTasks.length, 1);
  pass("Shift multiselect, structured clipboard, same task reference");

  const imagePaste = new win.Event("paste", { bubbles: true, cancelable: true });
  Object.defineProperty(imagePaste, "clipboardData", { value: { files: [new win.File(["before"], "before.png", { type: "image/png" }), new win.File(["after"], "after.png", { type: "image/png" })], getData: () => "" } });
  await act(async () => textareas()[5].dispatchEvent(imagePaste)); await settle();
  assert.equal(uploads, 2); assert.equal(document.querySelectorAll(".wp-images figure").length, 2);
  assert.ok(document.querySelector(".wp-image_group"));
  const range = document.querySelector<HTMLInputElement>('[aria-label="Image width"]')!;
  assert.ok(range); await input(range, "65");
  assert.equal(document.querySelector<HTMLElement>(".wp-image-frame")!.style.width, "65%");
  const resize = button("Resize image 1");
  resize.parentElement!.getBoundingClientRect = () => ({ width: 100 } as DOMRect);
  await act(async () => resize.dispatchEvent(new win.MouseEvent("pointerdown", { bubbles: true, clientX: 0 })));
  await act(async () => resize.dispatchEvent(new win.MouseEvent("pointermove", { bubbles: true, clientX: 10 })));
  await act(async () => resize.dispatchEvent(new win.MouseEvent("pointerup", { bubbles: true })));
  assert.equal(document.querySelector<HTMLElement>(".wp-image-frame")!.style.width, "75%");
  pass("Clipboard images form parallel group and support per-image resize");
  let finishUpload: () => void = () => {};
  uploadGate = new Promise<void>(resolve => { finishUpload = resolve; });
  const waitingPaste = new win.Event("paste", { bubbles: true, cancelable: true });
  Object.defineProperty(waitingPaste, "clipboardData", { value: { files: [new win.File(["extra"], "extra.png", { type: "image/png" })], getData: () => "" } });
  await act(async () => textareas()[0].dispatchEvent(waitingPaste));
  await click("Next date");
  assert.equal(document.querySelector<HTMLInputElement>('[aria-label="Workpad date"]')!.value, "2026-09-14");
  assert.equal(document.querySelector(".wp-main")!.hasAttribute("inert"), true);
  await act(async () => finishUpload()); uploadGate = null; await settle();
  assert.equal(uploads, 3);
  pass("Image upload locks date navigation until the original day mutation finishes");

  await click("Carry over to tomorrow");
  const carryChecks = Array.from(document.querySelectorAll<HTMLInputElement>(".wp-carry-check"));
  await act(async () => carryChecks[0].click()); await click("Copy 1 selected to tomorrow");
  assert.ok(carryRequest); assert.equal((carryRequest as { to: string }).to, "2026-09-15");
  assert.ok(days["2026-09-14"].blocks.some(b => b.id === first.id));
  await click("Next date");
  assert.ok(document.querySelector('[aria-label="Source 2026-09-14"]'));
  await click("Source 2026-09-14");
  assert.equal(document.querySelector<HTMLInputElement>('[aria-label="Workpad date"]')!.value, "2026-09-14");
  assert.ok(document.getElementById(`wp-${first.id}`)); pass("Carry header selection, preserved source and source navigation");

  const linkedEditor = textareas().find(t => t.closest(".wp-block-body")!.querySelector(".wp-task-link"))!;
  await input(linkedEditor, "Title guarded across navigation"); titleSaveFails = true;
  await click("Leave workpad"); assert.deepEqual(routes, []);
  assert.equal(linkedEditor.value, "Title guarded across navigation");
  assert.match(document.body.textContent!, /Task title save failed/);
  titleSaveFails = false; await click("Leave workpad");
  assert.equal(workTasks[0].title, "Title guarded across navigation");
  assert.deepEqual(routes, ["/worklog"]); routes.length = 0;
  pass("Navigation guard waits for linked task-title persistence and retains failed drafts");

  await input(textareas()[0], "Keep this unsaved draft"); saveFails = true;
  await click("Leave workpad");
  assert.deepEqual(routes, []); assert.equal(textareas()[0].value, "Keep this unsaved draft");
  assert.match(document.body.textContent!, /Offline: keep draft/);
  saveFails = false; await click("Leave workpad");
  assert.deepEqual(routes, ["/worklog"]); assert.equal(days["2026-09-14"].blocks[0].content, "Keep this unsaved draft");
  pass("Shell navigation flushes draft and blocks navigation on save failure");
  params = new URLSearchParams("date=2026-09-18"); await render(); await settle();
  assert.equal(document.querySelector<HTMLInputElement>('[aria-label="Workpad date"]')!.value, "2026-09-18");
  pass("Global tab URL date change updates mounted Today");
  assert.ok(saves >= 3);
  await act(async () => root.unmount()); win.close();
  console.log(`${checked} rendered Today critical paths passed.`);
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
