import {test,expect} from '../../helpers/browser.mjs';
import path from 'node:path';
const api=()=>process.env.QA_API_URL+'/api/money',dock=p=>p.locator('.money-dock'),rows=p=>p.locator('.money-main tbody tr');
async function call(request,url,method='GET',data){const r=await request.fetch(api()+url,{method,data});expect(r.ok(),`${method} ${url}: ${r.status()}`).toBe(true);return r.json();}
async function open(p,route){await p.goto('/money'+route);await expect(p.getByText('불러오는 중…',{exact:true})).toHaveCount(0);}
async function save(p){await dock(p).getByRole('button',{name:'저장',exact:true}).click();await expect(dock(p)).toHaveCount(0);}
async function capture(p,name){await p.screenshot({path:path.join(process.env.QA_RUN_DIR,name+'-synthetic.png'),fullPage:false});}
async function pick(scope,label,name){await scope.getByRole('button',{name:label,exact:true}).click();const menu=scope.locator('.category-picker-menu');await menu.getByLabel('카테고리 검색').fill(name);await menu.getByRole('button',{name,exact:true}).click();}
let root,target,child,inactive,account,direct,nested,pending;
const category=(name,parentId=null)=>({name,parentId,kind:'EXPENSE',color:'#D86F72',emoji:parentId?null:'🍽️',sortOrder:0,archived:false});
const entry=(amount,title,cat)=>({type:'EXPENSE',fromAccountId:account.id,toAccountId:null,amount,occurredAt:new Date().toISOString(),counterpartyText:'Synthetic hierarchy',title,categoryId:cat,memo:'Synthetic only',excluded:false});
test('money.category.seed',async({request})=>{
 const a=await call(request,'/categories/defaults','POST',{}),b=await call(request,'/categories/defaults','POST',{});expect(a.map(x=>x.id)).toEqual(b.map(x=>x.id));expect(a.some(x=>x.name==='세부분류 없음')).toBe(false);
 root=await call(request,'/categories','POST',category('2단계 식비'));target=await call(request,'/categories','POST',category('2단계 생활'));child=await call(request,'/categories','POST',category('2단계 배달',root.id));inactive=await call(request,'/categories','POST',{...category('2단계 보관',root.id),archived:true});
 account=await call(request,'/accounts','POST',{provider:'IBK',displayName:'2단계 검증 계좌',role:'SPENDING',suffix:'9099'});const t=await call(request,'/tracking');await call(request,'/tracking','PUT',{expense:[...t.expense,account.id],income:t.income,expectedVersion:t.version});
 direct=await call(request,'/transactions','POST',entry(1200,'2단계 대분류 직접',root.id));nested=await call(request,'/transactions','POST',entry(2300,'2단계 하위 선택',child.id));pending=await call(request,'/transactions','POST',entry(900,'2단계 검토',null));
});
test('money.category.management',async({page})=>{
 await open(page,'/classification');await page.getByRole('tab',{name:'카테고리',exact:true}).click();await page.getByRole('button',{name:'2단계 식비 관리 펼치기',exact:true}).click();await expect(page.locator('.category-management').getByText('2단계 배달',{exact:true})).toBeVisible();await rows(page).filter({hasText:'2단계 배달'}).click();await expect(dock(page).getByLabel('상위 카테고리')).toHaveValue(root.id);await capture(page,'01-category-hierarchy-panel');await dock(page).getByRole('button',{name:'취소',exact:true}).click();
});
test('money.category.picker-filter',async({page,request})=>{
 await open(page,'/bookkeeping');await page.getByLabel('가계부 검색').fill('2단계 하위 선택');await rows(page).filter({hasText:'2단계 하위 선택'}).click();await dock(page).getByRole('button',{name:'가계부 카테고리',exact:true}).click();const menu=dock(page).locator('.category-picker-menu');await menu.getByRole('button',{name:'2단계 식비 세부분류 펼치기',exact:true}).click();await expect(dock(page).getByRole('button',{name:'가계부 카테고리',exact:true})).toContainText('2단계 식비 > 2단계 배달');await menu.getByRole('button',{name:'🍽️ 2단계 식비',exact:true}).click();await save(page);
 expect((await call(request,'/bookkeeping/'+nested.id)).categoryId).toBe(root.id);expect((await call(request,'/transactions/'+nested.id)).categoryId).toBe(child.id);
 await rows(page).filter({hasText:'2단계 하위 선택'}).click();await pick(dock(page),'가계부 카테고리','2단계 배달');await save(page);expect((await call(request,'/bookkeeping/'+nested.id)).categoryId).toBe(child.id);
 await page.getByLabel('가계부 검색').fill('2단계');const filters=page.locator('.category-filters');await filters.getByRole('button',{name:'🍽️ 2단계 식비',exact:true}).dblclick();await expect(rows(page)).toHaveCount(2);await filters.getByRole('button',{name:'2단계 식비 필터 펼치기',exact:true}).click();await filters.getByRole('button',{name:'세부분류 없음',exact:true}).click();await expect(rows(page)).toHaveCount(1);await expect(rows(page)).toContainText('2단계 대분류 직접');await filters.getByRole('button',{name:'2단계 배달',exact:true}).dblclick();await expect(rows(page)).toHaveCount(1);await expect(rows(page)).toContainText('2단계 하위 선택');await rows(page).click();await dock(page).getByRole('button',{name:'가계부 카테고리',exact:true}).click();await menu.getByRole('button',{name:'2단계 식비 세부분류 펼치기',exact:true}).click();await capture(page,'03-bookkeeping-filter-picker');await dock(page).getByRole('button',{name:'취소',exact:true}).click();await filters.getByRole('button',{name:'전체 선택',exact:true}).click();
});
test('money.category.move-lifecycle',async({page,request})=>{
 await open(page,'/classification');await page.getByRole('button',{name:'2단계 식비 관리 펼치기',exact:true}).click();await rows(page).filter({hasText:'2단계 배달'}).click();await dock(page).getByLabel('상위 카테고리').selectOption(target.id);page.once('dialog',async d=>{expect(d.message()).toContain('연결 기록 1건');expect(d.message()).toContain('과거 대분류 통계');await d.accept();});await dock(page).getByRole('button',{name:'이동 영향 확인'}).click();await expect(dock(page)).toHaveCount(0);child=(await call(request,'/categories')).find(c=>c.id===child.id);expect(child.parentId).toBe(target.id);expect((await call(request,'/transactions/'+nested.id)).categoryId).toBe(child.id);
 const preview=await call(request,`/categories/${child.id}/impact`);child=await call(request,`/categories/${child.id}/move`,'PUT',{parentId:root.id,expectedVersion:child.version,expectedParentVersion:root.version,preview,confirmed:true});
 await page.reload();await expect(page.getByText('불러오는 중…',{exact:true})).toHaveCount(0);await rows(page).filter({hasText:'2단계 식비'}).click();await dock(page).getByLabel('비활성 · 과거 기록 유지').check();page.once('dialog',d=>d.accept());await save(page);let cats=await call(request,'/categories');expect(cats.find(c=>c.id===child.id).effectiveArchived).toBe(true);expect(cats.find(c=>c.id===child.id).archived).toBe(false);
 await rows(page).filter({hasText:'2단계 식비'}).click();await dock(page).getByLabel('비활성 · 과거 기록 유지').uncheck();await save(page);cats=await call(request,'/categories');root=cats.find(c=>c.id===root.id);expect(cats.find(c=>c.id===child.id).effectiveArchived).toBe(false);expect(cats.find(c=>c.id===inactive.id).archived).toBe(true);
});
test('money.category.rules-review',async({page,request})=>{
 const before=(await call(request,'/classification-rules')).length;await open(page,'/review');const row=rows(page).filter({hasText:'2단계 검토'});await row.locator('.category-picker > button').click();const menu=row.locator('.category-picker-menu');await menu.getByLabel('카테고리 검색').fill('2단계 배달');await menu.getByRole('button',{name:'2단계 배달',exact:true}).click();await row.getByRole('button',{name:'완료',exact:true}).click();await expect(row).toHaveCount(0);expect((await call(request,'/classification-rules')).length).toBe(before);expect((await call(request,'/bookkeeping/'+pending.id)).categoryId).toBe(child.id);
 await open(page,'/classification');await page.getByRole('tab',{name:'자동 분류 규칙'}).click();await page.getByRole('button',{name:'규칙 추가',exact:true}).click();await dock(page).getByLabel('규칙 이름').fill('2단계 규칙');await dock(page).getByLabel('조건 2 값').fill('Synthetic hierarchy');await pick(dock(page),'분류 카테고리','2단계 배달');await capture(page,'04-rule-shared-picker');await save(page);expect((await call(request,'/classification-rules')).find(r=>r.name==='2단계 규칙').categoryId).toBe(child.id);
});
test('money.category.overview',async({page})=>{
 await open(page,'');await page.getByRole('button',{name:'2단계 식비',exact:true}).click();const detail=page.getByRole('region',{name:'2단계 식비 상세 분석'});await expect(detail).toContainText('3,500');await expect(detail).toContainText('세부분류 없음');await expect(detail).toContainText('2단계 배달');await capture(page,'02-overview-category-drilldown');await detail.getByRole('button',{name:/세부분류 없음/}).click();await expect(page).toHaveURL(/money\/transactions/);await expect(rows(page)).toHaveCount(1);await expect(rows(page)).toContainText('2단계 대분류 직접');
});
