"use client";
import {useState} from "react";
import type {ChecklistItem,DailyCheck,DietStore,Importance,MeasurementKey} from "@/lib/diet/types";
import {measurements} from "@/lib/diet/types";
import {today,addDays,weekStart,monthStart,monthEnd,daysBetween} from "@/lib/diet/model";
import {WorkLogModal} from "../worklog/WorkLogModal";
import {SortableList} from "./SortableList";
const groups:Importance[]=["CORE","SECONDARY","OPTIONAL"];
export function ResultButtons({check,onChange,disabled,label}:{check:DailyCheck;onChange:(c:DailyCheck)=>void;disabled:boolean;label:string}) {return <span className="diet-results">{(["SUCCESS","FAILURE"] as const).map(s=><button key={s} type="button" disabled={disabled} className={check.state===s?s.toLowerCase():""} aria-label={`${label} ${s==="SUCCESS"?"성공":"실패"}`} aria-pressed={check.state===s} onClick={()=>onChange({...check,state:check.state===s?"MISSING":s})}>{s==="SUCCESS"?"✓":"×"}</button>)}</span>;}
export function ItemEditor({store,item,onClose}:{store:DietStore;item:ChecklistItem;onClose:()=>void}){const [draft,setDraft]=useState(item);return <WorkLogModal titleId="diet-item" title="체크리스트 항목" onClose={onClose}><form className="diet-form" onSubmit={e=>{e.preventDefault();void store.save("items",draft).then(onClose).catch(()=>{});}}><label>항목명<input required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>중요도<select value={draft.importance} onChange={e=>setDraft({...draft,importance:e.target.value as Importance})}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>핵심<textarea value={draft.keyPoint} onChange={e=>setDraft({...draft,keyPoint:e.target.value})}/></label><label>기록 시작일<input type="date" required value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label><div className="diet-columns">{(["weeklyReference","monthlyReference"] as const).map(k=><label key={k}>{k==="weeklyReference"?"주간":"월간"} 기준 성공 횟수<input type="number" min="0" max={k==="weeklyReference"?7:31} step="1" value={draft[k]??""} onChange={e=>setDraft({...draft,[k]:e.target.value===""?null:Number(e.target.value)})}/></label>)}</div><label className="diet-inline"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> 기록에 표시</label>{store.error&&<p role="alert">{store.error}</p>}<button className="primary" disabled={store.busy}>저장</button></form></WorkLogModal>;}
export const newItem=(order:number):ChecklistItem=>({id:crypto.randomUUID(),title:"",importance:"CORE",keyPoint:"",sortOrder:order,weeklyReference:null,monthlyReference:null,active:true,startDate:today()});
function NumberCell({value,label,onSave,disabled}:{value:number|null|undefined;label:string;onSave:(n:number|null)=>void;disabled:boolean}){const [draft,setDraft]=useState<string|null>(null);return <input aria-label={label} type="number" step="any" min="0" disabled={disabled} value={draft??value??""} placeholder="—" onChange={e=>setDraft(e.target.value)} onBlur={e=>{if(draft===null)return;if(!e.currentTarget.validity.valid)return;const n=draft===""?null:Number(draft);if(n!==(value??null))onSave(n);setDraft(null);}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/>;}
export default function Record({store}:{store:DietStore}) {
 const {data}=store;const [view,setView]=useState<"day"|"week"|"month">("week"),[date,setDate]=useState(today),[measurementFilters,setMeasurementFilters]=useState<Importance[]>([...groups]),[checklistFilters,setChecklistFilters]=useState<Importance[]>([...groups]),[mode,setMode]=useState<"records"|"checks">(()=>{if(typeof window==="undefined")return "records";try{return localStorage.getItem("diet.monthMode")==="checks"?"checks":"records";}catch{return "records";}}),[manage,setManage]=useState(false),[item,setItem]=useState<ChecklistItem|null>(null),[settings,setSettings]=useState(false);
 const importance=(key:MeasurementKey)=>data.settings.measurementImportance?.[key]??measurements.find(m=>m[0]===key)![3];
 const measurementVisible=(g:Importance)=>measurementFilters.includes(g);
 const checklistVisible=(g:Importance)=>checklistFilters.includes(g);
 const cols=groups.flatMap(g=>[...measurements].sort((a,b)=>(data.settings.measurementOrder?.indexOf(a[0])??0)-(data.settings.measurementOrder?.indexOf(b[0])??0)).filter(m=>importance(m[0])===g&&measurementVisible(g)));
 const items=groups.flatMap(g=>data.items.filter(i=>i.active&&i.importance===g&&checklistVisible(g)).sort((a,b)=>a.sortOrder-b.sortOrder));
 const day=(d:string)=>data.days.find(r=>r.date===d)??{date:d};
 const check=(d:string,id:string):DailyCheck=>data.checks.find(c=>c.date===d&&c.itemId===id)??{date:d,itemId:id,state:"MISSING",memo:""};
 const saveNumber=(d:string,key:MeasurementKey,n:number|null)=>{void store.saveDay({...day(d),[key]:n}).catch(()=>{});};
 const saveCheck=(c:DailyCheck)=>{void store.saveCheck(c).catch(()=>{});};
 const first=view==="day"?date:view==="week"?weekStart(date):monthStart(date),last=view==="day"?date:view==="week"?addDays(first,6):monthEnd(date);
 function shift(n:number){if(view!=="month")setDate(addDays(date,n*(view==="day"?1:7)));else{const d=new Date(first+"T00:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);setDate(d.toISOString().slice(0,10));}}
 function table(dates:string[],kind:"records"|"checks"){const columns=kind==="records"?cols.map(m=>({id:m[0],label:m[1]+` (${m[2]})`,importance:importance(m[0])})):items.map(i=>({id:i.id,label:i.title,importance:i.importance}));return <div className="diet-table-wrap"><table className="diet-record-table"><thead><tr><th rowSpan={2}>요일 / 날짜</th>{groups.map(g=>{const n=columns.filter(c=>c.importance===g).length;return n?<th key={g} colSpan={n}>{g}</th>:null;})}</tr><tr>{columns.map(c=><th key={c.id} title={items.find(i=>i.id===c.id)?.keyPoint}>{c.label}</th>)}</tr></thead><tbody>{dates.map(d=><tr key={d} className={d===today()?"today":""}><th><button className="diet-date-link" onClick={()=>{setDate(d);setView("day");}}>{new Intl.DateTimeFormat("ko-KR",{weekday:"short",timeZone:"UTC"}).format(new Date(d))} {d.slice(5)}</button></th>{columns.map(c=><td key={c.id}>{kind==="records"?<NumberCell value={day(d)[c.id as MeasurementKey]} label={`${d} ${c.label}`} disabled={store.busy} onSave={n=>saveNumber(d,c.id as MeasurementKey,n)}/>:d<items.find(i=>i.id===c.id)!.startDate||d>today()?<span className="muted">—</span>:<ResultButtons check={check(d,c.id)} onChange={saveCheck} disabled={store.busy} label={`${d} ${c.label}`}/>}</td>)}</tr>)}</tbody></table>{!columns.length&&<p className="diet-empty">표시할 항목이 없습니다. 항목 관리에서 추가하거나 필터를 변경하세요.</p>}</div>;}
 const weeks:string[][]=[];for(const d of daysBetween(first,last)){if(!weeks.length||weekStart(d)!==weekStart(weeks.at(-1)![0]))weeks.push([]);weeks.at(-1)!.push(d);}
 return <><header className="diet-heading"><div><h1>기록</h1><p>매일의 수치와 실천을 한곳에서 기록합니다.</p></div><div className="diet-toolbar"><button onClick={()=>setSettings(true)}>수치 설정</button><button onClick={()=>setManage(true)}>항목 관리</button></div></header><div className="diet-toolbar"><div className="diet-tabs">{(["day","week","month"] as const).map((v,i)=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{["일","주","월"][i]}</button>)}</div><button aria-label="이전 기간" onClick={()=>shift(-1)}>‹</button><strong>{first} {first!==last&&`– ${last}`}</strong><button aria-label="다음 기간" onClick={()=>shift(1)}>›</button><button onClick={()=>setDate(today())}>오늘</button><input aria-label="기준 날짜" type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/>{view==="month"&&<div className="diet-tabs" aria-label="월 보기 내용">{(["records","checks"] as const).map((v,i)=><button key={v} aria-pressed={mode===v} onClick={()=>{setMode(v);try{localStorage.setItem("diet.monthMode",v);}catch{}}}>{["기록","체크리스트"][i]}</button>)}</div>}</div>
 <div className="diet-filter-domains"><ImportanceFilter label="수치" selected={measurementFilters} onChange={setMeasurementFilters}/><ImportanceFilter label="체크리스트" selected={checklistFilters} onChange={setChecklistFilters}/></div>
 {view==="day"?<><h2>수치 기록</h2>{groups.filter(measurementVisible).map(g=><section className="diet-section" key={g}><h3>{g}</h3><div className="diet-measurements">{cols.filter(m=>importance(m[0])===g).map(m=><label key={m[0]}>{m[1]} <small>{m[2]}</small><NumberCell label={`${date} ${m[1]}`} value={day(date)[m[0]]} onSave={n=>saveNumber(date,m[0],n)} disabled={store.busy}/></label>)}</div></section>)}<h2>체크리스트 기록</h2><div className="diet-table-wrap"><table><thead><tr><th>항목명</th><th>핵심</th><th>메모</th><th>결과</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><th>{i.title}<small>{i.importance}</small></th><td>{i.keyPoint||"—"}</td><td><input aria-label={`${i.title} 메모`} key={`${date}-${i.id}-${check(date,i.id).memo}`} defaultValue={check(date,i.id).memo} disabled={store.busy||date>today()||date<i.startDate} onBlur={e=>{if(e.target.value!==check(date,i.id).memo)saveCheck({...check(date,i.id),memo:e.target.value});}}/></td><td><ResultButtons check={check(date,i.id)} disabled={store.busy||date>today()||date<i.startDate} label={i.title} onChange={saveCheck}/></td></tr>)}</tbody></table></div></>:view==="week"?<><h2>수치 기록</h2>{table(daysBetween(first,last),"records")}<h2>체크리스트 기록</h2>{table(daysBetween(first,last),"checks")}</>:weeks.map((w,i)=><section key={w[0]} className="diet-section"><h2>{i+1}주차 <small>{w[0]} – {w.at(-1)}</small></h2>{table(w,mode)}</section>)}
 {manage&&!item&&<WorkLogModal titleId="diet-items" title="체크리스트 항목 관리" onClose={()=>setManage(false)}><div className="diet"><button onClick={()=>setItem(newItem(data.items.length))}>+ 항목 추가</button><SortableList ids={[...data.items].sort((a,b)=>a.sortOrder-b.sortOrder).map(i=>i.id)} onReorder={ids=>void store.reorder("items",ids).catch(()=>{})}>{(id,handle)=>{const i=data.items.find(i=>i.id===id)!;return <div className="diet-manage-row">{handle}<span>{i.title} <small>{i.importance}{!i.active&&" · 숨김"}</small></span><button onClick={()=>setItem(i)}>편집</button></div>;}}</SortableList></div></WorkLogModal>}
 {item&&<ItemEditor store={store} item={item} onClose={()=>setItem(null)}/>}
 {settings&&<MeasurementSettings store={store} onClose={()=>setSettings(false)}/>}
 </>;
}
function MeasurementSettings({store,onClose}:{store:DietStore;onClose:()=>void}){const [draft,setDraft]=useState(store.data.settings);const order=draft.measurementOrder??measurements.map(m=>m[0]);return <WorkLogModal titleId="diet-measurement-settings" title="수치 표시 설정" onClose={onClose}><div className="diet"><SortableList ids={order} onReorder={ids=>setDraft({...draft,measurementOrder:ids as MeasurementKey[]})}>{(id,handle)=>{const m=measurements.find(m=>m[0]===id)!;return <div className="diet-manage-row">{handle}<span>{m[1]}</span><select aria-label={`${m[1]} 중요도`} value={draft.measurementImportance?.[m[0]]??m[3]} onChange={e=>setDraft({...draft,measurementImportance:{...draft.measurementImportance,[id]:e.target.value as Importance}})}>{groups.map(g=><option key={g}>{g}</option>)}</select></div>;}}</SortableList><button disabled={store.busy} onClick={()=>void store.saveSettings(draft).then(onClose).catch(()=>{})}>저장</button></div></WorkLogModal>;}

function ImportanceFilter({label,selected,onChange}:{label:string;selected:Importance[];onChange:(value:Importance[])=>void}){return <div className="diet-toolbar" role="group" aria-label={`${label} 중요도 필터`}><strong>{label}</strong>{groups.map(g=><button key={g} aria-label={`${label} ${g}`} aria-pressed={selected.includes(g)} onClick={()=>onChange(selected.includes(g)?selected.filter(v=>v!==g):[...selected,g])}>{g}</button>)}</div>;}
