import assert from "node:assert/strict";
import {test} from "node:test";
import React,{act} from "react";
import {createRoot} from "react-dom/client";
import {JSDOM} from "jsdom";
import Record from "./Record";
import type {DietStore,Importance,DailyCheck} from "@/lib/diet/types";
import {today} from "@/lib/diet/model";

test("independent section periods, importance filters, multi-select unrecorded and safe deletion",async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:"http://localhost"});
 Object.assign(globalThis,{React,window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
 const noop=async()=>{};const saved:DailyCheck[]=[];const deleted:string[]=[];
 const store:DietStore={data:{days:[],checks:[],goals:[],milestones:[],challenges:[],settings:{},items:(["CORE","SECONDARY","OPTIONAL"] as Importance[]).map((importance,i)=>({id:String(i),title:`item-${importance}`,importance,keyPoint:"",sortOrder:i,weeklyReference:null,monthlyReference:null,active:true,startDate:today()}))},busy:false,error:"",save:noop,remove:async(_,id)=>{deleted.push(id);},saveDay:noop,saveCheck:async check=>{saved.push(check);},saveSettings:noop,reorder:noop,reorderHome:noop};
 const root=createRoot(document.getElementById("root")!);
 const button=(label:string)=>{const b=document.querySelector<HTMLButtonElement>(`button[aria-label="${label}"]`)??[...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===label);assert.ok(b,label);return b;};
 const input=(label:string)=>{const node=document.querySelector<HTMLInputElement>(`input[aria-label="${label}"]`);assert.ok(node,label);return node;};
 await act(()=>root.render(<Record store={store}/>));
 await act(()=>button("수치 OPTIONAL").click());
 assert.equal(button("수치 OPTIONAL").getAttribute("aria-pressed"),"false");
 assert.equal(button("체크리스트 OPTIONAL").getAttribute("aria-pressed"),"true");
 await act(()=>button("체크리스트 SECONDARY").click());
 await act(()=>button("수치 일").click());
 assert.equal(button("체크리스트 주").getAttribute("aria-pressed"),"true");
 await act(()=>button("체크리스트 월").click());
 assert.equal(button("수치 일").getAttribute("aria-pressed"),"true");
 assert.equal(button("수치 OPTIONAL").getAttribute("aria-pressed"),"false");
 const numeric=document.querySelector('section[aria-label="수치 기록"]')!;
 assert.ok(numeric.contains(button("수치 일")));assert.ok(numeric.contains(button("수치 CORE")));
 assert.ok(numeric.textContent?.includes("공복 시간"));assert.ok(!numeric.textContent?.includes("허리둘레"));
 assert.ok(!document.querySelector('section[aria-label="체크리스트 기록"]')!.textContent?.includes("item-SECONDARY"));
 await act(()=>root.render(<Record store={{...store,busy:true}}/>));
 assert.equal(button(`${today()} item-CORE 기록 못함`).disabled,false);
 await act(()=>button(`${today()} item-CORE 기록 못함`).click());assert.equal(saved.at(-1)?.state,"UNRECORDED");
 await act(()=>input(`${today()} item-CORE 선택`).click());await act(()=>input(`${today()} item-OPTIONAL 선택`).click());
 await act(()=>button("선택 기록 못함").click());assert.deepEqual(saved.slice(-2).map(c=>c.itemId),["0","2"]);assert.ok(saved.slice(-2).every(c=>c.state==="UNRECORDED"));
 await act(()=>root.render(<Record store={store}/>));await act(()=>button("항목 관리").click());await act(()=>button("item-CORE 삭제").click());
 assert.equal(deleted.length,0);assert.ok(document.body.textContent?.includes("기존 기록과 통계는 보존"));
 await act(async()=>{button("삭제 확인").click();await new Promise(resolve=>setImmediate(resolve));});assert.deepEqual(deleted,["0"]);
 await act(()=>root.unmount());dom.window.close();
});
