"use client";
import {useMemo,useState} from "react";
import type {ChecklistItem,DietStore,Importance,MeasurementKey} from "@/lib/diet/types";
import {measurements} from "@/lib/diet/types";
import {today,addDays,weekStart,monthStart,monthEnd,daysBetween} from "@/lib/diet/model";
import {WorkLogModal} from "../worklog/WorkLogModal";
import {SortableList} from "./SortableList";
import {ChecklistRecordSection} from "./ChecklistRecord";
const groups:Importance[]=["CORE","SECONDARY","OPTIONAL"];
export function ItemEditor({store,item,onClose}:{store:DietStore;item:ChecklistItem;onClose:()=>void}){const [draft,setDraft]=useState(item);return <WorkLogModal titleId="diet-item" title="체크리스트 항목" onClose={onClose}><form className="diet-form" onSubmit={e=>{e.preventDefault();void store.save("items",draft).then(onClose).catch(()=>{});}}><label>항목명<input required maxLength={200} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>중요도<select value={draft.importance} onChange={e=>setDraft({...draft,importance:e.target.value as Importance})}>{groups.map(g=><option key={g}>{g}</option>)}</select></label><label>핵심<textarea value={draft.keyPoint} onChange={e=>setDraft({...draft,keyPoint:e.target.value})}/></label><label>기록 시작일<input type="date" required value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></label><div className="diet-columns">{(["weeklyReference","monthlyReference"] as const).map(k=><label key={k}>{k==="weeklyReference"?"주간":"월간"} 기준 성공 횟수<input type="number" min="0" max={k==="weeklyReference"?7:31} step="1" value={draft[k]??""} onChange={e=>setDraft({...draft,[k]:e.target.value===""?null:Number(e.target.value)})}/></label>)}</div><label className="diet-inline"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> 활성 (끄면 보관 · 과거 기록 유지)</label>{store.error&&<p role="alert">{store.error}</p>}<button className="primary" disabled={store.busy}>저장</button></form></WorkLogModal>;}
export const newItem=(order:number):ChecklistItem=>({id:crypto.randomUUID(),title:"",importance:"CORE",keyPoint:"",sortOrder:order,weeklyReference:null,monthlyReference:null,active:true,startDate:today()});
function NumberCell({value,label,onSave,disabled}:{value:number|null|undefined;label:string;onSave:(n:number|null)=>void;disabled:boolean}){const [draft,setDraft]=useState<string|null>(null);return <input aria-label={label} type="number" step="any" min="0" disabled={disabled} value={draft??value??""} placeholder="—" onChange={e=>setDraft(e.target.value)} onBlur={e=>{if(draft===null)return;if(!e.currentTarget.validity.valid)return;const n=draft===""?null:Number(draft);if(n!==(value??null))onSave(n);setDraft(null);}} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur();}}/>;}
export default function Record({store}:{store:DietStore}) {
 const [manage,setManage]=useState(false),[item,setItem]=useState<ChecklistItem|null>(null),[settings,setSettings]=useState(false),[removing,setRemoving]=useState<ChecklistItem|null>(null);
 return <>
  <header className="diet-heading"><div><h1>기록</h1><p>매일의 수치와 실천을 한곳에서 기록합니다.</p></div><div className="diet-toolbar"><button onClick={()=>setSettings(true)}>수치 설정</button><button onClick={()=>setManage(true)}>항목 관리</button></div></header>
  <RecordSection store={store} kind="records"/>
  <ChecklistRecordSection store={store}/>
  {manage&&!item&&<WorkLogModal titleId="diet-items" title="체크리스트 항목 관리" onClose={()=>setManage(false)}><div className="diet"><button onClick={()=>setItem(newItem(store.data.items.length))}>+ 항목 추가</button><SortableList ids={[...store.data.items].filter(i=>i.active).sort((a,b)=>a.sortOrder-b.sortOrder).map(i=>i.id)} onReorder={ids=>void store.reorder("items",ids).catch(()=>{})}>{(id,handle)=>{const i=store.data.items.find(i=>i.id===id)!;return <div className="diet-manage-row">{handle}<span>{i.title} <small>{i.importance}</small></span><button onClick={()=>setItem(i)}>편집</button><button aria-label={`${i.title} 삭제`} onClick={()=>setRemoving(i)}>삭제</button></div>;}}</SortableList><h3>보관된 항목</h3>{store.data.items.filter(i=>!i.active).map(i=><div key={i.id} className="diet-manage-row"><span>{i.title} <small>{i.importance} · 보관{(store.data.archivePeriods??[]).find(p=>p.itemId===i.id&&!p.restoredOn)?.archivedOn?` · ${(store.data.archivePeriods??[]).find(p=>p.itemId===i.id&&!p.restoredOn)?.archivedOn}`:""}</small></span><button aria-label={`${i.title} 복원`} disabled={store.busy||!store.restore} onClick={()=>void store.restore?.(i.id).catch(()=>{})}>복원</button></div>)}{!store.data.items.some(i=>!i.active)&&<p>보관된 항목이 없습니다.</p>}</div></WorkLogModal>}
  {removing&&<WorkLogModal titleId="diet-delete-item" title="체크리스트 항목 삭제" onClose={()=>setRemoving(null)}><div className="diet-form"><p>“{removing.title}” 항목을 보관할까요? 현재·이후 기록에서 숨겨지고 기존 기록과 통계는 보존됩니다. 보관 기간은 실패로 집계되지 않으며 항목 관리에서 같은 항목으로 복원할 수 있습니다.</p>{store.error&&<p role="alert">{store.error}</p>}<button onClick={()=>setRemoving(null)}>취소</button><button disabled={store.busy} onClick={()=>void store.remove("items",removing.id).then(()=>setRemoving(null)).catch(()=>{})}>보관(삭제) 확인</button></div></WorkLogModal>}
  {item&&<ItemEditor store={store} item={item} onClose={()=>setItem(null)}/>}
  {settings&&<MeasurementSettings store={store} onClose={()=>setSettings(false)}/>}
 </>;
}

type RecordView="day"|"week"|"month";
function RecordSection({store,kind}:{store:DietStore;kind:"records"}) {
 const {data}=store;
 const label="수치";
 const [view,setView]=useState<RecordView>("week"),[date,setDate]=useState(today),[filters,setFilters]=useState<Importance[]>([...groups]);
 const dayMap=useMemo(()=>new Map(data.days.map(day=>[day.date,day])),[data.days]);
 const importance=(key:MeasurementKey)=>data.settings.measurementImportance?.[key]??measurements.find(m=>m[0]===key)![3];
 const cols=groups.flatMap(g=>[...measurements].sort((a,b)=>(data.settings.measurementOrder?.indexOf(a[0])??0)-(data.settings.measurementOrder?.indexOf(b[0])??0)).filter(m=>importance(m[0])===g&&filters.includes(g)));
 const day=(d:string)=>dayMap.get(d)??{date:d};
 const first=view==="day"?date:view==="week"?weekStart(date):monthStart(date),last=view==="day"?date:view==="week"?addDays(first,6):monthEnd(date);
 const dates=daysBetween(first,last);
 function shift(n:number){if(view!=="month")setDate(addDays(date,n*(view==="day"?1:7)));else{const d=new Date(first+"T00:00:00Z");d.setUTCMonth(d.getUTCMonth()+n);setDate(d.toISOString().slice(0,10));}}
 function table(tableDates:string[]){const columns=cols.map(m=>({id:m[0],label:m[1]+` (${m[2]})`,importance:importance(m[0])}));return <div className="diet-table-wrap"><table className="diet-record-table"><thead><tr><th rowSpan={2}>요일 / 날짜</th>{groups.map(g=>{const n=columns.filter(c=>c.importance===g).length;return n?<th key={g} colSpan={n}>{g}</th>:null;})}</tr><tr>{columns.map(c=><th key={c.id}>{c.label}</th>)}</tr></thead><tbody>{tableDates.map(d=><tr key={d} className={d===today()?"today":""}><th><button className="diet-date-link" onClick={()=>{setDate(d);setView("day");}}>{new Intl.DateTimeFormat("ko-KR",{weekday:"short",timeZone:"UTC"}).format(new Date(d))} {d.slice(5)}</button></th>{columns.map(c=><td key={c.id}><NumberCell value={day(d)[c.id as MeasurementKey]} label={`${d} ${c.label}`} disabled={store.busy} onSave={n=>void store.saveDay({...day(d),[c.id]:n}).catch(()=>{})}/></td>)}</tr>)}</tbody></table>{!columns.length&&<p className="diet-empty">표시할 항목이 없습니다. 항목 관리에서 추가하거나 필터를 변경하세요.</p>}</div>;}
 const weeks:string[][]=[];for(const d of dates){if(!weeks.length||weekStart(d)!==weekStart(weeks.at(-1)![0]))weeks.push([]);weeks.at(-1)!.push(d);}
 return <section className="diet-record-section" aria-label={`${label} 기록`} data-kind={kind}>
  <h2>{label} 기록</h2>
  <div className="diet-toolbar"><div className="diet-tabs" role="group" aria-label={`${label} 기간 필터`}>{(["day","week","month"] as const).map((v,i)=><button key={v} aria-label={`${label} ${["일","주","월"][i]}`} aria-pressed={view===v} onClick={()=>setView(v)}>{["일","주","월"][i]}</button>)}</div><button aria-label={`${label} 이전 기간`} onClick={()=>shift(-1)}>‹</button><strong>{first} {first!==last&&`– ${last}`}</strong><button aria-label={`${label} 다음 기간`} onClick={()=>shift(1)}>›</button><button onClick={()=>setDate(today())}>오늘</button><input aria-label={`${label} 기준 날짜`} type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></div>
  <ImportanceFilter label={label} selected={filters} onChange={setFilters}/>
  {view==="day"?groups.filter(g=>filters.includes(g)).map(g=><div className="diet-section" key={g}><h3>{g}</h3><div className="diet-measurements">{cols.filter(m=>importance(m[0])===g).map(m=><label key={m[0]}>{m[1]} <small>{m[2]}</small><NumberCell label={`${date} ${m[1]}`} value={day(date)[m[0]]} onSave={n=>void store.saveDay({...day(date),[m[0]]:n}).catch(()=>{})} disabled={store.busy}/></label>)}</div></div>):view==="week"?table(dates):weeks.map((w,i)=><div key={w[0]} className="diet-section"><h3>{i+1}주차 <small>{w[0]} – {w.at(-1)}</small></h3>{table(w)}</div>)}
 </section>;
}
function MeasurementSettings({store,onClose}:{store:DietStore;onClose:()=>void}){const [draft,setDraft]=useState(store.data.settings);const order=draft.measurementOrder??measurements.map(m=>m[0]);return <WorkLogModal titleId="diet-measurement-settings" title="수치 표시 설정" onClose={onClose}><div className="diet"><SortableList ids={order} onReorder={ids=>setDraft({...draft,measurementOrder:ids as MeasurementKey[]})}>{(id,handle)=>{const m=measurements.find(m=>m[0]===id)!;return <div className="diet-manage-row">{handle}<span>{m[1]}</span><select aria-label={`${m[1]} 중요도`} value={draft.measurementImportance?.[m[0]]??m[3]} onChange={e=>setDraft({...draft,measurementImportance:{...draft.measurementImportance,[id]:e.target.value as Importance}})}>{groups.map(g=><option key={g}>{g}</option>)}</select></div>;}}</SortableList><button disabled={store.busy} onClick={()=>void store.saveSettings(draft).then(onClose).catch(()=>{})}>저장</button></div></WorkLogModal>;}

function ImportanceFilter({label,selected,onChange}:{label:string;selected:Importance[];onChange:(value:Importance[])=>void}){return <div className="diet-toolbar" role="group" aria-label={`${label} 중요도 필터`}><strong>{label}</strong>{groups.map(g=><button key={g} aria-label={`${label} ${g}`} aria-pressed={selected.includes(g)} onClick={()=>onChange(selected.includes(g)?selected.filter(v=>v!==g):[...selected,g])}>{g}</button>)}</div>;}
