import {randomUUID} from 'node:crypto';
import {test,expect} from '../../helpers/browser.mjs';
test.describe.configure({mode:'serial',timeout:180000});
const base=()=>process.env.QA_API_URL+'/api/money';
async function call(request,url,method='GET',data){const r=await request.fetch(base()+url,{method,data});expect(r.ok(),method+' '+url+' '+r.status()+(r.ok()?'':' '+await r.text())).toBe(true);return r.status()===204?null:r.json();}
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),from=today.slice(0,7)+'-01';
const accounts=[],facts=[];let root,child,other,loan,event,rule,conversation,draft,run;
const books=request=>call(request,`/bookkeeping?from=${from}&to=${today}&kind=EXPENSE&limit=50&offset=0`);
const item=b=>({id:b.id,transactionVersion:b.transactionVersion,overrideVersion:b.version,projectionVersion:b.projectionVersion,classificationVersion:b.classificationVersion??0,categoryId:child.id,directCorrection:true,thisTransactionOnly:false});
const result=o=>{expect(o.status).toBe('APPLIED');return o.result;};
async function open(page,route){await page.goto('/money'+route);await expect(page.locator('.money-main')).toBeVisible();await expect(page.getByText('불러오는 중…',{exact:true})).toHaveCount(0);}
async function shot(page,info,label){await page.screenshot({path:info.outputPath(label+'-synthetic.png'),fullPage:true});}
test.beforeAll(async({request})=>{
 test.setTimeout(180000);
 expect(process.env.QA_SYSTEM).toBe('money-integrated');
 for(let i=0;i<7;i++){let a=await call(request,'/accounts','POST',{provider:'KAKAO',displayName:'통합 검증 계좌 '+i,role:i===1?'SAVINGS':'SPENDING',suffix:String(8100+i)});await call(request,`/accounts/${a.id}/balance-records`,'POST',{type:'INITIAL_BALANCE',amount:500000,asOf:new Date(Date.now()-3600000).toISOString(),note:'Isolated synthetic anchor',expectedVersion:a.version});accounts.push(await call(request,'/accounts/'+a.id));}
 root=await call(request,'/categories','POST',{name:'통합 식사',color:'#336699',archived:false,sortOrder:0,kind:'EXPENSE'});child=await call(request,'/categories','POST',{name:'통합 점심',color:'#336699',archived:false,sortOrder:0,kind:'EXPENSE',parentId:root.id});other=await call(request,'/categories','POST',{name:'통합 교통',color:'#663399',archived:false,sortOrder:0,kind:'EXPENSE'});
 const tracking=await call(request,'/tracking');await call(request,'/tracking','PUT',{expense:[...tracking.expense,accounts[0].id],income:[accounts[0].id],expectedVersion:tracking.version});
 for(let i=0;i<22;i++)facts.push(await call(request,'/transactions','POST',{type:'EXPENSE',fromAccountId:accounts[0].id,toAccountId:null,amount:1000+i,occurredAt:new Date(Date.now()-600000+i*1000).toISOString(),counterpartyText:i<20?'통합 카페':'다른 거래처',title:'통합 점심 '+i,categoryId:null,memo:null,excluded:false}));
 loan=await call(request,'/loans','POST',{name:'통합 검증 대출',lender:'합성 기관',type:'PERSONAL',remainingPrincipal:200000,status:'ACTIVE'});
});
test('money.integrated.cross-01',async({request,page},info)=>{
 const tracking=await call(request,'/tracking'),balances=await call(request,'/account-balances'),prefs=await call(request,'/overview/preferences');
 const layout={layoutVersion:1,rows:[{id:'daily',name:'일상',accountIds:accounts.slice(0,3).map(a=>a.id)},{id:'reserve',name:'예비',accountIds:accounts.slice(3,6).map(a=>a.id)}]};
 await call(request,'/overview/preferences','PUT',{expectedVersion:prefs.version,layout,accountIds:layout.rows.flatMap(r=>r.accountIds)});expect(await call(request,'/tracking')).toEqual(tracking);expect(await call(request,'/account-balances')).toEqual(balances);
 await page.setViewportSize({width:1920,height:1200});await open(page,'');await expect(page.locator('.money-representative-grid>button')).toHaveCount(5);await expect(page.locator('.money-representative-grid').nth(1).locator('button')).toHaveCount(2);await shot(page,info,'overview-five');await page.getByRole('button',{name:'더 보기 1개',exact:true}).click();await expect(page.locator('.money-representative-grid>button')).toHaveCount(6);await shot(page,info,'overview-expanded');
});
test('money.integrated.cross-02',async({request,page,runtimeErrors},info)=>{
 await open(page,'');await page.getByRole('button',{name:/대표 계좌 설정/}).click();const dialog=page.getByRole('dialog',{name:'대표 계좌 배치'});await expect(dialog.locator('.money-representative-order li')).toHaveCount(6);await dialog.locator('.money-representative-order li').first().dragTo(dialog.locator('.money-representative-order li').nth(2));await expect(dialog.locator('.money-representative-order li').first()).toContainText(accounts[1].displayName);await dialog.locator('.money-representative-order li').first().focus();await page.keyboard.press('Alt+ArrowRight');await dialog.getByLabel('1행 이름 (선택)').fill('키보드 초안');
 const prefs=await call(request,'/overview/preferences');await call(request,'/overview/preferences','PUT',{expectedVersion:prefs.version,accountIds:prefs.accountIds,layout:{...prefs.layout,rows:prefs.layout.rows.map((r,i)=>i? r:{...r,name:'다른 기기'})}});await dialog.getByRole('button',{name:'설정 저장',exact:true}).click();await expect(dialog.getByText('최신 저장 배치',{exact:true})).toBeVisible();await expect(dialog.getByLabel('1행 이름 (선택)')).toHaveValue('키보드 초안');await shot(page,info,'layout-conflict');await dialog.getByRole('button',{name:'취소',exact:true}).click();expect((await call(request,'/overview/preferences')).layout.rows[0].name).toBe('다른 기기');const expected=runtimeErrors.filter(e=>e.type==='console'&&e.message.includes('status of 409'));expect(expected).toHaveLength(1);for(const error of expected)runtimeErrors.splice(runtimeErrors.indexOf(error),1);
});
test('money.integrated.cross-03',async({request,page},info)=>{
 const account=await call(request,'/accounts/'+accounts[1].id),prefs=await call(request,'/overview/preferences'),tracking=await call(request,'/tracking');await call(request,`/accounts/${account.id}/fund`,'PUT',{fundGroup:'SAVINGS',savingsSubtype:'INSTALLMENT',expectedVersion:account.version});expect((await call(request,'/accounts/'+account.id)).role).toBe(account.role);expect(await call(request,'/overview/preferences')).toEqual(prefs);expect(await call(request,'/tracking')).toEqual(tracking);
 await open(page,'/accounts');await expect(page.locator('.money-compact-accounts')).toContainText(accounts[0].displayName);await shot(page,info,'accounts');await open(page,'/loans');await expect(page.locator('.money-compact-loans')).toContainText(loan.name);await expect(page.locator('.money-compact-loans')).toContainText('설정 확인 필요');await shot(page,info,'loans');
});
test('money.integrated.cross-04',async({request,page},info)=>{
 const notification=(await call(request,'/notifications','POST',{sourcePackage:'com.kakaobank.channel',notificationKey:randomUUID(),idempotencyKey:randomUUID(),postedAt:new Date().toISOString(),title:'출금 10,000원',text:'입출금통장(8100) → 자유적금(8101) 잔액 467,769원'})).notification;await expect.poll(async()=>(await call(request,'/notifications/'+notification.id)).state).toBe('PROCESSED');
 const cutoff=new Date().toISOString(),url=`/accounts/${accounts[0].id}/reconciliation-snapshot?cutoff=${encodeURIComponent(cutoff)}`,s=await call(request,url);expect(s.items).toHaveLength(10);expect(s.registeredCount).toBeGreaterThanOrEqual(22);expect(s.totalEvidence).toBeGreaterThanOrEqual(22);const next=await call(request,url+'&offset=10&token='+encodeURIComponent(s.token));expect(next.registeredBalance).toBe(s.registeredBalance);expect(next.referenceBalance).toBe(s.referenceBalance);expect(next.items.map(r=>r.id).some(id=>s.items.some(r=>r.id===id))).toBe(false);expect(s.independentVerification).toBe(false);expect(s.status).toBe('REGISTERED_MATCH');expect(s.registeredBalance).toBe(467769);
 await open(page,'/reconciliation?account='+accounts[0].id);await expect(page.getByText('먼저 확인할 내역',{exact:true})).toBeVisible();await shot(page,info,'reconciliation');
 await page.setViewportSize({width:1920,height:800});await page.getByLabel('전체 증빙 검색').fill('통합');await expect(page.locator('.money-reconciliation-table tbody tr')).toHaveCount(10);
 const evidence=s.items.find(e=>e.bookkeepingVisible);expect(evidence).toBeTruthy();await page.getByRole('button',{name:evidence.title,exact:true}).click();await page.getByRole('button',{name:'가계부 분류 확인',exact:true}).click();await expect(page.getByLabel('가계부 제목')).toHaveValue(evidence.title);await page.getByRole('button',{name:'패널 닫기',exact:true}).click();await expect(page.locator('.money-reconciliation-table tr[aria-selected="true"]')).toContainText(evidence.title);
 await page.evaluate(()=>window.scrollTo(0,400));await expect.poll(()=>page.evaluate(()=>window.scrollY)).toBeGreaterThan(100);const position=await page.evaluate(()=>window.scrollY),criteria=await page.locator('.money-asof').textContent();
 // Dispatch the real navigation handler without Playwright scrolling an off-screen sidebar back to zero first. Other scenarios exercise actionable menu clicks.
 await page.locator('.app-sidebar').getByRole('button',{name:'Loans',exact:true}).dispatchEvent('click');await expect(page.locator('.money-compact-loans')).toBeVisible();await page.locator('.app-sidebar').getByRole('button',{name:'잔액 대사',exact:true}).dispatchEvent('click');await expect(page.getByLabel('잔액 점검 계좌')).toHaveValue(accounts[0].id);await expect(page.getByLabel('전체 증빙 검색')).toHaveValue('통합');await expect(page.locator('.money-asof')).toHaveText(criteria);await expect(page.locator('.money-reconciliation-table tr[aria-selected="true"]')).toContainText(evidence.title);await expect.poll(async()=>Math.abs((await page.evaluate(()=>window.scrollY))-position)).toBeLessThan(3);
 let release,started;const held=new Promise(resolve=>release=resolve),entered=new Promise(resolve=>started=resolve),detailURL='**/api/money/transactions/'+evidence.id;await page.route(detailURL,async route=>{started();await held;await route.continue();});try{await page.getByRole('button',{name:'금융 거래 확인',exact:true}).click();await entered;await page.getByLabel('전체 증빙 검색').fill('합성 증빙 없는 검색');await expect(page.getByText('현재 조회에서 이 내역을 확인할 수 없습니다. 선택을 해제하거나 조회 조건을 확인해 주세요.',{exact:true})).toBeVisible();const returned=page.waitForResponse(response=>response.url().endsWith('/transactions/'+evidence.id));release();await returned;await page.evaluate(()=>new Promise(requestAnimationFrame));await expect(page.locator('.money-dock:not(.money-dock-idle)')).toHaveCount(0);}finally{release();await page.unroute(detailURL);}await page.getByRole('button',{name:'선택 해제',exact:true}).click();await page.getByLabel('전체 증빙 검색').fill('');
});
test('money.integrated.cross-05',async({request,page},info)=>{
 await open(page,'/transactions');await expect(page.getByRole('table',{name:'Transactions'})).toBeVisible();await expect(page.locator('.money-classification-cell')).toHaveCount(0);await page.getByRole('button',{name:'통합 점심 0',exact:true}).click();await expect(page.locator('.money-dock[aria-label="거래 수정"]')).toBeVisible();await shot(page,info,'transactions-retained');
 const before=await call(request,'/transactions/'+facts[0].id),b=(await books(request)).items.find(b=>b.id===facts[0].id);result(await call(request,'/ai/classification/edit','POST',{requestId:randomUUID(),id:b.id,transactionVersion:b.transactionVersion,overrideVersion:b.version,projectionVersion:b.projectionVersion,patch:{title:'통합 텍스트 저장',memo:'합성 메모'},resetFields:[]}));const after=await call(request,'/transactions/'+facts[0].id);expect(after).toEqual(before);expect((await books(request)).items.find(b=>b.id===facts[0].id).title).toBe('통합 텍스트 저장');expect((await call(request,'/ai/classification/items/'+b.id)).origin).toBeUndefined();
});
test('money.integrated.cross-06',async({request,page},info)=>{
 const b=(await books(request)).items.find(b=>b.id===facts[0].id),id=randomUUID(),input={requestId:id,items:[item(b)]},saved=result(await call(request,'/ai/classification/save','POST',input));event=saved.items[0].eventId;expect(result(await call(request,'/ai/classification/save','POST',input))).toEqual(saved);expect((await call(request,'/ai/classification/outcomes/'+id)).status).toBe('APPLIED');const reread=(await books(request)).items.find(b=>b.id===facts[0].id);expect(reread.categoryId).toBe(child.id);expect(reread.classificationOrigin).toBe('DIRECT');
 await page.setViewportSize({width:1920,height:1200});await open(page,'/bookkeeping');await expect(page.locator('.money-classification-cell')).not.toHaveCount(0);await shot(page,info,'bookkeeping');
});
test('money.integrated.cross-07',async({request})=>{
 const rows=(await books(request)).items,targets=[rows.find(b=>b.id===facts[1].id),rows.find(b=>b.id===facts[2].id)],inputs=targets.map(item);inputs[1].overrideVersion+=1;const o=await call(request,'/ai/classification/save','POST',{requestId:randomUUID(),items:inputs});expect(o.status).toBe('NOT_APPLIED');for(const b of targets)expect((await call(request,'/ai/classification/items/'+b.id)).version).toBe(0);
 const ok=result(await call(request,'/ai/classification/save','POST',{requestId:randomUUID(),items:targets.map(item)}));expect(ok.completed).toBe(2);expect(ok.items.every(i=>i.classification.origin==='DIRECT')).toBe(true);
});
test('money.integrated.cross-08',async({request,page},info)=>{
 const state=await call(request,'/ai/classification/items/'+facts[0].id);result(await call(request,'/ai/classification/reference-exclusion','POST',{requestId:randomUUID(),id:facts[0].id,expectedVersion:state.version,excluded:true}));const b=(await books(request)).items.find(b=>b.id===facts[0].id);result(await call(request,'/ai/classification/save','POST',{requestId:randomUUID(),items:[item(b)]}));expect((await call(request,'/ai/classification/items/'+b.id)).futureReferenceExcluded).toBe(true);
 await page.setViewportSize({width:1920,height:1200});await open(page,'/review');await expect(page.locator('.money-ai-integrated-ledger')).toBeVisible();await page.locator('.money-ai-integrated-ledger tbody tr').first().click();await shot(page,info,'review');
});
test('money.integrated.cross-09',async({request,page},info)=>{
 const old=await call(request,'/ai/classification/undo-preview','POST',[event]);expect(old.eligibleEventIds).toHaveLength(0);expect(old.excluded[0].reason).toContain('이후');
 const history=await call(request,'/ai/classification/history'),latest=history.items.find(e=>e.transactionId===facts[1].id),preview=await call(request,'/ai/classification/undo-preview','POST',[latest.id]);expect(preview.eligibleEventIds).toEqual([latest.id]);result(await call(request,'/ai/classification/undo','POST',{requestId:randomUUID(),eventIds:preview.eligibleEventIds,fingerprint:preview.fingerprint}));expect((await books(request)).items.find(b=>b.id===facts[1].id).categoryId).toBeNull();
 await open(page,'/classification');await page.getByRole('tab',{name:/자동화|운영/}).click();await expect(page.getByText('자동화·직접 분류 이력',{exact:true})).toBeVisible();await shot(page,info,'history');
});
test('money.integrated.cross-10',async({request,page},info)=>{
 const before=await call(request,'/classification-rules');conversation=result(await call(request,'/ai/workspace/messages','POST',{requestId:randomUUID(),conversationId:null,expectedVersion:0,text:'선택한 합성 거래의 현재 분류 근거를 설명해 주세요.',references:[facts[0].id]})).conversation;expect(conversation.messages).toHaveLength(2);expect(await call(request,'/classification-rules')).toEqual(before);
 await open(page,'/classification');await page.getByRole('tab',{name:/AI 대화/}).click();await expect(page.getByText('저장된 대화',{exact:true})).toBeVisible();await page.getByRole('button',{name:conversation.title,exact:false}).click();await expect(page.getByText(conversation.messages[1].text,{exact:true})).toBeVisible();await shot(page,info,'conversation');await page.reload();await page.getByRole('tab',{name:/AI 대화/}).click();await expect(page.getByRole('button',{name:conversation.title,exact:false})).toBeVisible();await page.getByRole('button',{name:conversation.title,exact:false}).click();await expect(page.getByText(conversation.messages[1].text,{exact:true})).toBeVisible();
});
test('money.integrated.cross-11',async({request,page},info)=>{
 const ruleInput={name:'통합 미래 분류',conditions:[{field:'type',operator:'EXACT',value:'EXPENSE'},{field:'accountId',operator:'EXACT',value:accounts[0].id},{field:'merchant',operator:'EXACT',value:'통합 카페'}],categoryId:child.id,status:'ACTIVE',expectedVersion:0};draft=result(await call(request,'/ai/workspace/drafts','POST',{requestId:randomUUID(),id:null,expectedVersion:0,conversationId:conversation.id,targetRuleId:null,sourceVersion:0,summary:'통합 검증 미적용 초안',rule:ruleInput})).draft;expect((await call(request,'/classification-rules')).some(r=>r.name===ruleInput.name)).toBe(false);const selected=[{id:draft.id,version:draft.version}],preview=await call(request,'/ai/workspace/preview','POST',selected);expect(preview.canApply).toBe(true);const before=await books(request);await page.setViewportSize({width:1920,height:1200});await open(page,'/classification');await page.getByRole('tab',{name:/AI 대화/}).click();await page.getByLabel('통합 검증 미적용 초안',{exact:true}).check();await page.getByRole('button',{name:'선택 1개 변경·영향 검토',exact:true}).click();await expect(page.getByRole('heading',{name:'규칙 변경 검토',exact:true})).toBeVisible();await shot(page,info,'rule-change-review');await page.getByRole('button',{name:'검토한 선택 규칙 함께 승인',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'선택한 규칙 1개를 함께 적용했습니다.'})).toBeVisible();rule=(await call(request,'/classification-rules')).find(r=>r.name===ruleInput.name);expect(rule).toBeTruthy();expect((await books(request)).items.map(b=>[b.id,b.categoryId])).toEqual(before.items.map(b=>[b.id,b.categoryId]));
 await open(page,'/classification');await page.getByRole('tab',{name:/자동 분류 규칙/}).click();await expect(page.getByRole('button',{name:'통합 미래 분류',exact:true})).toBeVisible();await shot(page,info,'rules');
});
test('money.integrated.cross-12',async({request})=>{
 const settings=await call(request,'/ai/settings');await call(request,'/ai/settings','PUT',{automaticRules:true,externalLookup:false,expectedVersion:settings.version});const scope={ruleId:rule.id,ruleVersion:rule.version,from,to:today,accountId:accounts[0].id},preview=await call(request,'/ai/history-runs/preview','POST',scope);expect(preview.eligible).toBeGreaterThan(0);run=result(await call(request,'/ai/history-runs','POST',{requestId:randomUUID(),scope,fingerprint:preview.fingerprint})).run;let value=await call(request,'/ai/history-runs/'+run.id);result(await call(request,'/ai/history-runs/control','POST',{requestId:randomUUID(),id:run.id,expectedVersion:value.run.version,pause:true,retryFailed:false}));value=await call(request,'/ai/history-runs/'+run.id);expect(value.run.status).toBe('PAUSED');result(await call(request,'/ai/history-runs/control','POST',{requestId:randomUUID(),id:run.id,expectedVersion:value.run.version,pause:false,retryFailed:false}));await call(request,'/ai/history-runs/'+run.id+'/advance','POST',{});value=await call(request,'/ai/history-runs/'+run.id);expect(value.run.status).toBe('COMPLETED');expect(value.counts.find(c=>c.status==='APPLIED')?.count).toBeGreaterThan(0);expect((await call(request,'/ai/classification/items/'+facts[0].id)).origin).toBe('DIRECT');
});
test('money.integrated.cross-13',async({request,page},info)=>{
 const before=await call(request,'/transactions/'+facts[3].id),input={requestId:randomUUID(),transactionId:facts[3].id,transactionVersion:before.version,expectedVersion:0,merchantId:null,merchantVersion:null,name:'통합 확인 상호',region:'합성 지점',unlink:false,scope:'ONE_TRANSACTION'},preview=await call(request,'/ai/merchant-links/preview','POST',input);expect(preview.count).toBe(1);result(await call(request,'/ai/merchant-links/apply','POST',{...input,fingerprint:preview.fingerprint}));expect(await call(request,'/transactions/'+facts[3].id)).toEqual(before);const links=await call(request,'/ai/merchant-links');expect(links.items.find(i=>i.id===facts[3].id).name).toBe('통합 확인 상호');expect(links.items.find(i=>i.id===facts[4].id).merchantId).toBeNull();
 await page.setViewportSize({width:1920,height:1200});await open(page,'/classification');await page.getByRole('tab',{name:/거래처/}).click();await expect(page.getByRole('heading',{name:'거래처 분류',exact:true})).toBeVisible();await page.locator('tbody tr').filter({hasText:'통합 확인 상호'}).getByRole('button').click();await expect(page.getByLabel('연결할 거래처')).toHaveValue(links.items.find(i=>i.id===facts[3].id).merchantId);await shot(page,info,'merchants');
});
test('money.integrated.cross-14',async({request,page},info)=>{
 expect((await call(request,'/ai/provider')).enabled).toBe(false);const before=await call(request,'/transactions/'+facts[0].id);await page.setViewportSize({width:1440,height:1000});await open(page,'/bookkeeping');await expect(page.locator('.money-shell')).toHaveClass(/money-drawer-mode/);await shot(page,info,'bookkeeping-small-laptop');await page.setViewportSize({width:1920,height:1200});await expect(page.locator('.money-shell')).toHaveClass(/money-rail-mode/);expect(Math.round((await page.locator('.money-dock').boundingBox()).width)).toBe(300);await page.setViewportSize({width:480,height:1000});await open(page,'/bookkeeping');await expect(page.locator('.money-table-wrap').first()).toBeVisible();await shot(page,info,'bookkeeping-narrow');await open(page,'/review');await expect(page.locator('.money-ai-integrated-ledger')).toBeVisible();await shot(page,info,'review-narrow');await open(page,'/classification');await page.getByRole('tab',{name:/AI 대화/}).click();await expect(page.getByText('미적용 초안',{exact:true}).first()).toBeVisible();await shot(page,info,'conversation-narrow');expect(await call(request,'/transactions/'+facts[0].id)).toEqual(before);
});
