export type PlannedStatus = "WORK" | "DAY_OFF" | "ANNUAL_LEAVE" | "SICK_LEAVE";

export const PLANNED_STATUSES: PlannedStatus[] = ["WORK", "DAY_OFF", "ANNUAL_LEAVE", "SICK_LEAVE"];

// Fully resolved plan for a date: overrides applied on top of yearly defaults.
export interface EffectiveWorkSchedule {
  workDate: string; // yyyy-MM-dd
  plannedStatus: PlannedStatus;
  plannedStartTime: string | null; // HH:mm:ss
  graceMinutes: number | null;
  targetDurationMinutes: number | null;
  memo: string | null;
}

// Raw stored override for a date. A null field means "inherit from WorkSettings".
export interface WorkScheduleOverride {
  workDate: string;
  plannedStatus: PlannedStatus | null;
  plannedStartTime: string | null;
  graceMinutes: number | null;
  targetDurationMinutes: number | null;
  memo: string | null;
}

export interface WorkScheduleOverrideInput {
  plannedStatus: PlannedStatus | null;
  plannedStartTime: string | null;
  graceMinutes: number | null;
  targetDurationMinutes: number | null;
  memo: string | null;
}

// The canonical user-owned category, shared across Planning, Work Log
// work-time entries, the future time calendar, and future plan-versus-actual
// analytics — not a Planning-only concept, despite living in this file next
// to Planning-specific types today.
export interface ActivityCategory {
  id: string;
  name: string;
  parentId: string | null;
  sortOrder: number;
  isActive: boolean;
  isDefault: boolean;
}

export interface ActivityCategoryInput {
  name: string;
  parentId: string | null;
}

// Work Log — StartTimeCriterion (backend: com.kafka.backend.starttimecriterion)

export interface StartTimeCriterionDto {
  id: string;
  name: string;
  startTime: string; // "HH:mm:ss"
  isActive: boolean;
  sortOrder: number;
  /** Minutes of lateness grace on top of startTime — see docs/backend/start-time-criteria.md. */
  graceMinutes: number;
}

// Shared by create and update — isActive is ignored server-side on create.
// graceMinutes: null defaults to 0 server-side (matching every pre-existing criterion's behavior).
export interface StartTimeCriterionInput {
  name: string;
  startTime: string; // "HH:mm" or "HH:mm:ss"
  isActive: boolean | null;
  graceMinutes: number | null;
}

// Work Log — WorkRecord / WorkTimeEntry (backend: com.kafka.backend.workrecord / worktimeentry)

export type WorkAttendanceStatus = "WORK" | "EARLY_LEAVE" | "DAY_OFF" | "PAID_LEAVE" | "SICK_LEAVE" | "ABSENT";

export interface WorkTimeEntryDto {
  id: string;
  categoryId: string;
  item: string;
  minutes: number;
  memo: string | null;
  position: number;
}

// One line of WorkRecordRequest.workTimeEntries — id is null for a brand-new
// row; a non-null id matching one of the record's own current rows updates
// that row in place (identity preserved). List order is the position.
export interface WorkTimeEntryItemInput {
  id: string | null;
  categoryId: string;
  item: string;
  minutes: number;
  memo: string | null;
}

export interface WorkRecordDto {
  id: string;
  workDate: string; // "yyyy-MM-dd"
  status: WorkAttendanceStatus;
  clockIn: string | null; // "HH:mm:ss"
  clockOut: string | null;
  basicWorkMinutes: number | null;
  workLocation: string | null;
  workScore: number | null;
  memo: string | null;
  appliedCriterionId: string | null;
  appliedCriterionName: string | null;
  appliedStartTime: string | null; // "HH:mm:ss"
  /** The grace period (minutes) frozen alongside appliedStartTime at the
   *  moment the criterion was applied — null when no criterion is applied,
   *  or when this record predates the grace-period feature (treated as 0
   *  by every lateness calculation either way). */
  appliedGraceMinutes: number | null;
  /** null = not applicable. 0 = on time (within the grace-adjusted
   *  threshold). positive = minutes late beyond it. Raw — never
   *  pre-combined with isOnTimeOverride. */
  latenessMinutes: number | null;
  isOnTimeOverride: boolean;
  absenceAutoGenerated: boolean;
  absenceCorrectedAt: string | null;
  version: number;
  workTimeEntries: WorkTimeEntryDto[];
  netWorkMinutes: number;
}

// Full-state upsert body for PUT /api/work-records/{date} and
// POST /api/work-records/{date}/absence-correction. expectedVersion is
// required and checked when a record already exists for that date;
// irrelevant (send null) on first creation.
export interface WorkRecordInput {
  status: WorkAttendanceStatus;
  clockIn: string | null; // "HH:mm"
  clockOut: string | null;
  workLocation: string | null;
  workScore: number | null;
  memo: string | null;
  appliedCriterionId: string | null;
  expectedVersion: number | null;
  workTimeEntries: WorkTimeEntryItemInput[];
  isOnTimeOverride: boolean | null;
}

// Body for the dedicated clock-in/clock-out/clock-times-clear action
// endpoints — these only ever operate on an already-existing record.
export interface WorkRecordActionInput {
  expectedVersion: number | null;
}

export interface PlannedTimeBlock {
  id: string;
  title: string;
  startAt: string; // yyyy-MM-ddTHH:mm:ss, naive Asia/Seoul wall-clock
  endAt: string;
  categoryId: string | null;
  memo: string | null;
}

export interface PlannedTimeBlockInput {
  title: string;
  startAt: string;
  endAt: string;
  categoryId: string | null;
  memo: string | null;
}
