import {test} from 'node:test';
import assert from 'node:assert/strict';
import {actionBody,candidates,draftOf,resolve,readSaved,writeSaved,storageKey,type Endpoint,type Session} from './model';
import {tabTarget,restoreTabs} from '../globalTabs';
const data=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v),removeItem:(k:string)=>data.delete(k)}});
const ep=(date:string,time:string,zone:string,offset=''):Endpoint=>({date,time,zone,offset,known:true});
test('DST gaps are rejected and both fold offsets require an explicit choice',()=>{
 assert.deepEqual(candidates(ep('2025-03-09','02:30','America/New_York')),[]);
 const fold=ep('2025-11-02','01:30','America/New_York');assert.equal(candidates(fold).length,2);assert.throws(()=>resolve(fold));assert.equal(resolve({...fold,offset:'-240'})?.at,'2025-11-02T05:30:00.000Z');assert.equal(resolve({...fold,offset:'-300'})?.at,'2025-11-02T06:30:00.000Z');
});
test('invalid calendar dates and timezone names do not normalize silently',()=>{assert.throws(()=>resolve(ep('2025-02-30','12:00','UTC')));assert.throws(()=>resolve(ep('2025-01-01','12:00','Invalid/Zone')));});
const session:Session={id:crypto.randomUUID(),revision:7,bedtimeIntentAt:'2025-10-01T14:00:42Z',wakeAt:'2025-10-01T22:00:12Z',bedtimeTimezone:'Asia/Seoul',wakeTimezone:'Asia/Seoul',bedtimeOffsetMinutes:540,wakeOffsetMinutes:540,bedtimeCertainty:'REPORTED_NOW',bedtimeSource:'USER_TAP',logicalWakeDate:'2025-10-02',expectedWakeDate:'2025-10-02',status:'CLOSED',excludedAt:null,intervalMinutes:479.5};
test('correction sends only changed endpoint and preserves untouched seconds and provenance',()=>{const d=draftOf('main',session,'2025-10-02');d.end.time='07:05';d.end.offset='';const a=actionBody(d,'Asia/Seoul');assert.equal(a.entryPoint,'HISTORY_EDIT');assert.equal(a.expectedRevision,7);const p=a.payload as {fields:Record<string,string>;fieldCertainties:Record<string,string>};assert.deepEqual(Object.keys(p.fields),['wakeAt']);assert.equal(p.fieldCertainties.wakeAt,'RECALLED');});
test('incomplete endpoints remain missing instead of synthesized zero duration',()=>{const d=draftOf('main',{...session,wakeAt:null,status:'INCOMPLETE',intervalMinutes:null},'2025-10-02');d.start.time='23:05';assert.deepEqual(Object.keys((actionBody(d,'UTC').payload as {fields:object}).fields),['bedtimeIntentAt']);});
test('mixed zones and confirmed intervals exceeding 24h work',()=>{const d=draftOf('nap',null,'2025-10-01');d.start=ep('2025-10-01','00:00','UTC');d.end=ep('2025-10-02','11:00','Asia/Seoul');assert.throws(()=>actionBody(d,'UTC'),/LONG_INTERVAL/);const a=actionBody(d,'UTC',true);assert.equal(a.actionType,'CREATE_NAP');assert.equal((a.payload as Record<string,unknown>).endAt,'2025-10-02T02:00:00.000Z');});
test('drafts and exact pending bodies are owner-scoped and token free',()=>{const d=draftOf('nap',null,'2025-10-01');const pending={path:'/naps/actions',method:'POST',body:{operationId:'same',payload:{startAt:'kept'}}};writeSaved('A',{draft:d,settings:null,pending});assert.deepEqual(readSaved('A')?.pending,pending);assert.equal(readSaved('B'),null);assert.ok(!data.get(storageKey('A'))!.includes('Bearer'));});
test('Sleep deep links retain only valid route context; default titles migrate without changing IDs or pins',()=>{assert.equal(tabTarget('/life/sleep/records?date=2025-02-30&view=bogus&kind=nap&token=secret')?.route,'/life/sleep/records?kind=nap');assert.equal(tabTarget('/life/sleep/settings?date=2025-01-01&draft=private')?.route,'/life/sleep/settings');const s=restoreTabs(JSON.stringify({version:1,activeTabId:'old',tabs:[{tabId:'old',pinned:true,route:'/life/categories',title:'LIFE CODE · 카테고리'},{tabId:'custom',route:'/life/categories',title:'내 생활'}]}));assert.equal(s.tabs[0].title,'LIFE OS · 카테고리');assert.equal(s.tabs[0].tabId,'old');assert.equal(s.tabs[0].pinned,true);assert.equal(s.tabs[1].title,'내 생활');});
