"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { usePathname, useSearchParams } from "next/navigation";
import { Moon, List, ChartColumnBig, Settings as SettingsIcon, Tags, LayoutDashboard } from "lucide-react";
import { SharedSidebar } from "@/components/Sidebar";
import { useGlobalTabs, useShellNavigationGuard } from "@/components/GlobalTabs";
import { apiClient, ApiError } from "@/lib/api/client";
import { actionBody, candidates, changed, clockTime, draftOf, duration, envelope, localParts, readSaved, resolve, storageKey, writeSaved, type Draft, type Endpoint, type Metrics, type Nap, type NapSummary, type Pending, type Receipt, type Session, type Settings, type Today } from "@/lib/sleep/model";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { isAuthRequired } from "@/lib/supabase/env";
import "./sleep.css";

const prefix="/api/sleep/v1";
const pages=[{path:"/life/sleep",label:"개요",icon:LayoutDashboard},{path:"/life/sleep/records",label:"기록",icon:List},{path:"/life/sleep/statistics",label:"통계",icon:ChartColumnBig},{path:"/life/sleep/settings",label:"설정",icon:SettingsIcon}];
const addDay=(date:string,days:number)=>new Date(Date.parse(date+"T12:00:00Z")+days*86400000).toISOString().slice(0,10);
const labels:Record<string,string>={OPEN:"진행 중",CLOSED:"완료",INCOMPLETE:"보완 필요",complete:"완료",partial:"미완료",missing:"누락",unknown:"모름",excluded:"집계 제외",currentPendingDays:"기록 대기",NOT_TRACKED:"기록 시작 전"};
function recordRange(kind:"main"|"nap",record:Session|Nap){const n=record as Nap,s=record as Session;const text=(at:string|null,zone?:string)=>{if(!at)return "미기록";const p=localParts(at,zone??"Asia/Seoul");return `${p.date} ${p.time} (${zone??"Asia/Seoul"})`;};return kind==="nap"?`${text(n.startAt,n.startTimezone)} → ${text(n.endAt,n.endTimezone)}`:`${text(s.bedtimeIntentAt,s.bedtimeTimezone)} → ${text(s.wakeAt,s.wakeTimezone)}`;}
function Timeline({record,date,zone,onClick}:{record:Session;date:string;zone:string;onClick:()=>void}){
 const position=(at:string|null)=>{if(!at)return null;const p=localParts(at,zone);return (Date.parse(`${p.date}T${p.time}:00Z`)-Date.parse(addDay(date,-1)+"T18:00:00Z"))/864000;};
 const start=position(record.bedtimeIntentAt),end=position(record.wakeAt),known=start??end;
 if(known===null)return <button className="sleep-timeline-item" onClick={onClick}>시각 모름 · 상세</button>;
 const both=start!==null&&end!==null,top=Math.max(0,Math.min(98,both?start:known)),height=both?Math.max(2,Math.min(100,end)-Math.max(0,start)):2;
 return <button className={`sleep-timeline-item ${both?"":"sleep-point"}`} style={{top:`${top}%`,height:both?`${height}%`:undefined}} onClick={onClick} title={recordRange("main",record)}><span>{both?duration(record.intervalMinutes):record.status==="OPEN"?"● 진행 중":"● 미완료"}</span><span>{start!==null&&start<0?"↑ 이전 날짜":""}{end!==null&&end>100?" ↓ 이후 날짜":""}</span></button>;
}
function Modal({title,children,close}:{title:string;children:React.ReactNode;close:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current!,previous=document.activeElement as HTMLElement|null;dialog.showModal();return()=>{dialog.close();previous?.focus();};},[]);
 return <dialog ref={ref} className="sleep-dialog" onCancel={e=>{e.preventDefault();close();}} aria-labelledby="sleep-dialog-title"><h2 id="sleep-dialog-title">{title}</h2>{children}<button onClick={close}>계속 편집</button></dialog>;
}
function TimeInput({label,value,set,nap,disabled}:{label:string;value:Endpoint;set:(v:Endpoint)=>void;nap:boolean;disabled:boolean}){
 let offsets:{at:string;offset:number}[]=[];try{if(value.known&&value.date&&value.time)offsets=candidates(value);}catch{/* Validation remains inline on save. */}
 return <fieldset className="sleep-endpoint" disabled={disabled}><legend>{label}</legend>{!nap&&<label className="sleep-check"><input type="checkbox" checked={value.known} onChange={e=>set({...value,known:e.target.checked})}/>시각 입력 (해제하면 모름)</label>}
 <div className="sleep-fields"><label>날짜<input aria-label={`${label} 날짜`} type="date" value={value.date} disabled={!value.known&&!nap} onChange={e=>set({...value,date:e.target.value,known:nap||value.known,offset:""})}/></label><label>시각<input aria-label={`${label} 시각`} type="time" value={value.time} disabled={!value.known&&!nap} onChange={e=>set({...value,time:e.target.value,known:nap||value.known,offset:""})}/></label></div>
 <label>시간대 (IANA)<input aria-label={`${label} 시간대`} value={value.zone} disabled={!value.known&&!nap} onChange={e=>set({...value,zone:e.target.value,offset:""})} placeholder="Asia/Seoul"/></label>
 {offsets.length>1&&<label>중복 시각 UTC offset<select aria-label={`${label} UTC offset`} value={value.offset} onChange={e=>set({...value,offset:e.target.value})}><option value="">선택해주세요</option>{offsets.map(x=><option key={x.offset} value={String(x.offset)}>{x.offset>=0?"+":""}{x.offset}분 ({x.at})</option>)}</select></label>}
 </fieldset>;
}
function RecordText({kind,record}:{kind:"main"|"nap";record:Session|Nap}){const n=record as Nap,s=record as Session;return <><strong>{kind==="nap"?n.startLocalDate:s.logicalWakeDate??s.expectedWakeDate}</strong><span>{kind==="nap"?"낮잠":s.excludedAt?"집계 제외":labels[s.status]}</span><span>{duration(record.intervalMinutes)}</span><span>{recordRange(kind,record)}</span></>;}
export default function SleepWorkspace(){
 const path=usePathname(),params=useSearchParams(),shell=useGlobalTabs();const page=pages.find(x=>x.path===path)??pages[0];
 const [zone,setZone]=useState("Asia/Seoul"),[date,setDate]=useState(()=>/^\d{4}-\d{2}-\d{2}$/.test(params.get("date")??"")&&Number.isFinite(Date.parse(params.get("date")!))&&new Date(params.get("date")!).toISOString().slice(0,10)===params.get("date")?params.get("date")!:localParts(new Date().toISOString(),"Asia/Seoul").date);
 const [kind,setKind]=useState<"main"|"nap">(params.get("kind")==="nap"?"nap":"main"),[view,setView]=useState(params.get("view")==="list"?"list":"calendar"),[period,setPeriod]=useState(params.get("period")==="30d"?"30d":"7d");
 const [today,setToday]=useState<Today|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[summary,setSummary]=useState<NapSummary|null>(null),[sessions,setSessions]=useState<Session[]>([]),[naps,setNaps]=useState<Nap[]>([]);
 const [draft,setDraft]=useState<Draft|null>(null),[settingDraft,setSettingDraft]=useState<Settings|null>(null),[pending,setPending]=useState<Pending|null>(null),[error,setError]=useState(""),[detailError,setDetailError]=useState<Record<string,unknown>|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[includeExcluded,setIncludeExcluded]=useState(false),[online,setOnline]=useState(true);
 const [leave,setLeave]=useState<(()=>void)|null>(null),[confirm,setConfirm]=useState<"delete"|"long"|null>(null),[undo,setUndo]=useState<{receipt:Receipt;until:number}|null>(null),[events,setEvents]=useState<{items:Record<string,unknown>[];nextCursor:string|null}|null>(null);
 const owner=useRef<string|null>(null),epoch=useRef(0),saving=useRef(false),initialized=useRef(false);
 const state=useRef({draft,settingDraft,pending});state.current={draft,settingDraft,pending};const originalDraft=draft?.original?draftOf(draft.kind,draft.original,date):null;
 const draftDirty=!!draft&&(originalDraft?(changed(draft.start,originalDraft.start)||changed(draft.end,originalDraft.end)):(draft.start.known||draft.end.known||!!draft.start.time||!!draft.end.time));
 const dirty=draftDirty||!!settingDraft||!!pending;
 useEffect(()=>{if(path.endsWith("records")){const requested=params.get("date");if(requested&&/^\d{4}-\d{2}-\d{2}$/.test(requested)&&Number.isFinite(Date.parse(requested))&&new Date(requested).toISOString().slice(0,10)===requested)setDate(requested);setKind(params.get("kind")==="nap"?"nap":"main");setView(params.get("view")==="list"?"list":"calendar");}if(path.endsWith("statistics"))setPeriod(params.get("period")==="30d"?"30d":"7d");},[path,params]);
 const read=useCallback(<T,>(route:string)=>apiClient.scoped<T>(owner.current!,prefix+route),[]);
 const refresh=useCallback(async()=>{
  const generation=++epoch.current;setLoading(true);
  try{
   const t=await apiClient.get<Today>(prefix+"/today?timezone="+encodeURIComponent(zone));
   if(generation!==epoch.current)return;
   if(owner.current&&owner.current!==t.ownerId){setDraft(null);setSettingDraft(null);setPending(null);setToday(null);setSessions([]);setNaps([]);setMetrics(null);setSummary(null);setEvents(null);setUndo(null);setDetailError(null);initialized.current=false;setNotice("로그인 사용자가 변경되어 이전 계정 입력을 분리했습니다.");}
   owner.current=t.ownerId;
   if(!initialized.current){const saved=readSaved(t.ownerId);if(saved){setDraft(saved.draft);setSettingDraft(saved.settings);setPending(saved.pending);setNotice("이 계정에 보관한 입력을 복원했습니다. 저장 대기 요청은 직접 재시도해주세요.");}initialized.current=true;}
   const from=addDay(date,-6),to=date;
   async function all<T>(route:string){const rows:T[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const r: {items:T[];nextCursor:string|null}=await read<{items:T[];nextCursor:string|null}>(`${route}?from=${from}&to=${to}&limit=100&includeExcluded=${includeExcluded}${cursor?"&cursor="+encodeURIComponent(cursor):""}`);rows.push(...r.items);cursor=r.nextCursor;if(cursor){if(seen.has(cursor))throw Error("목록 커서가 반복되었습니다. 다시 조회해주세요.");seen.add(cursor);}}while(cursor);return rows;}
   const [m,main,nap]=await Promise.all([read<Metrics>(`/metrics?window=${path==="/life/sleep"?"7d":period}&timezone=${encodeURIComponent(zone)}`),all<Session>("/sessions"),all<Nap>("/naps")]);
   const n=await read<NapSummary>(`/naps/summary?from=${m.from}&to=${m.to}&timezone=${encodeURIComponent(zone)}`);
   if(generation!==epoch.current||owner.current!==t.ownerId)return;
   setToday(t);setMetrics(m);setSummary(n);setSessions(main.filter(s=>!t.deletedSessionIds.includes(s.id)));setNaps(nap);setError("");
  }catch(e){if(generation===epoch.current)setError(e instanceof Error?e.message:"조회하지 못했습니다.");}finally{if(generation===epoch.current)setLoading(false);}
 },[date,includeExcluded,path,period,read,zone]);
 useEffect(()=>{void refresh();return()=>{epoch.current++;};},[refresh]);
 useEffect(()=>{if(!isAuthRequired())return;const client=createSupabaseBrowserClient();if(!client)return;const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>{if(!owner.current||session?.user.id===owner.current)return;++epoch.current;owner.current=null;initialized.current=false;state.current={draft:null,settingDraft:null,pending:null};setDraft(null);setSettingDraft(null);setPending(null);setToday(null);setSessions([]);setNaps([]);setMetrics(null);setSummary(null);setEvents(null);setUndo(null);setLeave(null);setConfirm(null);setDetailError(null);setError("");setNotice("로그인 사용자가 변경되어 이전 계정 입력을 분리했습니다.");if(session)setTimeout(()=>void refresh(),0);});return()=>subscription.unsubscribe();},[refresh]);
 useEffect(()=>{const focus=()=>{if(!saving.current)void refresh();};const connectivity=()=>setOnline(navigator.onLine);connectivity();window.addEventListener("focus",focus);window.addEventListener("online",connectivity);window.addEventListener("offline",connectivity);return()=>{window.removeEventListener("focus",focus);window.removeEventListener("online",connectivity);window.removeEventListener("offline",connectivity);};},[refresh]);
 useEffect(()=>{if(owner.current&&initialized.current)try{if(dirty)writeSaved(owner.current,{draft,settings:settingDraft,pending});else localStorage.removeItem(storageKey(owner.current));}catch{setNotice("브라우저 저장소를 사용할 수 없습니다. 새로고침 전에 서버에 저장해주세요.");}},[draft,settingDraft,pending,dirty]);
 useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",unload);return()=>window.removeEventListener("beforeunload",unload);},[dirty]);
 useEffect(()=>{if(!undo)return;const timer=setTimeout(()=>setUndo(null),Math.max(0,undo.until-Date.now()));return()=>clearTimeout(timer);},[undo]);
 useShellNavigationGuard(proceed=>{if(dirty)setLeave(()=>proceed);else proceed();});
 function navigate(href:string){shell?.navigate(href);}
 function edit(next:Draft){if(dirty){setLeave(()=>()=>{setDraft(next);setSettingDraft(null);setEvents(null);setError("");setDetailError(null);});return;}setDraft(next);setEvents(null);setError("");setDetailError(null);}
 async function select(k:"main"|"nap",id:string){const selectedOwner=owner.current,generation=epoch.current;try{const canonical=await read<Session|Nap>(k==="main"?"/sessions/"+id:"/naps/"+id);if(selectedOwner!==owner.current||generation!==epoch.current)return;edit(draftOf(k,canonical,date));}catch(e){setError((e as Error).message);}}
 async function send(request:Pending):Promise<boolean>{
  if(saving.current||!owner.current)return false;const writer=owner.current;saving.current=true;setBusy(true);setError("");setNotice("");setDetailError(null);++epoch.current;
  try{
   // Persist exact operation/body before transport, including response loss and auth expiry.
   writeSaved(writer,{draft:state.current.draft,settings:state.current.settingDraft,pending:request});setPending(request);
   const receipt=await apiClient.scoped<Receipt>(writer,prefix+request.path,request.method,request.body);
   if(owner.current!==writer)return false;
   if(request.body.actionType){const expectedId=request.body.napId??request.body.sessionId;const receivedId=receipt.napId??receipt.sessionId;if(receipt.operationId!==request.body.operationId||expectedId!==receivedId||!Number.isInteger(receipt.newRevision))throw Error("저장 응답을 확인하지 못했습니다. 정확한 요청을 재시도해주세요.");}
   if(receipt.deleted)setUndo(null);
   if(request.body.actionType==="CORRECT_SESSION"&&draft?.original&&receipt.eventId&&!receipt.deleted)setUndo({receipt,until:Date.now()+8000});
   setDraft(null);setSettingDraft(null);setPending(null);state.current={draft:null,settingDraft:null,pending:null};localStorage.removeItem(storageKey(owner.current));setEvents(null);setNotice(receipt.deleted?"기록을 삭제했습니다.":"서버에 저장했습니다.");await refresh();return true;
  }catch(e){if(owner.current!==writer)return false;setError((e as Error).message);if(e instanceof ApiError){setDetailError(e.details);if(e.status>=400&&e.status<500&&e.status!==401){setPending(null);try{writeSaved(owner.current!,{draft:state.current.draft,settings:state.current.settingDraft,pending:null});}catch{/* Current draft stays in memory. */}}}return false;
  }finally{saving.current=false;setBusy(false);}
 }
 async function save(confirmed=false):Promise<boolean>{
  if(pending)return send(pending);if(!today)return false;
  try{
   if(settingDraft)return send({path:"/reminder-settings?timezone="+encodeURIComponent(zone),method:"PUT",body:{operationId:crypto.randomUUID(),expectedRevision:settingDraft.revision,bedtime:settingDraft.bedtime,wake:settingDraft.wake}});
   if(!draft||!draftDirty)return true;const body=actionBody(draft,zone,confirmed);return send({path:draft.kind==="nap"?"/naps/actions":"/actions",method:"POST",body});
  }catch(e){if((e as Error).message==="LONG_INTERVAL"){setConfirm("long");return false;}setError((e as Error).message);return false;}
 }
 async function reapply(){if(saving.current||(!draft&&!settingDraft))return;saving.current=true;setBusy(true);const writer=owner.current,generation=epoch.current;try{
  if(settingDraft){const current=await read<Settings>("/reminder-settings");if(writer!==owner.current||generation!==epoch.current)return;setSettingDraft({...settingDraft,revision:current.revision});}
  else if(draft){if(!draft.original){setDetailError(null);setError("생성 충돌은 겹치는 기록을 먼저비교한 뒤 시각을 수정해주세요.");return;}const current=await read<Session|Nap>((draft.kind==="main"?"/sessions/":"/naps/")+draft.id);if(writer!==owner.current||generation!==epoch.current)return;const base=draftOf(draft.kind,draft.original,date),latest=draftOf(draft.kind,current,date);setDraft({...draft,original:current,start:changed(draft.start,base.start)?draft.start:latest.start,end:changed(draft.end,base.end)?draft.end:latest.end});}
  setPending(null);setDetailError(null);setError("");setNotice("내 입력을 유지하고 최신 revision을 가져왔습니다. 내용을 확인한 뒤 새 요청으로 저장해주세요.");
 }catch(e){setError((e as Error).message);}finally{saving.current=false;setBusy(false);}}
 function discard(){if(pending){setError("응답이 확인되지 않은 요청이 있습니다. 정확한 요청을 재시도한 뒤 진행해주세요.");return;}setDraft(null);setSettingDraft(null);setEvents(null);setError("");setDetailError(null);if(owner.current)localStorage.removeItem(storageKey(owner.current));}
 async function remove(){if(!draft?.original)return;setConfirm(null);await send({path:draft.kind==="nap"?"/naps/actions":"/actions",method:"POST",body:envelope(draft.kind==="nap"?"DELETE_NAP":"DELETE_SESSION",draft.id,draft.original.revision,zone,{},draft.kind)});}
 async function undoEdit(){if(!undo||Date.now()>undo.until)return;const u=undo;setUndo(null);await send({path:"/actions",method:"POST",body:envelope("UNDO_EVENT",u.receipt.sessionId!,u.receipt.newRevision,zone,{targetEventId:u.receipt.eventId})});}
 function context(next:{date?:string;view?:string;kind?:"main"|"nap";period?:string}){if(dirty){setLeave(()=>()=>contextApply(next));return;}contextApply(next);}
 function contextApply(next:{date?:string;view?:string;kind?:"main"|"nap";period?:string}){if(next.date)setDate(next.date);if(next.kind)setKind(next.kind);if(next.view)setView(next.view);if(next.period)setPeriod(next.period);const q=new URLSearchParams(path.endsWith("records")?{date:next.date??date,kind:next.kind??kind,view:next.view??view}:path.endsWith("statistics")?{period:next.period??period}:{});window.history.replaceState(null,"",path+(q.size?"?"+q:""));}
 const records=kind==="main"?sessions:naps;const dates=Array.from({length:7},(_,i)=>addDay(date,i-6));
 let preview:number|null=null;try{if(draft){const s=originalDraft&&!changed(draft.start,originalDraft.start)?draft.kind==="nap"?(draft.original as Nap).startAt:(draft.original as Session).bedtimeIntentAt:resolve(draft.start)?.at,e=originalDraft&&!changed(draft.end,originalDraft.end)?draft.kind==="nap"?(draft.original as Nap).endAt:(draft.original as Session).wakeAt:resolve(draft.end)?.at;if(s&&e)preview=(Date.parse(e)-Date.parse(s))/60000;}}catch{/* Save displays validation detail. */}
 const napPanel=summary&&<section className="sleep-panel"><h2>낮잠 별도 집계</h2><div className="sleep-row"><strong>{summary.count}건</strong><span>보고 간격 합계 {duration(summary.totalIntervalMinutes)}</span><span>평균 {duration(summary.meanIntervalMinutes)}</span></div><p>주수면 평균·커버리지·OPS 지표에 합산하지 않습니다.</p><button onClick={()=>navigate("/life/sleep/records?kind=nap&view=list")}>낮잠 기록 보기</button></section>;
 const metricPanel=metrics&&<><div className="sleep-metrics"><section className="sleep-panel"><h2>평균 보고 간격</h2><strong>{duration(metrics.meanIntervalMinutes)}</strong><p>완전한 주수면 {metrics.completeCount}개 기준</p></section><section className="sleep-panel"><h2>기록 커버리지</h2><strong>{metrics.coverage.complete} / {metrics.coverage.expectedDays}일</strong><p>미완료 {metrics.coverage.partial} · 누락 {metrics.coverage.missing} · 모름 {metrics.coverage.unknown} · 대기 {metrics.coverage.currentPendingDays}</p></section><section className="sleep-panel"><h2>최근 변화</h2><strong>{metrics.trend.status==="AVAILABLE"?(metrics.trend.comparisonMinutes!=null&&metrics.trend.comparisonMinutes>=0?"+ ":"")+duration(metrics.trend.comparisonMinutes):"기준선 부족"}</strong><p>최근 N={metrics.trend.recentN} · 기준 N={metrics.trend.baselineN}</p></section></div></>;
 return <><div className="sleep-shell"><SharedSidebar system="LIFE CODE" groups={[{section:"SLEEP",items:pages.map(p=>({label:p.label,icon:p.icon,active:path===p.path,destination:p.path,action:()=>navigate(p.path)}))},{section:"LIFE OS",items:[{label:"생활 카테고리",icon:Tags,destination:"/life/categories",action:()=>navigate("/life/categories")}]}]} beforeLogout={async()=>{if(pending)throw Error("저장 응답을 재확인한 뒤 로그아웃해주세요.");if(dirty&&!window.confirm("이 계정의 저장 전 입력을 삭제하고 로그아웃할까요?"))throw Error("로그아웃 취소");if(owner.current)localStorage.removeItem(storageKey(owner.current));setDraft(null);setSettingDraft(null);}}/>
 <main className="sleep-workspace"><header className="sleep-header"><div><p className="sleep-eyebrow">LIFE OS / SLEEP</p><h1>수면 {page.label}</h1><p>서버에 반영된 기록 기준 · 보고된 시각 사이의 간격</p></div><div className="sleep-row"><button disabled={busy} onClick={()=>void refresh()}>새로고침</button>{path!=="/life/sleep/settings"&&<button className="sleep-primary" disabled={!today||busy} onClick={()=>{if(path.endsWith("records"))edit(draftOf("nap",null,date));else navigate("/life/sleep/records?kind=nap&view=list");}}>낮잠 기록</button>}</div></header>
 <label className="sleep-query-zone">조회 시간대<input value={zone} onChange={e=>setZone(e.target.value)} list="sleep-zones" disabled={busy||dirty}/></label><datalist id="sleep-zones"><option>Asia/Seoul</option><option>America/New_York</option><option>Europe/London</option><option>UTC</option></datalist>
 {!online&&<div role="status" className="sleep-message">오프라인입니다. 입력은 이 계정의 브라우저에 보관됩니다. 서버 저장은 연결 후 직접 재시도해주세요.</div>}
 {loading&&<p role="status">불러오는 중…</p>}{error&&<div role="alert" className="sleep-error">{error}{Boolean(detailError?.code)&&<p>오류: {String(detailError?.code)}</p>}{Boolean(detailError?.fieldErrors)&&<pre>{JSON.stringify(detailError?.fieldErrors,null,2)}</pre>}{Boolean(detailError?.serverSnapshot)&&<details open><summary>서버 값과 내 입력 비교</summary><div className="sleep-compare"><section><h3>서버 값 {String(detailError?.conflictingResourceType??"")}</h3><pre>{JSON.stringify(detailError?.serverSnapshot,null,2)}</pre></section><section><h3>내 입력 (보존됨)</h3><pre>{JSON.stringify(draft??settingDraft,null,2)}</pre></section></div></details>}{detailError?.code==="REVISION_CONFLICT"&&<button disabled={busy} onClick={()=>void reapply()}>내 입력 유지 · 최신 기록 가져오기</button>}{!dirty&&<button onClick={()=>void refresh()}>조회 다시 시도</button>}</div>}
 {notice&&<p role="status" className="sleep-message">{notice}</p>}{pending&&<section className="sleep-panel"><h2>응답 확인이 필요한 저장 요청</h2><p>작업 식별자와 본문을 그대로 보관했습니다. 재시도해도 중복 생성하지 않습니다.</p><button disabled={busy||!online} onClick={()=>void send(pending)}>정확한 요청 재시도</button></section>}
 {undo&&<div role="status" className="sleep-message">주수면을 수정했습니다. <button disabled={busy} onClick={()=>void undoEdit()}>되돌리기 (8초)</button></div>}
 {today&&path==="/life/sleep"&&<><div className="sleep-grid"><section className="sleep-panel"><h2>{today.activeSession?"진행 중인 주수면":"최근 완료 주수면"}</h2>{(today.activeSession??today.lastClosed)?<><p>{labels[(today.activeSession??today.lastClosed)!.status]}{today.staleOpen?" · 오래된 진행 기록 보완 필요":""}</p><p>{recordRange("main",(today.activeSession??today.lastClosed)!)}</p><p>취침 {(today.activeSession??today.lastClosed)!.bedtimeCertainty??"미기록"} · 기상 {(today.activeSession??today.lastClosed)!.wakeCertainty??"미기록"}</p><p className="sleep-value">{duration((today.activeSession??today.lastClosed)!.intervalMinutes)}</p><button onClick={()=>navigate("/life/sleep/records?date="+((today.activeSession??today.lastClosed)!.logicalWakeDate??(today.activeSession??today.lastClosed)!.expectedWakeDate))}>기록 확인·보완</button></>:<p>아직 서버에 기록한 주수면이 없습니다.</p>}</section><section className="sleep-panel"><h2>보완할 기록</h2>{today.pendingActions.length?today.pendingActions.slice(-8).reverse().map(p=><button className="sleep-record" key={p.occurrenceId} onClick={()=>navigate("/life/sleep/records?date="+p.expectedWakeDate)}><strong>{p.expectedWakeDate}</strong><span>{p.kind==="BEDTIME_REQUIRED"?"취침":"기상"} · {p.status==="ACKNOWLEDGED_UNKNOWN"?"모름":"기록 필요"}</span></button>):<p>현재 보완 요구가 없습니다.</p>}<p>휴대폰에서 아직 전송하지 않은 기록은 웹에서 확인할 수 없습니다.</p></section></div>{metricPanel}{napPanel}</>}
 {today&&path.endsWith("records")&&<><div className="sleep-toolbar"><div className="sleep-row"><button aria-pressed={kind==="main"} onClick={()=>context({kind:"main"})}>주수면</button><button aria-pressed={kind==="nap"} onClick={()=>context({kind:"nap"})}>낮잠</button><button disabled={busy||!!pending} onClick={()=>edit(draftOf(kind,null,date))}>{kind==="main"?"주수면 추가":"낮잠 추가"}</button></div><div className="sleep-row"><button aria-label="이전 7일" onClick={()=>context({date:addDay(date,-7)})}>‹</button><label>마지막 날짜<input type="date" value={date} onChange={e=>{if(e.target.value)context({date:e.target.value});}}/></label><button aria-label="다음 7일" onClick={()=>context({date:addDay(date,7)})}>›</button><button aria-pressed={view==="calendar"} onClick={()=>context({view:"calendar"})}>캘린더</button><button aria-pressed={view==="list"} onClick={()=>context({view:"list"})}>목록</button></div></div>
 {kind==="main"&&<label className="sleep-check"><input type="checkbox" checked={includeExcluded} disabled={dirty} onChange={e=>setIncludeExcluded(e.target.checked)}/>집계 제외 기록 포함</label>}
 <div className={draft?"sleep-grid":""}><section className="sleep-panel"><h2>{dates[0]} – {date}</h2><p>{kind==="main"?"주수면은 기상일 기준":"낮잠은 시작 시각의 현지 날짜 기준 · 같은 날 여러 건 가능"}</p>{view==="calendar"&&kind==="main"?<div className="sleep-time-scroll"><div className="sleep-time-calendar"><section className="sleep-axis"><h3>시각</h3><div>{["전날18","21","00","03","06","09","12","15","당일18"].map(t=><span key={t}>{t}</span>)}</div></section>{dates.map(day=><section key={day}><h3>{day.slice(5)}</h3><div className="sleep-time-day">{sessions.filter(r=>(r.logicalWakeDate??r.expectedWakeDate)===day).map(r=><Timeline key={r.id} record={r} date={day} zone={zone} onClick={()=>void select("main",r.id)}/>)}</div></section>)}</div><p>전날 18시부터 당일 18시 · 진행/미완료는 실제 알려진 시각만 표시 · 긴 구간은 상세에서 전체 날짜 확인</p></div>:view==="calendar"?<div className="sleep-calendar">{dates.map(day=><section key={day}><h3>{day.slice(5)}</h3>{records.filter(r=>(kind==="main"?((r as Session).logicalWakeDate??(r as Session).expectedWakeDate):(r as Nap).startLocalDate)===day).map(r=><button key={r.id} className={`sleep-record ${kind==="nap"?"sleep-nap":""}`} onClick={()=>void select(kind,r.id)}><RecordText kind={kind} record={r}/></button>)}</section>)}</div>:<div>{records.map(r=><button key={r.id} className={`sleep-record ${kind==="nap"?"sleep-nap":""}`} onClick={()=>void select(kind,r.id)}><RecordText kind={kind} record={r}/></button>)}</div>}{!records.length&&!loading&&<p>이 기간의 {kind==="main"?"주수면":"낮잠"} 기록이 없습니다.</p>}</section>
 {draft&&<section className="sleep-panel sleep-editor" aria-label="선택한 기록 편집"><h2>{draft.kind==="nap"?"낮잠 사후 기록":"주수면 기록 편집"}</h2><p>{draft.original?`revision ${draft.original.revision}`:"새 기록"} · 양 끝 날짜를 각각 확인하세요.</p><TimeInput disabled={busy||!!pending} label={draft.kind==="nap"?"시작":"취침"} value={draft.start} nap={draft.kind==="nap"} set={v=>setDraft({...draft,start:v})}/><TimeInput disabled={busy||!!pending} label={draft.kind==="nap"?"종료":"기상"} value={draft.end} nap={draft.kind==="nap"} set={v=>setDraft({...draft,end:v})}/><p>보고 간격: <strong>{preview==null?"미완료":preview>0?duration(preview):"날짜·순서 확인 필요"}</strong></p><div className="sleep-row"><button className="sleep-primary" disabled={busy||!online||!draftDirty} onClick={()=>void save()}>저장</button><button disabled={busy||!!pending} onClick={discard}>입력 버리기</button>{draft.original&&<button className="sleep-danger" disabled={busy||!!pending} onClick={()=>setConfirm("delete")}>삭제</button>}</div>{error&&<p className="sleep-danger">{error}</p>}<p>명시 저장 · 삭제에는 휴지통과 되돌리기가 없습니다.</p>{draft.kind==="main"&&draft.original&&<><p>취침: {(draft.original as Session).bedtimeCertainty??"미기록"} / {(draft.original as Session).bedtimeSource??"—"}<br/>기상: {(draft.original as Session).wakeCertainty??"미기록"} / {(draft.original as Session).wakeSource??"—"}</p><button onClick={async()=>{const readerOwner=owner.current,readerId=draft.id,generation=epoch.current;try{const r=await read<{items:Record<string,unknown>[];nextCursor:string|null}>(`/sessions/${draft.id}/events?limit=30${events?.nextCursor?"&cursor="+encodeURIComponent(events.nextCursor):""}`);if(readerOwner!==owner.current||readerId!==state.current.draft?.id||generation!==epoch.current)return;setEvents({items:[...(events?.items??[]),...r.items],nextCursor:r.nextCursor});}catch(e){setError((e as Error).message);}}}>{events?.nextCursor?"이력 더 보기":"수정 이력 보기"}</button>{events&&<details open><summary>수정 이력 {events.items.length}건</summary>{events.items.map((e,i)=><p key={i}>{String(e.actionType)} · revision {String(e.newRevision)} · {String(e.serverCommittedAt)}</p>)}</details>}</>}</section>}</div></>}
 {today&&path.endsWith("statistics")&&<><div className="sleep-row"><button aria-pressed={period==="7d"} onClick={()=>context({period:"7d"})}>7일</button><button aria-pressed={period==="30d"} onClick={()=>context({period:"30d"})}>30일</button><span>{metrics?.from} – {metrics?.to}</span></div>{metricPanel}<div className="sleep-grid"><section className="sleep-panel"><h2>날짜별 보고 간격</h2><p>누락과 미완료는 0시간으로 계산하지 않습니다.</p><div className="sleep-days">{metrics?.days.map(d=><button key={d.date} onClick={()=>navigate("/life/sleep/records?date="+d.date)}><span>{d.date.slice(5)}</span><div className="sleep-bar" style={{width:d.intervalMinutes==null?0:`${Math.min(100,d.intervalMinutes/720*100)}%`}}/><span>{d.intervalMinutes==null?labels[d.quality]??d.quality:duration(d.intervalMinutes)}</span></button>)}</div></section><section className="sleep-panel"><h2>시각 규칙성</h2>{metrics&&([['취침',metrics.bedtime],['기상',metrics.wake]] as const).map(([label,c])=><section key={label}><h3>{label} 시각</h3><p>중심 {clockTime(c.centerMinutes)} · 변동 {c.deviationMinutes==null?"—":Math.round(c.deviationMinutes)+"분"}</p><p>N={c.sampleCount} · {c.timezoneRegime??"시간대 혼합/없음"} · {c.status==="AVAILABLE"?"계산 가능":c.status==="MIXED_TIMEZONES"?"시간대 혼합":c.status==="UNAVAILABLE_LOW_CONCENTRATION"?"시각 집중도 부족":"표본 부족"}</p></section>)}</section></div>{napPanel}</>}
 {today&&path.endsWith("settings")&&<><div className="sleep-grid">{(['bedtime','wake'] as const).map(key=>{const settings=settingDraft??today.settings,r=settings[key];const update=(v:Partial<typeof r>)=>setSettingDraft({...settings,[key]:{...r,...v}});return <section className="sleep-panel" key={key}><h2>{key==="bedtime"?"취침":"기상"} 기록 알림</h2><label className="sleep-check"><input type="checkbox" checked={r.enabled} disabled={busy||!!pending} onChange={e=>update({enabled:e.target.checked})}/>알림 켜기</label><label>시각<input type="time" value={r.localTime} disabled={busy||!!pending} onChange={e=>update({localTime:e.target.value})}/></label><fieldset><legend>요일</legend><div className="sleep-row">{['월','화','수','목','금','토','일'].map((day,i)=><label className="sleep-check" key={day}><input type="checkbox" checked={r.weekdays.includes(i+1)} disabled={busy||!!pending} onChange={e=>update({weekdays:e.target.checked?[...r.weekdays,i+1].sort():r.weekdays.filter(v=>v!==i+1)})}/>{day}</label>)}</div></fieldset><label>방식<select value={r.profile} disabled={busy||!!pending} onChange={e=>update({profile:e.target.value})}>{[['SILENT','무음'],['VIBRATION','진동'],['SOUND','소리'],['SOUND_VIBRATION','소리 + 진동']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></section>;})}</div><div className="sleep-row"><button className="sleep-primary" disabled={!settingDraft||busy||!online} onClick={()=>void save()}>공유 설정 저장</button><button disabled={!settingDraft||busy||!!pending} onClick={discard}>입력 버리기</button></div><section className="sleep-panel"><h2>Android에서 관리</h2><p>OS 권한, 휴대폰 사용 기반 후보, 장치 선택, 실제 알림 전달·테스트는 Android에서 관리합니다. 웹은 알림 장치 소유권을 변경하지 않습니다.</p><p>공유 설정은 다음 동기화 후 아직 시작하지 않은 알림부터 적용됩니다. 현재 알림 장치: {today.settings.reminderDeviceId??"미지정"}. 개별 기록 삭제는 기록 화면에서 가능합니다.</p></section></>}
 </main></div>
 {leave&&<Modal title="저장하지 않은 입력" close={()=>setLeave(null)}><p>입력을 저장하거나 버린 뒤 이동하세요. 실패하면 입력과 현재 화면을 유지합니다.</p><div className="sleep-row"><button disabled={busy||!online} onClick={async()=>{const proceed=leave;if(await save()){setLeave(null);proceed();}}}>저장 후 이동</button><button disabled={busy||!!pending} onClick={()=>{const proceed=leave;discard();setLeave(null);proceed();}}>버리고 이동</button></div></Modal>}
 {confirm&&<Modal title={confirm==="delete"?"기록을 삭제할까요?":"18시간 이상 간격 확인"} close={()=>setConfirm(null)}><p>{confirm==="delete"?"기록과 수정 이력을 실제 삭제합니다. 삭제는 되돌릴 수 없습니다.":"시작과 종료 날짜·시각이 맞는지 확인해주세요. 확인된 긴 간격은 저장할 수 있습니다."}</p><button className={confirm==="delete"?"sleep-danger":"sleep-primary"} disabled={busy} onClick={()=>{if(confirm==="delete")void remove();else{setConfirm(null);void save(true);}}}>{confirm==="delete"?"삭제 확인":"시각 확인 · 저장"}</button></Modal>}
 </>;
}
